### ISSUE TITLE
Stylistic set for "disambiguation"

### ISSUE THREAD

**Issue by rsms** [rsms/inter#1]
Add a stylistic set where things like lower-case "L" have little hooks on them to disambiguate from upper-case "i", sort of like Ubuntu (http://font.ubuntu.com/)

Something along these lines:

<img width="780" alt="screenshot 2017-08-22 13 58 59" src="https://user-images.githubusercontent.com/47046/29587214-14cae646-8742-11e7-8373-67fd90691c13.png">

**Comment by rsms** [comment]
Note: https://github.com/rsms/interface/releases/tag/v1.2 adds slashed zero (`zero`) and tabular numbers (`tnum`) features, which partly helps with this.

**Comment by NetOperatorWibby** [comment]
I *love* slashed zeroes, this is excellent.

**Comment by rsms** [comment]
This has been implemented in the v3 branch and will be included in the upcoming 3.0 release.
I'll keep this open until that release.

**Comment by brianespinosa** [comment]
Thanks for this, and all your work on Inter @rsms. 👍

**Comment by rsms** [comment]
v3.0 shipped
