### ISSUE TITLE
Font is too 🔥

### ISSUE THREAD

**Issue by csampersand** [rsms/inter#103]
This is the best fucking font I have ever seen oh my god my life is changed forever holy shit I think I just wet myself Arial you can go suck a dick Open Sans more like Open Sucks I'm changing all my fonts to this my phone my computer new editor font for sure see ya later Dank Mono more like Stank Mono am I right good shit bay-bee

**Comment by pharan** [comment]
I can repro this issue reliably.

**Comment by rsms** [comment]
❤️

**Comment by rsms** [comment]
<img width="919" alt="screen shot 2019-01-01 at 18 50 00" src="https://user-images.githubusercontent.com/47046/50579030-7e1a0700-0dfe-11e9-9049-a8e24aa3459b.png">
<img width="909" alt="screen shot 2019-01-01 at 18 50 04" src="https://user-images.githubusercontent.com/47046/50579031-807c6100-0dfe-11e9-961d-1d2b8ad1a556.png">
