### ISSUE TITLE
Increase dngb_ballotx size

### ISSUE THREAD

**Issue by alevroub** [rsms/inter#105]
The `dngb_ballotx` glyph appears too small to be paired with the `dngb_check` checkmark. A slight increase in size is needed for them to look (optically) equal.

<img width="551" alt="screenshot 2018-12-30 at 16 38 52" src="https://user-images.githubusercontent.com/6848068/50548686-76692f80-0c51-11e9-878c-230e4a876386.png">

**Comment by rsms** [comment]
<img width="1069" alt="screen shot 2019-01-01 at 20 48 11" src="https://user-images.githubusercontent.com/47046/50580373-07373b00-0e0b-11e9-9041-5de2bc531871.png">
<img width="1055" alt="screen shot 2019-01-01 at 20 47 39" src="https://user-images.githubusercontent.com/47046/50580375-0a322b80-0e0b-11e9-8be9-9a02d69f13d9.png">
<img width="1019" alt="screen shot 2019-01-01 at 20 47 34" src="https://user-images.githubusercontent.com/47046/50580377-0bfbef00-0e0b-11e9-9588-00f43e4bb3a4.png">
<img width="787" alt="screen shot 2019-01-01 at 20 46 37" src="https://user-images.githubusercontent.com/47046/50580379-0ef6df80-0e0b-11e9-9d5a-c243bb16e456.png">
<img width="746" alt="screen shot 2019-01-01 at 20 46 43" src="https://user-images.githubusercontent.com/47046/50580383-128a6680-0e0b-11e9-9bae-b5148ae98ff8.png">
<img width="744" alt="screen shot 2019-01-01 at 20 46 28" src="https://user-images.githubusercontent.com/47046/50580384-13bb9380-0e0b-11e9-9d1f-7a1b66a6617b.png">
