### ISSUE TITLE
Illustration of 'r' and 'n' words

### ISSUE THREAD

**Issue by cereda** [rsms/inter#106]
Dear friends,

It would be desirable to have (perhaps in the documentation) a text that illustrates the combination _r n_ (as in _furniture_); that combination is often in on-screen sans fonts easily misreadable as _m_ (as in _rumor_), resulting in the ridiculous non-word _keming_.

All the best!

**Comment by rsms** [comment]
The standard "r" (there is an alternate) has a slightly longer tail than your run-of-the-mill grotesk "r" which might give you some additional cognitive hints for disambiguation. There really is no magical way to avoid this.

Here are the two "r"s for comparison:
<img width="969" alt="screen shot 2019-01-01 at 20 01 53" src="https://user-images.githubusercontent.com/47046/50579201-457b2d00-0e00-11e9-9535-a0c5ff5a0f07.png">

Closing this as it's not an issue with this typeface (or I misunderstood you; let me know if that is the case.)
