### ISSUE TITLE
Hinted TTF files missing hinting for several glyphs

### ISSUE THREAD

**Issue by aheid** [rsms/inter#107]
**Describe the bug**
The hinted TTF version does not seem to contain hinting on several glyphs.

**To Reproduce**
1.  Install hinted version, write text in say WordPad, save image of text.
2.  Delete and install unhinted version, write same text and save as new image.
3.  Compare images.

**Expected behavior**
The hinted version should be less blurry when using ClearType for all glyphs.

**Screenshots**
https://imgur.com/a/b1POgyN

**Environment**
- OS: Windows 10 1809
- WordPad
- Inter UI Regular 3.1;e6cb70c3f

**Additional context**
Do not use Word when trying to reproduce, it doesn't do proper font rendering (yay MS).
Tried the OTF version as well, but for some reason that looks like a blurry mess compared to the TTF versions.

**Comment by aheid** [comment]
I forgot to mention I'm running a 1920x1080 LCD display using 100% scaling, and of course ClearType enabled.

**Comment by rsms** [comment]
I'm currently using [ttfautohint](https://www.freetype.org/ttfautohint/) to create hinted TTF files for Windows. It's possible that [the settings used](https://github.com/rsms/inter/blob/b9326c6f99a81102be1103f4b68ff1eb7d7eca3b/Makefile#L155) are incorrect. It's also possible that ttfautohint is not perfect and simply ignores some glyphs.

Needs research by someone very familiar with TTF hinting and ttfautohint in particular.

**Comment by aheid** [comment]
By passing the unhinted version of the font used above through ttfautohint GUI with default settings seems to produce something renders very nice, at least for this small test.

https://imgur.com/a/rEmUZ0r

I next tried to reproduce the issue using the command line from the makefile, and I could. Removing the ```--composites``` flag made the font properly hinted again. Bug in ttfautohint?

**Comment by rsms** [comment]
Related to #87
