### ISSUE TITLE
(Web) Password input bullet characters very big on IE, Edge & Firefox.

### ISSUE THREAD

**Issue by DominikSerafin** [rsms/inter#112]
**Describe the bug**

When user types anyting in browser password input then browsers visually show bullet characters to hide the password. 

When Inter UI is used as font family on such password inputs then these bullet characters are very big on IE, MS Edge, Firefox and mobile Safari.

Characters are normal sized on Chrome and desktop Safari. 

(Note 1: bullet characters in normal text, outside the password inputs, are normal in size on all browsers)
(Note 2: revealing password on Edge shows normal-sized characters)

**To Reproduce**

I've seen this behavior in my app and to make sure it wasn't problem with my font style declarations or styles, I've done following on https://rsms.me/inter/ which resulted in the same problem:

1. Go to https://rsms.me/inter/
2. Open devtools
3. Add `<input type="password" placeholder="password" style="font-size: 15px; font-family: Inter UI, serif">` anywhere in HTML
4. Type anything in that input box.

**Expected behavior**

Bullet characters should probably render in smaller size on IE, Edge, Firefox and mobile Safari.

**Screenshots**

![inter-ui-bullets](https://user-images.githubusercontent.com/7447244/51363166-125ebc00-1ad7-11e9-8bbb-a33d5ce7b477.png)

**Environment**

- OS: Windows 10, iOS 12, macOS Mojave
- Desktop Chrome and desktop Safari are fine. 
- Affected are IE, Edge, Firefox and mobile Safari.
- I've seen this behavior in Inter UI 2.5 and Inter UI 3.4.

**Comment by rsms** [comment]
Interesting. I wonder if Firefox uses a different codepoint than bullet.

**Comment by DominikSerafin** [comment]
Hi @rsms I did some digging and I think you're right. U+2022 is used in webkit browsers and U+25CF is used in IE, Edge & Firefox.

**Comment by DominikSerafin** [comment]
For anyone here looking for temporary workaround/fix - I've personally fixed this by dynamically styling the password input to different (monospace) font if that input has value. If that input is empty then I'm using Inter UI - this way input placeholder is intact. 

The only downside is in case of browsers that allow revealing password (like MS Edge) - the revealed password is in that different font. But it's probably very rare edge case.

**Comment by DominikSerafin** [comment]
I originally thought this was problem with typeface and not with different browsers using different characters. I do agree now that this probably better to leave 'black circle' as it is in Inter UI. Thanks for taking the time and looking into it @rsms.
