### ISSUE TITLE
Add Oblique variant of Inter UI

### ISSUE THREAD

**Issue by Derpitron** [rsms/inter#113]
If possible, there could be an Oblique variant of Inter UI, to be shown as a choice between Italic and Oblique. IIRC, Italics have stylistic differences (slightly narrower in Sans Fonts), while obliques are just slanted. Please forgive me if I don't get it correctly, but I think Iosevka has both Italic and Oblique fonts. It just makes me inexplicably happy to see stuff like that, no pressure though! Thanks!

**Comment by rsms** [comment]
It’s a naming convention, really. Stylistically oblique is often a slanted version of the upstraight glyphs, though not always with the same width. Italic usually have little or no difference for Grotesks like Inter UI, but do differ stylistically for many slab, serif and script fonts. Inter UI’s italics are hand made glyph by glyph and are stylistically very similar to a computationally slanted version, which afaik is what the computer-generated Iosevka does. You can generate a slanted version of Inter UI really easily in most font editors like Glyphs or RoboFont.
