### ISSUE TITLE
Please consider to add superscript of square brackets

### ISSUE THREAD

**Issue by stone-zeng** [rsms/inter#114]
Superscript (`sups`) of square brackets (U+005B, U+005D) are widely used for citation. So please consider to add them.

**Comment by rsms** [comment]
https://github.com/rsms/inter/commit/8fd3df4c9f1998e09046bcb6da1f0053018428a4
<img width="1143" alt="screen shot 2019-02-03 at 13 01 24" src="https://user-images.githubusercontent.com/47046/52183447-d86f0480-27bc-11e9-8cf6-ef6187ac042e.png">
<img width="1240" alt="screen shot 2019-02-03 at 13 01 19" src="https://user-images.githubusercontent.com/47046/52183450-da38c800-27bc-11e9-81b2-32a195a2f446.png">
<img width="1032" alt="screen shot 2019-02-03 at 13 01 27" src="https://user-images.githubusercontent.com/47046/52183453-dc028b80-27bc-11e9-9cc2-3f6e437449ba.png">
