### ISSUE TITLE
Missing χ U+03C7 GREEK SMALL LETTER CHI

### ISSUE THREAD

**Issue by svenper** [rsms/inter#117]
Considering the many included rare/historical Greek characters (ϙ, ϝ, ϟ, ϡ, etc.), it seems strange that the simple χ is missing.
![chi](https://user-images.githubusercontent.com/15199675/51966757-4df96e80-2465-11e9-9967-ccc5b89cd03f.png)

**Comment by rsms** [comment]
Worked on adding chi this morning. Here's the result:

<img width="1129" alt="screen shot 2019-02-03 at 11 10 33" src="https://user-images.githubusercontent.com/47046/52181223-86ba8000-27a4-11e9-90c9-11253a9b5afe.png">
<img width="1144" alt="screen shot 2019-02-03 at 11 10 40" src="https://user-images.githubusercontent.com/47046/52181224-88844380-27a4-11e9-9521-d5435fa1bedc.png">
<img width="1049" alt="screen shot 2019-02-03 at 11 10 59" src="https://user-images.githubusercontent.com/47046/52181225-8a4e0700-27a4-11e9-8615-4db456cb80c1.png">

**Comment by rsms** [comment]
![chi-2](https://user-images.githubusercontent.com/47046/52181630-bbc8d180-27a8-11e9-9382-8381ff779e83.gif)
