### ISSUE TITLE
'đ' is displaying weirdly in Word

### ISSUE THREAD

**Issue by goranalkovic** [rsms/inter#118]
**Describe the bug**
There is a _hole_ in the letter 'đ' when viewed in Microsoft Word and Paint (possibly other apps).

**To Reproduce**
1. Install the font
2. Open MS Word or Paint
3. Type 'đ'

**Expected behavior**
(lowercase) đ shouldn't have a _hole_ in it

**Screenshots**
![Image of the problem](https://i.imgur.com/F3dHGzu.png)

**Environment**
- OS: Windows 10 Pro (build 18323)
- App that renders the font : Word (Office 365), Paint
- Version of font 3.2 (latest release on GitHub), TTF (non-hinted)

**Additional context**
I'm not seeing the issue on the website (in MS Edge or Chrome).

**Comment by rsms** [comment]
Which font files did you install?

The variable fonts (with ".var" in the filename) are composed of many smaller shapes to allow for interpolation. Some Windows apps don't deal well with that yet (it's a new technology.) If this is the case, make sure to remove any Inter UI ".var" font files from your system and install the font files that have styles in their name (e.g. Inter-UI-Regular.otf et al.)

**Comment by goranalkovic** [comment]
I installed the fonts from the `Inter UI (TTF)` folder. Tried re-purging everything and re-installing, the same is happening. Checked my `C:\Windows\Fonts` folder and no `.var` files there. Checked it, and it's still happening.

**Comment by goranalkovic** [comment]
I've tried the attached build and the released 3.3 version and I'm happy to report it's working!
Thank you very much!

**Comment by rsms** [comment]
:–)
