### ISSUE TITLE
build instructions?

### ISSUE THREAD

**Issue by alexmyczko** [rsms/inter#120]
Maybe it would be great to have a build system without pyenv/venv/docker and all?
For Debian/Ubuntu packages?

```
$ make all_otf      
Makefile:75: build/etc/generated.make: No such file or directory
make: *** No rule to make target 'build/etc/generated.make'.  Stop.
```

init.sh only supports venv builds? I want to build this without internet connection. I do have makefont, and whatever is needed...

**Comment by rsms** [comment]
See https://github.com/rsms/inter/blob/master/CONTRIBUTING.md#compiling-font-files

**Comment by rsms** [comment]
You can build with docker, or locally. init.sh installs deps in the project directory.

**Comment by bernaferrari** [comment]
Are these kind of errors expected when running `./dockermake -j test`? 
![image](https://user-images.githubusercontent.com/351125/52537744-16d26980-2d51-11e9-8624-ea66dcd059d5.png)

**Comment by alexmyczko** [comment]
Meanwhile I've got working packages (see debian/rules for how I build them)
http://phd-sid.ethz.ch/debian/fonts-inter/ (this is just here for reference, in case someone else wants to create packages that build from source)
