### ISSUE TITLE
Line-height problem with regular compared to black (ATS bug)

### ISSUE THREAD

**Issue by hmaesta** [rsms/inter#124]
![screen shot 2019-02-07 at 16 52 30](https://user-images.githubusercontent.com/741969/52440545-8ce29080-2b05-11e9-8007-88dce4ff4616.png)

Since I upgraded to Inter 3.3 there is a difference between line-height of `Regular` and `Bold`.

**Environment**
- OS: macOS 10.14.2
- Sketch 53 (72520)
- Inter 3.3

**Comment by vilav** [comment]
+1. Noticed the same.

• Keynote 8.3
• macOS 10.14.3

**Comment by rsms** [comment]
So strange. What font files do you have installed? (Please be as detailed and exact as possible.)

**Comment by rsms** [comment]
Something's definitely not right here.
diffing fontinfo of regular and black otf yields some weird differences:

```diff
@fontinfo black vs regular

     "head": {
-      "checkSumAdjustment": 1882288472,
+      "checkSumAdjustment": 1637560464,
...
-      "xMax": 4860,
-      "xMin": -2433,
-      "yMax": 3145,
-      "yMin": -1196
+      "xMax": 4650,
+      "xMin": -2080,
+      "yMax": 3072,
+      "yMin": -1084
...
     "hhea": {
...
-      "xMaxExtent": 4860
+      "xMaxExtent": 4650
```

**Comment by rsms** [comment]
Here's what I'm seeing for OTF files of v3.2:

```diff
@ black vs regular (v3.2 OTF)
     "head": {
...
-      "xMax": 4860,
-      "xMin": -2433,
-      "yMax": 3145,
-      "yMin": -1236
+      "xMax": 4524,
+      "xMin": -2080,
+      "yMax": 3012,
+      "yMin": -1076
     },
     "hhea": {
...
-      "xMaxExtent": 4860
+      "xMaxExtent": 4524
```

The black, regular and light masters all have _identical_ metrics in the source files, both Glyphs and UFO. The diff also shows that there are no differences between metrics that account for line-height, so this is really strange.

Additionally, it seems to only be an issue with ATS-based type rendering — the only way to reproduce this is with Apple software that directly uses ATS (i.e. no Safari.)

Adobe tools (uses adobe's type setter) as well as tools based on freetype and harfbuzz shows the correct line height.

**Comment by hmaesta** [comment]
> What font files do you have installed?

I downloaded the latest release from [inter/releases](https://github.com/rsms/inter/releases). ([Here my installed fonts.](https://drive.google.com/file/d/10wymVkLFCDgQRYpJvIFSsJwRfLoV_nh4/view?usp=sharing))

---

Another example comparing all weights and line-heights.

![screen shot 2019-02-08 at 07 42 28](https://user-images.githubusercontent.com/741969/52470483-62c8b700-2b75-11e9-8453-b52bdaf2aea5.png)

[Download Sketch file here](https://sketch.cloud/s/kdADD).

You mentioned that on Adobe software it's correct (and in fact the line-height number is), but when creating a grid line and comparing the weights, Bold and Black have a slight difference between others. _Could be a software bug though._ (it's impossible to screenshot since Illustration removes the "outer box" when hitting cmd – but you can [download file here](https://drive.google.com/file/d/1AzRVv4TO2DRSgMlDNdJQoSalpTGmL34Z/view?usp=sharing)).

**Comment by thundernixon** [comment]
I can help look into this!

Typically, Google Fonts projects need to set custom parameters in GlyphsApp to control vertical metrics in their various flavors. This is one thing that FontBakery helps to catch. I’m on my phone right now, but I’ll be able to post more detail later.

**Comment by rsms** [comment]
This is what I'm seeing:

Apple TextEdit: (uses ATS/CoreText)
<img width="248" alt="screen shot 2019-02-08 at 08 38 33" src="https://user-images.githubusercontent.com/47046/52491888-fbaf0080-2b7c-11e9-87b7-098310eb08d1.png">

Sketch 53: (uses ATS/CoreText)
<img width="612" alt="screen shot 2019-02-08 at 08 51 20" src="https://user-images.githubusercontent.com/47046/52492772-c6a3ad80-2b7e-11e9-8646-3abce45ec37d.png">

Illustrator CC 2019
<img width="546" alt="screen shot 2019-02-08 at 08 35 50" src="https://user-images.githubusercontent.com/47046/52491732-9eb34a80-2b7c-11e9-9b24-98db7e150c97.png">

Figma: (uses Freetype & Harfbuzz)
<img width="584" alt="screen shot 2019-02-08 at 08 48 47" src="https://user-images.githubusercontent.com/47046/52492619-64e34380-2b7e-11e9-98a5-70dd0d2bfa40.png">

InVision Studio 1.8.4: (uses ??)
<img width="604" alt="screen shot 2019-02-08 at 08 56 00" src="https://user-images.githubusercontent.com/47046/52493047-6bbe8600-2b7f-11e9-87ef-eaa7286da8c1.png">

Google Chrome 72: (uses Freetype & Harfbuzz)
<img width="570" alt="screen shot 2019-02-08 at 08 42 16" src="https://user-images.githubusercontent.com/47046/52492146-77a94880-2b7d-11e9-80ac-7e5f0cc62672.png">

Apple Safari 12: (uses ??)
<img width="556" alt="screen shot 2019-02-08 at 08 43 30" src="https://user-images.githubusercontent.com/47046/52492249-a9221400-2b7d-11e9-8e85-3e81f28b54e9.png">

Microsoft Edge 42: (probably uses DirectWrite; not sure)
![edge](https://user-images.githubusercontent.com/47046/52493519-834a3e80-2b80-11e9-8eb8-99fe79f2a2d0.PNG)

Microsoft WordPad: (Win 10; uses DirectWrite)
<img width="762" alt="screen shot 2019-02-08 at 09 10 10" src="https://user-images.githubusercontent.com/47046/52494058-d244a380-2b81-11e9-9a78-1ccbc2b08086.png">


This is the data I'm getting from Freetype for Inter-Black.otf:

```
ascender: 2708
descender: -660
faceFlags: 537
faceIndex: 0
familyName: Inter
height: 3368
maxAdvanceHeight: 3368
maxAdvanceWidth: 4928
numCharmaps: 3
numFaces: 1
numFixedSizes: 0
numGlyphs: 2345
styleFlags: 0
styleName: Black
underlinePosition: -576
underlineThickness: 320
unitsPerEm: 2816
```

This is the data I'm getting from Freetype for Inter-Regular.otf:

```
ascender: 2708
descender: -660
faceFlags: 537
faceIndex: 0
familyName: Inter
height: 3368
maxAdvanceHeight: 3368
maxAdvanceWidth: 4928
numCharmaps: 3
numFaces: 1
numFixedSizes: 0
numGlyphs: 2345
styleFlags: 0
styleName: Regular
underlinePosition: -560
underlineThickness: 192
unitsPerEm: 2816
```

**Comment by rsms** [comment]
I tried scaling the glyphs source to 2048 UPM, compiled font files and tested with the Apple apps. No difference. So probably not a UPM-related bug (there has been issues with uncommon UPMs in ATS/CoreText.)

**Comment by EdenSG** [comment]
Seeing the same thing on Apple Pages/Numbers/Keynote, presumably they use ATS/CoreText as well

**Comment by m4rc1e** [comment]
I've had this issue before on Android. Some applications use the font's yMin and yMax to determine the position for the first line of text.

**Comment by rsms** [comment]
Diffing `ttx`:

```
(. init.sh ; ttx build/fonts/const/Inter-Regular.otf & ; ttx build/fonts/const/Inter-Black.otf & ; wait)
diff -u build/fonts/const/Inter-*.ttx
```

Notable differences: (Black vs Regular)

```
-    <underlinePosition value="-416"/>
+    <underlinePosition value="-464"/>
```

This is by design though and shouldn't affect line height.
There really is nothing else sticking out that affects height... What a mystery.

**Comment by m4rc1e** [comment]
I'm pretty sure Roboto experienced this issue in Android. 

To solve it they forced the yMin and yMax using the following script, https://github.com/google/roboto/blob/master/scripts/force_yminmax.py

https://github.com/google/roboto/blob/master/Makefile#L39

**Comment by rsms** [comment]
@m4rc1e I patched the font files' yMin and yMax to match (otf -> ttx, patch values, ttx -> otf) and I get the same results.

**Comment by rsms** [comment]
Here are the highest and lowest glyphs in the regular and black masters: (from a script in Glyphs)

```
Master: Regular
   Highest: Adieresismacron (top y: 3072.0)
   Lowest: ydotbelow (bottom y: -1084.0)

Master: Black
   Highest: Idieresisacute (top y: 3146.0)
   Lowest: ydotbelow (bottom y: -1196.0)
```

(looks normal)

**Comment by m4rc1e** [comment]
Inter UI v3.2 seems to have the same issue.

<img width="1125" alt="screenshot 2019-02-08 at 17 56 04" src="https://user-images.githubusercontent.com/7525512/52496313-e8c31d00-2bca-11e9-8efc-94bc63d2a295.png">


@hmaesta what was the previous release you were using?

**Comment by hmaesta** [comment]
> what was the previous release you were using?

Unfortunately I don't remember, but I don't believe it was 3.2 since I can't remember the last time I updated (so it must be a long time).

**Comment by m4rc1e** [comment]
@hmaesta thanks. I can confirm 2.2 was ok.

<img width="1113" alt="screenshot 2019-02-08 at 18 35 39" src="https://user-images.githubusercontent.com/7525512/52498323-68071f80-2bd0-11e9-968b-9f4c35d95588.png">

@rsms Apologies for the goose chase. I may take a look at this on Monday...the beer is calling. Nice font btw! the progress between different versions is really impressive.

**Comment by thundernixon** [comment]
This seems to still be an issue in v3.3.

![image](https://user-images.githubusercontent.com/7355414/54779607-f4542b80-4bed-11e9-8c1c-41fe44916a03.png)

However, I (tentatively) think I may have resolved the issue (click image to see it bigger if the bounding boxes are too faint):

![image](https://user-images.githubusercontent.com/7355414/54783967-11422c00-4bf9-11e9-94b4-692c880376c1.png)

Pull Request with updates: https://github.com/rsms/inter/pull/141

---

I have followed [an earlier system suggested by @m4rc1e](https://github.com/googlefonts/fontbakery/issues/2164#issuecomment-436595886), using a script to apply custom parameters across all masters based on min and max heights, then rebuilding:

![image](https://user-images.githubusercontent.com/7355414/54778392-ed77e980-4bea-11e9-8abf-f880d161c619.png)


## Sketch (Inter 3.4 WIP)

Variable

![image](https://user-images.githubusercontent.com/7355414/54778152-4abf6b00-4bea-11e9-9489-d8648f94e6de.png)

Static

![image](https://user-images.githubusercontent.com/7355414/54778345-c8837680-4bea-11e9-8ffd-481c120d7905.png)

## TextEdit (Inter 3.4 WIP)

Variable

![image](https://user-images.githubusercontent.com/7355414/54778243-8bb77f80-4bea-11e9-9f5b-4b7ecacad79f.png)

Static

![image](https://user-images.githubusercontent.com/7355414/54778464-21eba580-4beb-11e9-9c17-6287b62361b6.png)

**Comment by rsms** [comment]
Confirming build off of master fb79b9ee89 works correctly and fixes the issues. Nice work @thundernixon !

ATS based apps:
<img width="991" alt="Screen Shot 2019-03-27 at 11 53 46" src="https://user-images.githubusercontent.com/47046/55104673-16372d80-5088-11e9-82ec-9afe9b42186c.png">
<img width="546" alt="Screen Shot 2019-03-27 at 11 54 48" src="https://user-images.githubusercontent.com/47046/55104683-1b947800-5088-11e9-86fc-849fcc2986ce.png">

Freetype/Harfbuzz:
<img width="703" alt="Screen Shot 2019-03-27 at 12 01 26" src="https://user-images.githubusercontent.com/47046/55104698-218a5900-5088-11e9-842b-96fc4ae0c5c8.png">

Here's a build of master fb79b9ee89 if you want to try yourself:
[Inter-3.4-fb79b9ee89.zip](https://github.com/rsms/inter/files/3014873/Inter-3.4-fb79b9ee89.zip)
