### ISSUE TITLE
Fonts are renamed to have BETA but not reflected in CSS files

### ISSUE THREAD

**Issue by jensenbox** [rsms/inter#127]
**Describe the bug**

**To Reproduce**
1. Include CSS on an HTML page
2. Specify any font that has the word Light or Thin in it
3. Font will be broken

**Expected behavior**
Font to show as expected.

**Additional context**

This line https://github.com/rsms/inter/blob/33aca189225fff8e5f94838190f8ed10f5f9d8f3/Makefile#L215 is renaming the fonts but the CSS is not reflecting the renaming.

**Comment by rsms** [comment]
Fixed in https://github.com/rsms/inter/commit/034a240d75f2b94259385ece271226d7e16b0c34
