### ISSUE TITLE
Fonts not loading on interactive lab – 404 response

### ISSUE THREAD

**Issue by thundernixon** [rsms/inter#129]
**Describe the bug**

The interactive lab is not serving newly-built fonts.

**To Reproduce**

I've updated my local repo with `git pull --force`, to make sure I have all the latest updates, and  the latest commit is now `0b8f63c0`. I set up the dev environment with `./init.sh` and rebuilt the fonts with `make -j all_web`. This build fresh webfonts from the source.

However, when I use `python docs/lab/serve.py` to serve the interactive lab, it doesn't load the fonts, but rather falls back to the system serif font and gives me the following series of errors in my terminal:

```
▶ python docs/lab/serve.py
-----------------------------------------------------------------
serving at http://localhost:3002/
127.0.0.1 - - [11/Feb/2019 14:17:40] code 404, message File not found
127.0.0.1 - - [11/Feb/2019 14:17:40] "GET /inter.css HTTP/1.1" 404 -
127.0.0.1 - - [11/Feb/2019 14:17:41] code 404, message File not found
127.0.0.1 - - [11/Feb/2019 14:17:41] "GET /inter.css HTTP/1.1" 404 -
127.0.0.1 - - [11/Feb/2019 14:17:41] code 404, message File not found
127.0.0.1 - - [11/Feb/2019 14:17:41] "GET /fonts/const/Inter-UI-Regular.woff2?r=js0pzayh HTTP/1.1" 404 -
127.0.0.1 - - [11/Feb/2019 14:17:41] code 404, message File not found
127.0.0.1 - - [11/Feb/2019 14:17:41] "GET /fonts/const/Inter-UI-Italic.woff2?r=js0pzayh HTTP/1.1" 404 -
127.0.0.1 - - [11/Feb/2019 14:17:41] code 404, message File not found
127.0.0.1 - - [11/Feb/2019 14:17:41] "GET /fonts/const/Inter-UI-Regular.woff?r=js0pzayh HTTP/1.1" 404 -
127.0.0.1 - - [11/Feb/2019 14:17:41] code 404, message File not found
127.0.0.1 - - [11/Feb/2019 14:17:41] "GET /fonts/const/Inter-UI-Italic.woff?r=js0pzayh HTTP/1.1" 404 -
127.0.0.1 - - [11/Feb/2019 14:17:41] code 404, message File not found
127.0.0.1 - - [11/Feb/2019 14:17:41] "GET /fonts/const/Inter-Regular.woff2?r=js0pzb6c HTTP/1.1" 404 -
127.0.0.1 - - [11/Feb/2019 14:17:41] code 404, message File not found
127.0.0.1 - - [11/Feb/2019 14:17:41] "GET /font-files/Inter-Regular.woff2?r=js0pzb6c HTTP/1.1" 404 -
127.0.0.1 - - [11/Feb/2019 14:17:41] code 404, message File not found
127.0.0.1 - - [11/Feb/2019 14:17:41] "GET /fonts/const/Inter-Regular.woff?r=js0pzb6c HTTP/1.1" 404 -
127.0.0.1 - - [11/Feb/2019 14:17:42] code 404, message File not found
127.0.0.1 - - [11/Feb/2019 14:17:42] "GET /font-files/Inter-Regular.woff?r=js0pzb6c HTTP/1.1" 404 -
127.0.0.1 - - [11/Feb/2019 14:17:42] code 404, message File not found
```

I've tried to update the `@font-face` declarations in the index.html file to have (what I think are) the correct relative paths to the fonts in `build/`, but this isn't yet working with paths like these:

```
src: url('../build/fonts/const/Inter-BlackItalic.woff2') format('woff2'),
     url('./font-files/Inter-BlackItalic.woff') format('woff2'),
     url('../build/fonts/const/Inter-BlackItalic.woff') format('woff'),
     url('./font-files/Inter-BlackItalic.woff') format('woff');
```

**Expected behavior**

I expect to see the newest fonts in order to help me check updates to spacing and kerning.

**Screenshots**

After initializing and building fresh fonts:

![image](https://user-images.githubusercontent.com/7355414/52588320-2cf03080-2e0a-11e9-860e-b4d985f20e16.png)

![image](https://user-images.githubusercontent.com/7355414/52588280-134ee900-2e0a-11e9-9b2e-39934efccfff.png)

After updating `@font-face` paths, fonts still won't load, and I now get these errors:
![image](https://user-images.githubusercontent.com/7355414/52588292-1b0e8d80-2e0a-11e9-9f03-d29ea6c51a71.png)

**Environment**
- OS: macOS Mojave 10.14.3 (18D109)
- App that renders the font: Chrome
- Version of font Name: Inter Regular. 3.4;0b8f63c0a 

(P.S.: It wasn't clear to me at first that fontdrop.info was a website, so maybe this template could be updated to suggest the site as `https://fontdrop.info/`)

**Additional context**
I just updated my OS to the latest Mojave and had to brew reinstall Python3 to get `init.sh` working. Potentially, this could have crossed some other wires?

**Comment by rsms** [comment]
Oh shoot! I'm sorry — I discovered that the lab locally relies on a symlink to exist, which I guess I've just created manually. Adding a line to the serve script that makes sure it's there.

**Comment by thundernixon** [comment]
That made it work! However, I ran into another snag once I rebuilt fonts and wanted to serve them. 

I believe this is fixed by https://github.com/rsms/inter/pull/130.
