### ISSUE TITLE
Unable to use some OpenType features

### ISSUE THREAD

**Issue by noahsscott** [rsms/inter#132]
**Describe the bug**
Unable to use some OpenType features using V3.3 of Inter. Example "salt", "cv08", "cv09", "cv10". 

**To Reproduce**
Steps to reproduce the behaviour:
1. Display Inter UI using hosted CSS file
2. Set font for use 
3. Style Inter text with Opentype feature eg. `-webkit-font-feature-settings: "cv08";
    font-feature-settings: "cv08";`
4. Style is not applied

**Environment**
- macOS 10.14.2
- Chrome Version 72.0.3626.109
- Version 3.3

**Additional context**
I can see the styles applied here: https://rsms.me/inter/lab/?feat-salt=1&feat-cv08=1&feat-cv09=1&feat-cv10=1 but cannot reproduce them.

**Comment by hugmanrique** [comment]
I'm hitting this same issue, how did you fix it?

**Comment by garrettqmartin8** [comment]
Also having the same issue in Chrome (81.0.4044.129) with the `zero` feature, but it works in Firefox Developer Edition (76.0b8) and Safari (13.1). Also subsetted with `pyftsubset`, but I don't think that's the issue since it loads perfectly in other browsers.
