### ISSUE TITLE
Asterisk at the beginning of a line followed by a capital letter is in unexpected location

### ISSUE THREAD

**Issue by brandonhaslegs** [rsms/inter#133]
When starting a line with an asterisk followed by a capital letter, the asterisk is aligned with the x-height. This makes it awkward to make an asterisk footnote. #57 is a related issue.

![image](https://user-images.githubusercontent.com/4406983/53252729-e333ff80-36bf-11e9-9ad4-9254fce8e99e.png)

**Comment by rsms** [comment]
We should consider only substituting asterisk for asterisk.case when it's in between two case glyphs or at the end of a case glyph, rather than simply adjacent to a case glyph.

**Comment by thundernixon** [comment]
It should also be possible to start a footnote with a number*. 

Therefore, it might be important to limit the vertical centering for only happening between numbers, and (if possible – I now there are issues with this) allowing for it to allow for spaces between numbers and the asterisk.

Quick question here ... do you have an example of when a vertically-centered asterisk is useful for caps? For numbers, I can see why this is useful as a multiplication symbol, e.g. `8 * 3 = 24`. Is it common to use caps in math equations like this, or is there some other context you have in mind for it?

---

_*847, for example_

**Comment by rsms** [comment]
3b9675ecb71ddcadf6ce6add539a0ec881e5a7db fixes this by moving asterisk out from the more "opportunistic" contextual substitution. Now, /asterisk is only sub'd for /asterisk.case when it appears in between two numbers.

Examples of /asterisk → /asterisk.case:

- `3*9`
- `3 *9`
- `3  *9`
- `3* 9`
- `3 * 9`
- `3  * 9`
- `3*  9`
- `3 *  9`
- `3  *  9`

In all other cases, /asterisk is unchanged.

Note that /asterisk.case can still be explicitly enabled via `case`

<img width="581" alt="Screen Shot 2019-03-31 at 13 29 51" src="https://user-images.githubusercontent.com/47046/55294624-16516900-53b9-11e9-93ab-a7453b394401.png">
