### ISSUE TITLE
Cyrillic letters look weird in Inter Thin version

### ISSUE THREAD

**Issue by olegbv2019** [rsms/inter#134]
**Describe the bug**
Letters' width is very different in both small and capital letters with Cyrillic alphabet (e.g. Russian) in case of Inter Thin.

**To Reproduce**
1. Create a design on Canva
2. Type 'абгдеёжзийклмнопрстуфхцчшщъыьэюя' in Inter Thin font.

**Expected behavior**
No visible differences in width of different parts of letters
**Screenshots**
[https://drive.google.com/file/d/1eS5_YxbahntgXwmn-xIPi2JQKy92ORKl/view?usp=sharing](url)

**Environment**
- ChromeOS (v74)
- Canva
- "Inter Thin"

**Comment by rsms** [comment]
This is "intended" — the lighter weights are work in progress and most Cyrillic glyphs are work-in-progress (hence the "BETA" label in the font style names :–)

**Comment by reli-msft** [comment]
![image](https://user-images.githubusercontent.com/50213618/60473713-46601080-9c23-11e9-9e82-53a9053c3677.png)
So many corruptions 😢

**Comment by reli-msft** [comment]
There are even corruptions on diacritics
![image](https://user-images.githubusercontent.com/50213618/60473735-67286600-9c23-11e9-881e-dd988b71d796.png)

**Comment by rsms** [comment]
Closed in favor of #181
