### ISSUE TITLE
'RSMS' is not a known registered Microsoft Typography Vendor id

### ISSUE THREAD

**Issue by thundernixon** [rsms/inter#137]
Currently, Inter uses vendor ID `RSMS` in the OS/2 table: `<achVendID value="RSMS"/>`. However, this is not yet a registered vendor ID. This isn't a total _requirement_ for an OpenType font to be valid, but it would probably be worth registering the ID in case some software requires it. 

For example, Google FontBakery (QA for Google Fonts) will give a `warn` status if there is no registered vendor ID for a font, which will add noise to reporting.

Registration is free and instructions are at:

https://docs.microsoft.com/en-us/typography/vendors/

(You just need to send an email with contact info).

**Comment by rsms** [comment]
Done.
From Microsoft via email: "Your ID RSMS is registered and listed in the Registered typography vendors list."
https://docs.microsoft.com/typography/vendors
