### ISSUE TITLE
Inter version number doesn't conform to OpenType spec + Google Fonts recommendations

### ISSUE THREAD

**Issue by thundernixon** [rsms/inter#138]
## Summary

Currently, Inter sets the version number (OpenType nameID `5`) in the format of `3.4;678e5afc0`. 

While this meets the minimum requirement of the [OpenType name spec](https://docs.microsoft.com/en-us/typography/opentype/spec/name#name-ids) for nameID `5`, it doesn't quite meet the recommendation to include "Version" in the version string.

As FontBakery puts it:

> ℹ️ <b>INFO:</b> Check for font-v versioning
> 
> * [com.google.fonts/check/166](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/166)
> * ℹ️ **INFO** Version string is: "3.4;862d1a785"
> The version string must ideally include a git commit hash and either a 'dev' or a 'release' suffix such as in the example below:
> "Version 1.3; git-0d08353-release"

I'm having trouble finding exactly how the version string is added in Inter – editing the `openTypeNameVersion` custom parameter in `Inter.glyphs` doesn't seem to make it into output files, so I'm guessing that something else in the toolchain is updating this string, though I haven't found it yet.

## Expected behavior

At the very least, it should include `Version `, as MS points out that it is used in some installer software.

If possible, it should also probably take the format of `Version 1.3; git-xxxxxxx-<release/dev>`.

## Additional context
 
I am working with a `qa` branch in my Inter fork. If you wish to replicate these checks, I have included directions for reproducing my QA process. https://github.com/thundernixon/inter/tree/qa/misc/googlefonts-qa

The latest full round of FontBakery checks is at https://github.com/thundernixon/inter/tree/qa/misc/googlefonts-qa/checks

If it's preferable to PR this branch earlier rather than later, let me know. Otherwise, I'll try to get past as many issues as possible, then PR.

**Comment by thundernixon** [comment]
Probably a closely related issue:

> 🔥 <b>FAIL:</b> Checking font version fields (head and name table).
> 
> * [com.google.fonts/check/044](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/044)
> * 🔥 **FAIL** head version is ('3', '004'), name version string for platform 3, encoding 1, is ('3', '400') [code: mismatch]

When the font is TTXed, the specific code looks like the following.

Head table: 
```
<fontRevision value="3.004"/>
```

Name table:
```
<namerecord nameID="5" platformID="3" platEncID="1" langID="0x409">
      3.4;862d1a785
</namerecord>
```

If there is code updating the string number, it should be written to ensure these two version numbers match. I _think_ it will work equally well to do one of the following:

1. Add leading `0`s to the `name` table version. Including the suggestion above, this would make it  take the form `Version 3.004; git-862d1a78-dev`.

2. Remove the leading `0`s from the `head` table version. It would take the form `3.4`.

Either way, the top comment should be reflect in the `name` table – this comment is just about matching the number after the decimal.

**Comment by thundernixon** [comment]
Not that this is a 100% guarantee that it's the best possible solution, _but_ I pass both FontBakery checks when I manually insert the following:

```
<namerecord nameID="5" platformID="3" platEncID="1" langID="0x409">
      Version 3.4;862d1a785
</namerecord>
```

```
<fontRevision value="3.4"/>
```

**Comment by rsms** [comment]
Interesting!

The version is set using the `defcon` library by the `updateFontVersion` function of `fontbuild` in the following manner:

```py
ufo.info.versionMajor = versionMajor
ufo.info.versionMinor = versionMinor
# versionMajor = 3 (type int)
# versionMinor = 4 (type int)
```

The opentype name "version" record is set like this:

```py
font.info.openTypeNameVersion = "%s;%s" % (version, buildtag)
# version = "3.4"
# buildtag = "862d1a785"
```

Clearly the parser of Font Bakery has a bug when it interprets "4" as "400" ..?

If we are to work around that bug, I think the only thing we can do (less of changing or patching defcon) is to pad the minor version with zeros in the opentype name table record.

Thoughts? Fix FontBakery parser or hack around it with padded zeros?

**Comment by rsms** [comment]
Related: I wrote this piece of code some time ago for parsing font versions and wrote this unit test based on a large collection of real-world font version strings. Font versioning is _all over the place_, ha ha. https://github.com/rsms/fontctrl/blob/cd4dad328cd0/client/version_test.go

**Comment by rsms** [comment]
I just went ahead with the hack for now.
After a test build, the name record looks like this: `3.004;git-36084ac6f`

**Comment by thundernixon** [comment]
> Clearly the parser of Font Bakery has a bug when it interprets "4" as "400" ..?

You're right, that is a rather obvious bug. Thanks! I'll PR/report the issue on that end.

Thanks for matching the version numbers on your end, though! As far as I know (I'll install it in a few places to verify), that should work well. Also, it'll pass the existing FontBakery tests, which is helpful.
