### ISSUE TITLE
Weird kerning on /v

### ISSUE THREAD

**Issue by laurensiusadi** [rsms/inter#143]
**Describe the bug**
Kerning on right side of /v is too wide

**To Reproduce**
1. Go to https://rsms.me/inter/lab/
2. Write 'activity'
3. See kerning between /v /i
4. Happens on default setting (kerning on)

**Screenshots**

Problems on most of weight, gonna put few here just to demonstrate
Weight 100
![firefox_2019-03-22_21-27-01](https://user-images.githubusercontent.com/5661040/54829698-8ee56500-4ce9-11e9-82f0-a2f1698bab55.png)
Weight 400
![firefox_2019-03-22_21-27-14](https://user-images.githubusercontent.com/5661040/54829703-9147bf00-4ce9-11e9-947e-d79026795e63.png)
Weight 700
![firefox_2019-03-22_21-27-25](https://user-images.githubusercontent.com/5661040/54829706-9278ec00-4ce9-11e9-9e33-e36c33d5b8fb.png)
Weight 900 (this is okay)
![firefox_2019-03-22_21-27-35](https://user-images.githubusercontent.com/5661040/54829709-93aa1900-4ce9-11e9-8f58-99403c7f10bf.png)

**Expected behavior**
Should act like when kerning is off

![firefox_2019-03-22_21-30-56](https://user-images.githubusercontent.com/5661040/54830022-437f8680-4cea-11e9-81ef-05e6af5f28d4.png)
![firefox_2019-03-22_21-31-12](https://user-images.githubusercontent.com/5661040/54830026-44b0b380-4cea-11e9-86d2-8d3313562820.png)
![firefox_2019-03-22_21-31-21](https://user-images.githubusercontent.com/5661040/54830029-45e1e080-4cea-11e9-9544-8b5f2d9b0b8c.png)

**Environment**
- OS: Windows 10
- Firefox Quantum 65.0.2
- Version of font Inter-vjtk5lkby

**Additional context**
Also happens on downloaded font, and the one served via CDN

**Comment by rsms** [comment]
Nice catch. Thank you.
