### ISSUE TITLE
Feature Request: Add more stylistic alternates

### ISSUE THREAD

**Issue by hydino2085143** [rsms/inter#152]
I have a few stylistic alternates I'd like to see:

- Alternate lowercase 't' without the curve
- Alternate '@' symbol, which has an uppercase 'A' minus the crossbar in it.
- Alternate lowercase 'y' without the curve
- Alternate punctuation with squares instead of circles
-  Alternate lowercase 'j' without the tail
- Alternate uppercase 'Q' and 'R' with undulating tails
- Alternate lowercase and uppercase 'o & O' that look a bit more like a circle than an oval

A few of these ideas came from my own pet peeves about other fonts (I'm looking at you, Arial)

**Comment by eiszfuchs** [comment]
If we're talking about pet peeves, I'd like to throw the traditional variant of ß into the mix. I can't stand the Sulzbacher variant.

**Comment by Derpitron** [comment]
Well, I'm not well versed in German typographical quirks, so I can't say anything about this .

**Comment by Derpitron** [comment]
What does the 'icebox' label mean?

**Comment by eiszfuchs** [comment]
@Derpitron
There has been a change request before in the code-targeted monospace font, Iosevka. https://github.com/be5invis/Iosevka/issues/141
Though it was the other way around, street signs with the traditional ß still exist, are somewhat iconic to some German cities and the traditional ß is way more distinguishable from the Greek letter Beta than the "modern" one. But it's a stylistic choice after all.

**Comment by rsms** [comment]
So not this existing alt? https://rsms.me/inter/glyphs/?g=germandbls.1

**Comment by gmosx** [comment]
> * Alternate lowercase and uppercase 'o & O' that look a bit more like a circle than an oval

I would love to have this alternate (also with 'G', etc). Would make Inter a great Futura (or Google Sans) alternative.

**Comment by Derpitron** [comment]
I have another idea for variants. It's definitely impossible, but I would like to see atleast a specimen of Inter with the curves at the ends of characters like "t" being 45 degrees or 90 degrees. It's been an idea in my head for quite some time now.

**Comment by eiszfuchs** [comment]
@rsms Ah, sorry. No, not like this alternative. The traditional variant is more or less composed from ſ and ʒ.
https://de.wikipedia.org/wiki/%C3%9F#/media/Datei:Berliner_Strassenschilder.jpg
