### ISSUE TITLE
Bad right arrow glyph (U+2192) in medium/bold italics

### ISSUE THREAD

**Issue by jmk** [rsms/inter#154]
**Describe the bug**
The right arrow glyph (U+2192) looks incorrect in the medium-to-bold weight italics. The long arrow glyph is not affected.

**To Reproduce**
1. https://rsms.me/inter/lab/?size=24&weight=700&italic=1
2. Scroll down to the arrow glyphs near the bottom.

**Expected behavior**
The glyph should look like a normal right arrow, of course. :)

**Screenshots**
![Screen Shot 2019-05-08 at 11 48 51 AM](https://user-images.githubusercontent.com/177193/57400142-b4d6a400-7187-11e9-8c30-2d6d5d820486.png)

**Environment**
- OS: macOS 10.13, RHEL 7.4
- App: Safari (lab page), Qt (FreeType/Harfbuzz)
- Version: 3.005; git-f04932174

**Additional context**
It looks like this is due to bad interpolation between the regular and black weights (both of which are not affected). The variable font shows this pretty clearly -- I'm guessing this is a control point order thing?
![interpolated](https://user-images.githubusercontent.com/177193/57400190-cfa91880-7187-11e9-926f-f6b3cd173423.gif)

**Comment by rsms** [comment]
Good catch! Definitely a bug.

**Comment by rsms** [comment]
Fixed in d41fc8a
![xijdghusifjdf](https://user-images.githubusercontent.com/47046/58388402-34130700-7fd3-11e9-9209-5eb5f62bb580.gif)

**Comment by rsms** [comment]
Shipped with [release 3.6](https://github.com/rsms/inter/releases/tag/v3.6)

**Comment by jmk** [comment]
Beautiful. Thanks! 👍
