### ISSUE TITLE
Reduce letter-spacing for tabular numbers

### ISSUE THREAD

**Issue by josephers** [rsms/inter#157]
The tabular numbers feature is great, but the numbers look very far apart.

Is it possible to reduce the spacing to have a similar density as the non-tabular numbers, similar to the example below?

![058FC574-87FD-4B90-97E4-D8B643DE60F3](https://user-images.githubusercontent.com/773203/57648096-9828da80-7592-11e9-9482-31ba5a4365f6.png)

**Comment by superpapuche** [comment]
This seems perfectly normal. To enhanced legibility on a table (for instance a bill) the space between tabular number is always loose. 
![Capture d’écran 2019-05-14 à 10 25 07](https://user-images.githubusercontent.com/7056916/57682890-f4dbd200-7632-11e9-9d6c-264c9d971f41.jpg)

**Comment by rsms** [comment]
Thank you for the suggestion, but the spacing is as intended. You can alter the over-all spacing when you use the font. In CSS that would be `letter-spacing`.
