### ISSUE TITLE
Line height jump in Windows 10 MS Word with Inter variable font (v3.5)

### ISSUE THREAD

**Issue by thundernixon** [rsms/inter#158]
## Describe the bug

In MS Word on Windows 10, Inter variable gets really big line heights by default – about 2x the leading of most other fonts (Calibri, Segoe, Roboto, etc). 

The problem doesn't exist for Inter static (tested for Thin, Regular, and Black TTFs).

The problem is not affected by subsetting the font to a smaller glyph range.
- @m4rc1e verified that the vertical metrics are set normally (as do checks in FontBakery), and suggested that the line spacing might be due to certain glyphs in the font (e.g. a Chinese or Arabic glyph may cue different layout settings in Word). However, subsetting Inter variable to `--unicodes="U+0020-007F"` (176 basic Latin glyphs) doesn't solve the issue.

**Calibri vs Inter-Regular.ttf (static)**

With Inter Regular, a static TTF, the default line heights is very similar to those of other fonts in MS Word, on Windows. The sizing is slightly different, but it's within the normal body size range for sans-serif fonts. Here's the MS Word default font Calibri as a comparative font:

![image](https://user-images.githubusercontent.com/7355414/57875324-aa985380-77e0-11e9-97d9-52e690d5302e.png)

**Calibri vs Inter.var.tff (variable)**

The variable version has huge line heights – without any changes to the document line height settings (i.e. I haven't applied "double spacing" in Word).

![image](https://user-images.githubusercontent.com/7355414/57875332-b08e3480-77e0-11e9-903d-acf9aaea8f0d.png)

Individual Screenshots:

<details><summary><b>Calibri in MS Word</b></summary>

![image](https://user-images.githubusercontent.com/7355414/57869470-1e336400-77d3-11e9-93a2-956bf64a313d.png)

</details>

<details><summary><b>Inter 3.5 (variable)  in MS Word</b></summary>

![image](https://user-images.githubusercontent.com/7355414/57873252-acabe380-77db-11e9-89bb-fba48627a175.png)

</details>

<details><summary><b>Inter Thin 3.5 (static)  in MS Word</b></summary>

![image](https://user-images.githubusercontent.com/7355414/57874861-88520600-77df-11e9-9db1-462b7d5a147d.png)

</details>

<details><summary><b>Inter Regular 3.5 (static)  in MS Word</b></summary>

![image](https://user-images.githubusercontent.com/7355414/57869477-21c6eb00-77d3-11e9-821e-9777f834cc20.png)

</details>

<details><summary><b>Inter Black 3.5 (static)  in MS Word</b></summary>

![image](https://user-images.githubusercontent.com/7355414/57874910-a0c22080-77df-11e9-8603-5e4116b4ccef.png)

</details>

<details><summary><b>Inter, subset with 176 basic glyphs for test</b> (Click to expand)</summary>

![image](https://user-images.githubusercontent.com/7355414/57874107-d960fa80-77dd-11e9-8c30-3c075c9e7784.png)

</details>

## To Reproduce
1. Install a static instance of inter on Windows 10 (I use VMware for this)
2. Use Word to make a document, and change the font to Inter. The metrics should be fine.
3. Uninstall this static font file.
3. Try separately with a variable version of Inter 3.5, and notice the difference.

## Expected behavior

I expect Inter Variable to have consistent line heights with static versions, and with other fonts.

## Environment
- OS: Windows 10 Home Edition, version 1809, running in VMware on macOS 10.14.4]
- App: Word, in Office 365
- Version: Inter Regular. Version 3.005;git-f04932174 (Inter.var.tff)

## Additional context

I don't believe this should affect the merging of https://github.com/google/fonts/pull/1908, because this is likely a MS Word issue as much as it is a font issue. 

It would still be nice to pinpoint the specific cause of the problem so that we can avoid it in future versions of this and other variable fonts, but I'm hoping we can do that post-release to Google Fonts, and subsequently update.

## Note on testing different versions in Windows

Unfortunately,  this is somewhat challenging to test, because it is difficult to uninstall Inter Variable from Windows:

![image](https://user-images.githubusercontent.com/7355414/57873639-c994e680-77dc-11e9-9709-8ad86feb3f52.png)

[This article describes two potential fixes](https://www.fontsmith.com/faqs/132), but neither works for me.

My workaround: I've found more success in using `ttx -t name inter.var.ttf` to get the name table, editing the font names, using `ttx -m inter.var.ttf testinter.var.ttx` to merge in the updates, and then testing that modified version. This is a bit messy, but I'm on a virtual machine, so I can easily replace it with a fresh version in the future.

**Comment by thundernixon** [comment]
With @m4rc1e's help, I was able to understand what is happening here.

If Inter is stripped of its MVAR table (which provides metrics variations for things like line height, underline position, etc), the line height shows as expected:

![image](https://user-images.githubusercontent.com/7355414/57934850-82672e00-788e-11e9-8e05-b82153a45a1b.png)

_However,_  this is a known DirectWrite bug which is being worked on. We should not release Inter Variable without an MVAR table, as that would have side effects. So, we should release the fonts with the MVAR table intact, and if people run into issues in MS Word in the short term, they will have to use static files to get around it.

**Comment by thundernixon** [comment]
Update: in Windows 10 v1903 (currently an "insider preview"), this bug has been fixed:

![image](https://user-images.githubusercontent.com/7355414/58034912-a1b3c480-7af5-11e9-845d-1efb2ea1e697.png)
![image](https://user-images.githubusercontent.com/7355414/58034930-aed0b380-7af5-11e9-81a7-dee05bd55fe3.png)

Unfortunately, there are other issues with how Windows / Word handles the Upright and Italic VFs. For example: 
- the italic instances aren't fully linked. That is, "Italic" and "Bold Italic" do show up in the Windows Font Settings, but they aren't possible to apply in Word with the _`I`_ button.
- if you install the Italic VF before the Upright VF, the default "Inter" will be Inter Regular Italic, and Regular is unselectable. However, this isn't the case if Upright VF is installed first. 

These linking issues don't exist on Mac, and seem to be inconsistent even within Windows. So, I think that probably indicates that these are Windows/Word bugs that are (hopefully) being worked through.

**Comment by reli-msft** [comment]
@thundernixon Which Word version are you using? O365 or 2016?
