### ISSUE TITLE
add recommended 'stack' to readme and website

### ISSUE THREAD

**Issue by mesqueeb** [rsms/inter#160]
The recommended 'font stack' shown with each Google Fonts is really useful.

**What would be the recommended 'font stack' for Inter?**

Maybe this could also be added to the readme and website. 🙃

**Comment by rsms** [comment]
What do you mean with "stack"? [Font fallback](https://en.wikipedia.org/wiki/Fallback_font) chains..?

**Comment by mesqueeb** [comment]
Yes! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rsms** [comment]
It's a matter of personal opinion, so I don't think it fits within this project. Thank you.

**Comment by rsms** [comment]
Normally `font-family: Inter, -system-ui, sans-serif` is enough.

**Comment by mesqueeb** [comment]
Exactly what I was looking for!! Newer devs might not know that `-system-ui` is a good fall back font. 
 Thanks!! 😉🎉

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
