### ISSUE TITLE
case + calt does not replace -> with arrow

### ISSUE THREAD

**Issue by VasiliyRusin** [rsms/inter#161]
**Describe the bug**
First of all. I'm not sure what it's a bug, but it looks pretty bad. And according to the demo from the website, it should be nicer.

![image](https://user-images.githubusercontent.com/3685852/58184617-a4700e80-7cdb-11e9-807e-f24f3c7440eb.png)

If I use `font-feature-settings: 'case' 1;`, I lose alt case, but if I didn't use it, my symbols jump with a different case.

## UPD.
Now I absolutely sure that it's a bug. Most features of 'calt' work as expected with `font-feature-settings: 'case' 1;`. But **arrows** not. The demo was updated.

![image](https://user-images.githubusercontent.com/3685852/58248392-2f0d4800-7d86-11e9-8ab2-caa56675ba1b.png)

**To Reproduce**
Just watch [demo](https://jsfiddle.net/34g7aoxm/).

**Expected behaviour**
I hoped to get both of these. Fixed vertical position and alt case.

**Screenshots**
![image](https://user-images.githubusercontent.com/3685852/58183492-a20cb500-7cd9-11e9-8c83-54bdce717a94.png)

**Environment**
- OS: Windows 10 1809

- Chrome and Affinity Designer. But I suppose that it will be on any app.
- Current version from css file.

**Comment by reli-msft** [comment]
`font-feature-settings: 'case' 1;` will turn on `case` feature **only**. If you need `calt` you need to write `font-feature-settings: 'case' 1, 'calt' on;`

**Comment by VasiliyRusin** [comment]
> `font-feature-settings: 'case' 1;`включит **только**`case` функцию . Если вам нужно, вам нужно написать****`calt``font-feature-settings: 'case' 1, 'calt' on;`

First of all, `calt` is on by default. But even if I `on` it, it won't work. See extended [demo](https://jsfiddle.net/y92vxq31/1/)

**Comment by reli-msft** [comment]
@VasiliyRusin @rsms 
I see the problem: In lookup 39, `uni2192.case` is built up with `uni002D.case` and `uni003E`, where the latter glyph **should be** `uni003E.case`. This mistake also happened in other arrow combinations.

![image](https://user-images.githubusercontent.com/50213618/58274843-960c0c00-7d48-11e9-991e-3341027d6117.png)

**Comment by rsms** [comment]
Good catch!

**Comment by rsms** [comment]
With fix landed in 39213de:
<img width="1010" alt="Screen Shot 2019-05-26 at 16 15 04" src="https://user-images.githubusercontent.com/47046/58388267-9e2aac80-7fd1-11e9-87ab-68938dc2d8a4.png">

**Comment by rsms** [comment]
Shipped with [release 3.6](https://github.com/rsms/inter/releases/tag/v3.6)
