### ISSUE TITLE
Question about Linux installation

### ISSUE THREAD

**Issue by orschiro** [rsms/inter#163]
Dear all, 

I wanted to install the latest 3.6 version on Fedora Linux. 

I downloaded the Zip file and wanted to extract it to `~/.fonts`.

But now I am unsure which folders I need.

Which is the right font type version to be used under Linux?

The installation instructions only mention Windows and Mac. 

Thank you!

![image](https://user-images.githubusercontent.com/170947/58405109-fa8bdb80-8066-11e9-89fe-9712586b1316.png)

**Comment by rsms** [comment]
See https://github.com/rsms/inter/blob/master/misc/dist/install-linux.txt

**Comment by rsms** [comment]
TL;DR: The "Inter (OTF)" folder

(you may also try the TTF files, but the OTF files provides the slightly better cubic bezier curves)

**Comment by orschiro** [comment]
Thanks so much for adding the instructions! :-)
