### ISSUE TITLE
0 and O, lowercase letter I and uppercase letter L look almost the same. Please correct.

### ISSUE THREAD

**Issue by den32ds** [rsms/inter#164]
![изображение](https://user-images.githubusercontent.com/24569064/58631603-c83ee000-82eb-11e9-929a-40d5191819d1.png)

P.S. Thanks for the font, it is very similar to Helvetica, which I like very much

**Comment by rsms** [comment]
Enable ss02 https://rsms.me/inter/#features/ss02

**Comment by den32ds** [comment]
@rsms oh, thanks
