### ISSUE TITLE
Add "Warning Sign" icon to Inter

### ISSUE THREAD

**Issue by skuwamoto** [rsms/inter#168]
User interfaces often have to show people when there is a problem, and a "warning sign" character would be helpful.

https://www.fileformat.info/info/unicode/char/26a0/index.htm

**Comment by rsms** [comment]
A few variations in the wild
<img width="661" alt="Screen Shot 2019-06-17 at 10 31 25" src="https://user-images.githubusercontent.com/47046/59624251-1b39d500-90eb-11e9-831f-b5f95bce6cd9.png">

**Comment by Derpitron** [comment]
About the first sample, does that mean that we may be getting color characters for certain symbols? OpenType does support them, and also, I like the last one the best.

**Comment by rsms** [comment]
@Derpitron With "in the wild" I mean "in other fonts". The color bitmap glyph you see is from Apple Emoji.

**Comment by Porges** [comment]
@rsms I wonder if it would be possible to get a black-on-white version as well as the current white-on-black version?
