### ISSUE TITLE
backware slant for Ͽ (Unicode 03FF) in sources & builds

### ISSUE THREAD

**Issue by thundernixon** [rsms/inter#170]
**Describe the bug**
It seems that Ͽ (Unicode 03FF) is mirrored in the [current sources & builds of Inter](https://github.com/rsms/inter/tree/230d288015545f8f083190d98f22775efec9212b).

![image](https://user-images.githubusercontent.com/7355414/61161474-da5a9380-a4d1-11e9-82b1-a4d5eaa22a8f.png)

**Expected behavior**
Presumably, this character should slant forward, along with all other glyphs.

I assume that it has been only partially transformed, and possibly not yet corrected for the synthetic skewing. You may be waiting to correct the skew along with overall italic refinement.

**Additional context**
I came across this issue as part of my exploration in https://github.com/rsms/inter/issues/169.

**Comment by rsms** [comment]
<img width="1832" alt="Screen Shot 2019-07-18 at 18 55 49" src="https://user-images.githubusercontent.com/47046/61503723-b265a700-a98d-11e9-9af9-ae48766b96a5.png">
