### ISSUE TITLE
Add alternate square-shaped punctuation

### ISSUE THREAD

**Issue by rellikmil** [rsms/inter#178]
Please add square full stop like this as OpenType feature
![изображение](https://user-images.githubusercontent.com/24569064/61795437-1542bc80-ae2c-11e9-939d-73d5986fdbae.png)

**Comment by Derpitron** [comment]
This would be a very subtle, but nice idea!

**Comment by rsms** [comment]
I _think_ that what you're asking for is square-shaped (or at least rectangle-shaped) punctuation. Inter contains hundreds of different glyphs that uses "dots" and "stop-like" shapes. The style of Inter is to use discs rather than rectangles for this, so what you are asking for is a pretty big deal — a change to the style and personality of the typeface.

This will probably not happen, but I will keep this request around for the future.

**Comment by alexmyczko** [comment]
Yeah it's also on i, !, ? and many more places, I'd merge this with the Helvetica R :) (couldn't find it anymore)

**Comment by den32ds** [comment]
Yeah, Inter almost equals Helvetica, so needs square-shaped punctuation

**Comment by Derpitron** [comment]
Yes, in my opinion, Inter has many good alternates, and it's almost like the swiss army knife of open sourced sans fonts. It can be put in as alternates, and if someone doesn't want them, they don't have to see them, although it'll definitely be a pain if you want to make stuff like cvXX features, as you'll have to individually make each character again.

**Comment by Derpitron** [comment]
@rsms, If someone were to make squared shaped punctuation for Inter as stylistic alternates, and they would include it in a pull request, would you include it?

**Comment by rsms** [comment]
It's happening. Get a test build here and let me know how what you think: [https://d.rsms.me/tmp/Inter-4.0-40095970e5.zip](https://d.rsms.me/tmp/Inter-4.0-40095970e5.zip)

![einrst8re](https://github.com/rsms/inter/assets/47046/8491e5fd-e9d7-41e2-a170-9c86c8d3bc07)

![sqpunc-400](https://github.com/rsms/inter/assets/47046/050547c7-6509-4c1f-9da7-576f9fd6441b)

**Comment by rellikmil** [comment]
Which OpenType feature is responsible for this?

**Comment by rsms** [comment]
@rellikmil ss07

**Comment by rsms** [comment]
> How much work did it take for you to make all of this?

I got Covid so it “bought me” three full days, which I rarely get otherwise. First iteration was done at Denver airport where I had a two hour layover:

![IMG_7326 Edited](https://github.com/rsms/inter/assets/47046/a00417ce-f894-4f20-888d-403e07b80586)

**Comment by rellikmil** [comment]
![изображение](https://github.com/rsms/inter/assets/24569064/ad84f64a-e4ba-45d3-b2ca-e56746920806)
Yes, it's working fine, thank you. I tried it in LibreOffice (Word is difficult to work with OpenType)
I'm also honored that you haven't forgotten my issue after four years.

**Comment by rsms** [comment]
> I'm also honored that you haven't forgotten my issue after four years.

This has been a popular feature request voiced my many. Thanks for filing an issue for it back in 2019
