### ISSUE TITLE
Cyrillic "a" does not have alt case

### ISSUE THREAD

**Issue by VasiliyRusin** [rsms/inter#179]
**To Reproduce**
See [https://jsfiddle.net/a04teq91/](https://jsfiddle.net/a04teq91/)

**Expected behavior**
Same a letter as Latin.

**Screenshots**
![image](https://user-images.githubusercontent.com/3685852/61928898-1860b880-afa4-11e9-9476-492bd748f292.png)

**Environment**
- OS: Windows 10
- Chrome
- Actual CDN version.

**Comment by rsms** [comment]
That would be U+0430, yes?

**Comment by VasiliyRusin** [comment]
I'm not sure that it's "enhancement". 

According to the Inter site data any "a" sing should have alt case, and maybe I'm wrong but I think it worked as expected in the previous releases.

![image](https://user-images.githubusercontent.com/3685852/62420843-383e5d80-b6c3-11e9-9688-42423855e37c.png)
