### ISSUE TITLE
Improve light for Greek, Cyrillic and other “extended” letters

### ISSUE THREAD

**Issue by be5invis** [rsms/inter#181]
![image](https://user-images.githubusercontent.com/240091/62436811-abf95e00-b6f5-11e9-911b-7d791688aee3.png)
![image](https://user-images.githubusercontent.com/240091/62436840-c5020f00-b6f5-11e9-821c-75b455f7d216.png)

**Comment by Derpitron** [comment]
I think this is the result of interpolation for thin styles.

**Comment by cssobral2013** [comment]
This, in fact, happens in all non-Basic Latin glyphs.

**Comment by rsms** [comment]
Good progress has been made on these improvements with #215 which landed in master as ed61e4e022fec206b6120f1e438c6bd8d5dab42b

**Comment by rsms** [comment]
Sample of what is now in master: https://rsms.me/etc/inter-thin-wip-20191127.html

These improvements will be included in the next release toward the end of the year. 

![inter-thin-wip](https://user-images.githubusercontent.com/47046/69768856-321f3180-1137-11ea-9ec3-2b7d623dfcc8.png)

**Comment by rsms** [comment]
More progress has been made on this in #218 which just landed in master.
 
Samples:
![ds0k01213](https://user-images.githubusercontent.com/47046/70417693-a484f100-1a16-11ea-9546-ef1289fbb829.png)

**Comment by rsms** [comment]
Okay folks. I think that with @KatjaSchimmel’s latest work in #219 which just landed in master we can close this out.

Attached is a PDF sheet overview of all glyphs in the Thin font master (which is in git master right now) as well as a build of git master.
[Inter-3.12-0cc708d7cb.zip](https://github.com/rsms/inter/files/4060289/Inter-3.12-0cc708d7cb.zip)
[Inter-thin-glyphs.pdf](https://github.com/rsms/inter/files/4060290/Inter-thin-glyphs.pdf)

**Comment by KatjaSchimmel** [comment]
Hey hey! I just saw that the _Inter-thin-glyphs.pdf_ is still showing the interpolation errors. I quickly made another PDF with the current state of the Thin master: 
[Inter-thin-glyphs-2.pdf](https://github.com/rsms/inter/files/4063675/Inter-thin-glyphs-2.pdf)

**Comment by be5invis** [comment]
@KatjaSchimmel PERFECT!

**Comment by peczony** [comment]
@rsms asked me to repost the bug from #214 here:

![](https://camo.githubusercontent.com/56932216711bedad0aea07a6b6fc195386cb99e4/68747470733a2f2f692e696d6775722e636f6d2f436944707168452e706e67)

Accents in Cyrillic should be placed in the same place as in Latin (sometimes Cyrillic accents are indeed placed a bit farther to the right than Latin accents, but not that far)

**Comment by peczony** [comment]
See some good examples from Vollkorn, STIX Two, Source Serif Pro, PT Sans

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/3784544/90529268-346d6400-e17c-11ea-8d45-8b57563800b5.png">

**Comment by rsms** [comment]
@peczony Thanks! Would you mind pasting the sample text you are using in between `\`` ... `\``

**Comment by peczony** [comment]
Sorry for the late reply. Here it is.
 
```
Latin á Cyrillic а́
```

Also, an accentuated version of the sample text you included earlier might be of some help:

```
Ру́сские лю́бят гото́вить еду́ и угоща́ть свои́х госте́й. В традицио́нном ру́сском обе́де три основны́х блю́да. Пе́рвым блю́дом всегда́ быва́ет суп.

РУ́ССКИЕ ЛЮ́БЯТ ГОТО́ВИТЬ ЕДУ́ И УГОЩА́ТЬ СВОИ́Х ГОСТЕ́Й. В ТРАДИЦИО́ННОМ РУ́ССКОМ ОБЕ́ДЕ ТРИ ОСНОВНЫ́Х БЛЮ́ДА. ПЕ́РВЫМ БЛЮ́ДОМ ВСЕГДА́ БЫВА́ЕТ СУП.
```

**Comment by VladWinner** [comment]
@peczony @rsms The problem with displaying accents in Cyrillic vowels can even be denoted as a separate issue. For reference, you can see how changes are made to other fonts such as Noto Sans and PT Root UI (also was done by Russian typographers).
![image](https://user-images.githubusercontent.com/13555921/103464571-d8c7ff80-4d45-11eb-9ee8-46da6b15e551.png)
![image](https://user-images.githubusercontent.com/13555921/103464709-d0bc8f80-4d46-11eb-9edf-f16c9548d84d.png)

**Comment by JapanYoshi** [comment]
#502 is relevant to this issue, methinks.

**Comment by Derpitron** [comment]
> #502 is relevant to this issue, methinks.

Not really. #502 is caused because some Greek glyphs are still based off of the old Roboto designs, which are more humanist (i.e more variable stroke width)

**Comment by rsms** [comment]
Greek tracked in https://github.com/rsms/inter/issues/502#issuecomment-1575166636 and has been completed.
