### ISSUE TITLE
Distinguish between lowercase l and uppercase I

### ISSUE THREAD

**Issue by brandonhaslegs** [rsms/inter#182]
Sometimes designers make the lowercase l a bit higher than the uppercase I or a bit thinner to make a distinction between the two. Inter has them at the exact same height and width making them indistinguishable. I know there are stylistic alternates with a curvy l and serifed I, but that has a totally different vibe than the simplicity of the default set.

![image](https://user-images.githubusercontent.com/4406983/62528249-d275e100-b83c-11e9-8655-c0f1299d7cc2.png)

**Comment by Derpitron** [comment]
What would be your solution, then? As you said, the serif 'I' and the curve-tail 'l' don't match Inter's default style.

**Comment by rsms** [comment]
You can opt in to lower case L with a tail using OpenType features: [`cv05`](https://rsms.me/inter/#features/cvXX) for the `l` alone or [`ss02`](https://rsms.me/inter/#features/ss02) for a whole set of “disambiguation” alternate glyphs.

**Comment by efstajas** [comment]
> make the lowercase l a bit higher than the uppercase I or a bit thinner to make a distinction between the two.

Sorry to open this back up, but I think that this would actually be a solid improvement. I realize that there's the l with tail alt, but as we all seem to agree, it's a departure from Inter's default style. Slightly bumping the height & thinning up the lower-case L would probably improve disambiguation while keeping simplicity.

**Comment by brandonhaslegs** [comment]
@rsms I know it has those alternates (I mentioned them in my original comment).

I just thiiiink it's unheard of to make the `I` and `l` identical. Was suggesting a change to the width or height of the `l`.
