### ISSUE TITLE
Thinspace and Narrow No-Break Space

### ISSUE THREAD

**Issue by maybegeek** [rsms/inter#185]
**Describe the bug**

* `Thinspace` should be narrower than `Space`.
* `Narrow No-Break Space` should be around the width of `Thinspace`.

**To Reproduce**

metrics from release version 3.9

**fullname** | **em** | **thinspace** | **space** | **nbsp** | **nnbsp**
-----|-----|-----|-----|-----|-----
Inter Black Italic | 2816 | 868 | 560 | 560 | 860
Inter Black | 2816 | 868 | 560 | 560 | 864
Inter Bold Italic | 2816 | 746 | 653 | 653 | 833
Inter Bold | 2816 | 746 | 653 | 653 | 835
Inter Extra Bold Italic | 2816 | 807 | 606 | 606 | 846
Inter Extra Bold | 2816 | 807 | 606 | 606 | 850
Inter Extra Light BETA | 2816 | 443 | 792 | 792 | 763
Inter Extra Light Italic BETA | 2816 | 443 | 792 | 792 | 765
Inter Italic | 2816 | 564 | 792 | 792 | 792
Inter Light BETA | 2816 | 503 | 792 | 792 | 778
Inter Light Italic BETA | 2816 | 503 | 792 | 792 | 778
Inter Medium Italic | 2816 | 625 | 746 | 746 | 806
Inter Medium | 2816 | 625 | 746 | 746 | 806
Inter Regular | 2816 | 564 | 792 | 792 | 792
Inter Semi Bold Italic | 2816 | 686 | 699 | 699 | 819
Inter Semi Bold | 2816 | 686 | 699 | 699 | 821
Inter Thin BETA | 2816 | 382 | 792 | 792 | 749
Inter Thin Italic BETA | 2816 | 382 | 792 | 792 | 751

**Expected behavior**

* `Thinspace` should be narrower than `Space`.
* `Narrow No-Break Space` should be around the width of `Thinspace`.

As small space between abbreviations `z. B.`, `d. h.` or between `S. 12` (page 12) or in french spacing `espace fine insécable`.

**Additional context**

The Unicode Standard, Version 12.1 (Code Chart for General Punctuation):

[https://www.unicode.org/charts/PDF/U2000.pdf](https://www.unicode.org/charts/PDF/U2000.pdf) page 3 and 4.

* (2009) THIN SPACE, a fifth of an em (or sometimes a sixth)
* (202F) NARROW NO-BREAK SPACE, a narrow form of a no-break space, typically the width of a thin space or a mid space

thanks,
christoph

**Comment by rsms** [comment]
Thank you :-)

**Comment by rsms** [comment]
<img width="682" alt="Screen Shot 2019-09-06 at 19 45 12" src="https://user-images.githubusercontent.com/47046/64468913-e8e2b700-d0de-11e9-9726-93d43c7aee1e.png">
<img width="670" alt="Screen Shot 2019-09-06 at 19 45 23" src="https://user-images.githubusercontent.com/47046/64468914-eaac7a80-d0de-11e9-92e9-00ce22197c9e.png">
<img width="693" alt="Screen Shot 2019-09-06 at 19 45 18" src="https://user-images.githubusercontent.com/47046/64468916-ec763e00-d0de-11e9-8e90-3cba3eddb7d7.png">
