### ISSUE TITLE
Xcode Install to help iOS usage

### ISSUE THREAD

**Issue by sowenjub** [rsms/inter#190]
I'm planning to use the font in an upcoming app and thought I could share some helper code for other iOS devs who'd want to use it since it always takes more time than it should (especially because there's often a missmatch between font file names and font names).

This could find its place on the website and/or in an install text file.

First, the text to modify the `Info.plist` file (as explained [here](https://developer.apple.com/documentation/uikit/text_display_and_fonts/adding_a_custom_font_to_your_app))

    <key>UIAppFonts</key>
	<array>
		<string>Inter-Bold.otf</string>
		<string>Inter-Regular.otf</string>
		<string>Inter-SemiBoldItalic.otf</string>
		<string>Inter-Medium.otf</string>
		<string>Inter-Thin-BETA.otf</string>
		<string>Inter-ExtraLight-BETA.otf</string>
		<string>Inter-Light-BETA.otf</string>
		<string>Inter-ExtraLightItalic-BETA.otf</string>
		<string>Inter-SemiBold.otf</string>
		<string>Inter-BlackItalic.otf</string>
		<string>Inter-MediumItalic.otf</string>
		<string>Inter-Black.otf</string>
		<string>Inter-Italic.otf</string>
		<string>Inter-ExtraBold.otf</string>
		<string>Inter-LightItalic-BETA.otf</string>
		<string>Inter-ExtraBoldItalic.otf</string>
		<string>Inter-BoldItalic.otf</string>
		<string>Inter-ThinItalic-BETA.otf</string>
	</array>

Then a helper extension

```
enum CustomFont: String {
    case interBold = "Inter-Bold",
    interRegular = "Inter-Regular",
    interSemiBoldItalic = "Inter-SemiBoldItalic",
    interMedium = "Inter-Medium",
    interThinBETA = "Inter-ThinBETA",
    interExtraLightBETA = "Inter-ExtraLightBETA",
    interLightBETA = "Inter-LightBETA",
    interExtraLightItalicBETA = "Inter-ExtraLightItalicBETA",
    interSemiBold = "Inter-SemiBold",
    interBlackItalic = "Inter-BlackItalic",
    interMediumItalic = "Inter-MediumItalic",
    interBlack = "Inter-Black",
    interItalic = "Inter-Italic",
    interExtraBold = "Inter-ExtraBold",
    interLightItalicBETA = "Inter-LightItalicBETA",
    interExtraBoldItalic = "Inter-ExtraBoldItalic",
    interBoldItalic = "Inter-BoldItalic",
    interThinItalicBETA = "Inter-ThinItalicBETA"
}

extension UIFont {
    convenience init?(customFont: CustomFont, size: CGFloat) {
        self.init(name: customFont.rawValue, size: size)
    }
}
```

Usage : `UIFont(customFont: .interRegular, size: 12)`

**Comment by Derpitron** [comment]
This seems helpful for iOS devs. @rsms Please add this to the website, or under some installation instructions!

**Comment by rsms** [comment]
I usually don’t add these sort of specialized instructions, because they quickly fall out of date, or does no apply to a different use case (for example someone using Objective-C instead of Swift, macOS instead of iOS, or an older Xcode version.) Plus, maintenance is complicated.

A quick google search led me straight to this seemingly good article: https://developer.apple.com/documentation/uikit/text_display_and_fonts/adding_a_custom_font_to_your_app

**Comment by sowenjub** [comment]
Well, I linked to that very article in my original post.
Opportunistic clicking will lead you to installing the fonts on mac/win, you don't even need a quick google search ;)

Also at this point it's not really more specialized than the Linux/Mac/Win/Mac instructions:
* the Info.plist structure is unlikely to change
* the macOS/iOS is likely just a matter of NSFont vs UIFont, and the most interesting part of the code are the actual names/string one need to use
* Swift is now a mature language and Objective-C devs would still find some value in the plist and the font names

Due to the BETA nature of some fonts, updating font names each time would certainly require extra maintenance ; or one could just add a couple more lines in the install-xcode.txt to explain how to handle a name discrepancy, which I was ready to draft (still am, but not pushing for it, I just wanted to share my take on your concerns).

Anyway, thanks for this wonderful font and considering this suggestion. Cheers.
