### ISSUE TITLE
Incorrect stroke thicknesses in all weights below 400 Regular and their Italics (except in Basic Latin glyphs)

### ISSUE THREAD

**Issue by cssobral2013** [rsms/inter#192]
**Describe the bug**
As per title, the stroke thicknesses in all weights below 400 Regular and their Italics are uneven (mainly in non-Basic Latin glyphs), some are even defective

**To Reproduce**
- In your app, select Light, ExtraLight, or Thin (or their Italics)
- Type any glyph, other than Basic Latin

**Expected behavior**
Stroke thicknesses should be right, mainly in non-Basic Latin glyphs

**Environment**
All OSes, apps and versions from 3.0 onwards display this problem

**Comment by cssobral2013** [comment]
P.S. I comprehend these are in Beta, only I've opened an issue to make this clear.

**Comment by Derpitron** [comment]
This issue has already been opened before, and we are working on it. #181
