### ISSUE TITLE
Positioning of bars in upper-case F, E, H, B

### ISSUE THREAD

**Issue by zbjornson** [rsms/inter#194]
**Describe the bug**
I'm not sure if this is a bug, but it looks like the position of the bars in upper-case F, E, H and B is not ideal at 11px on Windows. They straddle two pixels, creating a fuzzy, thick appearance. By comparison, Segoe aligns the bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/469365/63734637-e6a47100-c831-11e9-96df-25acdd82ff81.png) ![image](https://user-images.githubusercontent.com/469365/63734698-253a2b80-c832-11e9-9da4-ad8cb2a7fde7.png)

**Environment**
The above screenshots are from modifying rsms.me/inter.
- OS: Windows 10
- App that renders the font: Chrome 76, Firefox 70 and Edge 18 all have the same behavior
- Version of font: Inter var 3.9 (as used on rsms.me/inter)

Thanks!

**Comment by Jeremiidesu** [comment]
I could suggest in this case to use the hinted fonts: 
![image](https://user-images.githubusercontent.com/20820425/63896842-ae4c9080-c9f3-11e9-8ccd-8bab1edfd7af.png)
Windows 10, Notepad app
![image](https://user-images.githubusercontent.com/20820425/63896981-05526580-c9f4-11e9-943f-1e215c971adf.png)
Windows 10, Chrome 76

**Comment by rsms** [comment]
What @Jeremiidesu proposes is the solution you are looking for (use fonts with hinting programs in them, which is what is happening with Segoe UI in your example.)

**Comment by rsms** [comment]
Note that because of software immaturity, the variable fonts are not available with hints, so you’ll want to use the constant font files instead.
