### ISSUE TITLE
No font weights seemingly available on Windows 10 (variable font)

### ISSUE THREAD

**Issue by Jeremiidesu** [rsms/inter#195]
**Describe the bug**
No font weights are seemingly available, defaulting to a single 'Regular' weight name, having the thinnest upright version displayed. Additionally, all 18 instances of the variable font show up as being named "Regular" in the Windows font settings

My guess is, due to the latter bug, "client apps" only see the first instance, upright Thin, and think of it as Regular

**To Reproduce**
1. Install the font on Windows 10
2. Set it in Notepad

**Expected behavior**
Proper weight description (Thin, Light ...) with corresponding italics

**Screenshots**
![Screenshot of Notepad](https://user-images.githubusercontent.com/20820425/63894391-d5ec2a80-c9ec-11e9-828d-7f338a8a6c01.png)
Inter in Notepad

![Screenshot of the instance list](https://user-images.githubusercontent.com/20820425/63894429-e7cdcd80-c9ec-11e9-9a32-58f3fa64a651.png)
List of instances as reported by Windows

**Environment**
- OS: Windows 10 1903 (build 18362.239)
- App that renders the font: tested with Notepad and JetBrains Rider with the same results
- Version of font: Inter Regular. Version 3.009;git-2c0637eac (variable, dual axis)

**Comment by rsms** [comment]
Try using the single-axis variable fonts instead. Multi-axis fonts are not well supported at this time.

- Single-axis: Inter-upright.var.ttf, Inter-italic.var.ttf
- Multi-axis: Inter.var.ttf

See https://github.com/rsms/inter/blob/c130c691f579613490dabfe2da9bd7b2a562e70b/misc/dist/variable.txt which is included in the release ZIP file

**Comment by rsms** [comment]
Note that it’s also possible that these apps don’t support variable fonts _at all_ in which case you need to use the constant/static font files instead.
