### ISSUE TITLE
q is slanted the wrong way

### ISSUE THREAD

**Issue by domoritz** [rsms/inter#198]
**Describe the bug**

<img width="144" alt="Screen Shot 2019-09-09 at 11 38 05" src="https://user-images.githubusercontent.com/589034/64557421-5fa5cd00-d2f6-11e9-806e-7bf298529b9f.png">

**To Reproduce**

https://rsms.me/inter/lab/?varWeight=490&varSlant=10&varfont=1

**Environment**
- OS: macOS
- Browser: Chrome

**Comment by lordsutch** [comment]
I can verify this is also the case with macOS 10.14.6 using Inter.var.ttf, at least in the following apps:
* Chrome (77.0.3865.75)
* Font Book
* LibreOffice Writer
The problem does not occur in Firefox (70.0b6), but this is likely because Firefox can't slant the two-way variable font at all.

The problem is _not_ present in Inter-italic.var.ttf.

My _guess_ is that the problem is the result of the q glyph just being a mirror of the p glyph, and the two-way variable font not accounting for the mirroring when applying the slant. Now whether this is a macOS bug or a bug in the font itself, I can't say.

**Comment by lordsutch** [comment]
I can report that this problem also exists on Chrome OS 76.0.3809.136, suggesting either the bug is shared between macOS and Chrome OS (and presumably all Freetype-based font rendering implementations) or it is a font bug.

**Comment by ToadKing** [comment]
I also experience the bug on Windows 10 in both Firefox Beta 70.0b9 and Chrome Dev 78.0.3904.17. Microsoft Edge 44.18362.329.0 does not show the bug.

**Comment by jcbp** [comment]
I experience the bug on Linux Mint Tessa (19.1) in Firefox 69.0.1 and Chromium 76.0.3809.100.
I also experience the bug with the opening exclamation mark (¡)

![imagen](https://user-images.githubusercontent.com/892388/65707545-2645bf00-e063-11e9-8a75-0ce7618d92e2.png)

**Comment by thundernixon** [comment]
> the problem is the result of the q glyph just being a mirror of the p glyph

Right, mirrored components don't work as expected with transformations. I'm not sure of the precise reason for this, but basically, it just is treated as a reference to the "parent" glyph, and mirrors that glyph's transformations.

This regressed between release `3.8` to `3.10`. So, my guess is, the error was introduced either in `makefile` or `misc/fontbuild`, possibly with the introduction of the `compact-font-names` flag.

There is a function in the `misc/fontbuild` script that is meant to go through glyphs and decompose mirrored components, when generating UFOs to prep for the variable font. This function solved this problem previously.

From what I can tell by adding print statements into `misc/fontbuild`, the `composedGlyphIsNonTrivial()` function is never run. I assume this should probably be run as part of the `make designspace` flow.

**Comment by rsms** [comment]
This was a regression introduced in a recent upgrade of one of the 3rd party libraries used by fontbuild (fontmake).

**Comment by rsms** [comment]
Here is a build from master as is at the time of writing this comment.
[Inter-3.11-ba71122abf.zip](https://github.com/rsms/inter/files/3758073/Inter-3.11-ba71122abf.zip)

**Comment by rsms** [comment]
New release is out that includes a fix: https://github.com/rsms/inter/releases/tag/v3.11
