### ISSUE TITLE
BETA suffix is making the font hard to use in WPF

### ISSUE THREAD

**Issue by jankrib** [rsms/inter#199]
WPF interprets the inter font as two fonts. One named "Inter" and one named "Inter BETA".
This means that when styling text some weights work on the "Inter" font and some work on "Inter BETA". This makes it cumbersome to work with this font.

Is the BETA suffix really necessary? Isn't it cleaner to just have this documented on the website?

**Comment by rsms** [comment]
What is "WPF”? The “BETA” suffix is only part of the style name—the family name is the same in all fonts (“Inter”). Perhaps the software in question doesn’t handle font family names, or chooses to only deal with font style names for organization?

The BETA suffix is indeed necessary and even not enough — I get a steady stream of feedback from people surprised that the light weights have some seemingly broken glyphs. The light weights are work in progress and are released only as a beta version.

We are working on bringing the light weights to a production level this fall, so stay tuned!

> I’m keeping this issue open for now, to investigate what “WPF” is and what, if anything, can be done to help that software.

**Comment by be5invis** [comment]
WPF is https://github.com/dotnet/wpf, an (old) GUI framework for Windows.
WPF will preprocess the font names and "move" the BETA tag into the family name so the styles would fit into the weight-width-slantness model.

**Comment by fdwr** [comment]
@be5invis Yeah, WPF is stuck using the weight/width/slope model, and so these will remain distinct family groupings because there is no "beta" axis in WWS. IIRC, WPF >=4.0 used DirectWrite, and <4.0 used its own font parsing code, but the algorithm is identical (and publicly documented by Mikhail Leonov on the WPF text blog in a PDF).

**Comment by jankrib** [comment]
Sorry for not following up on this. Thanks to @be5invisand and @fdwr for clarifying the issue. I guess it's not worth fixing if it's only a problem in WPF. I'll include the workaround for reference if someone is struggling with the same issue and stumbles over this thread.

```
<Resources>
    <FontFamily x:Key="Inter">pack://application:,,,/<assembly>;component/Fonts/#Inter</FontFamily>
    <FontFamily x:Key="InterBeta">pack://application:,,,/<assembly>;component/Fonts/#Inter BETA</FontFamily>
</Resources>
```

Basically just treating Inter as two different fonts where only some combinations of FontFamily and FontWeight is valid.

**Comment by rsms** [comment]
Next release drops “BETA” from light styles
