### ISSUE TITLE
Variable fonts report incorrect version

### ISSUE THREAD

**Issue by lordsutch** [rsms/inter#202]
**Describe the bug**
In the Inter-3.10.zip archive, the variable fonts report a version of "1.0.0;git-src" rather than "3.010;git-aca7606f2" as shown by the other OpenType/TrueType font files. This makes it difficult to tell if the installed versions of the variable fonts are out of date.

It appears that the updateFontVersion() call in VarFontProject._build_interpolatable_masters() at https://github.com/rsms/inter/blob/master/misc/fontbuild#L185 does not have the intended effect of updating the version information in the variable font.

**To Reproduce**
Steps to reproduce the behavior (at a command line):
1. Run (e.g.) otfinfo -v Inter\ \(OTF\)/Inter-Italic.otf
2. Run (e.g.) otfinfo -v Inter\ \(TTF\ variable\)/Inter-italic.var.ttf

**Expected behavior**
Both otfinfo commands should show the same output: "Version 3.010;git-aca7606f2"

**Environment**
- OS: macOS 10.14.6 - but this should be OS-agnostic
- Version of font: 3.10 (3.010;git-aca7606f2)

**Comment by rsms** [comment]
Thank you. This is a know bug in the latest release. It’s due to changes to a library that the build toolchain uses and we’re working on a fix.

**Comment by rsms** [comment]
This was a regression introduced in a recent upgrade of one of the 3rd party libraries used by fontbuild (fontmake).

Here is a build from master as is at the time of writing this comment.
[Inter-3.11-ba71122abf.zip](https://github.com/rsms/inter/files/3758073/Inter-3.11-ba71122abf.zip)

**Comment by rsms** [comment]
New release is out that includes a fix: https://github.com/rsms/inter/releases/tag/v3.11
