### ISSUE TITLE
Inter’s copyleft symbol codepoint might not be the right unicode codepoint …

### ISSUE THREAD

**Issue by fooness** [rsms/inter#203]
I just wondered, is it possible that the unicode codepoint which is assigned to the copyleft symbol might not be the correct codepoint?

Inter website: https://rsms.me/inter/glyphs/?g=copyleft

Links to: https://codepoints.net/U+1F16C

See: https://www.fileformat.info/info/unicode/char/1f12f/index.htm

**Comment by rsms** [comment]
Good catch. Thank you

**Comment by rsms** [comment]
New release is out that includes a fix: https://github.com/rsms/inter/releases/tag/v3.11
