### ISSUE TITLE
double hyphen (--) to em dash (—)

### ISSUE THREAD

**Issue by harrisonlo** [rsms/inter#205]
I did notice that this would possibly clash with the --> or ---> arrows, but I think more people want to type em dash than the long arrows? (-> still works)

**Comment by rsms** [comment]
Not supporting this transformation was a conscious decision. Sometimes you may want “--“ (to hyphens) which would make it hard to opt out from, as most software doesn’t provide UI for configuring OpenType features like calt. Also, some operating systems (e.g. macOS) and many apps (e.g. Dropbox Paper) support this transformation already.

Additionally, typing hyphen, endash, and emdash is often available directly on the keyboard (for instance, on EN_* layout Apple keyboards, it’s ⌥ and ⌥⇧ with the hyphen key.)

Thanks for the suggestion though. Maybe some day it could be added to an opt-in OpenType feature.

**Comment by than** [comment]
Came here specifically looking for an opt-in OT feature for `--` to` —` inspired by https://blog.superhuman.com/how-to-hack-beautiful-flourishes-into-your-font-dc630bc52c3f
