### ISSUE TITLE
Add crescent character

### ISSUE THREAD

**Issue by rizqinizamil** [rsms/inter#209]
Hello sir,
Thank you for creating this awesome font.
Anyway, what do you think about adding crescent character? As we know, dark mode become popular now days.

Thank you again.

**Comment by rsms** [comment]
Are you referring to U+262A "STAR AND CRESCENT” (https://codepoints.net/U+262A) ?

**Comment by rizqinizamil** [comment]
Yes, you right. But without star.
Anyway the "Star & Crescent" is also able to represent dark mode 🤔.

**Comment by rsms** [comment]
I see. I will respectfully decline to add this to Inter. It seems that most systems provide this as a high-fidelity “emoji”.

**Comment by rizqinizamil** [comment]
I see. No problem, sir. Thank you for listening anyway.
