### ISSUE TITLE
Does Inter have a logo?

### ISSUE THREAD

**Issue by Bauke** [rsms/inter#213]
I'm working on a website where I'll be using Inter as the font (it's a great font by the way, love it!) and I'm in the process of creating an "Attributions" page where I'll list all the various external things I've used and attribute them properly with their licenses and stuff. So, after a little bit of searching through the repository the only "real" logo I've come across is [the favicon](https://github.com/rsms/inter/blob/master/docs/res/favicon.png) (which I've remade quickly so I have a higher quality version and one with the colors I'm using), but I was wondering if there is a proper logo that I missed.

**Comment by seanbunton** [comment]
I was wondering this recently too and mocked up the following:

![inter-logo-arrow](https://user-images.githubusercontent.com/851117/68639532-8ed3f700-0550-11ea-8202-4f262dc5f830.png)

![inter-logo-circle](https://user-images.githubusercontent.com/851117/68639537-91cee780-0550-11ea-8555-3a699fa0b6f2.png)

**Comment by rsms** [comment]
There’s no official logo — I would encourage you to come up with your own interpretation :–)

Here’s the design source for the website icon and the “social” (og) image: https://www.figma.com/file/g5Urj1eZ1Yf6ouifoArJiK/Inter-icon-%26-social-image

Here are some samples, also in source-design form: https://www.figma.com/c/file/768493324833417304
