### ISSUE TITLE
Multiplex widths of tabular figures

### ISSUE THREAD

**Issue by cssobral2013** [rsms/inter#217]
Describe the bug: The widths of tabular figures (that is, 0-9, currencies, dot, comma, colon, and semicolon) must have the same width across all 18 weights. Also, widths of tabular dot, comma, colon, and semicolon must have 50-60 percent the width of 0-9 and currencies.

To Reproduce Steps to reproduce the behavior: In three lines, type, without quotes, and with tabular figures enabled in your app that supports them,
"0123456789.,:;$£"
in Thin, Regular, and Black weights.

Expected behavior: In the example above, they must actually align vertically.

Environment: All OSes and apps that support OpenType figure replacing display this issue

Version of font: All versions of Inter from 3.0 onwards display this issue
Additional context Add any other context about the problem here.

**Comment by rsms** [comment]
Could you please provide some details about what the issue is?
Please follow this template for filing issue reports: https://github.com/rsms/inter/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Thank you

**Comment by cssobral2013** [comment]
The OP was edited above.

**Comment by cssobral2013** [comment]
Specifically, the widths of tabular figures (i.e., 0-9 and currencies)
should remain the same widths across all 18 styles.

Em seg, 9 de dez de 2019 5:06 AM, Rasmus <notifications@github.com>
escreveu:

**Comment by rsms** [comment]
See #227 for some conversation. It may be best to use a monospace font when monotonic glyph width is needed.
