### ISSUE TITLE
Word-Document using Inter does not print on HP Laserjet M553

### ISSUE THREAD

**Issue by olizei** [rsms/inter#220]
I have a Word-Document (Word 365) on Windows 10 that uses Inter for text. The document does not print on a HP Laserjet M553. The printing process starts, the printer wakes up from sleep mode and then does nothing more and goes back to sleep mode. If i change all text to Arial in the Word-document the printout works normally. 

Other Word-documents print without any issue.  

- Windows 10 Pro
- HP Laserjet M553
- Inter Regular 3.3;20b39288a

**Comment by rsms** [comment]
Would you mind moving the conversation there? Thank you.
