### ISSUE TITLE
Unwanted "smart" replacement of the letter x with a multiplication sign

### ISSUE THREAD

**Issue by captainmeta4** [rsms/inter#222]
**Describe the bug**
Typing a lowercase x between two numbers causes the letter x to be "smart" replaced with a multiplication sign.

**To Reproduce**
1. Type a numerical character
2. type an x
3. type another numerical character

**Expected behavior**
The letter x should remain as an x. The font should not trying to assume the user's intention and replacing characters with glyphs that belong to other characters. By doing this, the Inter font fails to accurately render string data.

**Screenshots**
A user signed up to our web site with the username "x0x7_". It was displayed like this (our usernames are prefixed with the "@" character, similar to twitter)

![](https://cdn.discordapp.com/attachments/606107279003222036/656501975717773355/Screen_Shot_2019-12-17_at_9.24.24_AM.png)

Removing Inter font from our site fixed this problem, and allowed the user's name to be correctly displayed.

**Environment**
- OSX, iOS

**Comment by Euguar** [comment]
Hi, @captainmeta4!

I guess it’s not a bug. You may to use CSS `font-feature-settings` property to disable `liga` option for element.
E.g.: `p { font-feature-settings: "liga" 0; }` — that’s line in CSS will allow you to disable transform from `x (symbol)` to `× (multiply sign)`.

 Goog luck!

**Comment by be5invis** [comment]
Should we use `liga` for "smart placements"? I think it should be `calt`, or even `case`.

**Comment by rsms** [comment]
It’s part of `calt` as @be5invis points out and not `liga`.

https://github.com/rsms/inter/blob/d8d4e0c26a82d5632b3833a27b372ff0a6d32d27/src/features/calt.fea#L251-L268

```css
body {
  font-variant-ligatures: no-contextual;
}
```

Should disable contextual alternates in a modern web browser. (https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures) You can use `font-feature-settings` too, but keep in mind that it **resets all font features** so you have to explicitly include all features you still want to keep enabled, like for instance `liga` or any cvXX or ssXX you may use.

**Comment by rsms** [comment]
Oh wait shit, I see that it’s ALSO in `liga`:

https://github.com/rsms/inter/blob/d8d4e0c26a82d5632b3833a27b372ff0a6d32d27/src/features/liga.fea#L69-L78

I’ll remove that from liga. Must be a mistake.
