### ISSUE TITLE
Problem with Cyrillic “ц” U+0426 (hinted, Windows) 

### ISSUE THREAD

**Issue by Blagochevsky** [rsms/inter#225]
There is a problem with hinting for letter "ц" 0426. Screenshot attached for different font sizes in Regular and Bold
<img width="768" alt="Screenshot 2019-12-24 at 17 17 15" src="https://user-images.githubusercontent.com/844402/71416535-e1d1bb80-2671-11ea-8730-f968bdecdd47.png">

**Comment by be5invis** [comment]
cc. @lemzwerg

**Comment by lemzwerg** [comment]
In case you are using ttfautohint for hinting you probably have to add a control instructions file to help the program hint this glyph correctly.

On the other hand, it is also possible that the some vertical coordinate values of glyph `ц` differ very slightly from `щ` (say, one font unit), which could cause different rounding at specific pixel sizes.

**Comment by Daymarius** [comment]
> In case you are using ttfautohint for hinting you probably have to add a control instructions file to help the program hint this glyph correctly.
> 
> On the other hand, it is also possible that the some vertical coordinate values of glyph `ц` differ very slightly from `щ` (say, one font unit), which could cause different rounding at specific pixel sizes.

`ц` made of two glyphs
![Screenshot_6](https://user-images.githubusercontent.com/18142611/71783991-2147c280-2ff7-11ea-9c06-b80fdfd42b89.png)
![Screenshot_7](https://user-images.githubusercontent.com/18142611/71783994-23aa1c80-2ff7-11ea-973d-8fd9625e6901.png)

**Comment by be5invis** [comment]
@Daymarius Oh, transformed reference. TTFAutohint really dislike this.

**Comment by rsms** [comment]
@Blagochevsky U+0426 is now outlined which should address the issue with hints. It looks good to me, but just in case: would you mind trying this pre-release build out and see if it looks good to you?

[Inter-3.12-93a2076a34-hinted-ttfs.zip](https://github.com/rsms/inter/files/4175644/Inter-3.12-93a2076a34-hinted-ttfs.zip)

**Comment by Daymarius** [comment]
> @Blagochevsky U+0426 is now outlined which should address the issue with hints. It looks good to me, but just in case: would you mind trying this pre-release build out and see if it looks good to you?
> 
> [Inter-3.12-93a2076a34-hinted-ttfs.zip](https://github.com/rsms/inter/files/4175644/Inter-3.12-93a2076a34-hinted-ttfs.zip)

"ц" (uni0446) have problems.

I highly recommend make "ц" (uni0446) as "Ц" (uni0426)

**Thin:**
![Screenshot_18](https://user-images.githubusercontent.com/18142611/74096463-2624f800-4b08-11ea-8d59-f680a0a493d9.png)
![Screenshot_19](https://user-images.githubusercontent.com/18142611/74096465-27eebb80-4b08-11ea-9496-1679ca9dd3ee.png)

**ExtraLight:**
![Screenshot_18](https://user-images.githubusercontent.com/18142611/74096488-6e441a80-4b08-11ea-95e2-404f61ca2340.png)
![Screenshot_19](https://user-images.githubusercontent.com/18142611/74096490-70a67480-4b08-11ea-804c-457d787dcd67.png)

**Medium:**
![Screenshot_20](https://user-images.githubusercontent.com/18142611/74096545-0fcb6c00-4b09-11ea-92ed-0989aeaebc14.png)
![Screenshot_21](https://user-images.githubusercontent.com/18142611/74096547-12c65c80-4b09-11ea-866d-819757adba3e.png)

**SemiBold:**
![Screenshot_18](https://user-images.githubusercontent.com/18142611/74096583-6f297c00-4b09-11ea-9fea-aa0d121f2dd8.png)
![Screenshot_19](https://user-images.githubusercontent.com/18142611/74096584-70f33f80-4b09-11ea-94c3-86b03fb88e08.png)

**Bold:**
![Screenshot_20](https://user-images.githubusercontent.com/18142611/74096613-c0d20680-4b09-11ea-9c53-173f50fcba77.png)
![Screenshot_21](https://user-images.githubusercontent.com/18142611/74096615-c3346080-4b09-11ea-934c-a60b2139fddf.png)

**ExtraBold:**
![Screenshot_18](https://user-images.githubusercontent.com/18142611/74096629-00005780-4b0a-11ea-82d9-5fd6a3f2e6a4.png)
![Screenshot_19](https://user-images.githubusercontent.com/18142611/74096630-01ca1b00-4b0a-11ea-839f-ed666ab0c18a.png)

**Black:**
![Screenshot_20](https://user-images.githubusercontent.com/18142611/74096662-51a8e200-4b0a-11ea-93a5-ecd94a43d703.png)
![Screenshot_21](https://user-images.githubusercontent.com/18142611/74096664-5372a580-4b0a-11ea-8671-2468939dcc44.png)
