### ISSUE TITLE
Win10 won't install both inter-roman and inter-italic variable fonts

### ISSUE THREAD

**Issue by apollolux** [rsms/inter#226]
**Describe the bug**
I originally attempted to install the single-file variable Inter font, but all of the weight and slant instances are named the same. I then attempted to install inter-roman and inter-italic, but installing one after the other results in Windows giving the "this font exists, replace?" dialog and only allowing one of the files to represent the family, resulting in either an all-upright or all-italic Inter without having the capabilities of the other slant. [The variable fork of Montserrat](https://github.com/cosmicmocha/Montserrat/tree/master/fonts/variable) also has this same installation issue with its two-file setup.

I'm under the assumption this is the fault of Windows and its inability to have two variable font files with the same family name and not the fault of Inter. The ideal solution would be to have the singular Inter variable file have properly named instances after being built, but I don't really know the solution to that given its current build process.

**To Reproduce**
1. Obtain Inter 3.11.
2. Attempt to install the variable inter-roman then inter-italic, or vice-versa.
3. Only one will be present in the OS.

**Expected behavior**
Both roman and italic versions to be available and accepted by the OS.

**Environment**
- OS: Windows 10 Home build 18362 (I think this is the November 2019 update)
- Version of font: Inter variable, single axis 3.011;git-f93a4a705 (from the 3.11 release)

**Additional context**
I will fully understand if this is out of scope of the Inter project itself and this gets closed. I just wanted to make y'all aware of this problem on Win10 and honestly if anyone here knows where to actually file this bug (e.g. which Microsoft github project or what MS department to email) that info would be very useful and much appreciated!

**Comment by rsms** [comment]
Thank you so much for the detailed report. I’ll close this out since I don’t think there’s anything Inter can do to resolve this, but the report will remain here on github for future reference!
