### ISSUE TITLE
Extract Alternate Digit Set into own File for Environments without Font Feature Settings

### ISSUE THREAD

**Issue by fritzfr** [rsms/inter#231]
Hi!

I'm wondering whether it's possible to extract the alternate digits, which in the browser can be accessed with `font-feature-settings: 'ss01' 1` into its own file in order to use them in a non-browser environment that does not support this setting, namely mobile development. 

There is no option for example in react-native to access these glyphs, so maybe by making a separate file and assigning it to the parts where I need those digits might work.

--UPDATE:
Okay I tried messing around with Glyphs App and tried simply copying the ss01 glyphs and pasting them in place of the normal ones, however, I'm getting this error when trying to export to OTF:

> Some glyphs are not compatible and will have no outlines

I have never worked with fonts before. It would be cool if someone could point me in the right direction. I have attached the file:

[Inter-SS01-default.zip](https://github.com/rsms/inter/files/4077863/Inter-SS01-default.zip)

Appreciate any feedback.

**Comment by felix-voicehub** [comment]
@rsms Any feedback on this? Would you be able to point me into the right direction on how to achieve this?

**Comment by felix-voicehub** [comment]
@rsms Would you be so kind to point me in the right direction? That would help a lot.

**Comment by VladWinner** [comment]
@fritzfr You can do it yourself with this app:
https://github.com/twardoch/fonttools-opentype-feature-freezer

Example of settings:
![image](https://user-images.githubusercontent.com/13555921/124336158-a472b600-dba5-11eb-9bc0-2b97b565ed69.png)
![image](https://user-images.githubusercontent.com/13555921/124336154-9f156b80-dba5-11eb-9abe-f8d6965db494.png)
