### ISSUE TITLE
Balance space between slash and zeroes in /percent

### ISSUE THREAD

**Issue by cssobral2013** [rsms/inter#237]
Specifically, the horizontal distribution on % and perthousand should be even in all 9 weights / matching italics.

**Comment by rsms** [comment]
Can you please provide more detail? Explain what the issue is, preferably with illustrations and what you think we should do about it. Be as detailed as you can and please make no assumptions. Thank you.

**Comment by cssobral2013** [comment]
@rsms, Specifically, The spaces between circles and slash must be equal in aforementioned glyphs.

**Comment by cssobral2013** [comment]
If you need, see the pictures below. All weights appear to display this issue.
![Sem título](https://user-images.githubusercontent.com/19995437/74113196-6ffdf480-4b81-11ea-8560-fea3430fd1d9.png)
![perthousand](https://user-images.githubusercontent.com/19995437/74113197-70968b00-4b81-11ea-9d36-ad00f208ecac.png)
![pertenthousand](https://user-images.githubusercontent.com/19995437/74113198-712f2180-4b81-11ea-81b0-ebb1fee6f57b.png)

**Comment by rsms** [comment]
"must be” is a little strongly worded, don’t you think? I will consider changing the design. The larger gap on the bottom side is intentional.

**Comment by rsms** [comment]
<img width="1671" alt="Screen Shot 2020-08-17 at 15 03 22" src="https://user-images.githubusercontent.com/47046/90448787-f2b8bc80-e09a-11ea-8df6-348d39495453.png">
Updated spacing

**Comment by rsms** [comment]
This has now been released as part of [version 3.14](https://github.com/rsms/inter/releases/tag/v3.14) 🎉

**Comment by cssobral2013** [comment]
@rsms - Thank you once more!

Em seg, 17 de ago de 2020 10:20 PM, Rasmus <notifications@github.com>
escreveu:
