### ISSUE TITLE
Red heart emojis show as black heart in firefox and chrome on macos.

### ISSUE THREAD

**Issue by eun-ice** [rsms/inter#238]
**Describe the bug**

The "red heart" emoji  ❤️ shows a black heart in firefox and chrome on macos.

In Safari it works correctly. Also other colors like the blue heart do not have that problem.

**To Reproduce**

1. Copy  ❤️ into the test at https://rsms.me/inter/ using chrome or firefox.

**Expected behavior**

A red heart should appear, instead of a black heart.

**Comment by rsms** [comment]
This is a bug in Chrome and Firefox. Try with Safari, a design tool or a native app and you should see the emoji heart when U+2764 (HEAVY BLACK HEART) U+FE0F (VARIATION SELECTOR-16) is used but a monochrome heart when U+2764 is used (i.e. without a variation selector, which is how an emoji grapheme is composed.)

Chrome bug is tracked here: https://bugs.chromium.org/p/chromium/issues/detail?id=964527

**Comment by eun-ice** [comment]
Thank you. As other fonts do not have this problem and Firefox and Chrome show the same behavior I thought it might be an issue of this font. 
Thank you for checking.

**Comment by aarongarciah** [comment]
This is still happening, "red_heart" emoji shows up as a black heart only in Chrome when using Inter. In Firefox and Safari it works just fine. If you use any other font that's snot Inter it will just work in Chrome, too.

Why only happens when using Inter?

Here's a reproduction https://codepen.io/aarongarciah/pen/KKvevjL?editors=1100

**Comment by torgeadelin** [comment]
@aarongarciah I'm getting the same issue... Only breaks in Chrome with Inter.
@rsms any clues?

**Comment by rsms** [comment]
[As mentioned](https://github.com/rsms/inter/issues/238#issuecomment-583785838), this is an issue with chrome. Your best bet is to speak to the chromium team and see if they can fix their weird behavior.
