### ISSUE TITLE
Adjust bold weight glyphs to match current metrics (x-height, cap height, etc.)

### ISSUE THREAD

**Issue by danvernon** [rsms/inter#24]
Hey guys, love the font - found this little issue though!

![screen shot 2017-09-01 at 17 07 08](https://user-images.githubusercontent.com/428197/29978189-07e8db60-8f38-11e7-8b67-8fc3f9e16828.png)

**Comment by rsms** [comment]
Correct. The bold version (from which the medium weight is derived) has a lot of work to be done. At a few point in the past the x height, cap height, ascender and descender values changed a few times. I haven't had time yet to adjust the bold weight to the current (and final) metrics.

**Comment by rsms** [comment]
@danvernon Would you mind trying [the latest release](https://github.com/rsms/inter/releases/latest) and see if the issue remains for you? The cap height and x-height should be the same for all weights. If there are still issues, I'm guessing it's related to autohinting for Windows ClearType, in which case I'd ask you to also test the font files in the "Inter UI (OTF)" folder of the zip file (or the "Inter UI (TTF)" folder if you can't use OTF for some reason.) These font files does not contain TrueType hints.

**Comment by rsms** [comment]
From the silence I'm assuming the more recent releases addressed this.
