### ISSUE TITLE
Consider `ccmp` for the tag of the OT feature that builds up boxed and circled letters (A⃝, etc.)

### ISSUE THREAD

**Issue by be5invis** [rsms/inter#241]
In most font production practices, `rlig` is more used in complex scripts to build up required ligatures, like the Lam-Alif in Arabic.
![image](https://user-images.githubusercontent.com/240091/74607406-980fbb00-508d-11ea-849d-76fb40e2acef.png)

In the case of building up the circled glyphs, `ccmp` is a better choice.

**Comment by rsms** [comment]
Thanks! Moved and tested. Seems to be working well and reduces the number of features to maintain as well.
