### ISSUE TITLE
Odd parentheses & brackets alignment

### ISSUE THREAD

**Issue by hugolantaume** [rsms/inter#243]
**Describe the bug**
In certain contexts, the vertical alignment of parentheses and brackets is odd.

**To Reproduce**
1. Go to Google Fonts: https://fonts.google.com/specimen/Inter
2. Type (Abcd), (abcD), [Abcd] or ($abc)

**Expected behavior**
I'd expect all parentheses / brackets in these examples to be symmetrical.

**Screenshots**
![Screenshot 2020-03-08 at 16 13 12](https://user-images.githubusercontent.com/3065538/76166306-e2043200-615d-11ea-9358-1da9d69e76dd.png)
![Screenshot 2020-03-08 at 16 14 59](https://user-images.githubusercontent.com/3065538/76166314-e892a980-615d-11ea-9344-6612b7985054.png)
![Screenshot 2020-03-08 at 16 13 24](https://user-images.githubusercontent.com/3065538/76166331-f9dbb600-615d-11ea-8424-da5f923cb361.png)
![Screenshot 2020-03-08 at 16 14 18](https://user-images.githubusercontent.com/3065538/76166334-fea06a00-615d-11ea-89c9-28f82bed6776.png)

**Environment**
- macOS 10.15.3
- Chrome

**Comment by rsms** [comment]
This is by design. Disable `calt` for all lower-case alignment. Enable `case` for all upper-case alignment.
