### ISSUE TITLE
Inter Display lowercase w

### ISSUE THREAD

**Issue by ChristopherBiscardi** [rsms/inter#244]
**Describe the bug**

font-weight 500-800 using Inter Display var have an interesting issue with the display of the lowercase w

**To Reproduce**
1. Use Inter Display
2. use a font-weight between 500 and 800

**Expected behavior**

The w renders well, as it does for <=400 and 900

**Screenshots**

at 500:

![image](https://user-images.githubusercontent.com/551247/76257809-a45fe180-620f-11ea-8441-3641ffb9ec32.png)

at 800

![image](https://user-images.githubusercontent.com/551247/76257937-de30e800-620f-11ea-9fba-929e3728a5fd.png)

at 900

![image](https://user-images.githubusercontent.com/551247/76257914-d113f900-620f-11ea-9114-1eaf9e258919.png)

**Environment**
- OS: [MacOS 10.15 beta
- App that renders the font: Chrome 80.0.3987.122
- Version of font: Inter Display var 3.12 alpha from (https://github.com/rsms/inter/releases/tag/v3.12-display-alpha)

**Comment by rsms** [comment]
Thank you for the report. The Display version is still in its early stages and there will be a lot of interpolation issues like these for a while.

**Comment by ChristopherBiscardi** [comment]
I figured :) Will hold off on filing any issues then
