### ISSUE TITLE
Tabular numbers not working when importing from Google Fonts

### ISSUE THREAD

**Issue by impulse** [rsms/inter#245]
**Describe the bug**

Tabular numbers do not work when importing from Google Fonts. 
Works perfectly fine when using `@import url("https://rsms.me/inter/inter.css");`

**To Reproduce**
1. `@import url("https://fonts.googleapis.com/css?family=Inter:200,300,400,500,600,700&display=swap&subset=latin-ext");`
2. Apply `font-variant-numeric: tabular-nums;` to an element

**Expected behavior**
Tabular nums should work when importing from Google Fonts

**Environment**
- OS: macOS 10.15.3
- Chrome

**Comment by rsms** [comment]
Please file issues with Google Fonts regarding fonts from Google. They do their own custom builds from source. https://github.com/google/fonts/issues
