### ISSUE TITLE
Letter "A" looks weird on a Mac

### ISSUE THREAD

**Issue by shopkueche** [rsms/inter#247]
**Describe the bug**
The Letter "A" looks weird on a Mac. On Windows everything seems fine.

**To Reproduce**
1. Install Inter-Font on Mac
2. Look the Typeface letter "A"

**Screenshots**
![Screenshot at Mar 19 14-34-44](https://user-images.githubusercontent.com/49638517/77073001-db43ad80-69ee-11ea-89d5-05121ef3b14c.png)

**Environment**
Mac OS 10.15.3
Google Chrome
Firefox

**Comment by osmantalha** [comment]
+1

**Comment by mseyitcom** [comment]
+1

**Comment by mseyitcom** [comment]
**Solved**: When converting _.tff_ format downloaded from google fonts to _.woff_ format, the letter A is broken. Instead, the woff format can be downloaded and used from the original source.

**Comment by jensamunch** [comment]
I downloaded the OTF fonts on my MacOS (Catalina) and this is how As look when PDF is exporting from Google Slides:

![image](https://user-images.githubusercontent.com/1650140/78124418-8d27a480-7407-11ea-9fa8-3630252579b2.png)

**Comment by mseyitcom** [comment]
> I downloaded the OTF fonts on my MacOS (Catalina) and this is how As look when PDF is exporting from Google Slides:
> 
> ![image](https://user-images.githubusercontent.com/1650140/78124418-8d27a480-7407-11ea-9fa8-3630252579b2.png)
> 
> They look fine in Keynote and other apps..

The problem will be solved when you download the font from "https://rsms.me/inter" source.

**Comment by rsms** [comment]
For local installation, **Please use the fonts provided from [this official repository](http://github.com/rsms/inter/releases/latest) and not Google Fonts**

Google Fonts does their own custom builds from source, so any issue you have with Inter that you downloaded from Google Fonts should be filed with them: → https://github.com/google/fonts/issues

**Comment by jensamunch** [comment]
I did.....but I guess you're saying the problem is with their export....

Thanks
