### ISSUE TITLE
Line height of Inter Var line-height on some Windows almost double of that in Mac

### ISSUE THREAD

**Issue by naktinis** [rsms/inter#249]
**Describe the bug**
I noticed that on my Windows machine default line-height of Inter variable is almost double of that on my Mac. I see no such issue with the regular Inter (non-variable).

I can reproduce it on both Firefox and Chrome, so it's probably not a browser issue.

**To Reproduce**
1. Load the test page https://rsms.me/inter/var-test.html
2. Disable fixed line-height in CSS
3. Line height of font samples becomes almost double

**Expected behavior**
Line height should match across operating systems.

**Screenshots**
![image](https://user-images.githubusercontent.com/657600/77349902-a2c80a80-6d33-11ea-9271-1a2b3411ae10.png)

**Environment**
- OS: Microsoft Windows 10 Pro (10.0.17763 Build 17763)
- App that renders the font: Firefox 74, Chrome 80
- Version of font: whichever version is used in the test page (https://rsms.me/inter/var-test.html)

**Additional context**
I first of all reproduced it on a production system and then double-checked the test page and it produced the same behaviour.

**Comment by rsms** [comment]
This is likely an issue with how Chrome and FF uses FreeType for rendering variable fonts. At least Chrome is working on using the OS for rendering which might fix this.

Would you mind trying the following:
1. Open https://rsms.me/inter/lab/?varfont=1 and make sure you see the line height issue (let me know yes/no)
2. Open https://rsms.me/inter/lab/?varfont=0 and tell me what you see — same line height issue or not?

Thank you

**Comment by rsms** [comment]
Friendly reminder re https://github.com/rsms/inter/issues/249#issuecomment-609072036

**Comment by naktinis** [comment]
Sorry for the delay. This seems to have been fixed by a windows update. I'll reopen if the issue comes back.

**Comment by ryan-mardiono-sal** [comment]
> This is likely an issue with how Chrome and FF uses FreeType for rendering variable fonts. At least Chrome is working on using the OS for rendering which might fix this.
> 
> Would you mind trying the following:
> 
> 1. Open https://rsms.me/inter/lab/?varfont=1 and make sure you see the line height issue (let me know yes/no)
> 2. Open https://rsms.me/inter/lab/?varfont=0 and tell me what you see — same line height issue or not?
> 
> Thank you

Sorry to bump such an old thread. But turning off variable font fixes this issue for me. Does that mean it is a Chrome issue or an OS issue? On Chrome Version 133.0.6943.142

Strangely only happens on v18. If I regress backwards it's fine

![Image](https://github.com/user-attachments/assets/a0c99d49-b884-4ec8-a01d-c83489ea17bd)

![Image](https://github.com/user-attachments/assets/3b9713b1-8f0b-4e8a-a2e4-60f4a3aab085)

Thanks
