### ISSUE TITLE
Circled letters, numbers and symbols are too large.

### ISSUE THREAD

**Issue by be5invis** [rsms/inter#250]
The circled and boxed letters, numbers and mathematical symbols are too large.
In most fonts their diameter are smaller than 1em.
![image](https://user-images.githubusercontent.com/240091/77372074-13fec200-6d22-11ea-8d4f-51f0ce755b21.png)
![image](https://user-images.githubusercontent.com/240091/77372120-31339080-6d22-11ea-8746-516e754b7160.png)

**Comment by rsms** [comment]
These are primarily used as ligatures for combining enclosing characters where IMHO it’s better to make them large (it also reduces work on my end as the enclosed glyphs are just components; no need to implement small caps.)

However, some of them are also mapped to dedicated codepoints. In the case of enclosed multiplication sign, that is U+2297.

I think that what we can do here is:
- unmap U+2297 from /multiply.circled
- add a new glyph /circlemultiply (or something like that) that is custom designed with a cap-height sized circle
- assign a private codepoint to /multiply.circled (all glyphs have codepoint mappings to allow users of apps with limited functionality to access all glyphs.)

Upside: U+2297 will appear as expected
Downside: Existing uses of U+2297 will break on font upgrade (plus there's more work.)

@be5invis Do you have a reference of an ideal U+2297 representation?

Here are a few samples: (looks like circle fitted to cap height is the right move and possibly to use the regular-sized multiply glyph as a component; i.e. not a smaller cross.)
<img width="314" alt="Screen Shot 2020-03-24 at 09 48 40" src="https://user-images.githubusercontent.com/47046/77453830-fe86a800-6db4-11ea-977b-6266fe9075a0.png">
<img width="270" alt="Screen Shot 2020-03-24 at 09 49 08" src="https://user-images.githubusercontent.com/47046/77453840-034b5c00-6db5-11ea-9ce9-8084c2466de4.png">
<img width="299" alt="Screen Shot 2020-03-24 at 09 48 55" src="https://user-images.githubusercontent.com/47046/77453843-05151f80-6db5-11ea-8b39-1b2651be8e89.png">
<img width="288" alt="Screen Shot 2020-03-24 at 09 49 22" src="https://user-images.githubusercontent.com/47046/77453850-07777980-6db5-11ea-92ab-ffb6b6a97477.png">
<img width="274" alt="Screen Shot 2020-03-24 at 09 49 50" src="https://user-images.githubusercontent.com/47046/77453856-09413d00-6db5-11ea-8662-289544f7119c.png">

**Comment by be5invis** [comment]
Since this is a math symbol, it should be as large as the × sign.
![image](https://user-images.githubusercontent.com/240091/77459528-17935700-6dbd-11ea-9ae1-24306a738513.png)

This should also apply to `⊕`, `⊖`, `⨸`
