### ISSUE TITLE
New "Stylistic set 2: Disambiguation" without zero disambiguation

### ISSUE THREAD

**Issue by manuelmeister** [rsms/inter#252]
Non-IT people don't understand the slashed zero and it is generally not often seen. But I really like the disambiguation of the big I, the small l and the german ß.

**Problem**
In Microsoft Word, you can only choose between stylistic sets. You can't activate character variants.

**Solution**
Is it possible to create a new stylistic set for everyone, without the slashed zero?

**Comment by rsms** [comment]
You can enable the individual alternates. ss02 is a “predefined set of alternates”. For example, here are all features enabled that comes with ss02, except from slashed zero: http://localhost:3003/?size=30&varfont=1&feat-cv05=1&feat-cv07=1&feat-cv08=1

**Comment by manuelmeister** [comment]
@rsms but I can’t activate character variants in Microsoft Word. You linked to localhost. Is it possible with the interactive fontlab to generate fontfiles with these changes?

**Comment by rsms** [comment]
Oops! I was running a local lab.

**Comment by rsms** [comment]
Okay, getting back to this. Checking out MS Word it indeed seems like it only gives you access to some OpenType features like stylistic sets and ligatures. I’ll see if adding a new stylistic set has any significant impact on file size :–)

**Comment by manuelmeister** [comment]
Works perfectly! Thank you
