### ISSUE TITLE
Bad emoji rendering on Linux

### ISSUE THREAD

**Issue by jorgicio** [rsms/inter#255]
**Describe the bug**
Everytime I get some text in notification, a lot of lines are showing instead of an emoji.

**To Reproduce**
1. Just being in the desktop.
2. Notification appears.
3. It renders lines instead of an emoji.

**Expected behavior**
A black-and-white emoji should show.

**Screenshots**
![image](https://user-images.githubusercontent.com/554710/78310881-94dd6b00-7525-11ea-869d-9e08d522bb1c.png)
 The original image with the emoji:
![image](https://user-images.githubusercontent.com/554710/78310897-a888d180-7525-11ea-9897-67f50100a578.png)

**Environment**
- OS: Calculate Linux 20 (with KDE)
- Native notifications in Linux with KDE
- Inter 3.12.

**Additional context**
Also happens in every text rendered with this font, such as file names and documents. But mostly in notifications which are shown everytime I get, for example, a new e-mail in the text.

**Comment by rsms** [comment]
What font files did you install? OTF, TTF unhinted or TTF hinted? Some Linux window managers use older versions of FreeType where unhinted TTFs gives you the best results. The best font files are the OTF ones as they use source-perfect cubic bézier curves. The hinted TTF files includes TrueType hints for systems like Microsoft ClearType.

**Comment by rsms** [comment]
Oh wait I just realize you are not actually reporting "bad rendering” but you are saying your Linux system does not handle font fallback. I see.

This is an issue with your Linux window manager, specifically with font fallback. Either your system lacks a font providing the codepoints you are looking for, or it is buggy. Please report this issue with your Linux distributor or window manager project.

Here’s an article explaining font fallback in more detail: https://raphlinus.github.io/rust/skribo/text/2019/04/04/font-fallback.html

**Comment by jorgicio** [comment]
Anyways, I installed the OTF fonts. Also, it didn't happen with some other fonts (I was using Noto). Also, I'll take a look in the article.
Thanks.
