### ISSUE TITLE
`ế` around weight = 200 is broken

### ISSUE THREAD

**Issue by be5invis** [rsms/inter#257]
![image](https://user-images.githubusercontent.com/240091/78832713-92a16380-79a0-11ea-876f-3232c803a830.png)

**Comment by rsms** [comment]
Thank you! Turns out the circumflex-acute component used on top of the e here is broken, so this affects many glyphs. Will fix right away.

**Comment by be5invis** [comment]
Verified as fixed in 3.13. Closed.
