### ISSUE TITLE
Greek lower case omega (ώ, ω) and font-weight from 450 up to 850. 

### ISSUE THREAD

**Issue by kaloletsi** [rsms/inter#259]
![Capture](https://user-images.githubusercontent.com/1839906/79024825-c3de8700-7b8c-11ea-9484-2ee8da7d6df1.PNG)

**Describe the bug**
The **Greek lower case omega (ώ, ω)** becomes **very narrow and illegible**, if you use **font-weight from 450 upto 850** . 

**To Reproduce**
You may reproduce the problem  in https://rsms.me/inter/. 

**Expected behavior**
I expect the letter to be clear regardless of the font-weight

**Screenshots**

**Environment**
- OS: Windows, IOS, Linux . The problem is the same everywhere

- App that renders the font [if applicable; e.g. Chrome, Firefox, Safari]

- Version of font [e.g. "Inter Regular 3.0;8cf05e4a" — you can use fontdrop.info to find out the version]
I am not sure. I use @import url('https://rsms.me/inter/inter.css'); to use it.

**Additional context**

**Comment by rsms** [comment]
You are using a very old version of the font. If you upgrade to a more recent version this will be resolved for you. https://github.com/rsms/inter/releases/latest

**Comment by be5invis** [comment]
@rsms It is reproducable in version 3.13.
![image](https://user-images.githubusercontent.com/240091/81443533-6f4a0f80-912a-11ea-83af-c1a187acbccb.png)
