### ISSUE TITLE
text-stroke

### ISSUE THREAD

**Issue by vlthemes** [rsms/inter#260]
Hello guys!

Inter font not working with these CSS properties:
    -webkit-text-stroke-width: 2px;
    -webkit-text-stroke-color: #fff;

**Comment by vlthemes** [comment]
https://take.ms/DjDoM

**Comment by rsms** [comment]
Please provide detailed information following [the issue template](https://github.com/rsms/inter/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) that should have shown for you when you created this issue.
