### ISSUE TITLE
Ubuntu 19.10: Single-axis Inter fonts (version 3.13) breaks font rendering in GNOME snap apps (renders tofu instead)

### ISSUE THREAD

**Issue by ytx21cn** [rsms/inter#261]
**Describe the bug**
When I have installed the single-axis inter fonts (version 3.13), the characters in selected GNOME snap apps become tofu characters.

**To Reproduce**
1. Download Inter font version 3.13.
2. Install the single-axis variable fonts.
3. Open a GNOME snap app, and then all characters become tofu characters.

**Expected behavior**
Letters should come up as usual.

**Screenshots**
![Screenshot from 2020-04-12 10-21-44](https://user-images.githubusercontent.com/5900105/79075401-71de5400-7ca7-11ea-9010-93b92de4c846.png)
![Screenshot from 2020-04-12 10-19-48](https://user-images.githubusercontent.com/5900105/79075363-32b00300-7ca7-11ea-8bbb-0b60b774b7e4.png)
![Screenshot from 2020-04-12 10-18-52](https://user-images.githubusercontent.com/5900105/79075356-317ed600-7ca7-11ea-862a-78f977b3f063.png)
![Screenshot from 2020-04-12 10-19-00](https://user-images.githubusercontent.com/5900105/79075358-32176c80-7ca7-11ea-8c8c-30d8820f6238.png)
![Screenshot from 2020-04-12 10-19-22](https://user-images.githubusercontent.com/5900105/79075360-32b00300-7ca7-11ea-8238-f424e20de61a.png)
![Screenshot from 2020-04-12 10-20-31](https://user-images.githubusercontent.com/5900105/79075370-48bdc380-7ca7-11ea-89ed-6fe84f166beb.png)

**Environment**
- OS: Ubuntu 19.10
- App that renders the font: gnome-characters, gnome-system-monitor, gnome-calculator, gnome-logs
- Version of font: 3.13

**Additional context**
A workaround is to install the traditional static weight version instead, getting rid of these variable font files at this moment.
![Screenshot from 2020-04-12 10-25-19](https://user-images.githubusercontent.com/5900105/79075474-f335e680-7ca7-11ea-9427-15d504e9dcfe.png)

**Comment by rsms** [comment]
This sounds like an issue with GNOME, likely how they use FreeType2 and Harfbuzz. You can report issues with the GNOME project here: https://gitlab.gnome.org/groups/GNOME/-/issues

I’d be happy to open this again if we find out that it’s an issue with the font itself. For instance, are other variable fonts working in the same GNOME setup? If, so can you provide a detailed test case where it is working? Thanks.
