### ISSUE TITLE
[Compliance] U+04CB CYRILLIC CAPITAL LETTER KHAKASSIAN CHE is incorrect

### ISSUE THREAD

**Issue by be5invis** [rsms/inter#262]
The current shape of U+04CB CYRILLIC CAPITAL LETTER KHAKASSIAN CHE is incorrect: the descender should be placed at the _left_ of the rightmost stroke. 
The current shape of U+04CC CYRILLIC SMALL LETTER KHAKASSIAN CHE is correct.
![image](https://user-images.githubusercontent.com/240091/79630694-4f659400-8108-11ea-8d8d-bb4e75bda139.png)

**Comment by be5invis** [comment]
Link: https://en.wikipedia.org/wiki/Khakassian_Che

**Comment by rsms** [comment]
![irrurure](https://github.com/user-attachments/assets/28a01fd8-b461-462c-b9d8-4237acb88047)
