### ISSUE TITLE
U+1E00’s circle at Regular is off-center

### ISSUE THREAD

**Issue by be5invis** [rsms/inter#266]
![image](https://user-images.githubusercontent.com/240091/79638786-2eb73180-813c-11ea-87cd-30f9fa6a2d73.png)

This doesn't repro in Thin and Black:
![image](https://user-images.githubusercontent.com/240091/79638805-4e4e5a00-813c-11ea-8ecd-76b7b10c348c.png)
![image](https://user-images.githubusercontent.com/240091/79638811-602ffd00-813c-11ea-9f8a-ffbd201ed316.png)

**Comment by rsms** [comment]
<img width="1458" alt="Screen Shot 2020-05-18 at 09 31 48" src="https://user-images.githubusercontent.com/47046/82237494-905cee00-98ea-11ea-9049-ba6e9b3360fb.png">
<img width="1415" alt="Screen Shot 2020-05-18 at 09 33 04" src="https://user-images.githubusercontent.com/47046/82237502-9652cf00-98ea-11ea-8357-2aec89af1827.png">

**Comment by rsms** [comment]
This has now been released as part of [version 3.14](https://github.com/rsms/inter/releases/tag/v3.14) 🎉
