### ISSUE TITLE
Capital "i" Letter Disambiguation Misalignment in Inter Display

### ISSUE THREAD

**Issue by originecode** [rsms/inter#267]
Capital "i" letter vertical bar is misaligned with its top and bottom bars.

I was using Inter Display in Affinity Designer, then enabled Disambiguation set, **ss02** according to the lab. Also noticeable on Inter Lab and in every weights. 

1. Enable SS02 feature with Inter Display

**Expected behavior**
Vertical bar of capital "i" letter has to be aligned with its top and bottom bars.

**Screenshots**
![bug_report](https://user-images.githubusercontent.com/42325924/79643470-63120880-81a3-11ea-97a8-aca5501c263f.png)

**Environment**
- OS: macOS 10.15.4
- Safari 13.1 & 13.2 (R104) + Affinity Designer 1.8.3 + Pages 10.0 + Latest Google Chrome
- Version of font: Inter Display 3.13

**Comment by rsms** [comment]
Inter Display is work in progress
