### ISSUE TITLE
variable font feature: controlling character / letter spacing width

### ISSUE THREAD

**Issue by techieshark** [rsms/inter#269]
First off, thanks for the amazing work here. Beautiful typeface!

I was considering Inter for a UI design but I'd like a typeface where the glyph/character/letter spacing is equal across weights (PT Sans has this property, for example, as do all monospaced fonts obviously). 

For my purposes, it doesn't matter if different characters take up different horizontal space so long as that space remains constant between weights. 

Currently, the same text set in Inter bold will be wider than that in Inter regular. I'm wondering if adding the ability to control the variable font's width (in addition to weight) could allow me to compensate.

**Additional context**

Alternatives you've considered:

Other typefaces I've considered are: PT Sans, iA Writer Quattro S, [Clear Sans](https://typographica.org/typeface-reviews/clear-sans/) (it's not exactly equal across weights but close), IBM Plex ([variable](https://v-fonts.com/fonts/ibm-plex-sans-variable)), various other monospaced fonts, other variable fonts such as Avenir Next Variable and [Aktiv Grotesk](https://v-fonts.com/fonts/aktiv-grotesk-vf)

- Add any other context or screenshots about the feature request here.

From: https://v-fonts.com/fonts/aktiv-grotesk-vf
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/1072292/79812217-98913e80-83bb-11ea-8759-bad08c09fdb9.png">

- Info about your problem

Text reflows when a subset of the text becomes bold. 

Even on short text, like a form field label, it's a tiny annoyance to see the text width change when made bold.

Similarly, see ancient issues like this: ["Inline elements shifting when made bold on hover"](https://stackoverflow.com/questions/556153/inline-elements-shifting-when-made-bold-on-hover). 

Let me know if the problem isn't clear and I'll whip up some screen grabs! :)

**Comment by rsms** [comment]
Adding a width axis is months if not years of work as 9 new masters would need to be designed. Maybe one day, but not now :–) Also I’m not sure this is what you want — it would make glyphs wider as the weight went down while it sounds like what you want is for spacing to be adjusted.

I think you best bet is to adjust tracking (`letter-spacing` in CSS) to achieve your goals.

Here’s a conversation related to this topic: https://twitter.com/ArrowType/status/1255132836354420741

**Comment by techieshark** [comment]
Thanks, @rsms - that's a great suggestion. 

I've played around with that and had some success. Sharing here for benefit of anyone else who comes along trying to do this.

Below we see three tests, trying to make font-weight 400 visually align with the same text at weight 700. The goal is making the total width for the bolded span the same width as the regular span, so lines don't reflow.

The first shows H characters with no spaces between them. We can eyeball it and say we need to expand the `letter-spacing` of the regular weight text to `0.19px` in order to match the overall width of the bold text.
<img width="379" alt="image" src="https://user-images.githubusercontent.com/1072292/81489056-93d1f300-92b4-11ea-8164-7f6ea7f2d8bc.png">

But then we try adding spaces between characters, to see if this will work in normal prose:
<img width="382" alt="image" src="https://user-images.githubusercontent.com/1072292/81489082-d8f62500-92b4-11ea-9f0d-b044c5168772.png">

Unfortunately, we find the bold space glyphs take less space than the regular ones, so our previous letter spacing of `0.19px` is too much and we need to actually shrink it down to `-0.25px` to make this align.

So I thought I'd try something similar to the trick from lettering.js and in this case we'll add a span around each space to force it to be the same weight and letter-spacing as our regular text.
 
<img width="767" alt="image" src="https://user-images.githubusercontent.com/1072292/81489120-63d71f80-92b5-11ea-8287-12268cba78d2.png">

Seems to line up!

And so with that trick, we can make this work. It also appears that the "en space" (`&ensp;`) space character is more similar across the font weights, so I might try using that instead of wrapping each space with a span. (Rasmus - I'm not sure how to check the exact spacing in the source/master but I'd be interested to know if you have any better ideas here or know of a specific space character that's the same across weights. And thanks again for this great font family.)
