### ISSUE TITLE
"A" looks really weird in Inter Display Extra Light and Light

### ISSUE THREAD

**Issue by FryingggPannn** [rsms/inter#270]
**Describe the bug**
The letter A looks like it came from a weird decorative font in Inter Display's Extra Light and Light weights. The problem is also there in italics.

**Screenshots**
<img width="1193" alt="Screen Shot 2020-04-23 at 09 15 34" src="https://user-images.githubusercontent.com/53242193/80048692-7cb8a480-8543-11ea-8b8a-2462b2124542.png">

**Environment**
I'm using Keynote on macOS Catalina but the same thing also happens on Font Book on the same computer. Version is Inter Display beta 1.

**Comment by Derpitron** [comment]
Inter decorative version confirmed??
Why would this be happening though? Renders fine on my Windows and Android.

**Comment by connor** [comment]
I'm [seeing](https://rsms.me/inter/lab/?family=display&size=52&weight=300) this too.

**Comment by FryingggPannn** [comment]
Same issue on iPadOS 13.

**Comment by rsms** [comment]
Thanks ya’ll. Inter Display is work in progress and MANY glyphs are broken like this in the variable version. I’d avoid the variable Inter Display font for now and stick with the static/constant font files for testing.

**Comment by rsms** [comment]
Fixed in 4ae05c12c5b80d487981a4b98a45cdc0dad0b304 :-)
