### ISSUE TITLE
omegatitlo-cyrl is defective in weights between Regular and Black (and their Italics)

### ISSUE THREAD

**Issue by cssobral2013** [rsms/inter#272]
**Describe the bug**
As per title, omegatitlo-cyrl is defective in weights between Regular and Black (and their Italics)

**To Reproduce**
Open, for example, Inter-Bold in a font editor, and navigate to omegatitlo-cyrl (U+047D)

**Expected behavior**
It should be perfect looking (see following section)

**Screenshots**
What it looks (all weights from Medium to ExtraBold, and their Italics, display this):
![inter-bold](https://user-images.githubusercontent.com/19995437/80160173-4f9bde80-85a3-11ea-99c7-64043ad6c75e.png)

What it should look (the remaining weights display this):
![inter-regular-2](https://user-images.githubusercontent.com/19995437/80160252-85d95e00-85a3-11ea-870c-81c32a90c31d.png)

**Environment**
All versions of Inter from 3.0 onwards, and all OSes and apps display this issue

**Comment by be5invis** [comment]
This also happens on Greek omega (ω) in 3.13:
![](https://user-images.githubusercontent.com/240091/81443533-6f4a0f80-912a-11ea-83af-c1a187acbccb.png)
![](https://user-images.githubusercontent.com/240091/81443687-b801c880-912a-11ea-9f0b-d09d3488a70e.png)

**Comment by rsms** [comment]
<img width="1515" alt="Screen Shot 2020-05-18 at 09 26 16" src="https://user-images.githubusercontent.com/47046/82236994-d2d1fb00-98e9-11ea-9e0e-bcdb007e3e82.png">
<img width="1695" alt="Screen Shot 2020-05-18 at 09 26 19" src="https://user-images.githubusercontent.com/47046/82236997-d5345500-98e9-11ea-8b09-cf9eb4daa37a.png">
<img width="1723" alt="Screen Shot 2020-05-18 at 09 26 23" src="https://user-images.githubusercontent.com/47046/82237001-d6fe1880-98e9-11ea-9a7d-5e52197a4013.png">

**Comment by rsms** [comment]
This has now been released as part of [version 3.14](https://github.com/rsms/inter/releases/tag/v3.14) 🎉
