### ISSUE TITLE
Wrong glyph for U+0479 CYRILLIC SMALL LETTER UK

### ISSUE THREAD

**Issue by dscorbett** [rsms/inter#273]
The right side of U+0479 CYRILLIC SMALL LETTER UK has a curl. It should be consistent with U+0443 CYRILLIC SMALL LETTER U and U+0478 CYRILLIC CAPITAL LETTER UK.

**Screenshot**
![уѸѹ](https://user-images.githubusercontent.com/1124347/80265956-728fc680-8667-11ea-97e3-2477d0ed26e5.png)

**Environment**
- OS: macOS 10.14.6
- Version of font: 3.013;git-d82f67bfa

**Comment by rsms** [comment]
<img width="834" alt="Screen Shot 2020-05-22 at 18 26 30" src="https://user-images.githubusercontent.com/47046/82718872-4eb9a380-9c5a-11ea-900c-429f975a92c1.png">

**Comment by rsms** [comment]
This has now been released as part of [version 3.14](https://github.com/rsms/inter/releases/tag/v3.14) 🎉
