### ISSUE TITLE
Wrong code point for superscript ⟨q⟩

### ISSUE THREAD

**Issue by dscorbett** [rsms/inter#275]
U+146B CANADIAN SYLLABICS KE is rendered as a superscript ⟨q⟩. This is wrong because it is an unrelated character, which only somewhat looks like a superscript ⟨q⟩. The superscript ⟨q⟩ should go in the Private Use Area, like the subscript ⟨q⟩ at U+E0AE.

**Screenshot**
![ᑫ](https://user-images.githubusercontent.com/1124347/80320569-2bc7db00-87e5-11ea-8aaf-458cf4f377ce.png)

**Environment**
- OS: macOS 10.14.6
- Version of font: 3.013;git-d82f67bfa

**Comment by rsms** [comment]
This has now been released as part of [version 3.14](https://github.com/rsms/inter/releases/tag/v3.14)
