### ISSUE TITLE
Offset Printing

### ISSUE THREAD

**Issue by m-f-u** [rsms/inter#276]
I'm thinking of using Inter as a house font for both online and print. It is really a wonderful project.

Is there any known issue, when using Inter for Offset printing / as a font for all common types of print production?

I read that Inter was not meant as a display font as of now and that display is in development. I didn't find exactly wether the issues are of technical or aesthetical nature. Is it mainly a matter of kerning, tapering, incisions and dots which are not 100% round – or is there more to it?

**Comment by FryingggPannn** [comment]
Inter was mainly designed to be used in user interfaces, not suitable for display use, but a display version is being developed now.

**Comment by rsms** [comment]
Inter has been used a lot in print. There should be no issues :-)

Inter was born out of a need for an open-source and high-quality typeface for computer screens but after years of evolution has become a multi-purpose workhorse grotesk.
Inter does not have ink traps but it does have “bridges” which in many cases has a similar effect to ink traps.

Here’s an illustration of the “bridges” (circled) and a version of /k at the far right without a “bridge”. At the bottom is a blurred version — note the difference between the shapes of the two “k”s:

<img width="1268" alt="Screen Shot 2020-05-08 at 11 10 46" src="https://user-images.githubusercontent.com/47046/81435504-dcef3f00-911c-11ea-8dea-3fd94e699aac.png">
