### ISSUE TITLE
'RATIO' (U+2236) in bold variant looks too thin and spaces are too wide

### ISSUE THREAD

**Issue by 73** [rsms/inter#278]
**Describe the bug**
I think the 'RATIO' (U+2236) is missing. 

**To Reproduce**
1.  See this string: Mi Mai 6 09‎∶06

**Expected behavior**
`∶` should look like `:` with regard to thickness and spacing.

**Screenshots**
This is my GNOME clock:
![Screenshot from 2020-05-06 08-59-49](https://user-images.githubusercontent.com/529346/81146338-6580aa80-8f78-11ea-8a58-9697775de35b.png)

Font viewer:
![Screenshot from 2020-05-06 10-19-56](https://user-images.githubusercontent.com/529346/81153465-3cb1e280-8f83-11ea-8ef4-81e08298cbbe.png)

**Environment**
- Ubuntu 20.04 in a GNOME session
- GNOME Panel
- Inter Regular and Bold 3.013;git-d82f67bfa

**Additional context**
*I think there not much more to say, it there?*

**Comment by reinhart1010** [comment]
As far as I know, Inter currently does not include a glyph for 'RATIO' (U+2236) yet. In Linux this is substituted by another font, possibly DejaVu Sans, which indeed have a thicker bold font weight than others (Ubuntu, Cantarell, Liberation Sans, etc.)

![image](https://user-images.githubusercontent.com/17312341/91652314-45916b80-eac0-11ea-8734-931d994e15ee.png)

We can also see that the glyph was substituted from DejaVu Sans as well (LibreOffice, on XFCE and GNOME)

@rsms This is similar to #212 but for GNOME Desktop (and some GTK3 apps) on Linux

Reference: https://developer.gnome.org/hig/stable/typography.html.en
