### ISSUE TITLE
Error when exporting variable font using Glyphs App

### ISSUE THREAD

**Issue by m-f-u** [rsms/inter#280]
**Infliction Error**
I get a series of error messages when trying to export variable font via Glyphs.

**Error Message**
Too many Inflections
The Glyph ›lowerHalfWhiteSquare‹ contains a curve with too many inflictions.
(original: "Zu viele Inklectionen – Die Glyphe ›lowerHalfWhiteSquare‹ enthält eine Kurve mit zu vielen Inflectionen.")

Each time a conflicting glyph is excluded from export, new errors for a new glyph shows up. Either as missing or inflicted. 

**To Reproduce**
1. Open Glyph App (Full Version)
2. File –> Export –> Variable Fonts

**Environment**
– Glyphs 2.6.4
- OS: macOS 10.15.4
- Inter 3.13

**Additional context**

**Comment by rsms** [comment]
Variable font export in Glyphs is a beta feature in development. It's likely an issue with Glyphs. Please see https://github.com/rsms/inter/blob/master/CONTRIBUTING.md for how to build from source.
