### ISSUE TITLE
Please clarify if "Inter" is a reserved font name for OFL license

### ISSUE THREAD

**Issue by Knagis** [rsms/inter#282]
Since OFL license prohibits things like subsetting while reusing the reserved font names, it would be useful to know if `Inter` is considered to be RFN in terms of the license (the license text seems to suggest that RFNs must be explicitly written out in the license text) - and thus if the partial font files can be included in CSS using the original name.

**Comment by rsms** [comment]
Updated! Thank you.
I think that derivative work that must not use Reserved Font Names are work that alters the appearance of the font. In other words, I think of subsetting as a delivery optimization, not as altering the work. Similar to how Spotify may store a fraction of an audio track (parity streams to aid its p2p technology) on a local hard drive which does not count as "reproduction".

**Comment by Knagis** [comment]
https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL-FAQ_web#b4b7db21

The license FAQ says that subsetting is a modification that prohibits the use of RFN.

I suppose I might be able to refer to this issue and keep using the name in this scenario but legal might disagree.

**Comment by rsms** [comment]
Wow, I'm surprised! That might mean that Google Fonts breaks pretty much every OFL-licensed font they serve, since they automatically subset all.

In regards to Inter, I'm totally fine with subsetting and reusing the name.

**Comment by lhinderberger** [comment]
Correct my if I'm wrong, but haven't you effectively made licensing for the Inter font stricter than before by updating your copyright statement to now include a Reserved Font Name where previously there was no mention of it? That's a subtle but breaking change for existing users of the font, without a major version bump and without mentioning it in the release notes.

Wouldn't it be better to explicitly _not_ use a Reserved Font Name? If you're not comfortable with that, that's okay, but I suggest you make breaking changes like this more clear, because the way it is now, it's a big surprise for everyone i.e. pulling this font from NPM.

**Comment by davelab6** [comment]
GF gets additional permission as required by the license.

I recommend dropping the RFN and asserting a trademark

**Comment by davelab6** [comment]
On Mon, Aug 24, 2020, 8:38 AM Lucas Hinderberger <notifications@github.com>
wrote:

> Correct my if I'm wrong, but haven't you effectively made licensing for
> the Inter font stricter than before by updating your copyright statement to
> now include a Reserved Font Name where previously there was no mention of
> it?
>

Yes, that's also how I see it

This also blocks updates to Google Fonts until we get the permission to
Google sorted out, and I prefer to ask for RFNs to be removed.

>

**Comment by davelab6** [comment]
There are really TWO ofl licenses, one default without any RFNs, and one with. 

Anyone can add any name as an rfn, but no one can remove RFNs added by others, and once there are multiple copyright holders who committed to a project under the RFN license, each holder must agree to remove it

**Comment by rsms** [comment]
Thanks! I've removed the RFN and asserted a trademark instead.
