### ISSUE TITLE
[opinion] The glyph of .notdef is striking

### ISSUE THREAD

**Issue by yn0793** [rsms/inter#283]
the .notdef glyph looks like spot in a text which containing notdef characters, attracting readers' attention. It will be better if the .notdef glyph is a white square like Noto Sans did.

**Comment by rsms** [comment]
Why is that better?
I think it's important that when a glyph completely fails to be fulfilled that the operator/user can clearly spot that fact.

Can you please provide real-world examples and some in-depth thinking why a space would be better? Thanks
