### ISSUE TITLE
Add /bitcoin U+20BF

### ISSUE THREAD

**Issue by rsms** [rsms/inter#284]
Task to add the glyph /bitcoin with a mapping to U+20BF

Inspiration:
<img width="728" alt="Screen Shot 2020-05-22 at 20 08 30" src="https://user-images.githubusercontent.com/47046/82720406-0dc88b80-9c68-11ea-98b9-a9306f5fa0ae.png">

**Comment by pedromvpg** [comment]
Yes please! 😄

**Comment by GBKS** [comment]
That would be fantastic. Any way to help with this as a non-type-designer?

**Comment by joe-rodgers** [comment]
Inter is beautiful and the Bitcoin symbol would be a great addition!

**Comment by isaacito** [comment]
+1

**Comment by artignatyev** [comment]
That would be awesome!

**Comment by Bosch-0** [comment]
+1

**Comment by rsms** [comment]
![sdf91i](https://user-images.githubusercontent.com/47046/90454452-2221f600-e0a8-11ea-830d-cacebdb8117d.gif)

**Comment by rsms** [comment]
This has now been released as part of [version 3.14](https://github.com/rsms/inter/releases/tag/v3.14) 🎉
