### ISSUE TITLE
v1.8.1 release zipfile name does not conform to previous release naming

### ISSUE THREAD

**Issue by chrissnell** [rsms/inter#29]
Saw the release notes and now understand why you changed the name to Inter UI.  I'm re-doing the Arch Linux package and noticed that the naming of your zipfile for the 1.8.1 release doesn't conform to what you've done previously.   It should be named `Inter-UI-1.8.1.zip` but is named `Inter-UI-1.8.zip`.   Can you update the release to use the standard name so that my package will build without me having to make ugly hacks?  Thanks!

**Comment by rsms** [comment]
Oops. Sorry about that — I wasn't aware that the Arch Linux package script depended on the names matching. I have changed the release name to "1.8" (the old "1.8" release is simply gone.)

**Comment by chrissnell** [comment]
It's not so much that the Arch packager depends on it, as it is my package configuration.  To make things easy, I keep the version number in a variable and use that in a number of places (like fetching the zip).  This is a typical pattern for the Arch packages.

Thanks!
