### ISSUE TITLE
Add insertion symbol U+2380

### ISSUE THREAD

**Issue by fabiospampinato** [rsms/inter#290]
Apparently Inter is the only font in the whole corpus of fonts available in Google Fonts that supports almost all of the characters used for representing shortcuts, but there's one missing, and that's the [insertion symbol](https://www.compart.com/en/unicode/U+2380).

It would be nice if that was supported too, for completeness.

P.s. I'm taking the list of all characters used for this purpose from [here](https://github.com/fabiospampinato/shortcuts/blob/85789be52a4416d75002e8732e8d9ecbf135d684/src/consts.ts#L493-L623).

**Comment by rsms** [comment]
<img width="1989" alt="Screen Shot 2020-08-17 at 15 46 39" src="https://user-images.githubusercontent.com/47046/90454761-fe12e480-e0a8-11ea-8065-556685e5bf46.png">

**Comment by rsms** [comment]
This has now been released as part of [version 3.14](https://github.com/rsms/inter/releases/tag/v3.14) 🎉
