### ISSUE TITLE
Different style for "enter/return" glyph

### ISSUE THREAD

**Issue by fabiospampinato** [rsms/inter#291]
The shortcuts-related symbols in this font seem to be inspired by the ones implemented in macOS' default font, I like this and I think most implemented symbols are actually a slight improvement even, but the glyph for the "enter" symbol looks a bit out of place compared to the others to me.

macOS default font:

![image](https://user-images.githubusercontent.com/1812093/84598011-9d281f80-ae5f-11ea-9f56-d6281e66a391.png)

![image](https://user-images.githubusercontent.com/1812093/84598099-1889d100-ae60-11ea-9538-65129cc99291.png)

Inter:

![image](https://user-images.githubusercontent.com/1812093/84598007-9ac5c580-ae5f-11ea-8c4b-5f740edf909f.png)

![image](https://user-images.githubusercontent.com/1812093/84598102-1c1d5800-ae60-11ea-8f5e-92250e41ad02.png)

Proposed changes

- I think mainly the arrow is being rendered too offset from the center, maybe I would even center it completely, it looks too weird on its own otherwise.
- This is possibly just my naked eye's impression, but the used stroke width seems maybe a bit thinner than the one used in other symbols, and maybe the tip of the arrow is slightly smaller than the one used for the tab symbol? I'm not sure.

**Comment by rsms** [comment]
This is by design. A stylistic choice. BTW, what you are seeing in your "macOS default font" is a font fallback to to two different fonts (since SF doesn't include these glyphs): Lucida Grande and Apple Symbols.

Here are a few sample glyphs: (note that the codepoint differs)
<img width="1164" alt="Screen Shot 2020-06-24 at 18 01 30" src="https://user-images.githubusercontent.com/47046/85641913-cc4f4580-b644-11ea-914f-f1650612fc87.png">

**Comment by fabiospampinato** [comment]
From what I can see when using the centered version of the enter symbol in shortcuts they just look more beautiful, previously the looked kind of broken, to me at least.

![image](https://user-images.githubusercontent.com/1812093/85727738-2c022b00-b6ef-11ea-82b0-c3bb6814c016.png)

Is this stylistic choice really worth it? Like what are we really getting from an offset enter symbol that's worth more than pretty shortcuts?

**Comment by fabiospampinato** [comment]
@rsms May I ask what's the rationale behind not changing centering the glyph? Like I don't understand what are the pros of this choice and how they outweigh being able to display shortcuts in a pretty way.
