### ISSUE TITLE
Inter Desktop OTF doesn't render in Adobe Acrobat PDF when exported from Adobe XD

### ISSUE THREAD

**Issue by emma-annex** [rsms/inter#294]
When exporting a file from Adobe XD, that uses the Inter Desktop OTF files for Mac from 3.13, the Adobe Acrobat PDF does not render/display the font correctly. Exporting to JPG or PNG is ok though. And using the native Mac app, Preview is also ok. 

We also tested the font in Sketch, Adobe InDesign, Illustrator, Word etc and did not reproduce the same issue. It appears purely from XD to Acrobat. 

**Steps to reproduce the behavior:**
1. Installed Inter-3.13-RSMS / Inter Desktop / OTF 
2. Create an Adobe XD document using Inter (Font weight irrelevant)
3. File > Export > Selected Artboard > Format: PDF > Export
4. Open PDF in Adobe Acrobat Pro DC

**Expected behavior**
We'd expect Adobe Acrobat to display the font correctly, as it does from InDesign, Illustrator, Sketch, Word. etc. 

**Environment**
App versions

- Creating in Adobe XD 30.0.12.14 
- Viewing in Adobe Acrobat Pro DC 2020.009.20067

- OS: MacOS10.15.4 on a 2019 MacBook Pro
- Version of font Inter 3.13 (Desktop OTF)

**Additional context**
Our work-around is to use the Hinted for Windows / Desktop / TTF files. This doesn't cause issues on export.

**Screenshots**
Included screen shots of the open Acrobat PDF when using both version of the font. You can clearly see the OTF versions are misaligned.

Screenshots of the Acrobat PDF after export from XD 
<img width="388" alt="Screenshot of XD-OTF-Export as PDF" src="https://user-images.githubusercontent.com/67446427/85811014-287aac80-b7a0-11ea-99d4-c9d19eeff836.png">

<img width="406" alt="Screenshot of XD-TTF-Export as PDF" src="https://user-images.githubusercontent.com/67446427/85811008-24e72580-b7a0-11ea-991a-206e5c018810.png">

**Comment by rsms** [comment]
Thank you for the detailed report! I've heard about this before — there seems to be an issue with PDF font embedding in some of the Adobe products.

---

I am able to reproduce this. It appears as the issues are with Acrobat as every other PDF renderer I've tried correctly renders the PDF:

Acrobat Pro 2020.12.20041.394260
<img width="820" alt="Screen Shot 2020-08-17 at 10 04 52" src="https://user-images.githubusercontent.com/47046/90423586-98573600-e071-11ea-8886-9a5af773f7c7.png">

Apple Preview 10.1 (944.6.16.1)
<img width="784" alt="Screen Shot 2020-08-17 at 10 05 07" src="https://user-images.githubusercontent.com/47046/90423629-a7d67f00-e071-11ea-849f-855fa140974c.png">

Chromium/Chrome 84
<img width="931" alt="Screen Shot 2020-08-17 at 10 06 01" src="https://user-images.githubusercontent.com/47046/90423678-bcb31280-e071-11ea-8a36-065c5bf57e87.png">

Firefox 79
<img width="874" alt="Screen Shot 2020-08-17 at 10 10 33" src="https://user-images.githubusercontent.com/47046/90423784-eec47480-e071-11ea-9d33-efca5067a221.png">

PDF.js 2.4.456
<img width="900" alt="Screen Shot 2020-08-17 at 10 06 51" src="https://user-images.githubusercontent.com/47046/90423714-d18fa600-e071-11ea-872d-aabc068e7e2a.png">

---

Here is a test PDF for others to try or use when submitting an issue with Adobe:
[adobe-xd-export-inter.pdf](https://github.com/rsms/inter/files/5085770/adobe-xd-export-inter.pdf)

**Comment by rsms** [comment]
I'm putting this on ice for now as this has been an issue for years and I've yet to find a "work around" for the issues in Acrobat. Here's to hoping that Adobe fixes it in a future release of Acrobat 🤞.
