### ISSUE TITLE
Way to change Font Name

### ISSUE THREAD

**Issue by Felix-MFU** [rsms/inter#296]
I have been playing with Inter on my machine, locally, altered quite an amount of glyphs and wanted to compare the changes to the original. 

Is there any way to quickly change the font family name? I looked into the font information on Glyphs and a couple of the python scripts but whatever I try results in errors, when compiling via Terminal.

Any help would be great. Many thanks, Felix

**Comment by rsms** [comment]
You can use [fonttools](https://github.com/fonttools/fonttools) either as a python library or using its `ttx` program.
