### ISSUE TITLE
Dotmacron Glyphs broken on Inter V

### ISSUE THREAD

**Issue by Felix-MFU** [rsms/inter#298]
**Describe the bug**
Dotmacron letters such as Adotmacron 01E0 push the dotmacron upwards for almost an entire cap height when displayed as or towards . 

**To Reproduce**
1. Use variable Font on Chrome
2. Change weight to maximum
3. See Adotmacron going throught the roof.

**Environment**
- OS: [e.g. macOS 10.15.4 Catalina]
- Chrome

**Comment by rsms** [comment]
As of 57d7d00d50c54dbbd351fc4ee0788469c3b86a9e:
![smdifo12l](https://user-images.githubusercontent.com/47046/90433388-9b0d5780-e080-11ea-8b3f-0f5082e4325b.gif)

**Comment by rsms** [comment]
This has now been released as part of [version 3.14](https://github.com/rsms/inter/releases/tag/v3.14) 🎉
