### ISSUE TITLE
Kerning issue with single closing quotation mark + comma or full stop

### ISSUE THREAD

**Issue by keikhcheung** [rsms/inter#299]
**Describe the bug**
The space between a single closing quotation mark and a following comma or full stop is too narrow. This makes it very hard to move the input caret (especially when pointing with the cursor) between them.

For instance:

- When you are writing and later want to add text in between; or
- When you want to select some text until the single closing quotation mark and not with the following comma or full stop. In this situation, the rendered highlight of text selection does not even correspond visually correctly to the selection (see screenshot below).

Known pairs:

- `’,`
- `’.`

**To Reproduce**
1. Type a single closing quotation mark.
2. Type a comma or full stop.
3. Try to move between them and add text (especially with the cursor).

**Expected behavior**

- Widen the rendered distance between in the above-mentioned pairs.
- Align the kerning so that the input caret between `’` and `,`/`.` can be rendered visually correctly and accurately.

**Screenshots**
<img width="412" alt="Inter typeface kerning issue with single quotation mark" src="https://user-images.githubusercontent.com/22561336/86513040-4b900680-be07-11ea-8349-3098cf74e920.png">

Please see in particular the input caret / I-beam position in the GIF below.
![Inter-Typeface-Kerning-Issue](https://user-images.githubusercontent.com/22561336/86513078-8134ef80-be07-11ea-9de3-d1615e6be285.gif)

Please note the difference between text selections until `’` and `’,`, compared to the ones with a closing double quotation mark.
![Inter-Typeface-Kerning-Issue-selection](https://user-images.githubusercontent.com/22561336/86513356-d8d45a80-be09-11ea-885e-9deba111b94c.gif)

**Environment**
- OS: macOS 10.14.6
- App that renders the font: Chrome, Firefox, Figma, Pages
- Version of font: Inter Regular. Version 3.013;git-d82f67bfa

Thank you.

**Comment by rsms** [comment]
Thank you for a detailed issue report!
Here's what it looks like since 3d1cc979f176868f73fa6488d34e29b57176ae32:
<img width="873" alt="Screen Shot 2020-08-17 at 12 05 00" src="https://user-images.githubusercontent.com/47046/90434868-fb9d9400-e082-11ea-9d1c-5f7769aabc5c.png">

This will be included in the next release. Thank you.

**Comment by rsms** [comment]
This has now been released as part of [version 3.14](https://github.com/rsms/inter/releases/tag/v3.14) 🎉
