### ISSUE TITLE
Italic angle inverted "when reopening Italic font files" in Glyphs

### ISSUE THREAD

**Issue by Felix-MFU** [rsms/inter#300]
**Describe the bug**
Opening Italic weights in Font Editor Glyphs leads to strange behavior. The canvas appears flipped, it should be tilted towards right instead of left. Not sure wether this leads to any problems.

**To Reproduce**

1. Open Inter Italic in Glyphs Version 2.6.5 (1342)
2. Doubleclick on Glyph to enter Edit Mode

**Screenshots**

![Bildschirmfoto 2020-07-05 um 13 54 49](https://user-images.githubusercontent.com/6161573/86532051-1945de00-bec7-11ea-9ff9-b33ce468a63e.jpg)

**Environment**
- OS: Mac OS X Catalina
- Glyphs Version 2.6.5 (1342)
- Inter 3.12

**Comment by rsms** [comment]
I can't reproduce.

Are you opening the .glyphs source file or a font file?

The .glyphs font file works correctly for me and if I open an OTF file that also imports correctly.
Here's importing an OTF file in Glyphs 2.6.6 (1346):
<img width="770" alt="Screen Shot 2020-08-17 at 12 17 44" src="https://user-images.githubusercontent.com/47046/90435424-d65d5580-e083-11ea-977c-9ce98313fdcc.png">

**Comment by rsms** [comment]
age
