### ISSUE TITLE
Colon should not jump high when next to a capital

### ISSUE THREAD

**Issue by cpkio** [rsms/inter#301]
I think the colon symbol should not jump up from a baseline when next to a capital letter, doesn't look good:
![happy_2020-07-08_141610](https://user-images.githubusercontent.com/1917113/86912420-9cfd0600-c125-11ea-8fed-c0a60f152365.png)

**Comment by rsms** [comment]
This is intended behavior. Disable calt (Contextual Alternates) to opt out of this feature.
