### ISSUE TITLE
WOFF2 issue glyph rendering

### ISSUE THREAD

**Issue by jkdavid** [rsms/inter#302]
Does anyone know why certain letters like a capital "A" renders weird and how to resolve this issue? I converted the font into a WOFF2 format. Could it be because of that?

![image](https://user-images.githubusercontent.com/14899123/87094963-b456f480-c1f4-11ea-8369-941cb44ae34a.png)

**Comment by anthrotype** [comment]
> I converted the font into a WOFF2 format. Could it be because of that?

probably yes -> https://github.com/google/woff2/issues/123

**Comment by mikehawkfish** [comment]
Referencing: https://github.com/fonttools/fonttools/issues/1636#issuecomment-502725185

> to compress a WOFF2 font without transforming glyf (and loca) table you can pass the --no-glyf-transform option to the fonttools ttLib.woff2 compress script:
> 
> $ fonttools ttLib.woff2 compress --no-glyf-transform MyFont.ttf

**Comment by rsms** [comment]
[Download the latest official release from https://github.com/rsms/inter/releases/latest](https://github.com/rsms/inter/releases/latest)

The font files provided by Google Fonts are compiled by them from source and are optimized for web. There are some missing glyphs in their version and overlap issue when you convert the web fonts. None of these issues exist in the official release :–)
