### ISSUE TITLE
Weird Interpolation

### ISSUE THREAD

**Issue by 303B37** [rsms/inter#304]
I playing around with the variable font files and it seems like the masters from the /A have different starting points, because the Interpolation behave weirdly. In the static display font files the /A looks the same.

I tried it with the latest version of Samsa in Chrome and Safari, but also in a animation made with Drawbot.
Font file and version: InterDisplay-roman.var.otf, Version 3.013;git-02c8f016f

![inter_interpolation-b-3 013_cut](https://user-images.githubusercontent.com/62469449/87954230-5a83e380-caac-11ea-99f0-4201d44e06d4.gif)

**Comment by rsms** [comment]
Thanks! The Display font is beta quality and not yet ready for production. There are many issues like these in the Display version.

What works well at the moment for Display is: Basic Latin, constant font files (non-variable.)
