### ISSUE TITLE
New inter-ui font not loading, old interface works fine

### ISSUE THREAD

**Issue by jenil** [rsms/inter#31]
After the font renaming, I tried referencing the `inter-ui.css` on my website but it doesn't seem to work 😞 

The new CSS that doesn't work:

<img width="1280" alt="screen shot 2017-09-22 at 11 56 33 am" src="https://user-images.githubusercontent.com/971411/30754068-4c9c4168-9f8f-11e7-9903-5c1678547f4a.png">

Here is the network information for that:

<img width="1280" alt="screen shot 2017-09-22 at 11 56 47 am" src="https://user-images.githubusercontent.com/971411/30754105-66ffb6e8-9f8f-11e7-9ef9-591635648168.png">

And, I don't know how but the old `interface.css` reference seems to work fine:

<img width="1280" alt="screen shot 2017-09-22 at 11 55 49 am" src="https://user-images.githubusercontent.com/971411/30754118-7cc722fe-9f8f-11e7-8535-acfa1b25fa55.png">

You can try this yourself by inspecting at [jgog.in](https://jgog.in)

**Comment by rsms** [comment]
When using "Inter UI", can you please do the following in Chrome:

1. Open up developer tools
2. Switch to the "Network" tab
3. Press shift-cmd-R (important that you press shift as well; shift-ctrl-R on Windows) to reload and ignore cache
4. When the page has finished loading, stop the network recorder and paste a screenshot here.

I tried reproducing this, but was unable to.

Here's a simple website on a different server under a different domain name that loads and uses all variants of the font, and it works just fine in all the web browsers I have installed on my machine: https://d.rsms.me/inter-ui-test/

Can you please let me know if the fonts fail to load on that website as well for you? Thanks.

**Comment by rsms** [comment]
This is what I see in Chrome's network recorder for the test site:
<img width="877" alt="screenshot 2017-09-22 11 05 37" src="https://user-images.githubusercontent.com/47046/30758141-027c1a08-9f86-11e7-87c9-7f6db0197c2e.png">

**Comment by jenil** [comment]
Hey @rsms thanks for setting up a test page, it helped!

I found the issue, so preloading the CSS is the issue.

This works:
`<link href="https://rsms.me/interface/interface.css" rel="preload" as="style">`

This doesn't work
`<link href="https://rsms.me/inter/inter-ui.css" rel="preload" as="style">`

But this works! 😕
`<link rel="stylesheet" href="https://rsms.me/inter/inter-ui.css">`

After doing some research I just learned that preloading of @font-face isn't something one can do (you need to use some [webfontloader](https://github.com/typekit/webfontloader)).

Also `Interface` is working for me because I have that font installed on my system.

Hopefully, this helps someone.

Thanks again!

**Comment by rsms** [comment]
Thanks for investigating this!
