### ISSUE TITLE
Add EOT, TTF and SVG file format

### ISSUE THREAD

**Issue by alyannangeline** [rsms/inter#316]
First of all, I am grateful for Inter's existence this really suits our site's brand. 

We are planning to locally host this font on our site. I got the file formats that we needed (WOFF, EOT, TTF, and SVG) here in [google-webfonts-helper](https://google-webfonts-helper.herokuapp.com/fonts/inter?subsets=latin). 

But it's missing the italics font. And I'm curious where cold I find these file formats for **Inter Italics Latin.** I only needed the Latin to have it more optimized. 

Super thanks for the help! :)

**Comment by rsms** [comment]
This is a question about google fonts. Please ask at https://github.com/google/fonts/issues
