### ISSUE TITLE
Wrong glyphs for U+2B12..U+2B13 SQUARE WITH TOP/BOTTOM HALF BLACK

### ISSUE THREAD

**Issue by dscorbett** [rsms/inter#320]
U+2B12 SQUARE WITH TOP HALF BLACK and U+2B13 SQUARE WITH BOTTOM HALF BLACK look wrong. They should be squares with the top/bottom halves filled in; instead, they are squares with horizontal lines one third of the way from the top/bottom.

**Screenshot**
![⬒⬓](https://user-images.githubusercontent.com/1124347/94216179-c455aa80-feac-11ea-9bf9-86edf3f55be9.png)

**Environment**

* OS: macOS 10.14.6
* Version of font: 3.015;git-7f5c04026

**Comment by rsms** [comment]
This is by design

**Comment by dscorbett** [comment]
What is the reasoning behind this design?
