### ISSUE TITLE
Add ฿ (U+0E3F) thai baht

### ISSUE THREAD

**Issue by xPaw** [rsms/inter#323]
https://en.wikipedia.org/wiki/Thai_baht

**Comment by inferno986return** [comment]
@rsms It's a standard currency symbol, I don't see why it shouldn't be included.

**Comment by xPaw** [comment]
Example use case is https://steamdb.info/app/945360/ where I have a price table in various currencies. All other used currencies appear to exist in Inter.

**Comment by rsms** [comment]
@xPaw That's a really neat website! Thanks for sharing. If there are other currency symbols missing or ones you think needs improvement, please let me know in a separate issue :-)

Thai baht symbol is on its way: (just running tests before pushing it.)

<img width="2120" alt="sdfu9nsdfio" src="https://user-images.githubusercontent.com/47046/112768621-ac80ef80-8fd1-11eb-836b-664241f1dc13.png">
