### ISSUE TITLE
Bengali language support

### ISSUE THREAD

**Issue by joemasilotti** [rsms/inter#326]
If possible, I would love support for the Bengali language. Currently, Bengali rendered with Inter shows big blackboxes.

**Comment by faahim** [comment]
I'd absolutely love to see Inter support Bengali. ❤️ 

If it helps to convince you to consider it, [Bengali is the 5th most used language](https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers) all over the world (and for context, English is 3rd). The BN web would really enjoy the Inter awesomeness if it was supported. 🙏

**Comment by rsms** [comment]
Sadly I don't see this happening, at least not within a 10 year time horizon. Not only do I have no experience at all with Bengali, but I also don't have the time. Perhaps a Bengali-native type designer out there could take on a new project in the same spirit as Inter!
