### ISSUE TITLE
Rendering difference on Windows between native (ttf hinted) and web fonts

### ISSUE THREAD

**Issue by naverseng** [rsms/inter#328]
**Describe the bug**
On Windows, when using Inter (TTF hinted) in Office apps (for example) or in Browser (Chrome) has different letters height then with web fonts. This distortion in letters form does not give credit to the font, as in the end it looks quite different.

Not using the OTF fonts as the rendering is really "drooling" and as such hard to read on screen - but sizing is better.

The difference is not really visible / not present when printing or generating a PDF.

**To Reproduce**
1. Install Inter 3.15 (hinted TTF)
2. Substitute in the CSS (example hereafter on the Inter website)

**Expected behavior**
Similar rendering.

**Screenshots**
With web font:
![image](https://user-images.githubusercontent.com/21339426/96732499-b0706c00-13b8-11eb-912c-41c1f39c6b97.png)

With native font:
![image](https://user-images.githubusercontent.com/21339426/96732581-c7af5980-13b8-11eb-8af8-1d544ddcba83.png)

Comparison:
![image](https://user-images.githubusercontent.com/21339426/96732843-15c45d00-13b9-11eb-929f-a6418a7c87ec.png)

**Environment**
- OS: Windows 10
- 3.15

**Comment by rsms** [comment]
I'm not sure I understand what the issue is here. Is the problem that you want the automatic line height to be the same in an Office app and a web browser? If so, that is not an issue with the font but how software works. This article by my friend Marcin goes into a little bit about natural line height: https://www.figma.com/blog/line-height-changes/

**Comment by naverseng** [comment]
Hi Rasmus, sorry if my explanation was not correct / precise enough.

The screenshot provided are made with the same software (Chrome), rendering the same text (from Inter website) : I have just forced rendering with the Native font in one case, versus the Web font in the other one. No other setting has been changed.

The issue is not the line height, but that the characters do not have the same 'ratio' in the TTF font, making them look quite different. This is not obvious  in the screenshots previous in github, need to zoom on fullsize to see.

Tried to make it more obvious in this zoom with the 'e' :
![image](https://user-images.githubusercontent.com/21339426/96797261-2815b980-1400-11eb-8ce0-af1728cfbfad.png)

**Comment by rsms** [comment]
I see. This is simply and unfortunately life with font rendering. Chrome uses its own shaping engine but in most cases (not all!) defers actual rasterization to Windows (for ClearType.) This means that the geometry may differ.

Second thing: You have to compare the exact same font files when comparing rendering. The hinted font files will _definitely_ look different than non-hinted ones (hints change how characters are rasterized.) Font format often also has an effect on rendering details, especially on Windows.

Looking at the two "e" glyphs in your screenshot, the left one looks like it was rendered by ClearType from a hinted TTF font while the right one looks like it was rendered from a font without hints (the horizontal bar has been modified by ClearType in the left example.)

You can learn more about TrueType hinting here: https://docs.microsoft.com/en-us/typography/truetype/hinting
