### ISSUE TITLE
Where is the woff version of the inter variable font?

### ISSUE THREAD

**Issue by Unknow-max** [rsms/inter#329]
Hi, 
First of all, thank you for this fantastic font.

The issue, like the title said, that in the release zip file, there isn't the woff version of the Inter variable font, only woff2, ttf and eot.
You can check it by yourself.

Thank you for reading.

**Comment by rsms** [comment]
woff is an older format. Web browsers that support variable fonts all support woff2 so there's no point in woff files for variable fonts.
