### ISSUE TITLE
NPM package?

### ISSUE THREAD

**Issue by drawcard** [rsms/inter#33]
Hi, it would be great if we could import this font as an npm package into projects. 

Instructions:
https://docs.npmjs.com/getting-started/creating-node-modules
https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by rsms** [comment]
I don't think data makes sense as an NPM package. I.e. I wouldn't import images or icons into a project via NPM. That seems really strange to me. The way I think about NPM is that it's a collection of JavaScript modules. (I've authored several NPM packages and have strong opinions around software package management — happy to have long and fun discussions about it in a different forum, e.g. email)

That said, if you'd like to publish an `inter-ui` package to NPM, I won't try to stop you 🙂

**Comment by rsms** [comment]
Possibly duplicate of #18
