### ISSUE TITLE
Font Weight Ignored WebKitGTK

### ISSUE THREAD

**Issue by ressonix** [rsms/inter#330]
**Describe the bug**
It appears that in WebKitGTK for WebKit browsers on Linux, font-weight is being ignored. I filed a bug report to WebKit and Epiphany (Gnome Web), but it was closed because WebKitGTK fully supports variable fonts.

**To Reproduce**
1. Browse to any site using Inter.
2. You'll notice that font-weight is being ignored.
3. When testing in other engines, it works just fine.

**Expected behavior**
Font weight to not be ignored.

**Screenshots**
![image](https://user-images.githubusercontent.com/60057409/97879887-7ffccc00-1cee-11eb-9451-79f2979e4f30.png)
![image](https://user-images.githubusercontent.com/60057409/97880537-4aa4ae00-1cef-11eb-9150-c1fd0edf82a6.png)

**Environment**
- OS: Linux (any distro)
- WebKitGTK (Epiphany/Gnome Web)
- Appears to affect any version

**Additional context**
Websites in screenshot are https://hostbend.com/ and https://tobiasbernard.com/. Depicted on the left is WebKitGTK and on the right is Chromium.

**Comment by ressonix** [comment]
UPDATE: I provided some further information to the WebKit team and they've re-opened the request. For anyone wanting to keep track of this issue, you can find it at: https://bugs.webkit.org/show_bug.cgi?id=177039

**Comment by rsms** [comment]
👍
