### ISSUE TITLE
Font size and weigth is different between Desktop version and web version

### ISSUE THREAD

**Issue by freeBunny** [rsms/inter#331]
Hi,

The font on the web is bigger and bolder than the desktop.

Example:
![Group 8](https://user-images.githubusercontent.com/73879570/97968057-cfaec680-1dc6-11eb-9912-14b2e7f48050.jpg)

Expecting the same behavior in them both

Environment
OS: macOS 10.15.7
App that renders the font: Sketch, Figma, Chrome, Firefox, Safari.
Version of font: 3.15

If it is possible to fix the gap will be amazing.

Thanks

**Comment by rsms** [comment]
I'm unable to reproduce by guessing what you did.
Could you please provide detailed steps describing how you got to each of the two screenshots? (check browser and app zoom, what "px" means in the app you are using, verify that an app like figma doesn't override the font source e.g. from Organization Fonts", or Adobe Fonts, etc.) Please be as specific as you can, thank you!

**Comment by rsms** [comment]
Here's what I see when I try to repro:
[<img width="1052" alt="sdjf0io12" src="https://user-images.githubusercontent.com/47046/102289761-4c6baf00-3ef4-11eb-86c0-481719b42697.png">](https://rsms.me/inter/lab/?letterSpacing=0&sample=Driver%27s%20License&size=14&weight=500)

**Comment by rsms** [comment]
dead
