### ISSUE TITLE
Classic Inter UI glyphs

### ISSUE THREAD

**Issue by noahmaranesi** [rsms/inter#332]
Hello, 

Long time user of the Inter font family. I opened up some old design projects I had and found that some were still using the Inter UI font family. I noticed that there were some differences that can no longer be found in the new Inter family, not even under any alternatives.

So my request is to please have those 'classic' Inter UI glyphs back in as an alternatives option. Alternatively, I see all the source files are available here on Github, so if this isn't a popular idea, I will just have to recompile an older version.

For example, here are two differences ("`a`" and "`i`"):

<img src="https://user-images.githubusercontent.com/12670516/98620362-4add2300-2359-11eb-8763-f5126433516c.png" width="25%">

Thank you for your time.

**Comment by Derpitron** [comment]
not sure if that's what is intended, but on the left side I only see Helvetica characters and not the old Inter UI characters.

**Comment by noahmaranesi** [comment]
@Derpitron you're correct. My bad. Sketch was acting as if the font was Inter UI when it clearly isn't. Thanks.
