### ISSUE TITLE
Misplaced anchor points on transformed glyphs

### ISSUE THREAD

**Issue by dscorbett** [rsms/inter#336]
Some glyphs created by rotating other glyphs also had their anchor points transformed.

**Screenshot**
Here is ⟨ɐ̌ɯ̌ɰ̌ɹ̌ɻ̌ʇ̌ʌ̌ʍ̌ʎ̌Ⅎ̌⟩. Each U+030C COMBINING CARON should appear above its base, but they instead all appear below the base.
![ɐ̌ɯ̌ɰ̌ɹ̌ɻ̌ʇ̌ʌ̌ʍ̌ʎ̌Ⅎ̌](https://user-images.githubusercontent.com/1124347/100546880-b405d700-3231-11eb-9dac-3311f79aed05.png)
Similarly, U+0347 COMBINING EQUALS SIGN BELOW should go below the base.
![ɐ͇ɯ͇ɰ͇ɹ͇ɻ͇ʇ͇ʌ͇ʍ͇ʎ͇Ⅎ͇](https://user-images.githubusercontent.com/1124347/100546926-047d3480-3232-11eb-96f7-c4a4cfaffa06.png)

**Environment**
- OS: macOS 10.14
- Version of font: 3.15

**Comment by rsms** [comment]
Thank you — good find!

**Comment by rsms** [comment]
Fixed in dc1f6bbe28b1c614a117a97b74ea7d6f50f4d7b7
<img width="792" alt="Screen Shot 2021-03-28 at 13 58 48" src="https://user-images.githubusercontent.com/47046/112767862-e64ff700-8fcd-11eb-9941-60bfdeba1b38.png">
