### ISSUE TITLE
Kelvin and Ångström signs are different from K and Å

### ISSUE THREAD

**Issue by PetterS** [rsms/inter#337]
The Kelvin and Ångström signs are currently different from K and Å. I don't know much about making fonts, but I thought it may be easy to just point them to K and Å, respectively?

(Same thing for ℃ and ℉ that even have serifs in Inter, but that is perhaps more work to fix?)

Then again, these glyphs are probably seldom used, so it does not matter much.

**Comment by rsms** [comment]
Is it possible you are mistaken and that the font you are looking at is not Inter?
The Kelvin and K are identical and so are Ångström and Å. Further, Inter does have custom Centigrade and Fahrenheit glyphs which do not have serifs.

Here are screenshots and links to the individual glyphs: (of the latest stable release of Inter)

- https://rsms.me/inter/glyphs/?g=angstrom
- https://rsms.me/inter/glyphs/?g=Aring
- https://rsms.me/inter/glyphs/?g=degreekelvin
- https://rsms.me/inter/glyphs/?g=K
- https://rsms.me/inter/glyphs/?g=degreefarenheit
- https://rsms.me/inter/glyphs/?g=degreecentigrade

<img width="849" alt="Screen Shot 2020-12-15 at 16 11 49" src="https://user-images.githubusercontent.com/47046/102288094-98b4f000-3ef0-11eb-8a75-34125935af1f.png">
<img width="781" alt="Screen Shot 2020-12-15 at 16 11 44" src="https://user-images.githubusercontent.com/47046/102288098-9a7eb380-3ef0-11eb-98e4-2b1023a196a4.png">
<img width="758" alt="Screen Shot 2020-12-15 at 16 11 40" src="https://user-images.githubusercontent.com/47046/102288099-9b174a00-3ef0-11eb-84a7-1e44ae0dc0b6.png">
<img width="888" alt="Screen Shot 2020-12-15 at 16 11 36" src="https://user-images.githubusercontent.com/47046/102288102-9bafe080-3ef0-11eb-8bec-bbb4d0b9a13f.png">
<img width="702" alt="Screen Shot 2020-12-15 at 16 11 30" src="https://user-images.githubusercontent.com/47046/102288103-9c487700-3ef0-11eb-96bf-cca17b6cace2.png">
<img width="778" alt="Screen Shot 2020-12-15 at 16 11 20" src="https://user-images.githubusercontent.com/47046/102288106-9ce10d80-3ef0-11eb-90da-4c0218ff8b3b.png">

Can you find out the exact font files you are using? (Version, file type and in case of Windows: if you are using fonts with or without hints.)

**Comment by PetterS** [comment]
I looked at the Inter web page where it looks like this on Windows, Chrome 87:
![image](https://user-images.githubusercontent.com/772305/102319179-bf1f6d80-3f7a-11eb-85af-1becd7999945.png)

So this is likely a rendering issue in Windows/Chrome then (unless the web page somehow uses an old version). If so, let's close this.

Also lists a few glyphs with serifs:
![image](https://user-images.githubusercontent.com/772305/102319055-9d25eb00-3f7a-11eb-8a22-f2dea4963a9a.png)

**Comment by PetterS** [comment]
![image](https://user-images.githubusercontent.com/772305/102319348-04dc3600-3f7b-11eb-9ae1-882f37537f51.png)

**Comment by rsms** [comment]
Oh weird, it appears as the font is not loading in your web browser. Could you please provide information about what browser you are using, if you have any unconventional browser extensions and what OS this is.

**Comment by PetterS** [comment]
Latest stable Chrome on Windows. (Extensions are 1Password and Google Docs offline)

![image](https://user-images.githubusercontent.com/772305/112280700-94ce0200-8c85-11eb-8fee-579362f59fc8.png)

Looks good now, but:

![image](https://user-images.githubusercontent.com/772305/112280785-aa432c00-8c85-11eb-822f-a1464fd26ee2.png)

**Comment by rsms** [comment]
Can't reproduce. [What I see](https://rsms.me/inter/glyphs/?g=angstrom) in Chrome, Safari and Firefox:

<img width="938" alt="Screen Shot 2021-03-31 at 18 31 37" src="https://user-images.githubusercontent.com/47046/113231120-60db7980-924f-11eb-9594-bc4e14118b86.png">

**Comment by PetterS** [comment]
Haha, this is weird. Yeah, I cannot assist more on this, even though it reproduces for me. Thanks for your work, Rasmus!
