### ISSUE TITLE
init.sh crashes on Linux

### ISSUE THREAD

**Issue by jamesgk** [rsms/inter#341]
**Describe the bug**
The `init.sh` script fails for me on Debian with the error `mv: cannot stat '/root/ttfautohint-build/ttfautohint*/frontend/ttfautohint': Permission denied` at https://github.com/rsms/inter/blob/717605c/init.sh#L334.

Is it necessary to run this script as root? If not, wouldn't it work to say `~/` instead of `/root/`?

(And if so, maybe warn if you're not running as root before installing 100s of MB of build artifacts into the user's home directory and then crashing?)

**To Reproduce**
1. `$ git clone https://github.com/rsms/inter.git`
2. `$ cd inter/`
3. `$ ./init.sh`

**Expected behavior**
The initialization script runs without errors.

**Environment**
- OS: Debian GNU/Linux 10 (buster)

**Comment by alexmyczko** [comment]
Works with Debian GNU/Linux unstable (sid)

**Comment by jamesgk** [comment]
Did you run the script as root? Or as a user that somehow has read access to /root/? Or did `"$DEPS_DIR/ttfautohint-${AUTOHINT_VERSION}"` already exist when you ran it? Otherwise, I don't understand how this script could possibly run without error.

**Comment by alexmyczko** [comment]
Ah right. 1st one.

**Comment by jamesgk** [comment]
Oh, I just realized there's already a PR to fix this, https://github.com/rsms/inter/pull/289. It seems like it's been abandoned so I'll fix the typo in it and open a new one.

**Comment by rsms** [comment]
Fixed in c758332430055ad16eef2a02565349286c8e1b6d
