### ISSUE TITLE
Overlapping paths when using stroke outlines

### ISSUE THREAD

**Issue by rohanbhangui** [rsms/inter#343]
When using stroke outline option on text layers in apps such as illustrator and adobe XD, some letters have overlapping paths

**To Reproduce**
1. Create a text layer and type letters such ad 'd', 'P', 'R' or 'e' (there are other similar letters)
2. Use an outline stroke 
3. Paths overlap for these letters

**Expected behavior**
Glyphs should not overlap and be one contiguous shape 

**Screenshots**
https://imgur.com/a/gJViFQe
https://imgur.com/a/C0bvzq9

**Environment**
- OS: WIndows 10
- Apps: Adobe Illustrator and Adobe XD (possibly other apps)
- Latest version: v3.15

**Comment by rsms** [comment]
By design. A quirk of Illustrator.
Use Pathfinder in illustrator to apply a boolean union before you stroke it.
