### ISSUE TITLE
[Compliance] U+2B12 and U+2B13 are incorrect

### ISSUE THREAD

**Issue by be5invis** [rsms/inter#344]
In Inter:
![image](https://user-images.githubusercontent.com/240091/104678268-e6637a80-569f-11eb-8d7d-14d7e758a960.png)

In [Unicode standard](https://www.unicode.org/charts/PDF/U2B00.pdf):
![image](https://user-images.githubusercontent.com/240091/104678289-f11e0f80-569f-11eb-8e4b-e6de68c5886b.png)

**Comment by kenmcd** [comment]
The Unicode descriptions would be helpful.
2B12 - Square with Top Half Black
2B13 - Square with Bottom Half Black

**Comment by rsms** [comment]
This is intentional; a conscious stylistic choice, which may be controversial but yolo :–)
Thanks for filing, though.
