### ISSUE TITLE
Horizontal bar of the lowercase "f" is off to right in Inter Display Thin (100) weight

### ISSUE THREAD

**Issue by TaigaYamada** [rsms/inter#346]
**Describe the bug**
In Inter Display Thin (100), the horizontal bar of the lowercase "f" is off to right and misaligned.
This is especially apparent when placed next to lowercase "t".

**To Reproduce**
1.Visit the lab page of Inter website
2.Set the Weight to Thin(100)
3.Set Family to Inter Display
4.Type in "f" and "t", then compare the placement of the horizontal bar

**Expected behavior**
Horizontal bar of "f" should be aligned to the center of the vertical stroke, much like the behavior in "t".

**Screenshots**
![image](https://user-images.githubusercontent.com/77144664/105633461-07944a00-5e9c-11eb-8e05-a85e1c37c108.png)

**Environment**
- OS: Windows 10
- App that renders the font: firefox
- Version of font: I assume Inter website uses the newest version, so 3.15

**Additional context**

**Comment by rsms** [comment]
This has been fixed with the opsz work currently being done in master. See #463
