### ISSUE TITLE
Letter A curve possibly inverted

### ISSUE THREAD

**Issue by Fourthbus** [rsms/inter#347]
> Did you get the font from Google Fonts? Then please head over to
> https://github.com/google/fonts/issues
> and file an issue with Google Fonts.
> If not, REMOVE THIS PARAGRAPH BEFORE FILING YOUR ISSUE.

**Describe the bug**
The letter A does not display properly in Mac Preview.

**To Reproduce**
1. Use Google Docs to export and download file as PDF
2. Open on Mac using Preview.app

**Screenshots**
<img width="151" alt="image" src="https://user-images.githubusercontent.com/13725288/105647348-ee3fcd80-5e9c-11eb-8f37-aa3f98585fc8.png">

**Environment**
- OS: [e.g. macOS 10.14]
- Preview.app
- Version of font N/A, as the current version on Google Docs (24 Jan 2021)

**Comment by TaigaYamada** [comment]
I think Google docs uses the Inter font from Google font.

So the issue probably needs to be filed with Google font repository, as stated at the beginning of this issue.

**Comment by rsms** [comment]
If this is with fonts from Google Fonts, then that's the issue — the Inter font files from google (compiled by google, not me) has this bug (they are also an older version and lack italics.) Please use the official fonts from <rsms.me/inter> — Thanks.
