### ISSUE TITLE
Wrong font-weight when inspecting Inter Medium in Figma

### ISSUE THREAD

**Issue by Bilalc** [rsms/inter#349]
**Describe the bug**
When inspecting text written with Inter Medium in Figma, the font-weight is shown as 400/normal, rather than 500/medium.

**To Reproduce**
1. Type any text using Inter Medium in Figma
2. Go the inspect panel and inspect the text

**Expected behavior**
Expected to the see the CSS properties in the inspect panel show font-weight: 500;

**Screenshots**
<img width="1159" alt="Screenshot 2021-02-03 at 11 19 00" src="https://user-images.githubusercontent.com/8267389/106733314-08527c00-6612-11eb-8985-4fe61a8842f2.png">
<img width="1159" alt="Screenshot 2021-02-03 at 11 19 07" src="https://user-images.githubusercontent.com/8267389/106733320-0a1c3f80-6612-11eb-8c96-edb0092f4623.png">

**Environment**
- OS: macOS 11.1
- App that renders the font: Figma (Desktop version)
- Version of font: Version 3.015;git-7f5c04026

**Additional context**
Unsure if this is some weird bug in Figma, or if the problem lies with the Inter font.

**Comment by rsms** [comment]
I am 99.99% certain this is a bug in Figma (I used to work at Figma and am familiar with its text implementation.) You might want to submit a bug report in Figma by using the "contact us" function ("?" button in the corner or reach out to them on Twitter.)
