### ISSUE TITLE
Kerning FA

### ISSUE THREAD

**Issue by gjermundrg** [rsms/inter#35]
Not sure if this is something worth adding a ticket for, but the kerning pair of "FA" seems a little off, especially in the heaviest weights. Cheers 👌
<img width="790" alt="FA" src="https://user-images.githubusercontent.com/465586/31220493-e7f84108-a9c0-11e7-8046-f38e6c997c56.png">

**Comment by rsms** [comment]
This is what it looks like to me using https://rsms.me/inter/lab/?sample=FAMILY&size=103&weight=900

<img width="390" alt="screenshot 2017-10-05 08 33 04" src="https://user-images.githubusercontent.com/47046/31236232-69941fb6-a9a8-11e7-8915-57dcdcd7e211.png">

What version of the typeface are you using (and what kind, OTF, TTF or WOFF?) What are are you viewing it in?

**Comment by rsms** [comment]
BTW, this is what it looks like in the upcoming major version 2.0 (that's currently in master source)

<img width="640" alt="screenshot 2017-10-05 08 40 34" src="https://user-images.githubusercontent.com/47046/31236428-ed80b802-a9a8-11e7-8e48-69ca4e703c8d.png">
<img width="647" alt="screenshot 2017-10-05 08 40 41" src="https://user-images.githubusercontent.com/47046/31236432-ef3bb570-a9a8-11e7-839f-28893f1889e4.png">

**Comment by gjermundrg** [comment]
Okay, nice. I used the 1.11 version OTF, but I guess it is resolved then.

**Comment by rsms** [comment]
Strange! I've been using 1.11 OTF for a while and haven't seen that messed-up FA pair. I'll double-check and install 1.11 clean. Gotta make sure there's nothing weird going on (make sure it doesn't happen again.)

2.0 will be out very soon and apart from a massive amount of glyph rework, there's a lot of improved kerning included as well.

Here's a pre-release (from current master) if you're curious to try it early.

[Inter-UI-2.0-1.12-pre-1087a6500b65b3.zip](https://github.com/rsms/inter/files/1360085/Inter-UI-2.0-1.12-pre-1087a6500b65b3.zip)
