### ISSUE TITLE
ttfs and hinted fonts aren't exclusive to Windows!

### ISSUE THREAD

**Issue by escondida** [rsms/inter#350]
Not a huge deal, since it's trivial to just install them anyway, but that's worth noting in your docs.

Perhaps a less confusing directory structure would be:

    basic/
        desktop/
        variable/ # if the variable ttfs aren't hinted
        web/
    hinted/
        desktop/
        variable/ # if the variable ttfs are also hinted
        web/

**Comment by rsms** [comment]
You're right, but the instructions are generally intended for people unfamiliar with these details. Someone using a Linux window manager with hinted text support will likely already know this, while a Windows user will most likely have no idea about these things and so keeping the message focused and as clear as possible for these users is the aim :–)
