### ISSUE TITLE
The letter "Å" is not compatible with Microsoft Publisher

### ISSUE THREAD

**Issue by Drufsen** [rsms/inter#357]
**Issue**
The letter capital "Å" is cut off in Microsoft Publisher.

**To Reproduce**
Write the letter "Å" using the Inter font.

**Screenshot**
![bild](https://user-images.githubusercontent.com/66948917/110034118-628e4c00-7d3a-11eb-9cb9-94824391c073.png)

**Environment**
- OS: Windows 10 Pro
- Microsoft Publisher (Office 365)
- Version 3.15

**Comment by rsms** [comment]
I'm 99% sure this is a limitation with Microsoft Publisher. It's known that some Microsoft apps from 2003 and older have issues with glyphs that extend outside the ascender and descender extremes of the font's declared metadata (which is the case with U+00C5 in Inter:
<img width="1263" alt="Screen Shot 2021-03-27 at 15 14 35" src="https://user-images.githubusercontent.com/47046/112736338-3a47d680-8f0f-11eb-9090-15fe0d7f1d57.png">

We could increase the ascender and descender values, but it would...

a) break all existing designs using Inter that uses intrinsic line height (which I think is a lot of stuff)
b) make the intrinsic line height too tall

It might be possible to hack around this by using negative leading metadata but I'm guessing that it will not be supported by some programs (possibly not by Microsoft programs which tends to have a lot of typography issues.)

Ideas are welcome!

**Comment by Drufsen** [comment]
Using the Google Fonts version https://fonts.google.com/specimen/Inter the same result will be produced in the editor. However, if the document is exported to a .PDF the letter displays as expected.

**Comment by rsms** [comment]
What's happening is that Microsoft Publisher incorrectly assumes that nothing will be drawn outside of ascender or descender. It should really look at the yMax and yMin values of the `head` table. Anyhow, unless you work at Microsoft I suppose you have no way to fix that. I'm sorry.

I looked into increasing the ascender and descender, but it will cause a lot of existing use of Inter to reflow. Plus, it would make Inter diverge quite a bit from other similar fonts in terms of its natural line height compared to its optical height.

@Drufsen could you try increasing the line height of the font in Microsoft Publisher? For example, set it to 1.6 or something. Maybe that could be a viable workaround.

**Comment by Drufsen** [comment]
Unfortunately, changing the line height didn't work. I did however accidentally discover that zoom level effects if the font is rendered correctly or not. This did sadly not have any effect on the exported .PDF.

This means that the using the Google Fonts version is the best solution at the moment.

**Comment by rsms** [comment]
You might want to submit a bug report for both this and the space issue in #356 to Microsoft.
I'm going to close this issue since I don't think there's anything I can do to help without drastically changing the appearance of the font. Sorry!

**Comment by khaledhosny** [comment]
MS apps usually use OS/2 win ascent and descent for clipping, so they need to be big enough (usually the same as the font box), but they also often use them incorrectly for line spacing which complicates things.
