### ISSUE TITLE
Any plans for Arabic language Support?

### ISSUE THREAD

**Issue by OssNass** [rsms/inter#358]
Do you have any plans for supporting other languages in the typeface especially Arabic ?!

**Comment by rsms** [comment]
Nope! Thanks for asking. It would be cool if someone familiar with Arabic script would take this on as a separate project :–)

**Comment by OssNass** [comment]
Arabic is my native language but I will not be able to help because I am not a graphic designer or font creator

**Comment by rizwanuu** [comment]
@ferastajuore can you please help me?

**Comment by ferastajuore** [comment]
@rizwanuu 

how can I help you, my friend

**Comment by rizwanuu** [comment]
> @rizwanuu
> 
> how can I help you, my friend

Thank you brother was getting issue in arabic font in react js. That is solved

**Comment by MoussaAhmed1** [comment]
> > @rizwanuu
> > how can I help you, my friend
> 
> Thank you brother was getting issue in arabic font in react js. That is solved

can you tell me what to do
