### ISSUE TITLE
Wrong glyph for U+0196 LATIN CAPITAL LETTER IOTA

### ISSUE THREAD

**Issue by dscorbett** [rsms/inter#359]
U+0196 LATIN CAPITAL LETTER IOTA incorrectly looks like U+0399 GREEK CAPITAL LETTER IOTA. It should look like a caps-height U+0269 LATIN SMALL LETTER IOTA, as it did in previous versions of Inter.

**Screenshots**
![Ɩ](https://user-images.githubusercontent.com/1124347/112770999-88d0a000-8ff7-11eb-909e-be7f76be2b17.png)

**Environment**
- OS: macOS 10.14
- App that renders the font: hb-view
- Version of font: Inter Regular Version 3.016;git-4cb8acb75

**Comment by rsms** [comment]
re 8977505c249e62ff231d9534c10b94d462bb2fec & #340

**Comment by rsms** [comment]
<img width="868" alt="Screen Shot 2021-03-29 at 16 36 31" src="https://user-images.githubusercontent.com/47046/112912733-17532900-90ad-11eb-9764-8a9da6479784.png">

**Comment by rsms** [comment]
[Released with v3.18](https://github.com/rsms/inter/releases/tag/v3.18)
