### ISSUE TITLE
Cyrillic "и" "к" looks too bold

### ISSUE THREAD

**Issue by g0ddest** [rsms/inter#36]
Small "к" and "и" looks bolder than analogs in latin.
You can compare "к" and "k".
Other small glyphs are also thiner.

![image](https://user-images.githubusercontent.com/831951/31927468-e7366660-b89c-11e7-821d-f6c3a752bab2.png)

**Comment by StefanPeev** [comment]
There is a lot of problems with the Cyrillic script. The lowercase **x-heigh** value is **1536** but the heigt of the Cyrillic lowercase **"н"** (uni043D) is 1488. The stem width of the lowercase Latin **"l"** is **236** but the stem width of the Cyrillic lowercase **"н"** (uni043D) is **276**. It's look like if the Cyrillic script is taken from another font.

**Comment by rsms** [comment]
Assuming v3.0 fixed this
