### ISSUE TITLE
Italicized backslash character (U+005C) slanted in the wrong direction

### ISSUE THREAD

**Issue by SL-Lee** [rsms/inter#362]
**Describe the bug**
The italicized backslash character, `\` (U+005C), is slanted in the wrong direction.

**To Reproduce**
1. Download and install [Inter v3.17](https://github.com/rsms/inter/releases/tag/v3.17).
2. In a text editor, set the font family to `Inter` and enable the italic font style.
3. Type `\` (the backslash character, U+005C).

**Expected behavior**
The backslash character should be slanted forwards (clockwise), not backwards (counter-clockwise).

**Screenshots**
Observe the backslashes in the second, italicized line for the bug:
![](https://user-images.githubusercontent.com/45960387/112958320-f0f8c080-9174-11eb-9595-8e7a2ac473c8.PNG)

Compare that to other fonts:
![Capture1](https://user-images.githubusercontent.com/45960387/112958767-606eb000-9175-11eb-866c-73fa3f782385.PNG)

**Environment**
- OS: Windows 8.1, Windows 10
- App that renders the font: Microsoft Word, Windows WordPad
- Version of font: All styles of Inter v3.17 (downloaded from [here](https://github.com/rsms/inter/releases/tag/v3.17))

**Additional context**
This issue seems similar to #360.

**Comment by rsms** [comment]
Thanks. Indeed this was caused by the same source file tooling upgrade (Glyphs 3) as #360

**Comment by rsms** [comment]
Before:
<img width="115" alt="Screen Shot 2021-03-31 at 15 34 07" src="https://user-images.githubusercontent.com/47046/113219737-d850df00-9236-11eb-9f00-63dde218ebcf.png">

After, with 5b0c6eb7981def5be7d127e776a332b151e33b64:
<img width="111" alt="Screen Shot 2021-03-31 at 15 35 13" src="https://user-images.githubusercontent.com/47046/113219762-e3a40a80-9236-11eb-9082-3bb5acf71e4c.png">
<img width="1140" alt="Screen Shot 2021-03-31 at 15 37 43" src="https://user-images.githubusercontent.com/47046/113219881-19e18a00-9237-11eb-8044-3414aacf088e.png">

**Comment by rsms** [comment]
[Released with v3.18](https://github.com/rsms/inter/releases/tag/v3.18)
