### ISSUE TITLE
Outlines in Inter Thin Italic to fat for asteriskcomb, doublemacroncomb, and doublemacronbelowcomb

### ISSUE THREAD

**Issue by ErwinDenissen** [rsms/inter#363]
Concerning Inter Version 3.017;git-08b277b76.

Characters "asteriskcomb" and "doublemacroncomb" are too fat in Inter Thin Italic. This also affects composite glyph "doublemacronbelowcomb".

Also "version" glyph seems outdated ;-)

In the attached screenshot the top line is Inter Thin Italic and the bottom line is Inter Thin.

![InterIssues](https://user-images.githubusercontent.com/77341841/112973857-0b6d7280-9152-11eb-9508-c6ec0c4f4649.png)

**Comment by rsms** [comment]
Thanks for the report!

The "version" glyph is not exported. (I'm assuming you are looking at the .glyphs source file)

I'm not sure where you found the names "asteriskcomb", "doublemacroncomb" and "doublemacronbelowcomb" — these are not names of glyph in Inter. Is it possible you've used some software that assigned these names? For example, U+0359 COMBINING ASTERISK BELOW does exist in Inter but is called "uni0359" in the .glyphs source file.

**Comment by rsms** [comment]
I've found U+035E COMBINING DOUBLE MACRON to be messed up for Thin Italic — nice find! (Still not sure where you got those glyph names from :–)

**Comment by ErwinDenissen** [comment]
I opened Inter-3.17\Inter Variable\Inter.ttf in FontCreator 14 which we intend to release in May this year.

![FontCreatorInter](https://user-images.githubusercontent.com/77341841/113227113-1b8c6b80-9292-11eb-9a65-b8ab2f717a38.png)

**Comment by rsms** [comment]
Ah! I'm guessing that you assign glyph names from maybe the Adobe Glyph List?
Anyhow, I found the asterisk glyph too U+20F0 COMBINING ASTERISK ABOVE and am fixing it. Thanks!

**Comment by rsms** [comment]
Before:
<img width="207" alt="Screen Shot 2021-03-31 at 17 50 26" src="https://user-images.githubusercontent.com/47046/113228420-b1e86f00-9249-11eb-9046-6bc87d0d8e8a.png">

After: (with 05cb494342374f9f69397c47dd12c18b4c8d2ca1)
<img width="206" alt="Screen Shot 2021-03-31 at 17 50 52" src="https://user-images.githubusercontent.com/47046/113228429-b90f7d00-9249-11eb-9aed-63b51b1dffea.png">

Once a new version has been released you'll be able to test it here: <https://rsms.me/inter/lab/?italic=1&sample=X⃰x⃰x͞x͟&size=64&weight=100>

**Comment by rsms** [comment]
Note that alignment is messed up and I'm not sure how to tackle this without crafting dedicated glyphs with mapping in ccmp. Maybe we can use marks/anchors for this?

**Comment by rsms** [comment]
Yup, marks works!
<img width="518" alt="Screen Shot 2021-03-31 at 18 27 12" src="https://user-images.githubusercontent.com/47046/113230836-ba8f7400-924e-11eb-9ce2-f3d719015ea1.png">

**Comment by rsms** [comment]
[Released with v3.18](https://github.com/rsms/inter/releases/tag/v3.18)
