### ISSUE TITLE
Is "Multi-axis, single variable font" still experimental?

### ISSUE THREAD

**Issue by xPaw** [rsms/inter#364]
https://github.com/rsms/inter/blob/310a73bad970c7ab593f9da4a1db12333c97f5ea/misc/dist/inter.css#L182-L192

It seems to work in Firefox and Chrome without `font-variation-settings`, and I can't quite see this on caniuse.

So is it still experimental or can be used safely for evergreen browsers?

**Comment by rsms** [comment]
It's not "experimental" specifically to Inter. Inter's variable font is production grade. The "experimental" disclaimer is related to implementors of text shapers/layout engines. Support for simple variable fonts is still spotty and support for multi-axis VFs is even spottier. Most web browsers do have good support and few bugs at the time of writing this, but a lot of non-web apps have issues. Refer to app manufacturers' documentation for more information.

Re your second question, for now I'd use single-axis variable fonts if you are targeting "anyone".

**Comment by xPaw** [comment]
Would you mind giving a pointer on figuring out what actually supports this? Caniuse doesn't list this specifically.
