### ISSUE TITLE
Option to alter Skew amount

### ISSUE THREAD

**Issue by TheLunaPark** [rsms/inter#365]
I discovered _Inter_ only a few days ago but it's already become one of my favourite typefaces. To be honest, the only thing I'd change is the skew at stroke junctions in some of the characters e.g. _g, h, n, m._ I personally would prefer them to be less skewed giving a thicker, less 'humanist' appearance. Perhaps it could be done using an alternative glyphs setting? I'm afraid I'm not able to contribute to this myself but I'd be very grateful if this could be achieved!

Thank you!

**Comment by rsms** [comment]
Hey hi glad you like Inter! I'm not sure I understand your request. Would you mind showing some visual examples of what you mean?

**Comment by TheLunaPark** [comment]
Hi, thank you for your reply. I apologise for not making myself clear enough! Hopefully the attached image explains things better.

I was referring to the junctions in some of the letters. The strokes reduce quite a lot giving it an almost humanist appearance at these points. I did read on the GitHub main page for Inter that this may have already been acknowledged and that Inter isn't suitable for large headings because of this. I believe its purpose is for better legibility at small pt sizes?

I hope that makes sense. Thanks for your time and for creating Inter in the first place!

![Inter GitHub Image](https://user-images.githubusercontent.com/82131815/122620743-a0b24000-d08b-11eb-8237-a392d999f55e.png)
