### ISSUE TITLE
discussion: diagonal arrows ( ↖ ↗ ↘ ↙ )

### ISSUE THREAD

**Issue by wayne-shih** [rsms/inter#366]
Currently the `northEastArrow ↗` and `northWestArrow ↖` on Inter is top aligned to the cap height and the `southEastArrow ↘` and `southWestArrow ↙` is bottom aligned to the baseline. 

Wondering if there was any specific intentions in this choice? 

<img width="803" alt="Screen Shot 2021-04-12 at 9 06 22 AM" src="https://user-images.githubusercontent.com/51947763/114321313-5df55880-9b6e-11eb-896c-e2a9fe08d52c.png">

I am currently using the northEastArrow as the external link icon. To me it just looks a bit off with the arrow slightly hovering

> <img width="441" alt="Screen Shot 2021-04-12 at 9 10 06 AM" src="https://user-images.githubusercontent.com/51947763/114321441-e673f900-9b6e-11eb-8508-34f4a78f2c89.png">

— —

Looking at other system fonts, they all seem to be centre vertical aligning to each other 

SF:

<img width="1066" alt="Screen Shot 2021-04-12 at 9 21 58 AM" src="https://user-images.githubusercontent.com/51947763/114321767-8f6f2380-9b70-11eb-84ab-be24b51f6ca5.png">

Segoe UI:

<img width="1058" alt="Screen Shot 2021-04-12 at 9 18 51 AM" src="https://user-images.githubusercontent.com/51947763/114321685-2091ca80-9b70-11eb-8283-51a99f0c249c.png">

Fira Sans:

<img width="946" alt="Screen Shot 2021-04-12 at 9 19 15 AM" src="https://user-images.githubusercontent.com/51947763/114321695-2b4c5f80-9b70-11eb-84c4-5fab4a7fd271.png">

Also begs the question if Inter decides to support Unicode _Supplemental Arrows-B_... and add northWestAndSouthEastArrow ⤡ + northEastAndSouthWestArrow ⤢ whether those would be centre aligned, or extended so the top hits the cap height and the bottom hits the baseline.

**Comment by rsms** [comment]
How about this?

<img width="1252" alt="Screen Shot 2023-06-07 at 13 37 07" src="https://github.com/rsms/inter/assets/47046/d6138f87-af9e-476a-8ad4-bffe87083111">
