### ISSUE TITLE
ccmp with numbers

### ISSUE THREAD

**Issue by thlinard** [rsms/inter#368]
**Describe the bug**
Numbers outside forms.

**To Reproduce**
1. Go to https://rsms.me/inter/

**Screenshots**
<img width="435" alt="Inter" src="https://user-images.githubusercontent.com/13808824/114536403-55c21980-9c51-11eb-9fe8-b52bfd27ecba.png">

**Environment**
- OS: macOS 10.15.7
- Firefox, Safari, Chrome

**Comment by hcsch** [comment]
It seems to me, that the HTML and text examples for that part of the page are just not right.
What I get visiting https://rsms.me/inter/#features/ccmp (with the result as shown in the image of the issue description):
```html
<grid columns="8">
    <c span="4" class="low-contrast">Disabled</c>
    <c span="4" class="low-contrast">Enabled</c>
    <c span="4" class="sample ff-none">Figure A<em>⃝</em></c>
    <c span="4" class="sample ff-ccmp">Figure A⃝</c>
    <c span="4" class="sample ff-none">Figure #<em>⃞</em></c>
    <c span="4" class="sample ff-ccmp">Figure #⃞</c>
    <c span="4" class="sample ff-none">Figure <em>⃝</em>3</c>
    <c span="4" class="sample ff-ccmp">Figure ⃝3</c>
    <c span="4" class="sample ff-none">Figure <em>⃞</em>3</c>
    <c span="4" class="sample ff-ccmp">Figure ⃞3</c>
</grid>
```
Here the composing characters are sometimes in front, sometimes behind the character to be enclosed, when they really should always be behind the character to enclose. The `<em>`s don't seem to hinder the composition of characters, though they also don't seem to have any visual effect for me.

This is what I would expect:
```html
<grid columns="8">
    <c span="4" class="low-contrast">Disabled</c>
    <c span="4" class="low-contrast">Enabled</c>
    <c span="4" class="sample ff-none">Figure A<em>⃝</em></c>
    <c span="4" class="sample ff-ccmp">Figure A⃝</c>
    <c span="4" class="sample ff-none">Figure #<em>⃞</em></c>
    <c span="4" class="sample ff-ccmp">Figure #⃞</c>
    <c span="4" class="sample ff-none">Figure 3<em>⃝</em></c>
    <c span="4" class="sample ff-ccmp">Figure 3⃝</c>
    <c span="4" class="sample ff-none">Figure 3<em>⃞</em></c>
    <c span="4" class="sample ff-ccmp">Figure 3⃞</c>
</grid>
```
And this is what it gives you:
![image](https://user-images.githubusercontent.com/34245439/119252948-22a76a00-bbaf-11eb-908e-4ae0f6117b2d.png)

Showing that Inter probably handles the ccmp features for enclosing compositions with numbers just fine :). It also results in more consistent issues with the default composition of character without ccmp enabled.

(I used Firefox 90.0a1 on ArchLinux for this)

**Comment by ChiefMikeK** [comment]
Also need to fix website render of `ss01`   
![inter-ss01](https://user-images.githubusercontent.com/20070053/119606007-a1b2c300-bda6-11eb-83ff-8c956f99f9b6.png)

**Comment by Porges** [comment]
Just noting that this appears identical to @thlinard’s image when using Windows (Edgium):

![image](https://user-images.githubusercontent.com/12575/122134166-2f5b6d00-ce92-11eb-8b8a-227211829079.png)

**Comment by rsms** [comment]
Good catch! Indeed the website data is incorrect.

**Comment by rsms** [comment]
<img width="461" alt="Screen Shot 2021-06-18 at 10 38 40" src="https://user-images.githubusercontent.com/47046/122598406-a3784b00-d021-11eb-92b1-3cacc5e611fe.png">
