### ISSUE TITLE
Euro sign

### ISSUE THREAD

**Issue by pakastin** [rsms/inter#37]
Euro sign `€` looks a bit weird:

- a bit too condensed – could be at least more like an open circle (~280°)
- bottom of the two horizontal lines should be shorter

I'm not saying it should be **exactly** this, but at least closer to: https://en.wikipedia.org/wiki/Euro_sign#/media/File:Euro_Construction.svg

*ps. I have to say how excited I'm about this project! Inter UI is the most beautiful UI font I've ever seen and it's getting even better all the time – **thank you** for doing this!* ❤️

**Comment by rsms** [comment]
Work in progress:
<img width="1429" alt="screen shot 2017-10-30 at 11 19 43" src="https://user-images.githubusercontent.com/47046/32188171-4f5bcd7c-bd64-11e7-9eeb-3af9761df63c.png">

**Comment by pakastin** [comment]
Wow, that’s a beauty! 👌

**Comment by rsms** [comment]
Progress update
<img width="1702" alt="frame 10 1" src="https://user-images.githubusercontent.com/47046/32401090-d85c14b0-c0c5-11e7-81eb-d3233348e778.png">

**Comment by pakastin** [comment]
I saw that on Twitter, it’s a beauty! 😎

**Comment by rsms** [comment]
Done in https://github.com/rsms/inter/commit/51185e3e73f32c2d62e9545b2754a09445cdc693

**Comment by pakastin** [comment]
Thank you, will try soon in practice!

**Comment by pakastin** [comment]
It's perfect, thank you! 🎉

**Comment by rsms** [comment]
😃
