### ISSUE TITLE
Cyrilic colon jumps up, comparing to latin colon

### ISSUE THREAD

**Issue by teinett** [rsms/inter#370]
<img width="697" alt="Снимок экрана 2021-04-26 в 22 14 42" src="https://user-images.githubusercontent.com/1038168/116137967-e92d2d00-a6dc-11eb-923a-bcf544ce7642.png">

Screenshot is attached.

https://fonts.google.com/specimen/Inter?preview.text=%D0%BA%D0%B8%D1%80%D0%B8%D0%BB%D0%B8%D1%86%D0%B0:%2016%20latin:%2016&preview.text_type=custom#standard-styles

**Comment by rsms** [comment]
Would you mind trying with the official release from https://rsms.me/inter/ ? The fonts from Google Fonts are really old (over a year behind releases.) You can try it quickly here: https://rsms.me/inter/lab/

Also, it would be helpful if you could post the sample text you used and not just a screenshot. Thanks!

**Comment by VladWinner** [comment]
Sample text:
`кириллица: 16 latin: 16`

I can't confirm this issue on the latest build.
![image](https://user-images.githubusercontent.com/13555921/122622102-4bccf480-d0a0-11eb-9c02-b3bc1634d346.png)

But I found another weirdness with "Other Inter family" option enabled (letters are not aligned):
![image](https://user-images.githubusercontent.com/13555921/122622181-89318200-d0a0-11eb-893d-454d6255bf39.png)
Maybe this is not a font problem, but online lab rendering problem.

**Comment by teinett** [comment]
@rsms I reinstalled the font from the provided link: font Inter-3.19. Thanks for the advice!

Cyrillic letter "ц" is better now, but it is still have difference with cyrillic "щ" with the same ending part:

<img width="603" alt="2021-06-22 13-07-37" src="https://user-images.githubusercontent.com/1038168/122906742-26b7da80-d35b-11eb-9f2f-f724a6ec72fb.png">

**Comment by VladWinner** [comment]
Then you should close your issue.

**Comment by rsms** [comment]
Glad to hear it. Thanks for testing it out!
