### ISSUE TITLE
ss01 for superscript and subscript numbers

### ISSUE THREAD

**Issue by stone-zeng** [rsms/inter#372]
The stylistic set 1 (alternate digits) should be applied for all the variants of digits, such as the superscripts and subscripts (³⁴⁶⁹ and ₃₄₆₉). It should be applied for `subs`, `sups`, `dnom`, `numr` and `frac` features as well.

**Comment by rsms** [comment]
I forgot to close this out — it's been implemented since version 4.0

<img width="1143" alt="Screen Shot 2024-11-18 at 18 56 48" src="https://github.com/user-attachments/assets/be877ad6-daa9-4284-9783-180cedb9d571">
