### ISSUE TITLE
Add U+25AA (small black square glyph)

### ISSUE THREAD

**Issue by dmitryperets** [rsms/inter#373]
It looks like the glyph U+25AA (corresponding to CSS `ul { list-style-type: square; }` - the small black square symbol) is missing in Inter. This is a popular choice for the third-level bulleted list in different user agent stylesheets. 

For example, I am using WeasyPrint to render PDF from HTML, with Inter as my main typeface. So I get weird symbols instead of the small black square in bulleted lists, unless I add other fonts where this glyph is available. 

Would be great to have it natively in Inter!

**Comment by rsms** [comment]
<img width="877" alt="sdf0jio1" src="https://user-images.githubusercontent.com/47046/122613043-06291100-d039-11eb-95b0-d4ed7166d030.png">

Once this lands in a new release you can try it out live here: [https://rsms.me/inter/lab/?sample=%E2%96%AAxxl%0A%E2%96%AAX...](https://rsms.me/inter/lab/?sample=%E2%96%AAxxl%0A%E2%96%AAXXL%0A%E2%80%A2xxl%0A%E2%80%A2XXL%0A%E2%81%83xxl%0A%E2%81%83XXL%0A%E2%80%A3xxl%0A%E2%80%A3XXL&size=48)

**Comment by rsms** [comment]
Here's a pre-release build with U+25AA:
[Inter-3.18-text-ad5c235a1c.zip](https://github.com/rsms/inter/files/6679288/Inter-3.18-text-ad5c235a1c.zip)

**Comment by rsms** [comment]
This has been released with [v3.19](https://github.com/rsms/inter/releases/tag/v3.19)
