### ISSUE TITLE
Please remove ligature for 0x

### ISSUE THREAD

**Issue by rillig** [rsms/inter#375]
The text `0x0` (zero, x, zero) is rendered indistinguishable from `0×0` (zero, multiplication, zero).
This creates confusion for at least some readers.
The ligature should be removed.

See also:
* https://youtrack.jetbrains.com/issue/JT-60903
* https://github.com/tonsky/FiraCode/issues/944
* https://github.com/JetBrains/JetBrainsMono/issues/98

**Comment by rsms** [comment]
This is a very popular feature and removing it would break a lot of existing things. You can turn it off (calt) where there's risk for ambiguity.

**Comment by kenmcd** [comment]
> This is a very popular feature and removing it would break a lot of existing things.

Popular with who and why?

What would it break?

Inserting a defined Unicode character where it does not belong is always going to create confusion.
To me this is just an annoyance that the other fonts have thankfully removed.

**Comment by rsms** [comment]
> > This is a very popular feature and removing it would break a lot of existing things.
> 
> Popular with who and why?
Humans. People using web browsers, Figma, Sketch etc. Here are the stats for people loading the font from the CDN:
<img width="778" alt="Screen Shot 2021-05-13 at 12 26 41" src="https://user-images.githubusercontent.com/47046/118176675-947cf800-b3e6-11eb-85f7-9ecf5f937e97.png">


> 
> What would it break?
Because it would cause things to look different.
<img width="774" alt="Screen Shot 2021-05-13 at 12 29 03" src="https://user-images.githubusercontent.com/47046/118176915-dad25700-b3e6-11eb-8bdd-ac016509b17d.png">


> Inserting a defined Unicode character where it does not belong is always going to create confusion.
> To me this is just an annoyance that the other fonts have thankfully removed.
You're welcome to disable calt.

**Comment by rillig** [comment]
> > > This is a very popular feature and removing it would break a lot of existing things.
> >
> > Popular with who and why?
>
> Humans.

That sounds like a no-op argument. Is there any font that is not created for humans? Ok, maybe OCR fonts, but aside from that?

> > Popular with who and why?
>
> People using web browsers, Figma, Sketch etc. Here are the stats for people loading the font from the CDN:
> <img alt="Screen Shot 2021-05-13 at 12 26 41" width="778" src="https://user-images.githubusercontent.com/47046/118176675-947cf800-b3e6-11eb-85f7-9ecf5f937e97.png">

Are these people actually aware of the 0x0 ligature? Otherwise your argument is flawed since it doesn't answer the question about the popularity of the 0x0 ligature. Instead it answers the question about the popularity of the font as a whole, which is an entirely different question.

> > What would it break?
> Because it would cause things to look different.
> <img alt="Screen Shot 2021-05-13 at 12 29 03" width="774" src="https://user-images.githubusercontent.com/47046/118176915-dad25700-b3e6-11eb-8bdd-ac016509b17d.png">

Looking different does not necessarily mean that it breaks something.
Apart from being rendered differently, is there anything that would _actually break_ if the 0x0 ligature were removed?
