### ISSUE TITLE
ss01 does not include one

### ISSUE THREAD

**Issue by hcsch** [rsms/inter#378]
**Describe the bug**
The feature file for ss01 does not include one, as such, when enabling the ss01 feature, the curved one is not used (unlike with cv01).

**To Reproduce**
1. Open https://rsms.me/inter/#features/ss01 (or use the lab with the ss01 feature on the website or built after cloning the repo)
2. Observe the default one both with the feature enabled and disabled

**Expected behavior**
One is included in ss01 and therefore exchanged for its alternate form when this feature is enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/34245439/119626105-29321d80-be0b-11eb-91cf-9f4086f24f9f.png)
vs
![image](https://user-images.githubusercontent.com/34245439/119626164-36e7a300-be0b-11eb-912b-8d42101f09c1.png)

**Environment**
- OS: ArchLinux
- Firefox
- 3.18 and bd96939

**Additional context**
This issue was discovered by @ChiefMikeK in #368

**Comment by rsms** [comment]
This is intentional, that /one.ss01 is not in ss01. It used to be and thus its glyph name.
Better would be to
- rename the glyphs to `one.1`
- remove the "1" highlight on the website example

**Comment by hcsch** [comment]
Ah alright then. Thanks for your response. Given a couple days time I could create a PR for that, though as of now I'm still unfamiliar with the code for the website.

**Comment by rsms** [comment]
<img width="462" alt="Screen Shot 2021-06-18 at 10 38 35" src="https://user-images.githubusercontent.com/47046/122598331-8a6f9a00-d021-11eb-87a0-9352653c31a9.png">
