### ISSUE TITLE
Inter V: Wrong interpolation of roman numeral eight (U2167)

### ISSUE THREAD

**Issue by grommas** [rsms/inter#382]
**Describe the bug**
In Inter V (Variable) the roman numeral eight has a wrong interpolation from weight 400 upwards. The single forms are moving. Seems to have a wrong order. 

**To Reproduce**
1. Use Inter V
2. Set the text to Ⅷ
3. Set the weight to more than 400

**Expected behavior**
Consistent interpolation

<img width="431" alt="Bildschirmfoto 2021-06-09 um 00 05 28" src="https://user-images.githubusercontent.com/5681075/121264038-cfbff900-c8b6-11eb-8a6d-5f68d3977fe5.png">

**Environment**
- OS: macOS 11.4
- InDesign
- Version of font: 3.018;git-588b23468

**Comment by rsms** [comment]
Good catch!

**Comment by rsms** [comment]
![sdfmio1](https://user-images.githubusercontent.com/47046/122615627-aaad5200-d03d-11eb-8648-ab02b8e06920.gif)

**Comment by rsms** [comment]
Once this lands in a release you can test it live here: [https://rsms.me/inter/lab/?sample=%E2%85%A0%20...](https://rsms.me/inter/lab/?sample=%E2%85%A0%20%E2%85%A1%20%E2%85%A2%20%E2%85%A3%20%E2%85%A4%20%E2%85%A5%20%E2%85%A6%20%E2%85%A7%20%E2%85%A8%20%E2%85%A9%20%E2%85%AA%20%E2%85%AB&size=64&varWeight=600&varfont=1)

**Comment by rsms** [comment]
This has been released with [v3.19](https://github.com/rsms/inter/releases/tag/v3.19)
