### ISSUE TITLE
3.19 inter font not showing up correctly on some web pages

### ISSUE THREAD

**Issue by Some-T** [rsms/inter#386]
I seen it on a few other pages, but basically this is an email from Grammarly:

[](https://i.gyazo.com/20e4097f6f4f156aa9727f1ff9abf7f4.png)

https://i.gyazo.com/48c812b7c25021512e4b22fcb0f2f5dc.mp4

This is happening in the latest version of Firefox web browser, it don't happen in chrome based browsers. 

Overall only started happening after installing font version v3.19 on Windows 10

**Comment by VladWinner** [comment]
This can happen if you install a new version of the font after the old one. Use a clean install (with pre-removal of old versions).

**Comment by Some-T** [comment]
> 
> 
> This can happen if you install a new version of the font after the old one. Use a clean install (with pre-removal of old versions).

Yeah it seemed to work as normal when I restarted my computer, and after doing this thanks.
