### ISSUE TITLE
Inter Display releases

### ISSUE THREAD

**Issue by manuelmeister** [rsms/inter#389]
Is it possible to create newer releases for `Inter Display` as well? I assume there have been changes since the last release ([beta-1](https://github.com/rsms/inter/releases/tag/display-beta-1))

**Comment by rsms** [comment]
There really have not been any changes since that release. Once there are I will make sure to publish new releases of Inter Display :–)

**Comment by rsms** [comment]
BTW, you can build your own by checking out the code, running the `./init.sh` script and then `make -j$(nproc) zip_display`
