### ISSUE TITLE
German Umlauts and "T"

### ISSUE THREAD

**Issue by fsavigny** [rsms/inter#39]
Hi!

I would like to report an issue: "T" collides with the dots of German Umlauts.
 
![umlauts](https://user-images.githubusercontent.com/21968142/32142855-dcaccc32-bc9f-11e7-8956-5450ffba7b63.png)

The French accent circonflexe also looks a bit misplaced next to "T", i.e. in the word "Tête".

Thank you very much for this beautiful font!

**Comment by rsms** [comment]
Oh man, definitely a bug and the result of being too agressive with kerning groups. I'll fix this in the next release.

**Comment by rsms** [comment]
[TODO] Explode diacritics into compound glyphs so that kerning exceptions can be made. Alternatively add kerning exceptions to features.fea, though we'd have to figure out how to visualize the kerning effectively (so it's not a slow game of adjusting & recompiling.)

**Comment by rsms** [comment]
Addressed and fixed in [version 2.3](https://github.com/rsms/inter/releases/tag/v2.3)
