### ISSUE TITLE
google fonts stylistic alternatives?

### ISSUE THREAD

**Issue by malykh** [rsms/inter#392]
Where are stylistic alternatives in google fonts? 
I get a list of stylistic alternatives options in figma (supplied by pre-installed default google fonts), but installing webfonts on  the website directly from google via "font-feature-settings" doesn't do anything.

**Comment by rsms** [comment]
Please ask Google Fonts.

**Comment by thien-do** [comment]
Just wanted to add a note for future visitors that Google Fonts is not really good in term of OpenType features. Many are missing. It's much better to host the font yourself or at least use the version hosted on rsms's website (which I believe means GitHub hosted)
