### ISSUE TITLE
Can i in My Team Project Game use this is Font?

### ISSUE THREAD

**Issue by chenjj100419** [rsms/inter#397]
Can i in My Team Project Game use this is Font?
My Team Project use AGPLv3.0
This is a public welfare project, only donation, we will not force charges, which are voluntary players.

我可以在我的团队项目游戏中使用这个字体吗？
我的团队项目使用AGPLv3.0协议
这是一个公益项目，只有捐款渠道，我们不会强行收费，这是玩家自愿的。

**Comment by nsemrau** [comment]
Inter is licensed under the SIL Open Font Licence 1.1. You can use it for your project and pretty much anything else. Refer to [the licence's text](https://choosealicense.com/licenses/ofl-1.1/) here if your team wants to clear up further questions.

**Comment by chenjj100419** [comment]
Can i use this is font in my video

**Comment by nsemrau** [comment]
Yes.

**Comment by rsms** [comment]
Yes
