### ISSUE TITLE
As this font family is open source, can I develop a new monospace font family, mixing with Fira Code?

### ISSUE THREAD

**Issue by gusbemacbe** [rsms/inter#40]
Hello,

I have just received an e-mail that you updated the fonts, adding many new glyphs. It is wonderful. As it is a multilingual font, it must be useful for a polyglot programmer and web developer and designer. 

But as it is an open source font family, can I develop a new monospaced font family, mixing with fonts Fira Code, Kawlab Mono and other fonts, and adding maths glyphs, Georgian, Hebrew and Klingon glyphs? Is it bad or good idea for you?

Maybe I'll start to develop the new glyphs for fonts Gidole, Source Code Pro and this font on holiday.

**Comment by rsms** [comment]
You can do whatever you want, as long as you're following [the license](https://github.com/rsms/inter/blob/master/LICENSE.txt) of Inter UI and the licenses of any other fonts you may be modifying or using :)

**Comment by rsms** [comment]
BTW, please don't file an issue when you have a question.

[Send me a message on Twitter](https://twitter.com/rsms) instead or [an email](https://github.com/rsms)

**Comment by kleerkoat** [comment]
sorry for the me too. would be a universal strain on my eyes across the system. thank you.
