### ISSUE TITLE
Installing single-axis ttfs (-italic.ttf and -roman.ttf) overwrites one another on Windows 10

### ISSUE THREAD

**Issue by huiguang-liang** [rsms/inter#400]
**Describe the bug**
Installing the single-axis Inter variable fonts on Windows 10 (-italic.ttf and -roman.ttf) will overwrite one another as they are both named `Inter`.

**To Reproduce**
1. Download and unzip from [Inter-3.19](https://github.com/rsms/inter/releases/download/v3.19/Inter-3.19.zip)
2. Go to `.\Inter-3.19\Inter Variable\Single axis`. Try installing each font one after another.
3. Warning message comes up: "The 'Inter' font is already installed. Do you want to replace it?"

**Expected behavior**
Inter-roman.ttf should install as a `Regular` variant, while the Inter-italic.ttf should install as an `Italic` variant. For reference, the variable [JetBrains Mono](https://github.com/JetBrains/JetBrainsMono/releases/tag/v2.242) font installs this way. JetBrains Mono still shows up correctly as one unified font family in Windows Fonts, as expected.

![image](https://user-images.githubusercontent.com/4099058/132693524-e0cf0bc8-d458-461d-b376-c7868e6c469d.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/4099058/132689873-66c30e34-784a-4afd-9f1a-f0a900c395ea.png)

**Environment**
- OS: Windows 10
- Version of font [https://github.com/rsms/inter/releases/tag/v3.19](https://github.com/rsms/inter/releases/tag/v3.19)

**Additional context**
I would have installed the 'combined' variable font in Inter `.\Inter-3.19\Inter Variable\Inter.ttf`, but font formatting does not work as expected in PowerPoint. Italic has to be explicitly chosen as a different font, rather than comply with italic font formatting (i.e. control+I), otherwise, faux-italic is applied instead. Please see attached screenshot.

![image](https://user-images.githubusercontent.com/4099058/132693021-43f49c25-dd8a-41b4-89fb-0d0cc37e9b7d.png)

**Comment by kenmcd** [comment]
>     3\. Warning message comes up: "The 'Inter' font is already installed. Do you want to replace it?"

This is a name conflict between the static Inter-Regular and the default instance in the variable Inter-roman - not a conflict between the roman and italic variable fonts.

Do not install both the static and the variable fonts.
This will cause many name conflicts between the static fonts and the named instances in the variable fonts.

**Comment by huiguang-liang** [comment]
> > ```
> > 3\. Warning message comes up: "The 'Inter' font is already installed. Do you want to replace it?"
> > ```
> 
> This is a name conflict between the static Inter-Regular and the default instance in the variable Inter-roman - not a conflict between the roman and italic variable fonts.
> 
> Do not install both the static and the variable fonts.
> This will cause many name conflicts between the static fonts and the named instances in the variable fonts.
> 
> UPDATE: you are right - just the variable fonts alone will conflict.
> I un-installed the static fonts and tried to install just the two variable fonts and got the same error.
> 
> So it looks like the only work-around at the moment is to use only the static fonts.

Thank you for the confirmation. Will await the devs to chip in. Cheers.

**Comment by rsms** [comment]
This has been resolved. Please try [v4.0-beta9f](https://github.com/rsms/inter/releases/tag/v4.0-beta9f)
