### ISSUE TITLE
v3.19 Interpolation Issues

### ISSUE THREAD

**Issue by kenmcd** [rsms/inter#401]
Inter v3.19 Interpolation Issues

**Regular**
030B acutedblnosp - ???
2423 spaceopenbox - startpoint different in Thin master
02F6 acutedblmiddlemod - ???
02FA tonehighendmod - element order different in Black master
036E vcomb - startpoint different on right element in Thin master
1DFD almostequaltobelowcomb - element order different in Thin master 
         (does not show here because I fixed it when testing, see Italics below - same issue)
2016 verticalbardbl - contours overlap

![v3 19-Regular-Interpolation-Issues-2021-09-09](https://user-images.githubusercontent.com/844920/132763045-9f49bd53-225f-494e-8d3b-acc5e595ceae.gif)

**Italic**
.notdef - wobbles - Italic master is upright, other two masters are slanted
0246 Estroke - startpoint different on vertical stroke in ThinItalic master
00D8 Oslash - slash wobbles
01FE Oslashacute - slash wobbles
20A1 colonmonetary - strokes wobble
030B acutedblnosp - ???
2380 insertion - startpoint different on v in ThinItalic master
02EF arrowheaddownlowmod - element order different in ThinItalic master
01C2 clickalveolar - element order different in BlackItalic master
2423 spaceopenbox - startpoint different in Thin master
02F6 acutedblmiddlemod - ???
035C doublebrevebelowcomb - startpoint different in Thin master
035D doublebrevecomb - startpoint different in Thin master
036E vcomb - startpoint different on right element in Thin master
03CF Kaisymbol - startpoint different on lower right element in Thin master 
1DFD almostequaltobelowcomb - element order different in Thin master
2016 verticalbardbl - contours overlap

![v3 19-Italic-Interpolation-Issues-2021-09-09](https://user-images.githubusercontent.com/844920/132763091-103c0a8e-8a63-4df6-b360-081760a569fe.gif)

**Comment by VladWinner** [comment]
https://github.com/rsms/inter/pull/426/commits/84cbc69c123f0dc71e9d4af5e5c4f5a3db5abf65 partially solves the issues

**Comment by kenmcd** [comment]
Checked these against the beta 2022-07-27 opsz .ttf and the majority of this appears to be fixed.
The only exceptions are the wobbling diagonals, which I am going to assume is a design decision.
So closing this regarding v3.19.
And will post any other issues as regarding the new betas.
