### ISSUE TITLE
Numbers and symbols before @ causes it to appear higher

### ISSUE THREAD

**Issue by ksimons** [rsms/inter#402]
**Describe the bug**
If you place a number or symbol before the @ symbol it will appear slightly higher than when the character immediately preceding the @ is a normal letter. Adding another character after the @ causes it to return to its correct placement. This looks very odd when using it in inputs.

**To Reproduce**
1. Take a look at the strings "test1@" and "test@" and notice that that the @ is lower in the second case

**Expected behavior**
That the @ symbol remains in the same alignment regardless of the preceding character

**Screenshots**

<img width="73" alt="Screen Shot 2021-09-24 at 15 50 34" src="https://user-images.githubusercontent.com/935932/134685611-d6ca7e04-2775-479b-9e17-561a61db381d.png">
<img width="93" alt="Screen Shot 2021-09-24 at 15 49 02" src="https://user-images.githubusercontent.com/935932/134685614-0b259cf5-bfe6-4abe-981b-34c4218e8012.png">

**Environment**
- OS: macOS 10.15.7
- App that renders the font: Chrome
- Version of font: Inter Regular. Version 3.019;git-0a5106e0b

**Comment by ksimons** [comment]
We also noticed that removing one of the @ glyphs from the font files makes this problem go away, so please disregard if this is a feature 😉

**Comment by kenmcd** [comment]
This is an OpenType feature and is working as expected.
See: Contextual alternates (calt) and Case alternates (case) features
Here: https://rsms.me/inter/#features
So, not a bug.

**Comment by ksimons** [comment]
Thanks for the explanation! I'll close it then.
