### ISSUE TITLE
Include slashed zero in the Inter font available through Google Fonts

### ISSUE THREAD

**Issue by chrisg2** [rsms/inter#403]
Is it possible to get a slashed-zero when using the Inter font that is published through [Google Fonts](https://fonts.google.com/specimen/Inter)?

It appears the Inter font that is currently available through Google fonts does not show the slashed zero when the `font-variant-numeric: slashed-zero` CSS style is applied. For example:

```html
<head>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500&display=swap" rel="stylesheet">
</head>
<body style="font-family: Inter; font-variant-numeric: slashed-zero">
    <p>Inter font from Google Fonts does NOT show slashed zeros: 0000000</p>
</body>
````

This appears as:
![image](https://user-images.githubusercontent.com/7718991/135253904-3d3059e7-e77f-4e49-953f-d7c4da3e3bc6.png)

On the other hand, the font available through cdnjs does show slashed zeros:

```html
<head>
<link href="https://cdnjs.cloudflare.com/ajax/libs/inter-ui/3.19.3/inter.css" rel="stylesheet">
</head>
<body style="font-family: Inter; font-variant-numeric: slashed-zero">
    <p>Inter font from cdnjs does show slashed zeros: 0000000</p>
</body>
````
This appears as:
![image](https://user-images.githubusercontent.com/7718991/135253818-22d00c9e-b17d-4ae8-8ff3-f2bfbb3ab535.png)

FWIW, this matter has also come up in the following queries:
* [Why is font-variant-numeric: slashed-zero not working with my google font?](https://stackoverflow.com/questions/67100585/why-is-font-variant-numeric-slashed-zero-not-working-with-my-google-font)
* [Inter fonts / slashed-zero](https://github.com/google/fonts/issues/3522)

**Comment by rsms** [comment]
Google fonts are in the process of updating their build of Inter so on a few weeks you should see it available from their distribution.
In the future, for issues related to fonts distributed by Google, please file an issue with them instead at https://github.com/google/fonts — Thanks!
