### ISSUE TITLE
Equal signs render on different heights in some strings

### ISSUE THREAD

**Issue by fegeleiner** [rsms/inter#407]
> Did you get the font from Google Fonts? Then please head over to
> https://github.com/google/fonts/issues
> and file an issue with Google Fonts.
> If not, REMOVE THIS PARAGRAPH BEFORE FILING YOUR ISSUE.

**Describe the bug**
Equal signs "=" get raised in some strings.

**To Reproduce**
1.render a string like ================3 (sorry)

**Expected behavior**
All equal signs look the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/55122076/136952748-bc17d9d6-c552-4567-94df-9a9c914e3f7d.png)

**Environment**
- Windows 10
- Chrome, Firefox
Inter script=latin rev=5

**Comment by VladWinner** [comment]
#381

**Comment by rsms** [comment]
See @VladWinner's comment linking to some more detail about this (by design)
