### ISSUE TITLE
Allow generating custom weights as static fonts

### ISSUE THREAD

**Issue by peirantan** [rsms/inter#408]
It would be nice for the make script to allow generating custom locations in the designspace as static fonts.

For example, can I do something like `make -j Regular 450` and have the script build a version of regular that’s 450 instead of 400 on the weight axis?

Better yet, can I also do: `make -j Bold 750`, generate a Bold as 750, then when both of the files are installed, they’re linked as a family?

**Comment by ThomasRettig** [comment]
I believe there is software available to do that. Personally, I use [Slice](https://github.com/source-foundry/Slice). Dinamo Font Gauntlet’s ```Generate Static Font File``` option works well too, but data is sent over to their server for processing.

**Comment by alexmyczko** [comment]
https://github.com/jonpalmisc/vfit can do that.
