### ISSUE TITLE
opsz variable font axis?

### ISSUE THREAD

**Issue by ThomasRettig** [rsms/inter#411]
Currently, I see two main masters of this family: Regular + Display variant. While I understand that _Inter Display_ is currently still in the beta stage, it would be nice if Inter Display and (regular) Inter could be joined together via an ```opsz``` variable font axis. This would be a great bonus for me since the total file size would be decreased considerably.

Would love to hear any input on this!

**Comment by rsms** [comment]
Really interesting idea... If we can pull this off it could mean a faster path to a quality release of Inter Display.

A thought: I fear it would be a large amount of work for three reasons:
1. Inter Display uses a different UPM (2048) and we'd need to scale existing Display glyphs to 2816 UPM which requires manual work to correct all points and curves (not a crazy amount of work; maybe a few weekends.)
2. Inter Display has different glyph shapes in some cases (for example "X" in Display has no angle "bridges") making some glyphs incompatible for interpolation (required for VF.) This is fixable by adding extremely small matching "bridges" and ink traps in the Display glyphs.
3. Inter Display uses a lower x-height. This is the biggest issue I think as AFAIK x-height metrics metadata is not variable (I might be wrong on this.) Also, even if it does work to scale x-height metrics it might be weird to the user (for example if they match lower-case text with icons.) 

Something I don't know how to do: Not having to add 6 additional masters to Inter.glyphs
I recall reading about a feature in Glyphs.app that allows adding per-glyph masters/keys. I'm going to do some research into this. As it is now with Inter.glyphs and its 6 masters, my maxed-out MacBook Pro can barely handle it. Glyphs.app is already laggy and slow as it is working on this font and making it even slower would be painful.

**Comment by rsms** [comment]
It's happening! #463

**Comment by rsms** [comment]
Done in source!

Close to shipping version 4 which incorporates an opsz axis. Here's the latest beta release: [v4.0-beta9f](https://github.com/rsms/inter/releases/tag/v4.0-beta9f)
