### ISSUE TITLE
Incorrect rendering in Inter Display v3.013

### ISSUE THREAD

**Issue by ThomasRettig** [rsms/inter#412]
**Describe the bug**
I am experiencing incorrect rendering of the character "A" in Inter Display.

## To Reproduce
1. Open Figma 
2. Create a text box
3. Type the uppercase letter "A"
4. Set font family to Inter Display

## Expected behavior
The uppercase letter "A" should render normally. I believe that this is some sort of interpolation issue. It is interesting to note that this only affects the ```extralight``` and ```light``` weights, not the ```thin``` weight. I also don't think this is a hinting issue as it does not change when I increase or decrease the font size.

## Screenshots
![Inter Display bug](https://user-images.githubusercontent.com/68767503/142863855-4378fa7b-a33f-46bc-8a94-138d009d1ac1.png)

## Environment
- OS: Windows 11
- Figma (desktop version)
- Version of font: 3.013 (latest version)

**Comment by kenmcd** [comment]
The latest version is v3.19 - not v3.13.
And this issue was fixed.

**Comment by kenmcd** [comment]
Some clarification: This issue was fixed in the Inter Display master.
**But,** the only Inter _Display_ fonts available for download are v3.13.
So some updated Display fonts are needed.
