### ISSUE TITLE
Add Inter Display and use tabular numbers by default

### ISSUE THREAD

**Issue by MattMayuga** [rsms/inter#413]
Thanks for the Inter font family! It has been a great font to use for UI elements.

While I'm at it, I have two things to consider:

### Add Inter Display the to releases tags
This is the first thing I want to have added to the release packages for newer versions of Inter. With these, it can make it easier to get the Display variants of Inter, so anyone can use it.

### Use tabular numbers by default
Some sans serif fonts, such as this font, Noto Sans, Fira Sans, Roboto, and many more have OpenType features which let you use tabular or proportional numbers. In my opinion, tabular numbers should be the default feature for numbers since not all programs have the ability to use OpenType features like this. Proportional numbers are suitable for headings and titles, while tabular numbers are for things like displaying date and time and comparing columns. I'm all right with this if tabular numbers aren't made the default.

**Comment by ThomasRettig** [comment]
Regarding Inter Display, I believe that it is still under beta development by the author, so perhaps it isn’t quite ready to be included in releases (yet). But I strongly agree with your second suggestion on enabling tabular numbers by default. FWIW, my current workaround for this, at least in my own projects, is to use a monospace font (with tabular numbers built-in).

**Comment by rsms** [comment]
Thank you @ThomasRettig — indeed Inter Display is not ready for mainstream use.

Regarding tabular numbers as default: no.
If you have a special need, like using 3rd party software without opentype settings, you can try using something like [opentype-feature-freezer](https://github.com/twardoch/fonttools-opentype-feature-freezer) to "freeze" feature configurations.
