### ISSUE TITLE
Many diamondwhite_x U+E000 styles have incorrect paths

### ISSUE THREAD

**Issue by ForestKatsch** [rsms/inter#415]
**Describe the bug**
Most of the `diamondwhite_x `U+E000` styles have pretty messed up paths on Chrome & Safari on macOS 12.

**To Reproduce**
1. Visit https://rsms.me/inter/glyphs/?g=diamondwhite_x
2. Many/most of the glyphs are pretty badly messed up

**Expected behavior**
The glyphs interpolate between the extreme styles smoothly

**Screenshots**
<img width="815" alt="Screen Shot 2021-11-30 at 4 24 22 PM" src="https://user-images.githubusercontent.com/42914657/144144082-0a0a4733-8bfb-4d71-a8ae-ac01a751b737.png">
<img width="800" alt="Screen Shot 2021-11-30 at 4 29 45 PM" src="https://user-images.githubusercontent.com/42914657/144144539-3ef659b3-f7b9-46c8-9e16-72248c9dbd45.png">

**Environment**
- OS: macOS 12.0.1
- Chrome 96.0.4664.55, Safari 15.1 (17612.2.9.1.20)
- Version of font: presumably 3.19 (URL from Network tab: `https://rsms.me/inter/font-files/Inter.var.woff2?v=3.19`) (fontdrop.info doesn't understand `.woff2`); 

**Additional context**
I've attached what I believe is the exact `.woff2` file exhibiting this issue
[Inter-diamondwhite_x-bug.zip](https://github.com/rsms/inter/files/7629529/Inter-diamondwhite_x-bug.zip)

**Comment by logant547** [comment]
Can confirm, the same thing happens in Microsoft Edge on Linux.
![Screenshot_20211208_004354](https://user-images.githubusercontent.com/45543257/145023421-fffeb0b9-b271-487f-8ac6-26576bf0ba37.png)

**Comment by kenmcd** [comment]
The element order is different in all three Italic masters.

![diamondwhite_x_E000_2021-12-09_17-05-27](https://user-images.githubusercontent.com/844920/145500095-08d76195-74a0-4e99-b6a6-e626a61f8727.gif)

**Comment by VladWinner** [comment]
https://github.com/rsms/inter/pull/426/commits/038c63e87bda60327f727809394b98e00569112d
