### ISSUE TITLE
Symbols not displaying correctly in Incognito.

### ISSUE THREAD

**Issue by aetinx** [rsms/inter#416]
> Both from Google Fonts AND Cloudflare CDN

**Describe the bug**
Some symbols don't display correctly in Incognito (Chrome 75, Chromebook).

**To Reproduce**
Steps to reproduce the behaviour:
1. Open https://beta.saco.ml and https://beta.saco.ml/docs#accounts/details in Incognito.

**Expected behaviour**
Display the fonts as they would browsing normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/65425469/144756712-5ce2fb9a-a8ac-4b09-9fb4-5d7a7f041d4e.png)
![image](https://user-images.githubusercontent.com/65425469/144756720-2cf34b48-f9f1-451d-948d-145e731beaa7.png)

**Environment**
- Google Chrome OS Version 75.0.3770.144 (Official Build) (32-bit)
- Chrome 75
- Version unknown

**Additional context**
...

**Comment by ThomasRettig** [comment]
The symbol in question appears to be the U+E13A private-use Unicode point. Does Inter cover this specific codepoint?

**Comment by aetinx** [comment]
> The symbol in question appears to be the U+E13A private-use Unicode point. Does Inter cover this specific codepoint? Maybe the fallback fonts are not deep enough?
> 
> I can confirm this is happening in latest Chrome version in MacOS 12 in both incognito and non-incognito modes.

It works when browsing normally.

**Comment by aetinx** [comment]
It works with `@import url("https://rsms.me/inter/inter.css?v=3.19");` though.

**Comment by ThomasRettig** [comment]
I thought so too. Maybe this is something wrong with the Google Fonts version?

**Comment by rsms** [comment]
The Google Fonts distro of Inter is years old and incomplete. Please use the official release from GitHub (also offered on Cloudflare CDN via the website rsms.me/inter)
