### ISSUE TITLE
Woff/Woff2 variables

### ISSUE THREAD

**Issue by Maraki412** [rsms/inter#417]
I have a file with huge number of woff/woff2 variable fonts which I cannot convert to TTF variables. Can you please explain the procedure and apps recommended, cause i have been trying for a long time and couldn`t find any tutorial anywhere. Thank you very much in advance.

**Comment by ThomasRettig** [comment]
Is this relating specifically to Inter? What options have you tried?

**Comment by Maraki412** [comment]
I tried FontForge with no success, I always get a basic 1 size TTF font, and same thing happens with any conversion app online. Somebody mentioned it could be done with Font Lab 7, but i`m afraid I don`t know the procedure as i mentioned before. I have windows 10 desktop.

**Comment by rsms** [comment]
Does not seem to be related to Inter
