### ISSUE TITLE
Inter Display font display circled number issue

### ISSUE THREAD

**Issue by WhiCCX0** [rsms/inter#418]
**Describe the bug**
I am using Inter Display on my android phone, but when the font display circled number suah as  ①②③④⑤⑥⑦⑧⑨
⑩⑪⑫⑬⑭⑮⑯⑰⑱⑲⑳⓪, it looks so wired
**To Reproduce**
1.go to [https://rsms.me/inter/lab/?antialias=default&family=display](url)
2.paste  ①②③④⑤⑥⑦⑧⑨⑩⑪⑫⑬⑭⑮⑯⑰⑱⑲⑳⓪ ,u will see

**Expected behavior**
I think this may be due to the fact that the middle number is not centered.
And ⓪ ①②③④⑤⑥⑦⑧⑨ look too big compared to normal letters and numbers

**Screenshots**
![Screenshot_20211227-144634_Lawnchair](https://user-images.githubusercontent.com/47388635/147443032-404f0277-23fd-46c0-bd57-08d42b25303c.png)
![Screenshot_20211227-144757_Lawnchair](https://user-images.githubusercontent.com/47388635/147443091-25be30a1-2db9-48a2-8337-82f56f3dcf78.png)

**Environment**
- OS: [Android 12]
- App that renders the font [Android 12 system]
- Version of font [InterDisplay.var.ttf Release v3.19]

**Additional context**
I don't know if this is a bug or a feature of inter display, if it's the feature, then just ignore this

**Comment by kenmcd** [comment]
Inter Display only includes the circled 0 thru 9.
Everything else you see is a fallback font.

But there is a problem in the Inter Display master (InterDisplay.glyphs) which causes the mis-alignment of the numbers in the circles.
It appears to be an interpolation issue.

![2021-12-27_12-11-37](https://user-images.githubusercontent.com/844920/147504345-e7375617-b6d5-4182-8cf1-1e9358ed8e5a.gif)

So there is an issue in the master(s) which would need to be fixed there,
and then new fonts generated.

**Comment by VladWinner** [comment]
Exists since v3.15 or earlier https://github.com/rsms/inter/issues/333
