### ISSUE TITLE
Section sign

### ISSUE THREAD

**Issue by fsavigny** [rsms/inter#42]
As I've studied law and therefore am frequently in touch with (European) legal documents, I've got another small suggestion regarding the section sign:
- it seems a little bit too low in relation to the following numbers — ideally the overlap at the top and the bottom would be the same.
- maybe the middle part could be a bit steeper and the top and bottom part narrower than the middle part; currently it looks more like two concatenated "S" letters (admittedly its origin) than a ligature.

![paragraph](https://user-images.githubusercontent.com/21968142/32244328-7e2f32dc-be78-11e7-9fec-0600bda7dff6.png)

Just a minor suggestion from a non-typographer — still love your font! ;-)

**Comment by fsavigny** [comment]
Or maybe a completely different approach, like i.e.
![00a7-500x500](https://user-images.githubusercontent.com/21968142/32246829-9785dad0-be80-11e7-86cd-56ca63dd726e.png)

? :smile:

**Comment by rsms** [comment]
Here's some work-in-progress of the section sign:

<img width="1541" alt="screen shot 2018-01-12 at 10 28 38" src="https://user-images.githubusercontent.com/47046/34889605-744ab482-f783-11e7-810c-f161c8285343.png">

**Comment by rsms** [comment]
Contextual sample
<img width="262" alt="screen shot 2018-01-12 at 10 43 05" src="https://user-images.githubusercontent.com/47046/34890085-6c9594ee-f785-11e7-8243-03a87b9d2f42.png">

**Comment by rsms** [comment]
![section-sample](https://user-images.githubusercontent.com/47046/34891351-2333f872-f78a-11e7-8297-dd18da958d1f.png)

**Comment by rsms** [comment]
Another update on progress
![section-sample 1](https://user-images.githubusercontent.com/47046/34909239-29a35fc2-f852-11e7-9d65-df41cc7b89b7.png)

**Comment by rsms** [comment]
Shipped in v2.4

**Comment by fsavigny** [comment]
Wow, awesome! Thank you very much!

**Comment by rsms** [comment]
You're welcome! Thanks for bringing this to my attention.

**Comment by jsbien** [comment]
I have a question to François Savigny. As it is off the topic, I would appreciate an answer by mail, my address is jsbien@uw.edu.pl.
Your proposal of "a completely different approach" is your own design or have you seen it in print? I know the shape is available in some fonts but I never saw it in print with one important exception: a 19th century dictionary of Polish which uses three shapes of the section sign, one practically identical with your proposal (for other cf. e.g. http://www.unicode.org/mail-arch/unicode-ml/y2010-m08/0073.html). So there is a problem how to encode them to preserve the difference (and even how to name them...).

Best regards

Janusz
