### ISSUE TITLE
It is a question!! Which version of Inter font look best in android?

### ISSUE THREAD

**Issue by KunalTanwar** [rsms/inter#435]
Firstly, I use this font almost everywhere!! Because it is best font in my opinion!!

Currently the zip file contains 3 version. I was thinking to install *Inter* in my android also. So, I was wondering which option is best for me?
![image](https://user-images.githubusercontent.com/77537933/153722361-430afc54-840e-4d02-8b1b-63b2a9ddebc4.png)

**Comment by ThomasRettig** [comment]
Anything except Inter Variable. AFAIK, Android doesn't natively support variable fonts yet. Your best bet would be "Inter Desktop".

**Comment by hydino2085143** [comment]
Hey, I would advise that you ask questions in the Discussions section of this repo, as Issues is for bug reports

**Comment by KunalTanwar** [comment]
> Anything except Inter Variable. AFAIK, Android doesn't natively support variable fonts yet. Your best bet would be "Inter Desktop".

I have tried **Inter Desktop** in android but I don't know why the `line-height` is looking unbalanced and `letter-spacing` is very extreme.

**Comment by ThomasRettig** [comment]
> > Anything except Inter Variable. AFAIK, Android doesn't natively support variable fonts yet. Your best bet would be "Inter Desktop".
> 
> I have tried **Inter Desktop** in android but I don't know why the `line-height` is looking unbalanced and `letter-spacing` is very extreme.

Hmm, would you like to share a screenshot?

**Comment by Daymarius** [comment]
Android uses TrueType fonts without hinting
