### ISSUE TITLE
[Question] Rendering Malayalam 'maatras'

### ISSUE THREAD

**Issue by joe733** [rsms/inter#436]
This this is the **correct** rendering of the word [`prominence` in Malayalam](https://translate.google.com/?sl=auto&tl=ml&text=prominence&op=translate). `പ്രാധാന്യം`.
![image](https://user-images.githubusercontent.com/38415384/156885886-dcd1fb15-4160-4d13-9013-70948e2d5e41.png)

---

It renders like that...

on [Whatsapp Web](https://web.whatsapp.com/), Firefox
![image](https://user-images.githubusercontent.com/38415384/156885930-372d2e33-0b4d-4217-a898-902ffe86d9fa.png)

on [micro](https://micro-editor.github.io/)
![image](https://user-images.githubusercontent.com/38415384/156886383-2c3a9468-3411-41a1-9bbc-7a22ef6869cc.png)

on [GNU Nano](https://www.nano-editor.org/)
![image](https://user-images.githubusercontent.com/38415384/156886409-04385314-5a5e-4282-a9c3-52b4b1f0f4c0.png)

on [VSCode](https://github.com/microsoft/vscode)
![image](https://user-images.githubusercontent.com/38415384/156886559-4544fdb0-99f0-4d92-bf4c-657a800b0fdf.png)

It's render wrong even on GitHub
![image](https://user-images.githubusercontent.com/38415384/156886675-deb5afd3-e756-4310-afa4-d8b9ef1dbd4e.png)

---

but on [Whatsapp Android](https://play.google.com/store/apps/details?id=com.whatsapp)
![image](https://user-images.githubusercontent.com/38415384/156887116-3f00fc3a-72ea-4bec-b17f-110c9d27e7cf.png)

and on [Microsoft Notepad](https://www.microsoft.com/en-us/p/windows-notepad/9msmlrh6lzf3)
![image](https://user-images.githubusercontent.com/38415384/156887382-bf7180c6-01f3-47f5-b09d-6aeb00b8c824.png)

---

I'm using [Inter system-wide](https://archlinux.org/packages/community/any/inter-font/) so is this a font specific issue ('cause changing it does not seem to have an effect)? or system locale? or something else?  Can someone help me to understand this behaviour please?

> I'm sorry if this isn't the right place to ask - any proper direction would be really helpful.

Here's my system info:

```dart

                   -`                    user@myhost 
                  .o+`                   --------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: Zen Laptop 21
               `+oooooo:                 Kernel: 5.16.12-arch1-1 
               -+oooooo+:                Uptime: 3 hours, 51 mins 
             `/:-:++oooo+:               Packages: 1152 (pacman) 
            `/++++/+++++++:              Shell: zsh 5.8.1 
           `/++++++++++++++:             Resolution: 1920x1080 
          `/+++ooooooooooooo/`           DE: Xfce 4.16 
         ./ooosssso++osssssso+`          WM: Xfwm4 
        .oossssso-````/ossssss+`         WM Theme: Orchis-dark-compact 
       -osssssso.      :ssssssso.        Theme: Orchis-dark-compact [GTK2], Cutefish-dark [GTK3] 
      :osssssss/        osssso+++.       Icons: Tela-circle-blue-dark [GTK2], Crule [GTK3] 
     /ossssssss/        +ssssooo/-       Terminal: xfce4-terminal 
   `/ossssso+/:-        -:/+osssso+-     Terminal Font: Fira Code 11 
  `+sso+:-`                 `.-/+oso:    CPU: Intel i5-10210U (8) @ 4.200GHz 
 `++:.                           `-/+/   GPU: Intel CometLake-U GT2 [UHD Graphics] 
 .`                                 `/   Memory: 3515MiB / 7780MiB
 

~
➜ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by joe733** [comment]
Nope, not a font issue - renders correctly with different fonts on notepad..

**Comment by hydino2085143** [comment]
I don't think Inter even has any Malayalam glyphs, only Latin, Cyrillic, and Greek glyphs.

**Comment by joe733** [comment]
If anybody's interested please follow up here: https://unix.stackexchange.com/questions/693123/disparity-in-rendering-malayalam-glyph
