### ISSUE TITLE
Accents enhancement for Pinyin typesetting

### ISSUE THREAD

**Issue by ShaunXyu** [rsms/inter#440]
**Describe the bug**
I plan to use Inter font to typeset Pinyin, the official romanization system of Mandarin Chinese. This is because Pinyin uses sans font and "single-storey letter a" out of habit, and I can easily do it by Inter's Opentype feature.
Pinyin uses accents to denote different tones. In the screenshoots below, I have typeset all the possibilities of Pinyin letters with accents (in light, regular, and medium weight font). As you can see, some accents are not at the proper position. 

**Expected behavior**
For example:
1. Accents of ǕǗǙǛ are inconsistent. Specifically, the diaeresis of ǕǗǙǛ have different height and weight. And the accents above diaeresis aren't at the same height either.
2. The acute of ǘ seems too long.
3. Ê/ê with macron/caron, M/m with grave, Ŋ/ŋ with acute/caron/grave,  ə with tilde need adjustmment.

**Screenshots**
![屏幕截图 2022-03-09 232232](https://user-images.githubusercontent.com/100661384/157472561-b45b5528-0bd5-495c-85f7-bb074ab469ec.png)

**Environment**
- OS: Windows 10
- LaTeX
- v3.19

**Additional context**
ǕǗǙǛǘ need to be adjust first, for they have already been listed in Unicode table. For others, maybe need to edit the Opentype feature table later.

**Test text**
ĀÁǍÀŌÓǑÒĒÉĚÈĪÍǏÌŪÚǓÙÜǕǗǙǛÊÊ̄ẾÊ̌ỀM̄ḾM̀ŃŇǸẐĈŜŊŊ́Ŋ̌Ŋ̀
āáǎàãōóǒòõēéěèīíǐìūúǔùüǖǘǚǜêê̄ếê̌ềəə̃m̄ḿm̀ńňǹẑĉŝŋŋ́ŋ̌ŋ̀

**Comment by rsms** [comment]
Nice find. Here's a Lab link to repro: [rsms.me/inter/lab/?sample=%C4%80%C3%81%C7...&size=96](https://rsms.me/inter/lab/?sample=%C4%80%C3%81%C7%8D%C3%80%C5%8C%C3%93%C7%91%C3%92%C4%92%C3%89%C4%9A%C3%88%C4%AA%C3%8D%C7%8F%C3%8C%C5%AA%C3%9A%C7%93%C3%99%C3%9C%C7%95%C7%97%C7%99%C7%9B%C3%8A%C3%8A%CC%84%E1%BA%BE%C3%8A%CC%8C%E1%BB%80M%CC%84%E1%B8%BEM%CC%80%C5%83%C5%87%C7%B8%E1%BA%90%C4%88%C5%9C%C5%8A%C5%8A%CC%81%C5%8A%CC%8C%C5%8A%CC%80%20%C4%81%C3%A1%C7%8E%C3%A0%C3%A3%C5%8D%C3%B3%C7%92%C3%B2%C3%B5%C4%93%C3%A9%C4%9B%C3%A8%C4%AB%C3%AD%C7%90%C3%AC%C5%AB%C3%BA%C7%94%C3%B9%C3%BC%C7%96%C7%98%C7%9A%C7%9C%C3%AA%C3%AA%CC%84%E1%BA%BF%C3%AA%CC%8C%E1%BB%81%C9%99%C9%99%CC%83m%CC%84%E1%B8%BFm%CC%80%C5%84%C5%88%C7%B9%E1%BA%91%C4%89%C5%9D%C5%8B%C5%8B%CC%81%C5%8B%CC%8C%C5%8B%CC%80&size=96)

**Comment by rsms** [comment]
Progress update; how it's looking as of now:

![ioenarst8neir](https://user-images.githubusercontent.com/47046/233713151-7076665a-a5ee-4462-9195-029bb94eca65.png)

Still a few marks/anchors missing: (for example Ŋ is missing a "top" anchor.)

<img width="1081" alt="Screen Shot 2023-04-21 at 11 50 48" src="https://user-images.githubusercontent.com/47046/233713187-ed2e7cb2-cdc4-410f-9158-805f4311b961.png">

**Comment by rsms** [comment]
Fixed as of fc0c3c9153bf52b5f8dff25a60212a36cce35c88

![ersnt82ei](https://user-images.githubusercontent.com/47046/233726314-176be750-4db6-4ca0-a697-93f40b6be5d2.png)
