### ISSUE TITLE
at sign drops down when following a digit

### ISSUE THREAD

**Issue by danilobuerger** [rsms/inter#441]
at sign drops down when following a digit

**To Reproduce**

1. Open https://rsms.me/inter/lab/ with current Chrome (99.0.4844.51)
2. Type `danilo2@`
3. Type `f`

Notice how the `@` drops down.

**Expected behavior**

The `@` sign should not move vertically

**Screenshots**

https://user-images.githubusercontent.com/996231/157825515-180b53ce-24b6-46e2-ad52-044c894f0803.mov

**Environment**
- macOS 12.2.1
- Chrome (99.0.4844.51)
- Inter Lab

**Comment by ThomasRettig** [comment]
This is normal behaviour. That "dropping down" of the "@" symbol because context alternates ("CALT") are enabled. Try disabling it, and the "@" should no longer drop down. :)

**Comment by ThomasRettig** [comment]
> Hi @ThomasRettig 👋 Thanks for the hint! That indeed works. Do you know the reasoning behind this? Why would you want the `@` sign be higher when following a digit instead of a letter?

Dropping the `@` sign is a pretty common contextual alternate in most fonts, as it helps align itself to the [baseline](https://typedecon.com/blogs/type-glossary/baseline/) of the font. The reasoning is that it makes it look a bit less awkward. It's a personal preference, really, but it seems like people prefer this as default behaviour! Perhaps this [TypeDrawers thread](https://typedrawers.com/discussion/956/proper-way-of-designing-the-symbol) and this [Typophile thread](https://web.archive.org/web/20131012190516/http://typophile.com/node/16765) is of interest to you.

**Comment by rsms** [comment]
Indeed as @ThomasRettig points out, [this is by design](https://github.com/rsms/inter/blob/ad5c235a1c228b55b8ccbd5d102ca683a4f2f0f0/src/features/calt.fea)
