### ISSUE TITLE
u+2022 moves upwards when followed by a digit

### ISSUE THREAD

**Issue by danilobuerger** [rsms/inter#442]
u+2022 `•` moves upwards when followed by a digit

**To Reproduce**

1. Open https://rsms.me/inter/lab/ with current Chrome (99.0.4844.51)
2. Type `••••••`
3. Type `1`

Notice how the last 5 `•` move upwards. The first `•` does not move.

**Expected behavior**

The `•` should not move vertically

**Screenshots**

https://user-images.githubusercontent.com/996231/157826357-74114a88-5179-4516-84dc-25ea178e58eb.mov

**Environment**
- macOS 12.2.1
- Chrome (99.0.4844.51)
- Inter Lab

**Comment by rsms** [comment]
This is by design. Disable calt OpenType feature for the range (or for the entire text) if you do not desire this functionality.

**Comment by aetinx** [comment]
> This is by design. Disable calt OpenType feature for the range (or for the entire text) if you do not desire this functionality.

Bullets are sometimes way too low without calt on. Would be nice to allow them to be higher up when near "tall" characters.
