### ISSUE TITLE
When using "case", the @ (at) symbol raises incorrectly

### ISSUE THREAD

**Issue by lydenyardley** [rsms/inter#443]
Hello,
Really great font so far in my testing. Hoping to use this on an upcoming project!

To reproduce:

1. Go to https://rsms.me/inter/lab/?varfont=1
2. Select 'case' feature
3. Watch the @ symbol in the email address 'rsms@notion.se' rise incorrectly

This is according to your docs on https://rsms.me/inter/

**Comment by lydenyardley** [comment]
Nudge

**Comment by kenmcd** [comment]
Why would you apply `case` to a lowercase email address?
Note: this works the same way in the Apple SF variable system interface fonts.

Do you have an example font where this is handled differently?

**Comment by rsms** [comment]
This is by design. [The case feature](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae#case) is for use in context of capital letters (upper-case.)
