### ISSUE TITLE
Variable font file size

### ISSUE THREAD

**Issue by aaronjensen** [rsms/inter#448]
Hi, I'm curious if there is any way to reduce the size of the variable font. It's currently about 227k, which is 10x the size of our other variable font we use for our app. I attempted to font squirrel it, but that seems to have stripped the variableness of it. Is manually subsetting an (or my only) option? What is it that makes it larger?

Thanks!

**Comment by ThomasRettig** [comment]
> Hi, I'm curious if there is any way to reduce the size of the variable font. It's currently about 227k, which is 10x the size of our other variable font we use for our app. I attempted to font squirrel it, but that seems to have stripped the variableness of it. Is manually subsetting an (or my only) option? What is it that makes it larger?
> 
> Thanks!

I believe manual subsetting is the way to go. You can either use software such as [Slice](https://slice-gui.netlify.app/) to extract specific design sub-spaces, character subsetting, or even both.

**Comment by aaronjensen** [comment]
Thank you, I ended up doing:

```
  pyftsubset\
    Inter-roman.var.woff2 \
    --output-file="inter-var.woff2" \
    --flavor=woff2 \
    --layout-features+="onum,pnum,smcp,c2sc,lnum,tnum,\
    subs,sups,cswh,dlig,ss01,ss03,zero"\
    --layout-features-="dnom,numr"\
    --unicodes="U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,\
    U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,\
    U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
```

Based on: https://markoskon.com/creating-font-subsets/#latin-subset

That got me down to 49k.
