### ISSUE TITLE
v2.3 appears very broken for me

### ISSUE THREAD

**Issue by chrissnell** [rsms/inter#45]
Not sure what happened here but I upgraded to 2.3 and all of the text looks as if it's in another language, like Georgian or something Asian that I don't recognize.  I upgraded via Arch AUR (I'm the maintainer of that package), which simply downloads and installs your v2.3 zip file.

**Comment by chrissnell** [comment]
![2017-11-29_2446x1187](https://user-images.githubusercontent.com/1072626/33412619-1f416f60-d552-11e7-8996-9d5f7833c501.png)

**Comment by rsms** [comment]
Yikes! I don't have a machine with Arch Linux to test with. Would you mind poking around and see if you can figure out what's going on? I've only tested the font on Windows 10 and macOS 10.

**Comment by rsms** [comment]
Did you figure out what was going on?

**Comment by chrissnell** [comment]
Nope.  I updated Firefox and restarted the browser and the problem is
gone.  Very strange.

**Comment by rsms** [comment]
¯\_(ツ)_/¯
