### ISSUE TITLE
Not showing correctly on iTerm in Mac

### ISSUE THREAD

**Issue by manishrjain** [rsms/inter#450]
**Describe the bug**
The fonts look awful on Mac.

**To Reproduce**
1. MacOS Monterey v12.2
2. Download and Install Inter fonts
3. Set them on iTerm2 Build 3.4.15

**Expected behavior**
Beautiful looking text.

**Screenshots**
<img width="928" alt="Screen Shot 2022-04-17 at 10 43 19 AM" src="https://user-images.githubusercontent.com/1782324/163726239-7a4c6c8e-832e-47a6-aced-e935e2f677b1.png">

**Environment**
- OS: MacOS Monterey v12.2
- App that renders the font [if applicable; e.g. Chrome, Adobe Illustrator]: iTerm2
- Version of font [e.g. "Inter Regular 3.0;8cf05e4a" — you can use fontdrop.info to find out the version]
Latest download from GitHub.

**Additional context**

**Comment by ThomasRettig** [comment]
Inter is a proportional font (non-monospaced), so I think the iTerm2 is forcing it to become fixed-width. Could you try another proportional font (eg. San Francisco)? :-)

**Comment by shahmilav** [comment]
I can confirm that this is the case. iTerm monospaces any fixed-width font, such as Helvetica and San Francisco.
