### ISSUE TITLE
Strange `q` on new early Display Font

### ISSUE THREAD

**Issue by brycewray** [rsms/inter#453]
**Bug**
On the lab page, if you use the “I” selector to make the new early Display Font slant, the lower-case **q** appears to slant leftward rather than rightward. I tried `pq` to see some descenders together and noticed this oddity.

**To Reproduce**
1. Visit the Display [lab page](https://rsms.me/inter/lab/?family=display) and type `pq` into an area on the page.
2. Use the “I” selector to make the font slant.
3. Observe that the `q` slants leftward instead of rightward.

**Expected behavior**
The `q` slants rightward with the other letters.

**Screenshots**
(N/A)

**Environment**
- OS: macOS 12.3.1.
- App that renders the font: Google Chrome 100.0.4896.127.
- Version of font: [Inter Display beta 2](https://github.com/rsms/inter/releases/tag/display-beta-2).

**Additional context**
(N/A)

**Comment by shahmilav** [comment]
# screenshots for clarity

![image](https://user-images.githubusercontent.com/53659750/168918075-89cee618-fe1a-420c-9288-b311e8fd32b0.png)
(display variant)

## settings
![image](https://user-images.githubusercontent.com/53659750/168918169-07e3ec50-1aa0-460d-bc26-983b6b01ff34.png)



## compared to Inter Regular
![image](https://user-images.githubusercontent.com/53659750/168918624-6e676f7b-ce0c-4e91-8bcd-04de1c5a4e1f.png)

**Comment by rsms** [comment]
Thank you. One of many "work in progress" things with Inter Display.
