### ISSUE TITLE
`cv11` has no effect on `subs`/`sups`

### ISSUE THREAD

**Issue by LoganDark** [rsms/inter#456]
**Describe the bug**
The `cv11` font feature has no effect on the `subs`/`sups` features.

**To Reproduce**
1. Apply both `cv11` and `subs` (or `sups`) font features
2. observe how `a` is double-storey when `cv11` should have made it single-storey

**Expected behavior**
The subscript/superscript `a` should be single-storey

**Screenshots**
Chrome 91.0.4472.101 on Windows 10 2004 build 19041.928 (x64):  
![image](https://user-images.githubusercontent.com/4723091/166331885-4349388e-c40a-4858-bcce-6a8bd162bf9b.png)

Chrome 83.0.4103.97 on macOS 10.14.6 Mojave:  
![image](https://user-images.githubusercontent.com/4723091/166331982-4073770f-30de-4d63-b937-e63c0eb59e90.png)

**Environment**
- OS: Windows 10 2004 build 19041.928 (x64)
- App that renders the font: Google Chrome 91.0.4472.101
- Version of font: Inter var experimental, Version 3.019;git-0a5106e0b

**Additional context**
N/A

**Comment by rsms** [comment]
Simply not implemented.
Repro link: <https://rsms.me/inter/lab/?feat-cv11=1&feat-sups=1&sample=a&size=68>

**Comment by LoganDark** [comment]
> Simply not implemented. Repro link: https://rsms.me/inter/lab/?feat-cv11=1&feat-sups=1&sample=a&size=68

Figured; the issue template just compelled me to do a ton of unnecessary work. :p

**Comment by rsms** [comment]
![aaa](https://github.com/user-attachments/assets/c98d4b3d-5059-4e59-ba2f-02955cf45398)
