### ISSUE TITLE
Convert UPM to 2048

### ISSUE THREAD

**Issue by rsms** [rsms/inter#458]
I've started work on converting Inter to UPM 2048 in the [`upm2048` branch](https://github.com/rsms/inter/tree/upm2048)

Two key reasons for this change:
1. Inter Display is designed at 2048 — this change will make it possible to some day merge Display and standard "Text" Inter into one VF.
2. Some old font rasterizers and printer drivers/firmware has bugs that causes issues with certain UPM. (For example see #156)

After a few hours of initial work, the 2048 UPM version renders almost identical in both Figma and web browsers compared to the current 2816 UPM version:

<img width="1943" alt="Screen Shot 2022-05-22 at 13 20 03" src="https://user-images.githubusercontent.com/47046/169714407-c1c44d74-de13-4fd2-a108-54bfd8d89ca6.png">

The biggest downside of converting to 2048 UPM is that design work gets harder since 1dp@11dp no longer corresponds to a power-of-two number which in turn means that a assisting grid for snapping and visual assist is no longer possible. I think this is a totally okay trade off.

Latest test build: [Inter-4.00-e77ce318de.zip](https://github.com/rsms/inter/files/8766323/Inter-4.00-e77ce318de.zip)

**Comment by rsms** [comment]
Beta build for testing:
[Inter-3.19-text-faded04f9f.zip](https://github.com/rsms/inter/files/8750301/Inter-3.19-text-faded04f9f.zip)

**Comment by kenmcd** [comment]
> Beta build for testing: [Inter-3.19-text-faded04f9f.zip](https://github.com/rsms/inter/files/8750301/Inter-3.19-text-faded04f9f.zip)

Some of the fonts are 2048 UPM, some of them are 1000 UPM.
Appears to be the same in both OTF and TTF.

Thin - 2048
ExtraLight - 1000
Light - 1000
Regular - 2048
Medium - 1000
SemiBold - 1000
Bold - 1000
ExtraBold - 1000
Black - 2048

**Comment by rsms** [comment]
Thanks @kenmcd for catching that. It is an issue with the new version of glyphsLib. I've added a work-around and made a fresh build which can be grabbed from the main post above.

**Comment by rsms** [comment]
Moved to #462
