### ISSUE TITLE
Variable font 

### ISSUE THREAD

**Issue by augustskare** [rsms/inter#46]
Any plans on adding variable font support?

**Comment by rsms** [comment]
Nope. Maybe one day in the future. Would be fun. Support of variable fonts is still scarce at best right now, so returns are small with a large investment in time and effort.

I'll leave this here though, as an "enhancement"

**Comment by jenil** [comment]
Usage [70% globally](https://caniuse.com/#feat=variable-fonts) at this time and increasing everyday seems like a good usage stat.

**Comment by brianespinosa** [comment]
> Usage 70% globally at this time and increasing everyday seems like a good usage stat.

Unless you know for sure your user base is only using modern browsers and you are not going to encounter that those older users, I don't personally think 70% is a good usage stat when it comes to CSS. You're still going to have to use media queries with fallbacks to pick up the other users to still give them they need. Or... you can just define your fonts the way you always have and wait until support passes 85% - 90%.

**Comment by rsms** [comment]
That future day is now.
Version 3.0, currently in beta, comes as both "traditional" constant fonts as well as a Variable font with two axes:

- weight (wgth)
- italic (ital)

You can get the latest beta pre-releases here: https://github.com/rsms/inter/releases

I'd very much appreciate as much testing as possible — please report and issues with the variable font, here or in a separate github issue. Thank you all!
