### ISSUE TITLE
Can dynamic metrics be achieved with optical size metric?

### ISSUE THREAD

**Issue by max-hk** [rsms/inter#460]
[Google recently updated their Roboto font with "optical sizes"](https://material.io/blog/roboto-flex), which makes Roboto scale nicely under different font sizes.

![image](https://user-images.githubusercontent.com/35831069/170113090-7eb651e8-5e65-4433-b236-9837af9a7bc1.png)

Can the same optimization be added to Inter so that [dynamic metrics](https://rsms.me/inter/dynmetrics/) would be applied automatically?

It is common to set a negative `letter-spacing` when using Inter in titles and headings. It would be better if that was applied put of the box.

**Comment by rsms** [comment]
Yes it can be done but only in software that supports linking physical font size to opsz an axis. Inter does not have an opsz axis (it is work in progress.)

**Comment by rsms** [comment]
In the future, please use [Discussions forum](https://github.com/rsms/inter/discussions/categories/q-a) for questions. Issues are for ...issues. Thank you.

**Comment by max-hk** [comment]
@rsms It is a feature request actually. Sorry for the poor wordings
