### ISSUE TITLE
More of a buglet, actually... a typo in Capital G with spur character variant name

### ISSUE THREAD

**Issue by alex-kovac** [rsms/inter#461]
**Describe the bug**
A possible typo in 'Capital G with spur' character variant name.

**To Reproduce**
1. If your app supports Character variant names, look there. In my case, this app is Affinity Publisher.
2. Open 'Typography' palette, scroll to 'Character Variant' section
3. Look for 'Captital G with spur'

**Expected behavior**
Probably it should say 'Capital G with spur'

**Screenshots**
![image](https://user-images.githubusercontent.com/174563/170546413-811ccd3a-a6fa-4ec4-aea7-89335f478ca4.png)

**Environment**
- OS: macOS Monterey, but any OS will do, really.
- Affinity Publisher
- Inter Regular 3.19 b597068546

**Additional context**
Nothing really comes to mind.

**Comment by rsms** [comment]
Oops :–D
