### ISSUE TITLE
Beta Interpolation Issue - .notdef

### ISSUE THREAD

**Issue by kenmcd** [rsms/inter#464]
From: Inter-V-opsz-20220528-6765e3993118d8.zip - (2022-05-28)
File: Inter-V.var.ttf
Appears the contour direction is different in two masters: 
ThinDisplay and :wt=100,sl=0,op=72 

![2022-05-28_14-03-58](https://user-images.githubusercontent.com/844920/170842927-00fbba25-19d3-482e-a6de-fdfe090b29a7.gif)

**Comment by rsms** [comment]
Fun!

**Comment by rsms** [comment]
Looks like I unknowingly fixed this already
![CleanShot 2022-05-31 at 12 53 18 mp4](https://user-images.githubusercontent.com/47046/171273764-b6a1c6e0-3094-4e0a-98d6-b7bd3a18a02b.gif)

**Comment by kenmcd** [comment]
Hmmmm ... I am still seeing this in the last ZIP.
Inter-opsz-beta-4.00-e322506294.zip - (2022-05-31)
What is odd is that on Samsa it looks just like your animation above.
But in both FontLab and FontCreator I can still see the issue. 
In FontLab when I look directly at that glyph in those two masters I can see the different direction on the contours.
So please take a look at **.notdef** in **ThinDisplay** and **:wt=100,sl=0,op=72**.

Another weird one. Like you said - Fun!
