### ISSUE TITLE
Misalignment of handles on curves after 2048 UPM change

### ISSUE THREAD

**Issue by eweracs** [rsms/inter#465]
In almost all glyphs and all their layers, the handles are misaligned (vertically/horizontally off by a unit).
<img width="523" alt="image" src="https://user-images.githubusercontent.com/51919489/171461791-a978ca0b-4b65-48c5-8fbb-f9026b5e5852.png">

Also note that the baseline overshoot does not adhere to the defined zone.

**Comment by eweracs** [comment]
Your screenshot shows O, mine o. Did a fresh pull right before taking the screenshot, should be up to date :)

**Comment by rsms** [comment]
Indeed, Glyphs caused ~75% of Bézier handles on curves to become misaligned during UPM scaling. (Either a floating-point bug or lack of ceil/floor to round coordinates to the grid. cc @schriftgestalt) Thanks for finding this!

**Comment by schriftgestalt** [comment]
Do you happen to have a version just before the scaling to 2048? And how exactly did you do it?

**Comment by rsms** [comment]
> Do you happen to have a version just before the scaling to 2048? And how exactly did you do it?

Yes! This is the .glyphs file just before conversion: https://github.com/rsms/inter/raw/633839ad550073f9d12e6cea7964a30523974b68/src/Inter.glyphs

I did it by opening font info and then the "arrows" icon next to the UPM.
<img width="962" alt="Screen Shot 2022-06-01 at 14 49 39" src="https://user-images.githubusercontent.com/47046/171507865-882c946e-05a8-4988-8c4f-423b56627121.png">

I can reproduce the result (just tried it.)

Before scaling:
<img width="1034" alt="Screen Shot 2022-06-01 at 14 49 17" src="https://user-images.githubusercontent.com/47046/171507843-e378d0c8-3b78-409d-ace2-0d6cc23b5498.png">

After scaling:
<img width="877" alt="Screen Shot 2022-06-01 at 14 49 56" src="https://user-images.githubusercontent.com/47046/171507901-ce9e898d-3ee4-48e3-9ad9-3d54831c2d8c.png">

**Comment by schriftgestalt** [comment]
I found the issue. You have set a grid of 2 units. When rounding coordinates, offcurve nodes are always rounded to a 1 unit grid, otherwise round dots in pixel fonts would be difficult. 
I’ll see if I can increase the threshold a bit.

**Comment by rsms** [comment]
> I found the issue. You have set a grid of 2 units. When rounding coordinates, offcurve nodes are always rounded to a 1 unit grid, otherwise round dots in pixel fonts would be difficult.
> I’ll see if I can increase the threshold a bit.

Ah. Interesting. I wonder if you could improve this "magic" by rounding offcurve nodes that are part of an angle-locked anchor (i.e. is green-colored) with the same constraints as the anchor itself. Maybe pixel fonts uses that?

I'm too far gone now to start over with the scaling, but if I did, would first doubling the grid and then doing the scaling "fix" it? (We're getting OT here, so feel free to ignore this :•)

**Comment by rsms** [comment]
I wrote & ran a script to attempt to repair off-by-one handles, landed in d1272ce9c904201c97e68da030b2fa9530e895a7 — this shouldn't be an issue anymore. However the programmatic approach I took is conservative so there may still be some misaligned handles that will have to be manually corrected.
