### ISSUE TITLE
sub-par rendering

### ISSUE THREAD

**Issue by DrummerHead** [rsms/inter#47]
On Windows 7 > Firefox 57.0

![](https://i.imgur.com/B2TDIXU.jpg)

Default zoom level, don't have any addon that "tweaks" typography or anything similar.

I don't know where the fault lies, I'm just doing a drive-by report. Cheers!

**Comment by rsms** [comment]
Could you please be more specific? What are you expecting things to look like? Does it look different in Chrome? In Edge?
I've got a Windows 10 machine that I'm testing on and it looks good here.

Closing this for now until there's something substantial and concrete to investigate.
