### ISSUE TITLE
Is it legal to use the fonts in commercial mobile application?

### ISSUE THREAD

**Issue by FtiJackie** [rsms/inter#471]
Hi, Our company has release an application on Google Play and Other App Store, this is a commercial application. We want to use the font to refine the font style, consummate the UI page. Is is legal? Or we need another additional statement?

**Comment by bamboo512** [comment]
The license is in the **LICENSE.txt** file.
I think you may pay attention to the second term:
> 2) Original or Modified Versions of the Font Software may be bundled,
redistributed and/or sold with any software, provided that each copy
contains the above copyright notice and this license. These can be
included either as stand-alone text files, human-readable headers or
in the appropriate machine-readable metadata fields within text or
binary files as long as those fields can be easily viewed by the user.

**Comment by FtiJackie** [comment]
> The license is in the **LICENSE.txt** file. I think you may pay attention to the second term:
> 
> > 2. Original or Modified Versions of the Font Software may be bundled,
> >    redistributed and/or sold with any software, provided that each copy
> >    contains the above copyright notice and this license. These can be
> >    included either as stand-alone text files, human-readable headers or
> >    in the appropriate machine-readable metadata fields within text or
> >    binary files as long as those fields can be easily viewed by the user.

Thank you, but i have a question. For example, our company's a shopping center app use the font as app page's default text font, what should I do additional?@bamboo512

**Comment by rsms** [comment]
Yes. For details, please read the license (standard Open Font License) https://github.com/rsms/inter/blob/master/LICENSE.txt

In the future, please use [Discussions](https://github.com/rsms/inter/discussions) for questions and discussions instead of misusing the Issue feature. Thank you.
