### ISSUE TITLE
Long s too bold

### ISSUE THREAD

**Issue by sigurdhasle** [rsms/inter#475]
**Describe the bug**
I am impressed that this font has a long ſ – even if long ſ-s are out of fashion. But the long ſ in Inter seems to be bolder than it should be – i believe it should be the same shape as the f, but without the crossbar.

**To Reproduce**
If you insert a long ſ next to an f it looks bolder (and bigger in some weights of the font).

**Expected behavior**
I expected the ſ to look like the f.

**Screenshots**
![image](https://user-images.githubusercontent.com/47284316/180621837-42b63b25-7b20-4596-9cd4-5b6347fec0cb.png)

**Environment**
- OS: Windows 11
- App that renders the font: Libre Office Writer – and other.
- Version of font: Inter Regular. Version 3.019;git-0a5106e0b – and several other (all?) weights

**Additional context**
Thank you for a fantastic font!

**Comment by rsms** [comment]
Thank you! What it looks like after the fix:

![slong](https://user-images.githubusercontent.com/47046/180843883-a7b17f43-c1fb-439a-942a-0a4e9d2e27d9.png)

**Comment by sigurdhasle** [comment]
Nice! Thank you very much!
(Where can I download the corrected files? Are they still called 3.19?)

**Comment by rsms** [comment]
It will be included in a future 4.0 release. You can build your own font files from source or download a beta version here: https://github.com/rsms/inter/discussions/463
