### ISSUE TITLE
Semi colon and Hyphen are not vertically centered

### ISSUE THREAD

**Issue by KunalTanwar** [rsms/inter#476]
**Describe the bug**
`U+003A` (semi colon) and `U+002D` (hyphen) are not vertically centered when using together.

**To Reproduce**
1. Type `semi colon` and then `hyphen`
2. See `hyphen` is not centered in respect of `colon` vertically.

**Expected behavior**
Both should be vertically centered.

**Screenshots**
![Behavior in Chrome](https://user-images.githubusercontent.com/77537933/181917371-adf03789-3c0d-4d70-8d80-7694ab56b98d.png)

**Environment**
- OS: Windows 11
- App that renders the font - **Chrome**
- Version of font - v3.19 using **Inter Var** from [inter.css](https://rsms.me/inter/inter.css)

**Comment by kenmcd** [comment]
The colon and hyphen are at the appropriate height for normal use in the lowercase text.
In some interface uses they may be shifted vertically such as in uppercase text or time displays, etc. 
That may be what you are looking for here.
Also some interface fonts may use the `ratio` character in time displays (`2236`).

Inter uses the OpenType Case Sensitive Forms (`case`) feature to shift these when appropriate.
This is Inter v3.19 below. 
Inter does not currently have a ratio character (it has been requested).
Note: this is exactly the same as how it works in the Apple SF interface fonts.
![Inter-colon-hyphen-case](https://user-images.githubusercontent.com/844920/181935059-b61daa24-1bf2-421f-a593-4615d32ebc33.png)

Segoe UI does have a ratio character.
So in that font the combination of `case` and the `ratio` character give you the vertical alignment.
![SegoeUI-colon-hyphen-case](https://user-images.githubusercontent.com/844920/181935171-004f4614-dc88-4662-84ef-9211898070cc.png)

So with Inter you just need to enable the `case` feature to get the "vertically centered" that you desire.

**Comment by rsms** [comment]
Thanks @kenmcd for the thoughtful explanation and help!
Next release of Inter will include U+2236 RATIO. You can download a beta build here: https://github.com/rsms/inter/discussions/463
