### ISSUE TITLE
`-->` is not replaced with a long arrow when typed inside an input-field (chromium)

### ISSUE THREAD

**Issue by andrejilderda** [rsms/inter#478]
**Describe the bug**
When you type `-->` inside an input field in a Chromium browser, only the last `->` is being replaced with an arrow →, resulting in `-→` (see screenshot below).

**To Reproduce**
1. Visit [this Codesandbox link](https://codesandbox.io/s/inter-arrow-bug-in-input-field-hsh3m1?file=/index.html) with a Chromium browser
2. type `-->` inside the text input.

**Expected behavior**
I'd expect `-->` to result in a long arrow, like is the case outside a text input.

**Screenshots**
<img width="414" alt="image" src="https://user-images.githubusercontent.com/487182/186649209-5f26d8dd-7705-4239-97d4-b8ac45b706a4.png">

**Environment**
- OS: [e.g. macOS 12.4]
- Chromium
- Inter Regular 3.19 (woff2)

**Additional context**
Typing `<--` works fine.

**Comment by andrejilderda** [comment]
I noticed [Iosevka](https://typeof.net/Iosevka) has the same bug, so I guess this is a Chromium issue.

**Comment by rsms** [comment]
Yeah, this is an issue with Chromium. https://bugs.chromium.org/p/chromium/issues/list

Generally, if you find an issue that happens in a web browser, test in a couple of different browsers; if you see different results it is most likely a browser bug.
