### ISSUE TITLE
Cyrillic її (two U+0457 CYRILLIC SMALL LETTER YI)

### ISSUE THREAD

**Issue by ichik** [rsms/inter#479]
**Describe the bug**
ї stands too close to its neighbors, especially ones with diacritics, e.g. second ї (see attached screenshot).

**Expected behavior**
A little bit more space / additional kerning would greatly help.

**Screenshots**
<img width="138" alt="image" src="https://user-images.githubusercontent.com/80973/185955872-f176f26b-a024-45ea-bf7b-50365f86f49e.png">

**Comment by rsms** [comment]
Please provide the following info: (it was in the issue template)

**Environment**
- OS: [e.g. macOS 10.14]
- App that renders the font [if applicable; e.g. Chrome, Adobe Illustrator]
- Version of font [e.g. "Inter Regular 3.0;8cf05e4a" — you can use fontdrop.info to find out the version]

**Comment by ichik** [comment]
@rsms hey, thanks for following up on this.
This (`її` sticking together too close) is reproducible on a variety of platforms for me: macOS 12.6 with Chrome, Firefox, and Safari, Windows 11 with Chrome and Firefox, Android 10 with Chrome and Firefox etc. 
fontdrop.info doesn't seem to support woff2, but the corresponding ttf from the same download is showing `3.019;git-0a5106e0b` (It is `3.19` archive downloaded from rsms.me).
I also checked and the same effect can be observed in Figma (not sure which version they have installed there) and in TextEdit when using locally installed font.

**Comment by KrasnayaPloshchad** [comment]
As my suggestion, this letter should have contextual alternate to produce collision avoidance. See also https://github.com/adobe-fonts/source-serif/issues/48.

**Comment by rsms** [comment]
Added an specialized "narrow" version of /idieresis that is used instead of the normal (wide) version when two yi or idieresis are next to each other:

![idieresis.narrow](https://user-images.githubusercontent.com/47046/195960002-7ca9bc80-423f-4c6d-97d8-f54e813d0238.png)

In case CCMP fails, there's also ample kerning:

![fallback](https://user-images.githubusercontent.com/47046/195960175-16ae0fdd-986b-4795-9110-6eaac8fd0986.png)

**Comment by rsms** [comment]
Let me know if this looks good to y'all!

**Comment by kenmcd** [comment]
This was also discussed in a Roboto-Flex issue.
https://github.com/googlefonts/roboto-flex/issues/348
Because of that issue I kinda went on a quest to see how this is handled in other fonts. Found a number of fonts, including a couple fonts made by Ukrainian designers for  two different Ukrainian organizations. Wanted to see how the Ukrainians would handle it themselves. 
Been meaning to summarize it all. Was going to do it today, and did work on it, but got distracted. Maybe finish it tomorrow. 

Would like to review what has been done in a new beta when you get a chance.

**Comment by rsms** [comment]
@kenmcd That would be really interesting to learn about. You can grab the latest build here: https://github.com/rsms/inter/suites/8786622744/artifacts/399000934 (every push is built automatically and can be downloaded up to a day after the hit push. See the “Actions” tab in GitHub for an overview.)

**Comment by ichik** [comment]
I find the ligature quite pleasant. The four dots look fine in thinner weights, but start to look weird past the second line.

**Comment by rsms** [comment]
I made a "three dot" ligature this morning. Definitely reads better and if it's still recognized as two idieresis, I think this is the better solution.

![ii2](https://user-images.githubusercontent.com/47046/196003843-4e262738-8475-4f11-bdaf-62ace61cead6.png)

**Comment by rsms** [comment]
Now there's a ligature for capital letter with two dots as well (U+00CF and U+0407)

![ii2cap](https://user-images.githubusercontent.com/47046/196004973-a6064db8-d98d-4eb0-bd0e-aca85f30d42a.png)

**Comment by kenmcd** [comment]
When I started investigating this I found quite a few fonts using the three dots.
Such as Proba Pro, a commercial font, used on a number of Ukrainian websites including the Ukrainian Embassy in the US, the Ukrainian parliament, and the Ukrainian NATO sub-site.
e-Ukraine, commissioned by and used on the website of The Ministry and the Committee for Digital Transformation of Ukraine - equally spaces the four dots, and also has a ligature with the right quote. The NAMU fonts, created for the National Art Museum of Ukraine (NAMU) - also uses the four equally spaced dots.
There are other fonts with other ligatures, and there other collisions to deal with (parentheses , brackets, quotes, etc.).
Some fonts use ccmp, some use liga, some use dlig, some use rlig, and some use calt.
I like ccmp as it even works in Word (where calt is not On by default).
Glad you are doing this.
The last few months I have spent quite a bit of time in the Ukrainian military's Telegram groups, and other groups, on my android phone. So I have to look at the Roboto collisions all the time (quite annoying).
I will take a look at the latest beta, and get back to getting this done.

**Comment by toplinden** [comment]
Iʼm Ukrainian and I never saw or donʼt remember three dot ligature. And I may guess the reason: a combination `ії` is also often used.

**Comment by rsms** [comment]
I'll take this as the ligature being a good solution. Thank you all for your help!

**Comment by rsms** [comment]
Included in [v4.0-beta6](https://github.com/rsms/inter/releases/tag/v4.0-beta6)
