### ISSUE TITLE
"Inter UI Bold" font problems in LibreOffice (Linux/Ubuntu 16.04.3, installed OTF version)

### ISSUE THREAD

**Issue by reinhart1010** [rsms/inter#48]
Hello, I would like to report a bug when installing the OTF version of Inter UI on my Linux Mint 18.3 (Ubuntu 16.04.3).

When I tested the font in LibreOffice Writer (a document processor software), the font names "Inter UI Bold" is separated from the bold weight of "Inter UI".

This means that the bold version of Inter UI is not selected when I type a bold text using the "Inter UI" font name. Here's a screenshot to describe the problem:

![Font sample](https://user-images.githubusercontent.com/17312341/34442321-fa35caae-ecf3-11e7-9606-3b6a73d69bbf.png)

**Comment by rsms** [comment]
Could you please try installing and testing LibreOffice with Noto Sans? https://www.google.com/get/noto/#sans-lgc

I suspect that there's a bug in LibreOffice that doesn't handle spaces in the `family name` of the font.

A font provides two important properties in its embedded metadata

- family name ("Inter UI")
- style ("Regular", "Italic", "Bold", "Bold Italic" ... etc)

Another possibility is that LibreOffice does a fragile hack where they instead use the "full name" property and try to parse its text content. There's currently a bug in the bold version of Inter UI for that field where "Bold" appears twice ("full name" = "Inter UI Bold Bold".) However, LibreOffice should really use the Family name and Style properties and show those to the user. If you find the issue, perhaps you could file a report with LibreOffice as well :)

I'll keep this issue open for now until we've figured this out.

**Comment by rsms** [comment]
Can you try this build (off of 4552fb970d17257ce043868e83eb78eed3134a33) and let me know if that fixes the issues for you @reinhart1010 ?

[Inter-UI-2.3-4552fb970d.zip](https://github.com/rsms/inter/files/1613684/Inter-UI-2.3-4552fb970d.zip)

**Comment by rsms** [comment]
Ping

**Comment by reinhart1010** [comment]
Ok. I am currently not using the device where the bug is discovered; will check tomorrow.

**Comment by reinhart1010** [comment]
That fixes the issue. Thanks.
![image](https://user-images.githubusercontent.com/17312341/34805950-0ca39b4e-f6b3-11e7-8ffe-523241cfc230.png)

**Comment by rsms** [comment]
You may want to file an issue with LibreOffice as they should display the family name and style properties of the font rather than perform brittle text parsing of the "full name" :–)

**Comment by reinhart1010** [comment]
I don't know whether the bug report exists or not, while this bug also happens with [Aileron](http://dotcolon.net/font/aileron/) don't as well.

**Comment by reinhart1010** [comment]
Sorry for late response, but there's a related issue reported to LibreOffice back in 2013.
https://bugs.documentfoundation.org/show_bug.cgi?id=72944
