### ISSUE TITLE
Embedding Inter in a Word document

### ISSUE THREAD

**Issue by ScribbleGhost** [rsms/inter#482]
I am looking to embed Inter to a Word document but I am only able to do this with the TTF files in:
`Inter-3.19\Inter Hinted for Windows\Desktop\ ... .ttf`
But these are **_hinted_** fonts and I don't want that.

Am I missing something or is this the only way to embed fonts in Word on Windows.

**Comment by ousia** [comment]
@ScribbleGhost, it seems that [only TrueType fonts are allowed, no OpenType ones](https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/fails-embedding-adobe-opentype-font).

**Comment by ScribbleGhost** [comment]
@ousia Yeah, I know. That was not the question.

**Comment by rsms** [comment]
Please use the [Discussion forum feature](https://github.com/rsms/inter/discussions/categories/q-a) for questions
