### ISSUE TITLE
cv06 (stylized "r") too tall for the Display inter font

### ISSUE THREAD

**Issue by michealp-coder** [rsms/inter#485]
**Describe the bug**
The stylized "r" (cv06) is too tall.

**To Reproduce**
1. https://rsms.me/inter/lab/?family=display
2. Type the word "Guarn"
3. Increase the Size (font size on the panel) to "70" or larger
5. Toggle cv06 (on the side panel) to on. Note how the letter "r" is much much taller than the letter "u", "a" or "n".

**Expected behavior**
The stylized letter "r" (cv06) to be at the same height as non-stylized letters.

**Environment**
- OS: macOS 12.5.1 / Safari 15.6.1

**Comment by kenmcd** [comment]
This does _not_ appear to be fixed in the most current beta.
Which you can get here: https://github.com/rsms/inter/discussions/463

@rsms The `cv06` version of the `r` is still too tall in the latest beta when the `opsz` is set to the max, and the weight is set to 400. So it appears the Display master may be the problem.

**Comment by rsms** [comment]
It's a TODO for Display.
You can see what glyphs are still work in progress for display by filtering the Glyphs document on the tag "TODO-opsz".

https://github.com/rsms/inter/blob/d4b714e2c2779d7226d6dab89ae923f4e2eb5cfe/src/Inter.glyphspackage/glyphs/r.1.glyph#L701

**Comment by rsms** [comment]
/r.1 will be removed in the next release

**Comment by michealp-coder** [comment]
Hi @rsms 

I don’t believe this has been fixed. 

How to reproduce:

1. Go to https://rsms.me/inter/lab/
2. Set font to Display
3. Set weight to 300+ (no bug <300 weights)
4. Set cv06 to on
5. Type the word “Guarn”
6. You’ll see how “r” is too tall

Thanks in advance for all you do. Truly appreciate this great typeface you’ve made.

**Comment by kenmcd** [comment]
This has been fixed in the v4 dev version (v4 beta 7 is fine).
What is on the demo page above is the old v3.19.

Current development is focused on v4.
So it is not likely v3.19 will be updated.
And it is probably too early to put v4 on the demo page.
