### ISSUE TITLE
cv11 (stylized "a") too tall for the Display inter font

### ISSUE THREAD

**Issue by michealp-coder** [rsms/inter#486]
**Describe the bug**
The stylized "a" (cv11) is too tall.

**To Reproduce**
1. https://rsms.me/inter/lab/?family=display
2. Type the word "Guarn"
3. Increase the Size (font size on the panel) to "70" or larger
5. Toggle cv11 (on the side panel) to on. Note how the letter "a" is much much taller than the letter "u", "r" or "n".

**Expected behavior**
The stylized letter "a" (cv11) to be at the same height as non-stylized letters.

**Environment**
- OS: macOS 12.5.1 / Safari 15.6.1

**Comment by kenmcd** [comment]
This appears to be fixed in the most current beta.
Which you can get here: https://github.com/rsms/inter/discussions/463
