### ISSUE TITLE
polytonic Greek acute and grave accents

### ISSUE THREAD

**Issue by ousia** [rsms/inter#489]
@rsms,

I got the fonts for https://github.com/rsms/inter/releases/download/v3.19/Inter-3.19.zip and used OTF versions (Inter Desktop).

Here you have single acute and grave accents for Greek (odd lines contain oxia and grave, the even lines contain tonos and grave):
 
![abde-1](https://user-images.githubusercontent.com/203767/190491784-7b34004c-6281-4191-856e-94834887f0fc.png)
![abde-2](https://user-images.githubusercontent.com/203767/190491779-a0b9ffeb-f505-4743-8009-7d9ab56f6996.png)
![abde-3](https://user-images.githubusercontent.com/203767/190491777-36d6fa0a-be9c-44dc-b787-bee6c2f0116d.png)
![abde-4](https://user-images.githubusercontent.com/203767/190491775-4fe9266b-1c8c-421f-b6f0-315a004061e6.png)

For some strange reason, there are fonts that distinguish tonos and oxia. Well, tonos is accent and oxia is acute. The monotonic Greek accent (by law) is acute.

But since OpenType defines polytonic Greek as a language, if you want to keep different glyphs for tonos and oxia, there is a way to get automatic oxia with tonos using substitutions:

```
feature locl {

    @tonosuppercase = [Alphatonos Epsilontonos Etatonos Iotatonos
                       Omicrontonos Omegatonos Upsilontonos];

    @tonoslowercase = [alphatonos epsilontonos etatonos iotatonos
                       iotadieresistonos omicrontonos omegatonos
                       upsilontonos upsilondieresistonos];

    @oxiauppercase = [uni1FBB uni1FC9 uni1FCB uni1FDB uni1FF9
                      uni1FFB uni1FEB];

    @oxialowercase = [uni1F71 uni1F73 uni1F75 uni1F77 uni1FD3
                      uni1F79 uni1F7D uni1F7B uni1FE3];

    script grek;

        language PGR exclude_dflt;

            lookup TonosOxia {
                sub @tonosuppercase by @oxiauppercase;
                sub @tonoslowercase by @oxialowercase;
            } TonosOxia;

} locl;
```

Acute and grave accents aren’t placed at the same vowel height and there are too different from each other.

I think that varia (the grave accent) should be redone. I wonder whether which is best: from tonos or from oxia.

Many thanks for your excellent work.

**Comment by rsms** [comment]
Thanks! Very interesting

**Comment by ousia** [comment]
@rsms,

as for spirits, I think that rotating the ogonek 180° would do the trick for the smooth spirit. Mirroring the result would to the trick for the rough spirit.

Just in case it might help.

**Comment by ousia** [comment]
This is related to the discussion in #490.

**Comment by ousia** [comment]
@rsms, I’m afraid I cannot contribute myself, since I don’t have any font editor that handles variable fonts.

BTW, the code for the feature file needs no extra editing, only to be added in the right file.

**Comment by rsms** [comment]
Done in the past few days

![greek-az-reg](https://github.com/rsms/inter/assets/47046/12ac81fa-d4d9-47ee-9a8b-baf6c89516ad)

![greek-az-extralight](https://github.com/rsms/inter/assets/47046/faf1b221-ce5e-4321-960a-5a0a9c8b5322)

![greek-az-extrabold](https://github.com/rsms/inter/assets/47046/c4c64e8f-2d97-4bc5-81be-558feeee74d8)
