### ISSUE TITLE
Inter UI-Regular Italic Missing?

### ISSUE THREAD

**Issue by sguergachi** [rsms/inter#49]
In the last 2 releases it seems Inter UI-Regular Italic is missing, any reason why?

**Comment by rsms** [comment]
It's there alright, as `Inter-UI-Italic.{otf,ttf,woff,woff2}` (no longer has "Regular" in its name)

If there's an app that doesn't display it properly, please comment in this issue with the apps name, version, your operating system and it's version, what version of Inter UI you are using (if you don't know, you can find the version in Font Book if you're using a Mac, any with 3rd party software on Windows) as well what format of the font you're using (OTF or TTF.)
