### ISSUE TITLE
Using Inter font family and adding a -webkit-text-stroke style breaks a text (specifically number "4" in the text)

### ISSUE THREAD

**Issue by acaballes** [rsms/inter#494]
**Describe the bug**
Using Inter font family and adding a -webkit-text-stroke style breaks a text (specifically number "4" text). Please see attached image.

**To Reproduce**
1. Use Inter font family (imported in local)
2. style a text (include a number 4 in the text) to have an outline for example:
 CSS:  
        p {
            color: #FFFFFF;
	    -webkit-text-stroke: 1px #000000;
	    font-family: 'Inter Bold';
	    font-size: 16px;
	}
3. Load the page

Result: The number 4 text outline breaks as what is identified in the screenshot

**Expected behavior**
Any text or a number should not break when styled with -webkit-text-stroke css property

**Screenshots**
![Screenshot 2022-09-27 143024](https://user-images.githubusercontent.com/12888878/192449969-69133cc4-79de-454e-b67b-df108c365bc5.png)

**Environment**
- any browser

**Comment by rsms** [comment]
This is a limitation of some web browsers; not a font issue.
The static font files have overlap removal (boolean union) applied to them, so you can try using those instead of the variable font (VFs need to have some overlaps for interpolation to work properly.)
