### ISSUE TITLE
Renders incorrectly in PDF on Chrome

### ISSUE THREAD

**Issue by jackiehluo** [rsms/inter#50]
Hey, there! Follow-up from [Twitter](https://twitter.com/rsms/status/951586575229452288):

As mentioned, I've both exported and saved as PDF from both Pages and TextEdit and uploaded to the web to find that the font doesn't render correctly. It works in Safari, just not Chrome. [Here's](http://jackieluo.com/static/jackie-luo.pdf) the PDF in question—if I download it, it renders locally, but it doesn't work specifically in Chrome.

Here are some screenshots of how it looks to me!

Web:
<img width="806" alt="screen shot 2018-01-11 at 2 56 31 pm" src="https://user-images.githubusercontent.com/8452682/34851597-9802e876-f6df-11e7-847e-01207ac5f9f6.png">

Local:
<img width="957" alt="screen shot 2018-01-11 at 2 55 10 pm" src="https://user-images.githubusercontent.com/8452682/34851556-692de8a2-f6df-11e7-856f-b0a6b6459f72.png">

Let me know if there's any other useful information I can provide! I would be curious to see if you see what I see on web, too...

Thank you so much for the help and for creating this lovely typeface!

- Original PDF: 
[jackie-luo.pdf](https://github.com/rsms/inter/files/1624426/jackie-luo.pdf)

**Comment by rsms** [comment]
Opening the PDF in question in macOS Preview.app causes Preview to hang on my computer. This is very interesting.

Here is a PDF that was created from Apple Pages that do seem to work: 
[inter-ui-test-pages-export.pdf](https://github.com/rsms/inter/files/1624442/inter-ui-test-pages-export.pdf)

**Comment by rsms** [comment]
Here's a build of the most recent (unreleased) version.
@jackiehluo Can you please uninstall any current Inter UI font files and then install the OTF versions in this zip, reopen Page.app and export a new PDF?

If that doesn't work, can you also try removing the OTF files and instead installing the TTF (unhinted or not, doesn't matter), reopen Pages.app and export a new PDF and see if that works. If this is the case, then the theory is that there's a bug in Chrome's PDF renderer in relation to CFF font data and we might want to file an issue with Chromium in that case.

**Comment by rsms** [comment]
Also, feel free to upload an simplified PDF generated in the same way. May be easier to debug/poke at the PDF source with something smaller & simpler.

**Comment by rsms** [comment]
Friendly ping

**Comment by jenil** [comment]
Hey @rsms this is the same issue I too asked you about on [Twitter](https://twitter.com/GeekGogari/status/950077593423892480).

**Comment by jenil** [comment]
[Here](https://www.dropbox.com/s/oym5mj95i0mpa00/cv.pdf?dl=0) is the link to a PDF I just created using Sketch and Inter UI mentioned above 👆

**Comment by rsms** [comment]
Interesting @jenil — this also crashes my Preview.app, just as @jackiehluo's PDF does. Could one of you please try the build [linked to above](https://github.com/rsms/inter/issues/50#issuecomment-357093377) and see if the issue persists?

I am unable to repro this myself — PDFs I create with Inter UI seems to render perfectly fine wherever I try it (and I'm using the OTF files too, which contains the better CFF glyphs with cubic bezier data; TTF can only use quadratic bezier data.)

**Comment by jenil** [comment]
The PDF I created was using [Inter-UI-2.3-5e86f69013.zip](https://github.com/rsms/inter/files/1624460/Inter-UI-2.3-5e86f69013.zip) built. Tried from TTF and OTF.

Also, for me the PDF works (along with Inter UI) in the Preview.app on High Sierra. It's only the browsers that don't render the font.

**Comment by jackiehluo** [comment]
Just retried with the TTF, and it's still not working. Going to try the OTF!

Sidenote, the PDF is hosted on GitHub, and it looks like it shows correctly in GitHub's preview, which generates a PNG... it's really just Chrome's PDF viewer, apparently.

<img width="1005" alt="screen shot 2018-01-17 at 2 56 20 pm" src="https://user-images.githubusercontent.com/8452682/35071758-c55cebda-fb96-11e7-94dc-05bf56f1a8c1.png">

**Comment by jackiehluo** [comment]
[OTF.pdf](https://github.com/rsms/inter/files/1640933/OTF.pdf)
[TTF.pdf](https://github.com/rsms/inter/files/1640934/TTF.pdf)

Ahhh, TTF worked for me! Going to retry with the original file.

**Comment by jackiehluo** [comment]
And that worked! Looks like it's the Chromium bug—@jenil, that wasn't the case for you?

Thank you so much for all of the help, @rsms!

**Comment by jenil** [comment]
Yaay! Yes the TTF version worked for me too :) 

Thanks @jackiehluo @rsms
