### ISSUE TITLE
Greek (and other) glyphs with mismatching design (mainly stroke weight)

### ISSUE THREAD

**Issue by JapanYoshi** [rsms/inter#502]
**Describe the bug**
Inter v3.19. When using Inter for Greek text, some letters have weirdly mismatching spacing and thicknesses.

It’s the most noticeable in the Regular weight:
![Screenshot_20221003_110416](https://user-images.githubusercontent.com/8707990/193535473-015e7033-a84e-431a-ab0d-221f26c8e8b1.png)

![Screenshot_20221003_173711](https://user-images.githubusercontent.com/8707990/193535118-2c38ce0b-9f62-4be9-9534-784e0ad11bb9.png)
Note the wide right-side bearing of κ, and the thickness of δ ξ and σ.

**Environment**
- OS: Android
- App that renders the font: Firefox for Android showing Google Fonts, QuickEdit
- Version of font: Inter Regular v3.19 (downloaded from this repo, but same issue is present on Google Fonts)

**Comment by rsms** [comment]
This has likely been fixed since 3.19 was released. Can you try [Inter-4.00-12211fa1c0.zip](https://github.com/rsms/inter/files/9680120/Inter-4.00-12211fa1c0.zip) and see if that looks better for you?

**Comment by JapanYoshi** [comment]
Nope, kappa is fixed but the rest still have the same issue.
![image](https://user-images.githubusercontent.com/8707990/193808917-4bbc9fed-8c96-4670-ac49-3a9d965eb802.png)

I looked thorugh the font on FontForge, and I saw that a lot of other letters have this issue as well:
![image](https://user-images.githubusercontent.com/8707990/193808999-8c57d6d0-b0d5-464f-8b9b-8cb03d43d7f1.png)

Ƌ ƍ Ə Ɛ ƛ Ɯ Ƣ ƣ Ʀ ƪ Ʋ ƺ ƽ ƾ ƿ Ȝ ȝ Ƞ Ȣ ȣ ȸ ȹ Ɂ ɂ Ʌ ɒ ɔ ɘ ɚ ɤ ɸ ɷ ʃ ʄ ʅ ʆ ʈ ʊ ʋ ʔ ʕ ʖ ʗ ʡ ʢ ʦ ʧ ʪ ʱ ʴ ʵ ʶ ʻ ˀ ˁ ˠ ˤ ˥ ˦ ˧ ˨ ˩ ˪ ˫ ˮ  ̒̓ ̕  ̡ ̢ ͣ ͤ ͥ ͦ ͧ ͨ ͩ ͪ ͫ ͬ ͭ ͮ ͯ Ͱ ͱk ͷ ͻ δ ξ ς σ ϝ ϐ ϑ ϗ Ϛ ϛ Ϟ Ϡ ϡ ϰ ϱ ϵ ϶ ϻ Ͻ Ѽ ѽ Ѿ ѿ Ҁ ҁ Ỽ ỽ Ỿ ỿ ₔ ℓ ∂
i.sc l.sc y.sc

I think I recognize these character shapes from Roboto. Maybe Inter is inheriting some of Roboto instead of being all original.

In addition to the above, I suspect U+1DD4 - 1DF5 is just unaltered Roboto.

**Comment by rsms** [comment]
Thank you!

**Comment by rsms** [comment]
Last ~10-15 commits lands improved Greek

![inter-greek-roman](https://github.com/rsms/inter/assets/47046/0acf8ede-b36f-4c9d-9f70-4680179f4139)

![inter-greek-italic](https://github.com/rsms/inter/assets/47046/9ffd8fed-6ad4-4ddf-af30-8da7f69d222c)

![greek-display-vs-text](https://github.com/rsms/inter/assets/47046/c0cc5bb2-ad60-43c9-9e02-a2442520760f)
