### ISSUE TITLE
Consider parallelizing the build

### ISSUE THREAD

**Issue by ctrlcctrlv** [rsms/inter#507]
With e.g. GNU parallel or [MFEKparallel](https://github.com/MFEK/parallel) (which is a Rust GNU parallel rewrite fork I maintain but did not write)

**Comment by rsms** [comment]
I'm curious how that would help? Currently you can invoke make as `make -j$(nproc)` (or `make -j`) to run tasks in parallel. On my machine (nproc=32, 3.2GHz xeon w) building all ~80 fonts takes about a minute, compared to about 15 min without `-j`.
