### ISSUE TITLE
Small Cyrillic /i and /y issue in 4.0-betas

### ISSUE THREAD

**Issue by dayfuaim** [rsms/inter#509]
**Describe the bug**
Small Cyrillic /i (`и`) and /y (`ы`) from 4.0-betas are wider than one from 3.x.
It breaks visual design of the font.

**To Reproduce**
1. Install any of 4.0-betas

**Expected behavior**
Width of Small Cyrillic /i and /y is unchanged.

**Screenshots**
3.x (from https://rsms.me/inter/lab):
 ![Снимок экрана от 2022-10-09 18-44-12](https://user-images.githubusercontent.com/1274699/194763502-ab05b92d-e720-47c9-b545-9f07050f0445.png)

4.0-beta5 (current version that I use):
![image](https://user-images.githubusercontent.com/1274699/194763443-83ab6312-0e3a-4c7a-995b-f94e2e0545d7.png)

**Environment**
- OS-independent (i.e. I see it in Ubuntu 22.10, macOS 10.15.3)
- App-independent (so for applications)
- Version of font: Inter Regular 4.0-beta5.

**Additional context**
None

**Comment by rsms** [comment]
Does this look better to you @dayfuaim?

<img width="1067" alt="Screen Shot 2022-10-14 at 14 08 21" src="https://user-images.githubusercontent.com/47046/195944253-cf9f9e6c-53ae-4cfc-b059-b5c2868f9e27.png">

**Comment by dayfuaim** [comment]
> Does this look better to you @dayfuaim?
> 
> <img alt="Screen Shot 2022-10-14 at 14 08 21" width="1067" src="https://user-images.githubusercontent.com/47046/195944253-cf9f9e6c-53ae-4cfc-b059-b5c2868f9e27.png">
> 
> <img alt="reasytnesci" width="941" src="https://user-images.githubusercontent.com/47046/195945337-b1fca4ff-27f6-4e5b-bdb4-98044cd0875d.png">

@rsms Yes, thank you. :)

**Comment by rsms** [comment]
Excellent! Thanks for confirming @dayfuaim :–)

**Comment by rsms** [comment]
Included in [v4.0-beta6](https://github.com/rsms/inter/releases/tag/v4.0-beta6)
