### ISSUE TITLE
4.0beta5 variable font files overwriting each other on Windows

### ISSUE THREAD

**Issue by Voxybuns** [rsms/inter#510]
**Describe the bug**
I'm trying to install the variable font files of Inter 4 on my computer. However, when I go to install the italic file after installing the roman one, Windows tells me that the font has already been installed, only leaving me the option to overwrite the roman variant. This could be related to #488 

**To Reproduce**
1. Unzip "Inter.var.ttf" and "Inter-Italic.var.tff"
2. Attempt to install them both

**Expected behavior**
Both fonts should install normally, with Inter Italic being recognized as a subfamily of Inter, rather than trying to overwrite the roman subfamily.

**Environment**
- OS: Windows 11 22H2
- Version of font: 4.000;git-e0f93cc

**Comment by rsms** [comment]
Would love help from a Windows-font expert on this one

**Comment by rsms** [comment]
In case the cause for this was the issue described in #488, which I just fixed, could you please try this build and see if it behaves as expected @Voxybuns? [Inter-4.00-8c2631206b.zip](https://github.com/rsms/inter/files/9793329/Inter-4.00-8c2631206b.zip)

**Comment by Voxybuns** [comment]
@rsms Works like a charm on the build you've linked, the roman and italic font files don't try to overwrite each other anymore. Thanks a bunch! 😄

**Comment by rsms** [comment]
Glad to hear it :-)
