### ISSUE TITLE
German umlauts, weight & opsz

### ISSUE THREAD

**Issue by jwschoop** [rsms/inter#513]
Inter 4.0 Beta6 using the variable woff2 files. The browser used is Edge 106.

There seems to be an issue with german umlauts, opsz & weight. On higher font sizes the dots move too far together. This only happens with higher weights but it affects the italic and the roman style.

<img width="332" alt="Screenshot 2022-10-22 102621" src="https://user-images.githubusercontent.com/19785875/197329578-fad6b889-fd48-4a6e-8268-b02cee121685.png">

**Comment by kenmcd** [comment]
Already fixed. Will be in next beta. See https://github.com/rsms/inter/issues/511
