### ISSUE TITLE
Number one open digit and default

### ISSUE THREAD

**Issue by userxx347** [rsms/inter#514]
**Describe the bug**
I don't know if this is done well or not, but why while the other numbers change with the open digits, the number one is the same for both, I mean, the default number one is the open digit, the number one that comes by default should not be the number one that you can choose as an alternative and the open digit be the one that is currently by default?

**Comment by rsms** [comment]
This sounds more like a question than a bug report. [Try asking in Q&A](https://github.com/rsms/inter/discussions/categories/q-a)
