### ISSUE TITLE
Inter 4 Beta 7 - Interpolation Issue - lmidtilde

### ISSUE THREAD

**Issue by kenmcd** [rsms/inter#516]
Inter 4 Beta 7 - Interpolation Issue - lmidtilde
Files: `Inter.var.ttf` and `Inter-Italic.var.ttf`
Characters/glyphs: lmidtilde (`026B`) and lmidtilde.ss02

FontLab did not like these characters (only showed default master and no interpolation).
So I made demo below in FontCreator.
Also checked it on Samsa and it shows the same issues.
Also affects the Italic.

![2022-10-28_12-32-03](https://user-images.githubusercontent.com/844920/198718165-61e42ae0-ff4d-42d6-a176-9c1ee7c26f5b.gif)

**Comment by rsms** [comment]
Thank you!

**Comment by rsms** [comment]
Fixed

<img width="1092" alt="Screen Shot 2023-04-21 at 14 07 28" src="https://user-images.githubusercontent.com/47046/233734853-fa415a62-9288-408a-87cf-d1a125e78489.png">
