### ISSUE TITLE
Kerning of disambiguated "l" question

### ISSUE THREAD

**Issue by adamcc** [rsms/inter#518]
Inter is super-useful and I really like the availability of the disambiguated alternate. 

Is the kerning of the disambiguated "l" OK?

"Ambiguous" Inter. Evenly spaced.
<img width="438" alt="Screen Shot 2022-11-14 at 4 36 07 PM" src="https://user-images.githubusercontent.com/497933/201613387-04db1385-20b2-47ca-a1ce-b21158244d90.png">

Disambiguated. li and la spacings look a little cramped to me.
<img width="460" alt="Screen Shot 2022-11-14 at 4 36 24 PM" src="https://user-images.githubusercontent.com/497933/201613491-b2e155cd-da64-481f-9e52-53174d648e57.png">

Fira Sans.
<img width="536" alt="Screen Shot 2022-11-14 at 4 34 10 PM" src="https://user-images.githubusercontent.com/497933/201613016-bd50d08f-fb1c-4555-af3c-92ce560147f0.png">

**Comment by rsms** [comment]
Some screenshots of current state

<img width="1175" alt="Screen Shot 2023-04-29 at 15 13 05" src="https://user-images.githubusercontent.com/47046/235326227-784840a1-248c-4a9e-be1d-5fd0df6bdbc9.png">

<img width="1052" alt="Screen Shot 2023-04-29 at 15 13 15" src="https://user-images.githubusercontent.com/47046/235326223-c06f78ec-b9fb-4dbe-84f7-328f73d3a6e4.png">

<img width="931" alt="Screen Shot 2023-04-29 at 15 13 11" src="https://user-images.githubusercontent.com/47046/235326226-c2653c40-3a76-483c-ad9f-c8298c0b086a.png">

<img width="1256" alt="Screen Shot 2023-04-29 at 15 13 37" src="https://user-images.githubusercontent.com/47046/235326220-6c32c6ea-262c-4ac9-a062-44640eab0421.png">

**Comment by rsms** [comment]
Made another pass on spacing (sidebearings and kerning) as well as letterforms (the tail has been adjusted for the display styles)

Some text samples:

## Inter text

<img width="911" alt="Screen Shot 2023-05-04 at 16 58 33" src="https://user-images.githubusercontent.com/47046/236354443-6962080e-36a2-4ea1-a5f5-2ef7e7c7e615.png">

<img width="908" alt="Screen Shot 2023-05-04 at 16 59 03" src="https://user-images.githubusercontent.com/47046/236354478-eeaf8887-d9a0-4245-bcd9-7f8203034653.png">

<img width="908" alt="Screen Shot 2023-05-04 at 16 59 17" src="https://user-images.githubusercontent.com/47046/236354486-0ad2b957-9b4b-43e8-919a-63ea40daea99.png">

## Inter Display

<img width="893" alt="Screen Shot 2023-05-04 at 16 59 39" src="https://user-images.githubusercontent.com/47046/236354511-f2d0f1ea-3018-4d15-8c80-271047a2d8c6.png">

<img width="882" alt="Screen Shot 2023-05-04 at 17 00 44" src="https://user-images.githubusercontent.com/47046/236354521-1faba38c-5cd0-4bb7-b7a2-bb68f52170ce.png">

<img width="885" alt="Screen Shot 2023-05-04 at 17 01 15" src="https://user-images.githubusercontent.com/47046/236354533-9184656f-9b01-49bd-9249-b35a1ed8cfb6.png">
