### ISSUE TITLE
Inter with Stylistic Alternates turned on by default 

### ISSUE THREAD

**Issue by ldanielswakman** [rsms/inter#521]
We are switching to using Inter font with nebenan.de, but the stylistic alternate version with single story az which is lovely. But I wonder if there is a version available where it's turned on by default? Because we can't always expect every team member to turn the advanced don't features on...

Thanks!

**Comment by johnfactotum** [comment]
This is covered in the FAQ: https://rsms.me/inter/#faq-otfeat-customize-compile

**Comment by VladWinner** [comment]
Here is a more flexible utility: https://github.com/MuTsunTsai/fontfreeze

**Comment by ldanielswakman** [comment]
Thanks both for answering this!
