### ISSUE TITLE
Missing Null character (0x00)

### ISSUE THREAD

**Issue by igoriuz** [rsms/inter#522]
**Describe the bug**
Text overflows in flutter web apps use a null character (0x00) after ellipsis. If the font doesn't provide the character, Flutter uses a fallback which looks like a burger instead of an empty space.

(My source: https://github.com/flutter/flutter/issues/90135#issuecomment-984916656)

**To Reproduce**
1. Use this font in a flutter app (we've downloaded it directly instead of using google fonts service)

(Code sample with google font service, please click on "Run"): https://dartpad.dartlang.org/?id=493c8b3ef8931cbac3fbbe5c04b9c4cf

**Expected behavior**
Empty space instead of fallback null character from flutter. 

**Screenshots**
Please see either the code sample above or this comment: https://github.com/flutter/flutter/issues/76473#issuecomment-823570806

**Environment**
- OS: macOS 13.0.1
- Each major browser (chrome, firefox, safari)
- Inter Regular. Version 3.012;git-06b166889, Inter Regular. Version 3.019;git-0a5106e0b (other font styles are also affected)

**Additional context**
Roboto font has this null character. Maybe its worth looking into it.

Thank you very much for providing this wonderful font!

**Comment by rsms** [comment]
Ha ha ha... OMG what a terrible hack in Flutter, actually using NULL on purpose in text runs. I imagine this might brake other stuff in ...interesting ways.

Okay, I think the impact of adding this is minimal, so I'll go ahead with a "Flutter weirdness workaround" :–)
