### ISSUE TITLE
A variant without NTD currency symbol (元)?

### ISSUE THREAD

**Issue by nestflow** [rsms/inter#523]
First thanks so much for developing the great font!

I used lastest 4.0-beta7 font as my default system font for Android. It works well but I notice a recent pull #472 added support for currency New Taiwan Dollar (元). I recognize this will help in some applications, but it's also a very common character in Chinese other than currency usage. As latin font has the highest priority in the system, it will override the one (元) in CJK font, leading to a bit strange display results (like misalignment). It can also be a problem for other systems that follows similar priority settings for multilanguages.

Honestly, I believe it's a problem that the system/software should consider, rather than font designers. But it might be a good idea to have a "light" version more restricted in character sets, without support for currencies for example.

**Comment by Dianliang233** [comment]
Do note that apart from Taiwan, 元 is also used for CNY in China. Also, 元 is one of the more common CJK characters. This change is quite impactful and I really think it should be reverted (at least for 元), as it causes confusion and inconsistency in the text.

![image](https://user-images.githubusercontent.com/45287180/206441295-b047ae2d-55b1-4c59-8c87-45f2b2a7e846.png)

^ Inter applies first, and the fallback font is Noto Sans CJK CN. Notice how strange 元 is among the other characters in the text.

**Comment by johnfactotum** [comment]
In my opinion, instead of a variant, it'd be better to just remove all the glyphs introduced in #472.

Although "元" (U+5143) is listed as a currency symbol for "Yuan, yen, won, HKD" in Unicode (The Unicode Standard 15.0, Chapter 22), this is very misleading. The yuan, yen, and won have Latin currency symbols, and the HKD and TWD are commonly written with "$".

```js
new Intl.NumberFormat('en', { style: 'currency', currency: 'JPY' }).format(100)
// "￥100"
new Intl.NumberFormat('en', { style: 'currency', currency: 'CNY' }).format(100)
// "CN¥100.00"
new Intl.NumberFormat('en', { style: 'currency', currency: 'KRW' }).format(100)
// "₩100"
new Intl.NumberFormat('en', { style: 'currency', currency: 'TWD' }).format(100)
// "NT$100.00"
new Intl.NumberFormat('en', { style: 'currency', currency: 'HKD' }).format(100)
// "HK$100.00"
```

So in other words, "元" is used as a currency symbol only in certain CJK contexts. It is not generally used in Latin or trans-writing-system contexts. Also, properly speaking, it's not even a symbol for the NTD. According to [Wikipedia's article on the New Taiwan dollar](https://en.wikipedia.org/wiki/New_Taiwan_dollar), "元" is an informal nickname for the currency.  The formal symbol, the one mentioned in The Unicode Standard, for TWD, is 圓 (U+5713).

Fundamentally, "元" is just not a currency symbol. Neither is "ლ". And neither are "د.م." and "د.إ.". These are all just regular characters. Inter should not have these glyphs unless it has full CJK/Geogian/Arabic support.

And while "﷼" is technically a currency symbol, it's really just a ligature, and one that exists purely for comparability, according to The Unicode Standard (v15.0, Chapter 9):
> The character was invented by a typewriter standardization committee in 1973 and is encoded in the Unicode Standard as a compatibility character, as it continues to be specified in Iranian national standards for character sets and keyboard layouts, including ISIRI 9147:2007. Except for a short life during the typewriter era, it has not received widespread usage outside standards, as Iranians prefer to spell out the word as <reh, farsi yeh, alef, lam>.

The symbols "؋",  Although they are genuinely currency symbols, given that none of them are Latin, and they are likely to be used with other characters from their native writing systems, it'd probably be better to leave them for fonts that do support those writing systems.

**Comment by quiple** [comment]
This is just as ridiculous as adding 円 because it's the Japanese yen symbol, or adding 원 because it's the Korean won symbol. I think it's correct to remove 元.

**Comment by lxgw** [comment]
The "元" is a common used Chinese Character more than a currency symbol of RMB, NTD or HKD. However, some Western fonts add this character as a currency symbol, such as Neue Frutiger World.

![41c64826a39b9557e33bc8012784b999.jpeg](https://user-images.githubusercontent.com/51902309/224067528-4022aee1-376d-4a77-aab4-b2b7e427c9fd.jpeg)
 
(The Western font is New Frutiger World and the fallback font is Hanyi RunYuan.)

**Comment by MY1L** [comment]
更糟糕的是，这个“元”字无论从中文还是西文角度来看都**太难看**了。
如果确实要做，应当放到字体特性中避免影响常用字符，甚至不需要新字形，完全可以用 “π̅（U+03C0 U+0305）” 组合来表达，范例：https://www.bilibili.com/read/cv13183071

**Comment by NightFurySL2001** [comment]
（@MY1L 请注意已离题，@lxgw 提供的图片是 Frutiger Neue World所提供的“元”符号，并不是Inter的字形。Inter所放置的“元”字形请参考 @Dianliang233 的附图。）

**Comment by SpinEve** [comment]
> （@MY1L 请注意已离题，@lxgw 提供的图片是 Frutiger Neue World所提供的“元”符号，并不是Inter的字形。Inter所放置的“元”字形请参考 @Dianliang233 的附图或 pull request #472。） (Please note that the image provided by @lxgw is the glyph of 元 in Frutiger Neue World, not from Inter. The glyph pulled into Inter can be seen in the picture posted by @Dianliang233 or in pull request #472.)

You are right, and I actually think the glyph of 元 in the Inter font looks well - it's just not so suitable to have one, as people in this thread says.

**Comment by be5invis** [comment]
The ideograph "元" is equivalent to the **WORD** "dollar" / "pound" in English, instead of the symbol "$" / "￡".

**Comment by YVVT** [comment]
> （@MY1L 请注意已离题，@lxgw 提供的图片是 Frutiger Neue World所提供的“元”符号，并不是Inter的字形。Inter所放置的“元”字形请参考 @Dianliang233 的附图或 pull request #472。） (Please note that the image provided by @lxgw is the glyph of 元 in Frutiger Neue World, not from Inter. The glyph pulled into Inter can be seen in the picture posted by @Dianliang233 or in pull request #472.)

我觉得 lxgw 在这里想表达这样一种现象，部分西文字体把“元”等字符当做货币符号，强行按照西文字符的设计风格来设计“元”字，忽略了“元”作为常用汉字的用途，显然这不是一种好的现象。

I think lxgw wants to express a phenomenom that some Latin fonts treat “元” as a currency symbol, where “元” is designed according to the design style of Latin characters. Obviously, this is not a good phenomenom.

**Comment by NightFurySL2001** [comment]
>>（@/MY1L 请注意已离题，@/lxgw 提供的图片是 Frutiger Neue World所提供的“元”符号，并不是Inter的字形。Inter所放置的“元”字形请参考 @/Dianliang233 的附图或 pull request https://github.com/rsms/inter/pull/472。）
>> (Please note that the image provided by @/lxgw is the glyph of 元 in Frutiger Neue World, not from Inter. The glyph pulled into Inter can be seen in the picture posted by @/Dianliang233 or in pull request https://github.com/rsms/inter/pull/472.)
>
>我觉得 lxgw 在这里想表达这样一种现象，部分西文字体把“元”等字符当做货币符号，强行按照西文字符的设计风格来设计“元”字，忽略了“元”作为常用汉字的用途，显然这不是一种好的现象。
>I think lxgw wants to express a phenomenom that some Latin fonts treat “元” as a currency symbol, where “元” is designed according to the design style of Latin characters. Obviously, this is not a good phenomenom.

Quote original comment from @/MY1L:
> 更糟糕的是，这个“元”字无论从中文还是西文角度来看都**太难看**了。

She was referring to the design shown by @/lxgw which is *not* the design provided to Inter. The glyph of 元 provided in #472 is as below:
![image](https://user-images.githubusercontent.com/33471049/225533630-107921d4-8c24-4824-a396-df08cdd58606.png)

However, her other suggestion, quoted below:
> 完全可以用 “π̅（U+03C0 U+0305）” 组合来表达

is still a bad idea. There is no precedence of using π̅ as the character 元, and it is obviously not used as such in real life. Seeing as 元 is a character/word, **not a symbol**, the glyph should just be completely removed and Inter **should not** use π̅ as a representation of 元 as suggested by @/MY1L.

P/S: I still stand with @/johnfactotum that #472 should just be reverted completely as it overrides Arabic abjads too.

**Comment by MY1L** [comment]
@NightFurySL2001 等等，不要误会，我没有要求字体输入“π̅ ”出“元”字形的意思，我意思是删除“元”字形及其映射即可。
其实我选择π̅ 组合的原因就是因为现实中不存在，不会发生误用，且同时这种组合并不违背字体特性`mark`（即无需添加预组合字形），毕竟“◌̅ ”是结合符号。就像⃀U+20C0在统一码收录前用「С̲」表达一样，实际上字体中没有预置⃀的字形。

**Comment by rsms** [comment]
All removed (#472 and related subsequent fixes have been reverted.)
CC @NaN-xyz
