### ISSUE TITLE
Problem with embedding Inter to MS Word

### ISSUE THREAD

**Issue by Chulio3000** [rsms/inter#525]
The typo is embedded to a MS Word letter(.dotx) template using it in the letters footer.
When I then open the template with the Typo deactivated MS Word claims that Inter is selected,
but in fact it is using Calibri. When I then activate Inter on my computer again and re-open the Word File 
everything looks as it should again.

Does anyone know why it is not working to embed Inter to the Word-File?
I think it should work because it says embedding Inter is not limited.

**Background**
The Typo is embedded in MS Word because it should be send to people working on the Word-File
that may not have Inter on their Computer.

**Environment**
- macOS 11.6.6
- MS Word 16.86
- Inter:VF:2021:0a5106e0b

**Comment by Chulio3000** [comment]
Does anybody please have an idea on this or knows how to solve this problem? Thanks in advance!

**Comment by kenmcd** [comment]
On a Mac stand-alone MS Word cannot embed fonts.
But Word for Microsoft 365 for Mac can.
Not sure if variable fonts can be embedded - have not tried it.
See info here:  
https://support.microsoft.com/en-us/office/benefits-of-embedding-custom-fonts-cb3982aa-ea76-4323-b008-86670f222dbc#OfficeVersion=macOS

Not an issue with the Inter fonts - please close this issue.

**Comment by Chulio3000** [comment]
Thanks for your answer, @kenmcd. Unfortunately we are using Mircosoft 365 already and checked all the steps in the tutorial.
The Problem still occurs. Thanks nevertheless. I will close the ticket now. If anyone else has an idea, please let me know.
