### ISSUE TITLE
Kerning of "Gi" pair too wide

### ISSUE THREAD

**Issue by bengiannis** [rsms/inter#526]
**Describe the bug**
Kerning between uppercase G and lowercase i ("Gi") is too wide

**To Reproduce**
1. Type "Gi" with kerning pairs enabled.

**Expected behavior**
"Gi" kerning should be slightly tighter.

**Screenshots**
![1](https://user-images.githubusercontent.com/32772525/213275718-fc9fbf8c-649f-4476-b26e-e5b617f040cf.png)
![2](https://user-images.githubusercontent.com/32772525/213275719-db2180b9-d66a-4afa-bcfd-7b4518b3e09d.png)
![3](https://user-images.githubusercontent.com/32772525/213275720-b671effe-c18d-4f53-b850-20a84d93cc51.png)
![4](https://user-images.githubusercontent.com/32772525/213275721-7f97403b-83c5-4a61-aa20-fddb0677af87.png)
![5](https://user-images.githubusercontent.com/32772525/213275723-09cb5687-6085-4da0-9f99-45154e130104.png)
![6](https://user-images.githubusercontent.com/32772525/213275724-5dd2b3eb-6364-4bba-a888-1a26b870d061.png)

**Environment**
- OS: macOS 12.6
- App: Figma, Safari, seems like all
- Version: Inter (All weights) 3.19

**Additional context**
It seems like it's currently using the same kerning as "Oi", except the right side of Inter's "G"  is flat, not rounded. This causes a gap.

**Comment by rsms** [comment]
As @kenmcd alludes to, this has been fixed in the source version.
Thank you for the report though!
