### ISSUE TITLE
ɪ, ʀ, ʁ, ʏ 48 units too short

### ISSUE THREAD

**Issue by JapanYoshi** [rsms/inter#528]
**Describe the bug**

The small-cap I is used in the International Phonetic Alphabet as e.g. the "I" sound in the English word "kit". It is supposed to be an x-height tall, but it is currently 48 units too short. The same issue happens with 3 other IPA characters (that I know of).

I noticed they're all small-caps. Is it an intentional design choice?

**To Reproduce**
1. type one of the following letters: ɪ, ʀ, ʁ, ʏ
2. compare their height to ASCII lowercase letters such as i, n, and x

**Expected behavior**

They should have the same height (excluding visual compensation).

**Screenshots**

![image](https://user-images.githubusercontent.com/8707990/215322473-c269c37f-97e1-4c97-9e2c-c02fe30a789b.png)

**Environment**
- OS: [e.g. macOS 10.14] Windows 10
- App that renders the font [if applicable; e.g. Chrome, Adobe Illustrator] FontForge, Inkscape
- Version of font [e.g. "Inter Regular 3.0;8cf05e4a" — you can use fontdrop.info to find out the version] Inter Thin 3.019; git-0a5106e0b

**Additional context**

**Comment by rsms** [comment]
Closing this since it's been addressed in version 4
