### ISSUE TITLE
Numbers width different to each other

### ISSUE THREAD

**Issue by vergoossen** [rsms/inter#531]
**Describe the bug**
Numbers don't have same width, which looks a bit strange when you but dates or money amounts among each other.
![image](https://user-images.githubusercontent.com/25444741/216473678-c2e75d89-23e3-434a-aa2c-f51ae57a3af2.png)

**To Reproduce**
Install Inter font and write the dates and amounts in Excel (Windows).

**Expected behavior**
I know each font has his own behavior, and Arial is not leading. But I would expect the numbers to have the same width?

**Environment**
Windows 10 / Excel

**Comment by VladWinner** [comment]
> Numbers don't have same width

This is intentional. 

> Arial is not leading

It's Calibri.

> But I would expect the numbers to have the same width?

https://rsms.me/inter/#features/tnum

Duplicate of #521 #413

**Comment by vergoossen** [comment]
Sorry.
Thankyou for clarifying
