### ISSUE TITLE
Some missing diacritic compositions and some missing mark anchors

### ISSUE THREAD

**Issue by robintown** [rsms/inter#532]
**Describe the bug**
Diacritics on some Latin vowel letter + underdot combinations are not positioned correctly.

**To Reproduce**
View the following characters with Inter:

```
a 	ạ 	ạ́ 	ạ̈ 	ậ
u 	ụ 	ụ́ 	ụ̈ 	ụ̂
ı 	ı̣ 	ị́ 	ị̈ 	ị̂
o 	ọ 	ọ́ 	ọ̈ 	ộ
e 	ẹ 	ẹ́ 	ẹ̈ 	ệ 
```

**Expected behavior**
The underdot diacritic should not impede other diacritics from attaching correctly. Also, dotless ı + underdot shouldn't look broken.

**Screenshots**

![Screenshot from 2023-02-12 12-47-36](https://user-images.githubusercontent.com/48614497/218327764-1f551b5b-5f9f-428b-b74f-1c20b838d00a.png)

**Environment**
- OS: NixOS unstable
- App that renders the font: Gnome Text Editor
- Version of font: Inter Regular 3.19

**Additional context**
Perhaps the problematic characters don't appear in any natural languages, but they do appear in some constructed languages.

**Comment by rsms** [comment]
Related: #155 #534

**Comment by rsms** [comment]
What's going on here I think are two things: 1) missing/unimplemented compositions (e.g. "i with grave") and 2) missing mark anchors. The latter are weird: the source has marks but something seems to go wrong when building font files.

**Comment by rsms** [comment]
Should be fixed now

![eiranst8iersn](https://user-images.githubusercontent.com/47046/233726803-f04962d5-bdf5-4b82-a91d-388c213e0ec5.png)
