### ISSUE TITLE
Missing diacritics anchor for Latin vowels with macron/breve

### ISSUE THREAD

**Issue by feophan** [rsms/inter#534]
**Describe the bug**
Combining diacritics with characters having a macron or a breve results in incorrect diacritics placement.

**To Reproduce**
1. Type a character in-built with a diacritic, e.g. ā U+0101
2. Type a combining diacritic, e.g. ́  U+0301
3. Observe the diacritics placement

**Expected behavior**
The diacritics should be placed above and not on the side of the glyph

**Screenshots**
![image](https://user-images.githubusercontent.com/31542979/219939942-c3dd7e57-86af-4d08-b79b-2f54202b5ff4.png)

**Environment**
- OS: Windows 10
- Word, Obsidian
- Version of font "Inter Regular 3.019;git-0a5106e0b"

**Comment by escapezn** [comment]
3.019 is out of date, please see [4.0-beta7](https://github.com/rsms/inter/releases/tag/v4.0-beta7), it may have been improved.

**Comment by feophan** [comment]
Just checked, the behaviour of 4.0 is the same as above.

**Comment by feophan** [comment]
I checked the GPOS tables, and in mkmk only the double acute is marked as a base

![image](https://user-images.githubusercontent.com/31542979/220700014-ad65c47d-8d96-4782-9e25-ea36e922a382.png)

interestingly, the combinations I'm looking for already exist as variant pre-composed glyphs (e.g. uni1DC4.lc for macron + acute), there's just no clear way to access them in the word editor.

**Comment by feophan** [comment]
Creating a rule in ccmp.fea

```
sub macroncomb acutecomb by macronacutecomb.lc;
sub macroncomb gravecomb by macrongravecomb.lc;
sub brevenosp acutecomb by breveacutecomb.cn;
sub brevenosp gravecomb by brevegravecomb.cn;
```

before ccmp03 lookup fixed the issue for combinations with macron. However, the breve is missing the mark anchor in the export, even though it's defined the same way as for the macron. I assume it has something to do with a font building script, but I have not found what caused the anchors to be deleted for some marks and not the others. I suppose it's also relevant for another open issue about dotless i.

**Comment by rsms** [comment]
Interesting. At the core, Inter is using fontmake from Google. It does seem to be an issue with Inter though. /macron does not have a matching "top" (but /a does.) If I add a "top" anchor to /macron, your example "works as expected":

<img width="1591" alt="Screen Shot 2023-03-15 at 14 08 11" src="https://user-images.githubusercontent.com/47046/225443604-ad0ac65c-b259-4219-83bc-53f68dc1b030.png">

**Comment by rsms** [comment]
Related: #155 #532

**Comment by rsms** [comment]
> before ccmp03 lookup fixed the issue for combinations with macron

I can't get this to work. How exactly did you do it? If I add those substitution rules to anywhere in ccmp, I see no effect. Using FontGoggles for testing:

<img width="557" alt="Screen Shot 2023-04-19 at 10 20 56" src="https://user-images.githubusercontent.com/47046/233152297-7addb354-43ad-4b70-a60c-e7499c5e26e8.png">

Here's what I'm trying: Taking U+0101 U+0301 as an example, /macron has a top anchor and of course /acute has a matching _top anchor. The exported /macroncomb and /acutecomb are simply component instances of /macron and /acute, just with zero advance width, so they should have the same anchors in the final font.

<img width="1713" alt="ienorast8ri" src="https://user-images.githubusercontent.com/47046/233154423-6c0809dd-0dd8-40cb-877f-6302986337fe.png">

In ccmp, adding this:

```fea
# ...
  sub i.numr' @CCMP_ACC by uni2071.ccmp;
} ccmp02;

sub macroncomb acutecomb by macronacutecomb.lc;
sub macroncomb gravecomb by macrongravecomb.lc;
sub brevenosp acutecomb by breveacutecomb.cn;
sub brevenosp gravecomb by brevegravecomb.cn;

lookup ccmp03 {
  sub d caroncmb by dcaron;
# ...
```

However, this is the result:

<img width="557" alt="Screen Shot 2023-04-19 at 10 20 56" src="https://user-images.githubusercontent.com/47046/233152297-7addb354-43ad-4b70-a60c-e7499c5e26e8.png">

**Comment by rsms** [comment]
The substitution do work for just the two accents but not when used after e.g. /a. I think that what is happening is /a + /macroncomb gets sub'd first into /amacron and then there's no rule for /amacron + /acutecomb
 
<img width="876" alt="Screen Shot 2023-04-19 at 10 35 19" src="https://user-images.githubusercontent.com/47046/233155681-fb8e4c9e-b86f-4e5c-b7a5-9d2055b02d30.png">
<img width="871" alt="Screen Shot 2023-04-19 at 10 35 32" src="https://user-images.githubusercontent.com/47046/233155709-13bf1992-673d-444b-ba64-b104380cbb96.png">

**Comment by rsms** [comment]
Oh no, it seems there's either...
- a bug in Glyphs
- a bug in fontmake
- a misconception on my end that I can use components for marks

If I decompose the component instances in macroncomb and acutecomb mkmk works as expected:

<img width="638" alt="Screen Shot 2023-04-20 at 09 29 21" src="https://user-images.githubusercontent.com/47046/233430304-99191829-ef8e-48b8-9db3-e561c2143716.png">

My suspicion is on fontmake since this is how accents have been for a long while and was working before I started using fontmake to compile fonts.

**Comment by rsms** [comment]
Resolved with https://github.com/rsms/inter/commit/aa522f1a954b48696a885a7c53e4a43525deee3a

<img width="1242" alt="Screen Shot 2023-04-21 at 10 17 11" src="https://user-images.githubusercontent.com/47046/233697134-20f54902-bad4-47c3-a1e1-8e37c44dd1f5.png">
