### ISSUE TITLE
Missing below anchor for dotless i

### ISSUE THREAD

**Issue by feophan** [rsms/inter#535]
**Describe the bug**
Dotless i character ı U+0131 is missing an anchor for below diacritics.

**To Reproduce**
1. Type dotless i ı U+0131
2. Type a below diacritic, e.g. combining inverted breve below ̯  U+032F
3. Observe the result

**Expected behavior**
The diacritic should be placed under the glyph, not by its side

**Screenshots**
![image](https://user-images.githubusercontent.com/31542979/219940408-695535fa-9571-4b38-9a55-e0861bb2793d.png)

**Environment**
- OS: Windows 10
- Word, Obsidian
- Version of font "Inter Regular 3.019;git-0a5106e0b"

**Comment by rsms** [comment]
Fixed in source and will be included with version 4

<img width="1229" alt="Screen Shot 2023-04-04 at 14 04 48" src="https://user-images.githubusercontent.com/47046/229922006-b4c5307a-8400-498a-9879-c9383576adb1.png">
