### ISSUE TITLE
Wrong character representation

### ISSUE THREAD

**Issue by cavanslr** [rsms/inter#536]
**Describe the bug**
The character "Ə"(latin capital letter schwa) is not accurately represented.

**Expected behavior**
It was supposed to be symmetrical to the character "G".

**Screenshots**
<img width="1134" alt="screenshot" src="https://user-images.githubusercontent.com/126523831/221984615-c73f846f-0eab-4e5d-803c-d00523c9a0aa.png">

**Comment by rsms** [comment]
Thank you. But please, in the future, _follow the issue guidelines!_
