### ISSUE TITLE
Problems with Office and PDF

### ISSUE THREAD

**Issue by miguelrpinho** [rsms/inter#537]
Hey everyone! I'm having trouble with this font on a specific occasion. Whenever I use Inter or Inter V on Word, Excel or Powerpoint (or any Microsoft Office app, when I export to pdf, it appears like so (on Adobe Acrobat). Weirdly, on Edge's own pdf reader, it shows up correctly.

on excel: ![test](https://user-images.githubusercontent.com/126801838/222481450-7f7de933-d807-4afe-af34-be07ac2a9072.jpg)
pdf on acrobat reader: ![test2](https://user-images.githubusercontent.com/126801838/222481935-bad9fe35-2a91-4983-80cf-623daf173c85.jpg)

If I do the same in Word, it appears correctly; however, the text isn't selectable, it gets converted to bitmap.
What might be the problem?

**Comment by kenmcd** [comment]
Could you please attach the PDFs here?

What version of Office are you using?

**Comment by miguelrpinho** [comment]
[test.pdf](https://github.com/rsms/inter/files/10881266/test.pdf)
Here it is.
I'm using Microsoft 365 for Windows.

**Comment by kenmcd** [comment]
The PDF shows the static fonts as not embedded, and as Type 1.
So I think you installed the static `.otf` fonts.
IIRC Office applications (or Excel) will not embed `.otf` fonts.
Regardless, it appears the PDF reader has problems connecting the un-embedded fonts, to the user's installed fonts.

The PDF shows fine in PDF-XChange, InFix, MasterPDF, FoxitPDF.
But, has same error in NitroPDF.

Un-install the `.otf` fonts and install the `.ttf` fonts.
(from the `Inter Hinted for Windows` folder)

If that does not fix it, I do not know what is happening.
Make sure you did not install the fonts multiple times.
(check your Font folders for duplicate files)
Also do not have both the `.otf` and `.ttf` fonts installed at the same time.

**Comment by miguelrpinho** [comment]
It worked!
Thank you so much :)

**Comment by SusPaw** [comment]
is that solution still valid for 2026? i am having a similar issue. thank you!

**Comment by kenmcd** [comment]
> is that solution still valid for 2026? i am having a similar issue. thank you!

Yes. Use the static `.ttf` fonts.
Windows apps cannot embed variable fonts correctly. 
And will not embed `.otf` fonts.
Have not checked Office 2024 lately, but it is likely this is still the situation.
