### ISSUE TITLE
Can't access the Inter Display in Figma

### ISSUE THREAD

**Issue by stacknetco** [rsms/inter#538]
**Describe the bug**
I have downloaded the Inter Display font, but for some reason, it is not accessible in Figma.

**Environment**
- OS: macOS 12.1
- App that renders the font: Figma
- Version of the font: The one from [4.0-beta7](https://github.com/rsms/inter/releases/tag/v4.0-beta7)

**Comment by rsms** [comment]
- _exactly_ what font files did you install and _exactly_ where and how did you install them?
- Can you access Inter Display in other apps, like TextEdit?

**Comment by rsms** [comment]
Closing this since it's been over a month w/o a response
