### ISSUE TITLE
Print problems with overlapping shapes on PC

### ISSUE THREAD

**Issue by Kalmnas** [rsms/inter#54]
When installing InterUI 2.5 Beta on a Mac with Indesign, the screen font shows no overlapping problem. Indesign 2017, and 2018. And the font renders ok but looks blurry on print. Visual ok in pdf. 

My customer is working on PC and his visuals even look brooken in the pdf. And when he opens the Indesign document. 
[test.pdf](https://github.com/rsms/inter/files/1703475/test.pdf)

**Comment by rsms** [comment]
Could you please provide the InDesign document used to produce `test.pdf`?

**Comment by Kalmnas** [comment]
Sorry for taking so long to get back to you. The customer changed typeface. I have now tried to work with the latest font file 2.5 and it seems to work fine! Both on screen and in print! Great job! And I can now recommend it to usage over all medias. Thank you for fixing and getting back! Keep up the great job!
