### ISSUE TITLE
V4's kerning for `ili` sequence made the spacing inconsistent

### ISSUE THREAD

**Issue by be5invis** [rsms/inter#540]
![image](https://user-images.githubusercontent.com/240091/224539760-e9238f45-89b3-4491-bf8d-b77d72ad8da9.png)

**Comment by rsms** [comment]
Thanks!

**Comment by nfriedli** [comment]
It seems to me that there are always problems of spacing. between l and i or between i and b. But I only see them when the optical size (opsz) is high.

Here are 2 screenshots with the variable font *.ttf in version 4.0b8. Example in https://wakamaifondue.com/beta/

![opsz 32](https://github.com/rsms/inter/assets/503520/73c9b315-9482-445d-b59e-c273a389702d)

![opsz 14](https://github.com/rsms/inter/assets/503520/ccf17a5b-4db2-4a2b-bb33-a62f0ed9f073)
