### ISSUE TITLE
Positioning of combining dot above right used in Pe̍h-ōe-jī

### ISSUE THREAD

**Issue by NightFurySL2001** [rsms/inter#543]
[Pe̍h-ōe-jī](https://en.wikipedia.org/wiki/Pe%CC%8Dh-%C5%8De-j%C4%AB) is a romanization of Min Nan Chinese as used in Taiwan, which has some special diacritics not appearing in Western texts. It seems that Inter already have most of the diacritics required, but the positioning of top right dot and top line vertical still show some problems.
![image](https://user-images.githubusercontent.com/33471049/225592523-df2eeaac-9cc2-4473-a3d0-0a0b16843d7e.png)

Reference on how it should look:
![image](https://user-images.githubusercontent.com/33471049/225594168-38c83748-6a3f-4330-874f-23a0ad287e40.png)

**Comment by rsms** [comment]
Inter actually does _not_ have these glyphs. What's happening is that U+0358 "COMBINING DOT ABOVE RIGHT" is drawn next to another glyph:

<img width="455" alt="Screen Shot 2023-04-19 at 10 00 54" src="https://user-images.githubusercontent.com/47046/233148591-366438ea-76c7-4257-b4e9-2d7624a0abcc.png">

Fonts with "proper" support for these characters uses [ccmp](https://learn.microsoft.com/en-us/typography/opentype/spec/features_ae#ccmp) to substitute e.g. U+00F3 U+0358 with a single internal glyph, specially designed for that combination. Inter contains many such compositions, but not for these particular combinations. _(I realize you probably know how ccmp works, but being extra clear here for the sake of precision and for other's reading this.)_

If you feel strongly about adding this to Inter, please [create a feature request issue](https://github.com/rsms/inter/issues/new?assignees=&labels=&template=feature_request.md)
