### ISSUE TITLE
is the project dead?

### ISSUE THREAD

**Issue by oantonioo** [rsms/inter#548]
I made the mistake of putting the CDN to the rsms.me source in all my projects.

It has been several weeks since it does not work correctly, it takes between 17 and 25 seconds to download a few kb.
This problem has no solution I understand after so long. :(

I am right?

**Comment by rsms** [comment]
This is an issue with Cloudflare. Please, in the future, follow the issue guidelines.

**Comment by oantonioo** [comment]
Maybe I don't explain well.
I do not link against Cloudflare but directly against rsms.me

but it's more!
Your web page has the same problem, it takes more than 20 seconds to load the page.

If you think that I do not have the right to have a reasonable doubt, I accept it and I fully understand that my comment matters more to you than the problem that I expose.

**Comment by oantonioo** [comment]
I understand that you have no interest in solving it, I have already lost 4 hours to eliminate these styles in a dozen websites, tomorrow I will continue eliminating them.

Today you only see an ungrateful fool trying to help, others will not waste their valuable time.

Have a good week.
