### ISSUE TITLE
Bottom stroke for tabular /one

### ISSUE THREAD

**Issue by uvarov916** [rsms/inter#557]
We use tabular nums in our product and recently switched to Inter. After the change many users noticed that "1" looks weird since it has smaller width than other numbers and visually has more space around it. 

Our previous font and many other fonts use a variant of "1" with underline when tabular nums are enabled. Most of the monospace fonts also have underline in 1. With underline it looks wider and thus more balanced with other numbers. 

Can you add a variant of 1 with underline to Inter? 

![image](https://user-images.githubusercontent.com/5665700/232190471-3c7d012b-7018-4ac2-9e27-fc28b20d907c.png)

**Comment by rsms** [comment]
## Some WIP samples

Regular (wght=400 opsz=14):

![oaresnt82uei](https://user-images.githubusercontent.com/47046/232338066-ce8de183-b88b-4a70-9e61-f5fbd0e58ccc.png)

Display Regular (wght=400 opsz=32) and Regular (wght=400 opsz=14):

<img width="1089" alt="Screen Shot 2023-04-16 at 12 39 51" src="https://user-images.githubusercontent.com/47046/232338148-5e5df71b-3adb-4c62-a88b-bbb78f04655b.png">

Display Extra Light (wght=700 opsz=32) and Extra Light (wght=700 opsz=14):

<img width="876" alt="Screen Shot 2023-04-16 at 12 44 54" src="https://user-images.githubusercontent.com/47046/232338206-678908cc-d71b-4f80-9ebb-de25bced535d.png">

Display Bold (wght=200 opsz=32) and Bold (wght=200 opsz=14):

<img width="837" alt="Screen Shot 2023-04-16 at 12 45 58" src="https://user-images.githubusercontent.com/47046/232338261-b1f86623-6ecb-47f0-ab74-7c9b3c7c1a2e.png">

**Comment by rsms** [comment]
More examples (doing a full overhaul of tabular figures)

![inter-tnum](https://user-images.githubusercontent.com/47046/232347203-1e408dc0-b59b-41a7-b34e-d9a387e8781f.png)

![inter-tnum-text-sample srgb](https://user-images.githubusercontent.com/47046/232347473-324cf2cc-33ef-4ddd-8637-1cbeb2a371d0.png)
