### ISSUE TITLE
4k resolution legibility 

### ISSUE THREAD

**Issue by howdev** [rsms/inter#56]
At 4k resolution the Regular is thin and too tiring too read. Medium is thicker but letters are not clear like Apple's font medium. Can you improve to somewhere in between either to make a new font style or change Regular or Medium.

**Comment by rsms** [comment]
Please provide the following:
- technical/objective description of the issue (please refrain from filing issues based on personal taste)
- version of the font you're using
- type of font (OTF or TTF?)
- OS details and OS version
- what app(s) you're using to rasterize the font and their versions
- reproducible case, if possible, or state if you can't reproduce
- screenshots

**Comment by jonhue** [comment]
@howdev 

I find the legibility of the Regular font weight on a 4k resolution to be perfectly adequate. Perhaps you are running into some issue related with the program or OS you are using.
