### ISSUE TITLE
Issue with displaying Inter Display in Figma

### ISSUE THREAD

**Issue by andersdrage** [rsms/inter#561]
**Describe the bug**
The display weights of Inter are not showed in Figma. The other weights are showing fine. 
It looks as if I have not installed the display weights, but I have.

**To Reproduce**
1. Type text
2. Select font selector
3. Find Inter and try to choose the display weights

**Expected behavior**
Display weights are displayed in Figma, can be selected and used.

**Screenshots**
See attached screenshare

**Environment**
- OS: macOS 13.2.1
- App that renders the font: Illustrator and Photoshop
- Version of font : Version 4.000;git-4fc901f 

https://user-images.githubusercontent.com/3912208/233219183-995746e1-3fcf-4ae2-ae66-c5670f510376.mp4

**Comment by rsms** [comment]
What font files did you install? (exactly)

This is what I see in Figma if I install InterV.var.ttf & InterV-Italic.var.ttf in ~/Library/Fonts

<img width="224" alt="Screen Shot 2023-04-21 at 14 01 53" src="https://user-images.githubusercontent.com/47046/233734095-c1c533e6-1d9f-49c5-8912-341d7950a891.png">


Also, make sure you are not on a Figma Organization where someone uploaded Inter to the org — Figma then overrides any local fonts with the same name, with those uploaded to the org.

**Comment by rsms** [comment]
Ping

**Comment by rsms** [comment]
Been over a month w/o a reply. Happy to open up this again when we have an actionable repro

**Comment by andersdrage** [comment]
Sorry for going awol - I installed the variable font file as you mentioned and it worked. Previously I had installed the single font files and did not work - but I think the problem is on my end, something fishy with this Mac *smirk*.

Thanks for following up and apologies again for being slow.

**Comment by rsms** [comment]
Thanks for confirming
