### ISSUE TITLE
Inter Display: "ци" Looks Bad On Ultra-Bold and Heavy

### ISSUE THREAD

**Issue by EldarAgalarov** [rsms/inter#564]
**Describe the bug**
Cyrillic letter pair "ци" looks bad using Inter Display font with Ultra-Bold and Heavy weights (maybe kerning problems on thinner weights also persist).

**To Reproduce**
1. Open any editor, for example Inkscape and type following word: "Инвестиция";
2. Set font to Inter Display and weight to Heavy;
3. Feel the pain your inner perfectionist feels.

![image](https://user-images.githubusercontent.com/11322690/234725566-c1411ace-e6fb-490b-9deb-414754fcc913.png)

**Expected behavior**
I expect to see result how it looks using "standard" Inter (non-Display):
![image](https://user-images.githubusercontent.com/11322690/234073839-6350707b-7e07-4fe2-b944-ad88360f5370.png)
As you can see there is no kerning problems, at least at first look.

**Screenshots**
Unlike Inter, Inter Display have kerning problem. Letter pair "ци" - looks bad. There are almost no space between glyphs "ц" and "и":
![image](https://user-images.githubusercontent.com/11322690/234071937-e04caddd-75b8-484e-a7b3-e15ff1a3e925.png)

Letter pair "щи" - looks ok:
![image](https://user-images.githubusercontent.com/11322690/234072144-761c54f6-a592-4d65-967b-eadbe834c053.png)

**Environment**
- OS: Ubuntu 23.04
- App: Inkscape 1.2.2, GIMP 2.10.34
- Version of font: latest trunk built using Makefile

**Comment by rsms** [comment]
Please DO NOT discard [the issue template](https://github.com/rsms/inter/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) when filing an issue.

Update your issue by copy-pasting the following and filling out the details requested:

```
> Did you get the font from Google Fonts? Then please head over to
> https://github.com/google/fonts/issues
> and file an issue with Google Fonts.
> If not, REMOVE THIS PARAGRAPH BEFORE FILING YOUR ISSUE.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1.
2.
3.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment**
- OS: [e.g. macOS 10.14]
- App that renders the font [if applicable; e.g. Chrome, Adobe Illustrator]
- Version of font [e.g. "Inter Regular 3.0;8cf05e4a" — you can use fontdrop.info to find out the version]

**Additional context**
Add any other context about the problem here.
```

**Comment by EldarAgalarov** [comment]
Done, @rsms

**Comment by rsms** [comment]
Thank you!

**Comment by rsms** [comment]
Does this look better?

![after](https://user-images.githubusercontent.com/47046/234921081-83e5595d-a4ca-493b-934c-10bae5d1c58c.png)


Here's what it looked like yesterday:

![before](https://user-images.githubusercontent.com/47046/234921107-fb593804-18ff-4c8c-9f5f-a599e5947df5.png)

**Comment by EldarAgalarov** [comment]
Yes, it looks better now! To be consistent, kerning for "ц" and "щ" glyphs must be equals for all pairs and triples. But this is up to you of course :)

**Comment by rsms** [comment]
Thanks for confirming!

> To be consistent, kerning for "ц" and "щ" glyphs must be the same for all pairs and triples

They have identical spacing:

<img width="1049" alt="Screen Shot 2023-04-27 at 10 51 53" src="https://user-images.githubusercontent.com/47046/234950556-19ade70b-da00-43c7-82e1-807d5e18f338.png">
<img width="1170" alt="Screen Shot 2023-04-27 at 10 51 58" src="https://user-images.githubusercontent.com/47046/234950578-1d27b1dc-e3d0-4919-92f1-7f15e2ffb331.png">
