### ISSUE TITLE
Weird rendering of disambiguated capital `I`

### ISSUE THREAD

**Issue by dcastil** [rsms/inter#565]
**Describe the bug**

The disambiguated capital `I` has its stem poke over the top of the top horizontal line at smaller font sizes.

**To Reproduce**

1. Go to https://rsms.me/inter/lab/?feat-ss02=1&size=12
2. Zoom into the capital letter `I`

**Expected behavior**

The top of the letter should end with the top horizontal line instead of the stem.

**Screenshots**

Here it's at a font-size of 12px.

<img width="653" alt="Screenshot 2023-04-26 at 10 25 33" src="https://user-images.githubusercontent.com/31006608/234517158-d8eb4b23-c200-471c-9ef3-625a482797a3.png">

Here is an 1:1 size example (where we noticed it first)

<img width="173" alt="Screenshot 2023-04-26 at 10 27 38" src="https://user-images.githubusercontent.com/31006608/234517304-d58ff7a0-02ab-4ef5-b218-2cbde04bb9f7.png">

**Environment**

- OS: MacOS 13.3.1
- App that renders the font: Chrome
- Version of font:  3.19

**Comment by rsms** [comment]
Fixed in v4
