### ISSUE TITLE
Project: Improved Cyrillic design for v4

### ISSUE THREAD

**Issue by rsms** [rsms/inter#567]
The past few days I've done some work to improve Cyrillic for version 4. Doing so I realize the depth of knowledge needed to design really good Cyrillic glyphs is quite significant:

- There are local differences (e.g. Russian vs Bulgarian)
- Some glyphs have very fine margins in terms of stylistic freedom that makes it hard to induce the "Inter style" into them (e.g. Л)
- Wide diversity of quality and style in existing grotesks with Cyrillic (e.g. Helvetica Neue, Linotype 2019, uses a Latin K U+004B in place of К U+041A)

Here is a list of Cyrillic glyphs currently in Inter:

- CSV of codepoints and glyph names: [inter-cyrillic-glyphs.csv](https://github.com/rsms/inter/files/11375319/inter-cyrillic-glyphs.csv)
- PDF overview, roman: [Inter-roman-cyrillic.pdf](https://github.com/rsms/inter/files/11375194/Inter-roman-cyrillic.pdf)
- PDF overview, italic: [Inter-italic-cyrillic.pdf](https://github.com/rsms/inter/files/11375199/Inter-italic-cyrillic.pdf)

![inter-cyrillic-w400-o32](https://user-images.githubusercontent.com/47046/235720971-c22d82c9-722e-4fe2-bdc7-7526593092bb.png)

Here's a conversation tree with some interesting feedback, sources and ideas: [twitter.com/rsms/status/1653196861245898753](https://twitter.com/rsms/status/1653196861245898753)

Here's a handbook on the design of Inter. This is a good place to start, before changing or creating any glyphs: [Inter design program.pdf](https://d.rsms.me/stuff/Inter-design-program.pdf) (Alternatively [online as a Figma document](https://www.figma.com/community/file/1235373470096870126))

[![rsatulmyr8](https://user-images.githubusercontent.com/47046/235808575-4a599cd8-5550-4c3c-a7b2-4beac4e51474.png)](https://d.rsms.me/stuff/Inter-design-program.pdf)

**Comment by kenmcd** [comment]
Some useful critiques of some Cyrillic sans serif fonts...

**Cyrillic on Google Fonts: Humanist Sans**
https://type.today/en/journal/humanist

**Cyrillic on Google Fonts: Neo-Grotesques**
https://type.today/en/journal/neo

**Cyrillic on Google Fonts: Geometric Sans** 
https://type.today/en/journal/geo

Some pretty detailed examinations of letter shapes.
These are just the "sans" articles. Also two on serif fonts.

Another...
**The relatively easy way to find out the quality of a Cyrillic typeface**
https://leksandra.livejournal.com/115861.html
and
**How to understand Cyrillic**
https://info.paratype.com/how-to-understand-cyrillic/

**Comment by rsms** [comment]
New location of Alexandra's article "How to understand Cyrillic" https://info.paratype.com/how-to-understand-cyrillic/

**Comment by EldarAgalarov** [comment]
@rsms Uppercase and lowercase "И" glyphs are inconsistent. Green circle - looks ok, red - looks bad.

![image](https://user-images.githubusercontent.com/11322690/235888493-f20d2062-8aac-4b80-a02f-73a8b94d8a94.png)

**Comment by EldarAgalarov** [comment]
@rsms 
Lowercase "М" is not consistent compared to other glyphs with sharp corners. It has no cutted pieces:

![image](https://user-images.githubusercontent.com/11322690/235890963-abeb540d-d063-46c7-bac2-5fb83937e216.png)

**Comment by EldarAgalarov** [comment]
@rsms 
"Ж" and "К" glyphs looks bad. Better to redesign them following way:

![image](https://user-images.githubusercontent.com/11322690/235893784-5ff1435b-3293-4e64-a59c-8192c7786b95.png)

**Comment by EldarAgalarov** [comment]
@rsms isn't better to redesign "М" like this:

![image](https://user-images.githubusercontent.com/11322690/235901968-8f8a324d-a29f-4358-b9e4-bdbc7bb6f4b0.png)

**Comment by rastvortsev** [comment]
Hello Rasmus
Alexander Vilinskyy asked me to help you with Inter Cyrillic. 
I downloaded the sources  Inter-Roman and Inter-Italic from April 5 and will try to improve the Cyrillic alphabet.

**Comment by rastvortsev** [comment]
This may have happened after font scaling, but now the thickness of the stems in the Thin font is sometimes 48, and sometimes 46. It probably needs to be one of them. Which one do we leave / assign?
https://drive.google.com/drive/folders/1L3cCZyicR19mjAJLhaBHz1MPGTb8f4qQ?usp=share_link

**Comment by rsms** [comment]
(for the record, Dmytro and I had a conversation via email regarding some of the questions above)

**Comment by ravid-dubsteper** [comment]
how is the progress
🥺
👉👈

**Comment by Daymarius** [comment]
Is this the final version of cyrillic for v4? Some glyphs still don't look quite natural in v4.0.

**Comment by ravid-dubsteper** [comment]
![IMG_20231122_193959_228.jpg](https://github.com/rsms/inter/assets/78262241/e53d4756-5e47-4ef4-96f1-f0a77a4dcfb3)

**Comment by rsms** [comment]
See [Improvements to Cyrillic glyphs #696](https://github.com/rsms/inter/issues/696)
