### ISSUE TITLE
Default calt feature causes confusion between x and × and incorrect text display.

### ISSUE THREAD

**Issue by kepstin** [rsms/inter#571]
I'm opening an issue based on the [feedback I had over in the “What projects have you seen that use Inter?” discussion thread](https://github.com/rsms/inter/discussions/492#discussioncomment-5744130), after I noted that the version of Inter as used in Gitlab disables `calt`.

The biggest issue I have is with the vertical movement of the letter “x”, which causes it to be rendered incorrectly in some contexts, and be confusable with the multiplication sign “×”. The letter “x” should always remain firmly planted on the baseline.

An example of numbers written in hexadecimal:
![Screenshot 2023-05-11 at 12-00-06 11 57 — Thu May 11 2023](https://github.com/rsms/inter/assets/38788/ddbc80dd-fcbe-4e80-a74e-f8f52bb5b855)
Which should look like this:
![Screenshot 2023-05-11 at 12-01-15 11 57 — Thu May 11 2023](https://github.com/rsms/inter/assets/38788/d1ca1ccd-ad1c-4799-9b74-d87488662e2a)

An example of confusion between letter “x” and multiplication sign “×”:
![Screenshot 2023-05-11 at 12-03-00 11 57 — Thu May 11 2023](https://github.com/rsms/inter/assets/38788/d40ac1e1-589e-4c10-a80d-cd3e16f4ad1c)
<details>
<summary>Guess which one is the letter and which one is the multiplication sign! Ready? Click to open.</summary>

![Screenshot 2023-05-11 at 12-04-19 11 57 — Thu May 11 2023](https://github.com/rsms/inter/assets/38788/eca163d2-e047-4669-9cf5-27ad402f62cf)
The first one was the letter, the second was the multiplication sign.

</details>

Screenshots taken in Inter Lab on 2023-05-11.

**Comment by rsms** [comment]
Has been fixed and will be included in the next release

**Comment by kepstin** [comment]
Taking a look at https://github.com/rsms/inter/commit/e57491754ec76ecb492a4a56307e1b87fc899510 this doesn't actually seem solved?

There's some workarounds for the hexadecimal case specifically, but it still substitutes the multiplication sign in some (but not all) bits of text where it looks like multiplication, so the confusion between the letter x and multiplication sign remains.

**Comment by rsms** [comment]
I've heard from lots of people who find `3x3` → `3×3` useful, so I'm unlikely to remove that from `calt` (and I struggle to see when you would want 3x3 rather than 3×3) but your hexadecimal example is legit and has been "fixed."

**Comment by kepstin** [comment]
If someone wants the rendering “3×3”, they should be explicitly using a multiplication sign.

I guess an example is that I regularly assist people using ffmpeg in matrix chat channels. A lot of command-line options to ffmpeg take a display resolution as a string like “1920x1080”. In this case, the character in between the numbers must be a literal letter “x”, not a multiplication sign, and it's very confusing to have the letter x rendered with a different glyph.

**Comment by rsms** [comment]
> If someone wants the rendering “3×3”, they should be explicitly using a multiplication sign.

I agree, but in practice many people don't know this or don't know how to do it.
The same can be said for many other substitutions, like U+0308 U+0065 vs U+00EB (ë) or U+002D U+003E vs U+2192 (→). I choose to look at these things from a pragmatic lens rather than an academic one; adjust to how people behave, rather than trying to make people change their behavior.

> I guess an example is that I regularly assist people using ffmpeg in matrix chat channels. A lot of command-line options to ffmpeg take a display resolution as a string like “1920x1080”. In this case, the character in between the numbers must be a literal letter “x”, not a multiplication sign, and it's very confusing to have the letter x rendered with a different glyph.

Thanks for a concrete example!
The substitution does not affect the clipboard — when the user copies `1920x1080` (which looks like "1920×1080" on the screen) what is actually put on their clipboard is `1920x1080` (not `1920×1080`) so when they paste in a terminal the expected and correct thing happens (`x` not `×`)
