### ISSUE TITLE
String "7.5.2.2" looks bad with small text sizes: the "7.5" part looks bad, the "2.2" looks ok

### ISSUE THREAD

**Issue by EldarAgalarov** [rsms/inter#572]
**Describe the bug**
The string "7.5.2.2" looks bad on small text sizes: "7" and "5" visually are too close each other:

tiny size:
![image](https://github.com/rsms/inter/assets/11322690/e97112f8-5d92-4c2a-b134-15515cf2749b)

bigger size:
![image](https://github.com/rsms/inter/assets/11322690/cba1348b-c6a0-4ac8-b2e3-af163199657b)

**To Reproduce**
1. Pick Inter Regular font
2. Type "7.5.2.2"
3. Feel the pain

**Expected behavior**
"7" and "5" glyphs together visually must look like "2" and "2" glyphs together, i.e. - with wider spacing.

**Screenshots**
Loook above.

**Environment**
- OS: Ubuntu 23.04
- LibreOffice Writer 7.5.2.2
- Inter Regular Beta 7

**Comment by quiple** [comment]
<img width="50" alt="2023-05-12 125410" src="https://github.com/rsms/inter/assets/11014257/26c3d4da-7409-41ed-a5eb-569ab3cf3e28">

It may be a good choice for you to use tabular numbers...

**Comment by EldarAgalarov** [comment]
@quiple Look carefully. This is the version number of LibreOffice.

**Comment by rsms** [comment]
> <img alt="2023-05-12 125410" width="50" src="https://user-images.githubusercontent.com/11014257/237865477-26c3d4da-7409-41ed-a5eb-569ab3cf3e28.png">
> It may be a good choice for you to use tabular numbers...

I agree. What you’ll want @EldarAgalarov is to enable the tnum feature, which enables glyphs designed specifically for these purposes.

if you look at a few other high-quality fonts you’ll find that “7” and “.” are kerned a bit tight. Here’s an example from this very issue (Apple San Francisco Pro)

![IMG_3798](https://github.com/rsms/inter/assets/47046/510360c1-c128-4320-b4fc-438e9c5998e3)
