### ISSUE TITLE
Mismatching sterling and lira

### ISSUE THREAD

**Issue by cssobral2013** [rsms/inter#574]
**Describe the bug**
The sterling (U+A3) and lira (U+20A4) don't match

**To Reproduce**
1. Open, for example, Inter-Regular.ttf in FontForge

**Expected behavior**
The glyphs mentioned should be equal, except that sterling has one horizontal bar and lira, two

**Screenshots**
![Captura de tela_2023-05-27_20-07-01](https://github.com/rsms/inter/assets/19995437/68e5467d-f851-4fc6-a8ae-97c8f457c2b2)
![Captura de tela_2023-05-27_20-07-43](https://github.com/rsms/inter/assets/19995437/6b168168-2eff-471e-aab7-a6e466a70863)

**Environment**
This issue is displayed in v4.0-beta9 and earlier, and all apps and OSes, as this is a glyph issue

**Comment by rsms** [comment]
a2d84eb0eaacc1330ab1353d89e79c88c9716ecc

Roman: (text thin, text regular, text black, display thin, display regular, display black)
<img width="2079" alt="Screen Shot 2023-05-28 at 11 47 33" src="https://github.com/rsms/inter/assets/47046/7b2273c4-a55e-4cb3-8455-729d615bc6e0">
<img width="2078" alt="Screen Shot 2023-05-28 at 11 47 37" src="https://github.com/rsms/inter/assets/47046/90ff76ac-b3a2-475d-834c-8c826b9ad1f2">


Italic:
<img width="1742" alt="Screen Shot 2023-05-28 at 11 50 54" src="https://github.com/rsms/inter/assets/47046/edfbaf62-9b82-42e4-87e0-733f0b49159d">
<img width="1719" alt="Screen Shot 2023-05-28 at 11 50 50" src="https://github.com/rsms/inter/assets/47046/9f690cd8-2fb6-4fc3-88a3-2627d7a891de">
