### ISSUE TITLE
Changing font size to > 14pt and < 28pt in InDesign of Inter Variable forces style to Italic

### ISSUE THREAD

**Issue by acordy** [rsms/inter#578]
**Describe the bug**
Changing the font size to any value with the range of the optical size axis forces it into Italic.

**To Reproduce**
1. Ensure that "Map Optical Size to Font Size in Variable Font" is enabled in the InDesign preferences;
2. Create a text box and type in, for example, the letter "e";
3. In the "Character" panel, select "Inter Variable", "Regular", and enter a font size greater than 14pt and less than 28pt.

**Expected behavior**
Entering a font size that lies within the optical size range should not switch the font style from Regular to Italic.

**Screenshots**
![Inter-Style-Change-Screenshot-1](https://github.com/rsms/inter/assets/3484052/df8b439e-9570-4a2d-987f-d1e95fdec5a1)
![Inter-Style-Change-Screenshot-2](https://github.com/rsms/inter/assets/3484052/b2e590ea-d445-4e45-a733-5aaad1dfa266)

**Environment**
- macOS Ventura 13.3.1 (a)
- InDesign 18.3
- Inter Regular 4.000;git-3d3fc0c

**Additional context**
I should note that, once it switches to Italic, trying to set the style back to Regular forces the optical size to its upper limit of 28pt. So you are now left with, say, font size 21pt and optical size 28pt. Trying to now set the optical size to 21pt to match the font size forces it back to Italic.

So changes to the optical size, once the font size is within the range of 14-28, also forces Italic. What this means is that there is no way right now to have Inter Regular at say font size 21pt with a matching optical size of 21pt in InDesign. Since the issue described here relates to Italic being forced on updating the font size, and not the optical size, perhaps that should be a separate issue. Since they seemed related however, I have not done so, but would be happy to open a separate issue for that as well if that makes sense. First time contributing to this kind of project, so not sure...

In any case thanks for all the great work!

**Comment by rsms** [comment]
Woah, that’s a crazy bug. I can’t reproduce in other software (like macOS native or Figma) so guessing this is specific to InDesign (or most Adobe products.)

Can you please test with another VF that has an opsz axis, like Apple San Francisco Pro? (Free to use locally on macOS)

**Comment by acordy** [comment]
First off, thanks for looking into this; also I've followed the project for a while but never had an opportunity to comment on the incredible work you've done and put into this project. I deal with a lot of typography in my work, and Inter is a beautiful and well-designed typeface, so thank you for all the amazing work!

I have just commented on another issue that I have just tested with "SF Pro" on my machine, and it works as expected, and specifically as expected with regards to this issue as well. Changing font sizes for San Fransisco Pro does not force Regular to switch to Italic, whether set to font sizes within or without the optical size range of the axis.

Happy to test anything else or help in any other way I can. Thanks again for looking into it.

**Comment by acordy** [comment]
I just installed and tested an earlier version of the beta (Inter Variable Regular version 4.000;git-3c8e0fc, version 4.0-beta9 in Github, before versions "b" and "c"), and that version **does** work as expected: sizes 14pt and less render the regular version of Inter, and then a smooth interpolation to Inter Display on the optical axis between sizes 14pt and 32pt, and anything greater than size 32pt being rendered at the upper limit of optical size 32pt.

Of note:
- In this version the optical range is 14-32, and in the newest version it's 14-28;
- In Font Book, this earlier version is interpreted as having "36 styles", whereas the latest beta has "18 styles" in the styles column in the app.

Not sure if those observations are significant, but thought I'd point them out.

In any case, it looks like the issue appeared between versions 4.0-beta9 and  4.0-beta9b.

**Comment by rsms** [comment]
Conversation moved to #577 which is most likely the same cause
