### ISSUE TITLE
Without "Smooth edges of screen fonts" small Inter look jagged with uneven thickness

### ISSUE THREAD

**Issue by maa7** [rsms/inter#580]
Hello,
**Describe the bug**
For a number of reasons, I don't use font smoothing. When "Smooth edges of screen fonts" checkbox not enabled in Windows, small sized Inter (for example 12) look jagged with uneven thickness.

**Expected behavior**
Many fonts look good without anti-aliasing at small size (12), for example Arial, Century Gothic, Microsoft Sans Serif, Tahoma, Trebuchet MS, Verdana, PT Sans, Ubuntu, Averta, Avenir Next LT Pro, Informa Pro, Myriad Pro, Segoe UI, AmpleSoft Pro, Corbel, Dopis, FS Albert Pro, Lintel, Montserrat, Neuron Angled, Normative Pro, PF Adamant Sans Pro, TT Interphases Pro, Univia Pro Book, and so on.
It would be great if the Inter font also displayed well without anti-aliasing.

**Screenshots**
Look at 100 or 200 percent:
![inter12compare](https://github.com/rsms/inter/assets/45234995/c3ab4e83-95e0-415c-9bf4-28e8fc77cd12)

**Environment**
- OS: Windows 7
- App that renders the font: Word, Chrome
- Version of font: Inter Regular 3.19 Hinted for Windows

**Comment by rsms** [comment]
This is unfortunately not something Inter aims to support. Anyhow, what makes it work (or not) is good TrueType hints. Inter uses ttfautohint which does a best guess.

Can you please try the new upcoming version 4? https://github.com/rsms/inter/releases/tag/v4.0-beta9d

**Comment by maa7** [comment]
Unfortunately, there are no improvements in version 4:
**Screenshots**
Look at 100 or 200 percent:
![interv4_12compare](https://github.com/rsms/inter/assets/45234995/e11c4822-60a7-46e0-9a13-00ac718b813c)

**Comment by vitorsr** [comment]
The option `--windows-compatibility, -W` is not going have any effect here [1].

This is a font design issue having to do with stems’ widths here being close to 2 dx at 12 pt/16 ppem and glyphs’ misalignments with respect to the discretized grid which makes it less amenable to TrueType autohinting.

![Screenshot 2023-06-14 172740](https://github.com/rsms/inter/assets/40741601/81fcd658-6f3d-459c-821b-c54e2dd75efc)

Here I recommend you to use _hinted_ PostScript outlines.

![Screenshot 2023-06-14 154306](https://github.com/rsms/inter/assets/40741601/e95160a1-a32c-4fd8-b84f-6d4b97ff4b29)

![Screenshot 2023-06-14 154510](https://github.com/rsms/inter/assets/40741601/0daadc99-d5e2-42a6-b4bf-5e208ca0c770)

[1] https://freetype.org/ttfautohint/doc/ttfautohint.html#windows-compatibility

**Comment by rsms** [comment]
psautohint adds a lot of data to the font files:

```shell
$ ls Inter-Medium*.otf
561k Inter-Medium-psautohint.otf
273k Inter-Medium.otf
```

Additionally, I'm not sure about support for CFF curves in web browsers (ie when encoded as woff2.)

**Comment by rsms** [comment]
Re ttfautohint, @vitorsr do you know if there's a way to "tell it" about the stems? Maybe via `--stem-width-mode` or `--fallback-stem-width`..?

**Comment by rsms** [comment]
For what it's worth, Apple's shaper/renderer produces almost exactly the same results with CFF (w/ psautohint) and TT (w/ ttfautohint):

![psautohint-v-ttfautohint](https://github.com/rsms/inter/assets/47046/bbaedb54-c05e-4e5a-aad5-4bdf6f22a0d7)

(AFAIK macOS doesn't do any shape-shifting, only uses hints for grid fitting during rasterization.)

**Comment by maa7** [comment]
Looks like the macOS rasterizer doesn't use hinting https://glyphsapp.com/learn/hinting-truetype-autohinting#g-testing

**Comment by rsms** [comment]
> Looks like the macOS rasterizer doesn't use hinting https://glyphsapp.com/learn/hinting-truetype-autohinting#g-testing

That's right, no shape-shifting but I think it uses hinting data for grid fitting since it renders a little differently depending on hints available (as seen above)

**Comment by rsms** [comment]
I've spent the morning in Microsoft VTT (which might be the least ergonomic, most painful-to-use UI ever?) Anyhow, I've tested three different autohint flavors:

- VTTs autohinter (Tools → AutoHint → Light Latin AutoHint)
- ttfautohint (version 1.8.4.7-5d5b) with default settings (`--stem-width-mode=qsq`)
- ttfautohint with `--stem-width-mode=qqq`

Four rendering modes: (VTT → Display → General Options → ...)

- ClearType (with subpixel AA for standard LCD arrangement)
- ClearType Grey
- Grey Scale
- Binary (1-bit)

Here are comprehensive screenshots of all combinations:

<img width="1907" alt="inter-59350f46f208-vtt-ClearType" src="https://github.com/rsms/inter/assets/47046/228b70c9-45e5-49e3-a4e2-31fecd10b89c">

<img width="1908" alt="inter-59350f46f208-vtt-ClearType-Grey" src="https://github.com/rsms/inter/assets/47046/dee13f97-2cb5-4ebc-97c0-ec4370bd6f46">

<img width="1906" alt="inter-59350f46f208-vtt-Binary" src="https://github.com/rsms/inter/assets/47046/4a211629-e0a1-402f-b100-f8b625a35f65">

<img width="1907" alt="inter-59350f46f208-vtt-Grey-Scale" src="https://github.com/rsms/inter/assets/47046/bb3bf3b3-9613-42a3-ae7a-38d7d3d870c0">

All but the binary (1-bit) rendering looks acceptable to me.

Here's a comparison of the three different hinting techniques, rendered in "ClearType" mode:

<img width="1859" alt="cleartype" src="https://github.com/rsms/inter/assets/47046/21659b26-e59c-4d75-8513-f3d745db1309">

**Comment by rsms** [comment]
I've put together an interactive thing for testing rendering in web browsers: https://rsms.me/etc/inter4-hint-test/

Here's what 12px looks like in Chrome on macOS:

<img width="1066" alt="Screen Shot 2023-06-17 at 13 05 02" src="https://github.com/rsms/inter/assets/47046/83e82591-6d50-43b5-9c67-b71fe2c78c60">

Chrome on Windows 10: (can't seem to disable anti-aliasing on Windows)

<img width="1056" alt="Screen Shot 2023-06-17 at 13 05 51" src="https://github.com/rsms/inter/assets/47046/c6fc4a9b-4f0e-4d8f-a6df-5ab2229738ed">

**Comment by maa7** [comment]
Windows 7 (smoothing off), Chrome, 16px (12pt):
![inter_hinting](https://github.com/rsms/inter/assets/45234995/5c8899a9-792a-44d0-b0ca-a8c816cf33b9)
psautohint looks the best

**Comment by maa7** [comment]
As I see it in the description of the [ttfautohint](http://freetype.org/ttfautohint/#works):
_"The auto-hinter no longer tries to provide good hinting for monochrome rasterization. Instead, it expects anti-aliasing with 256 gray levels"_
This may explain the poor result in mode without smoothing.
Can you add to the test page truetype fonts auto-hinted by other software?

**Comment by vitorsr** [comment]
@rsms, I will give you some precise and thorough feedback when I get the chance. I would love to clarify some things regarding hinting.

**Comment by rsms** [comment]
> Can you add to the test page truetype fonts auto-hinted by other software?

What other software do you have in mind?

**Comment by vitorsr** [comment]
I am not sure that he or she appreciates that there is not exactly an abundance of autohinting software.

**Comment by maa7** [comment]
Thank you!
Now that the small size font looks good without anti-aliasing, could you add a 'gasp' table to turn anti-aliasing off for sizes from 8 to 16 ppem?
I'm not sure if this table works for OTF, but maybe you can still find an TTF autohinter with a similar quality.

**Comment by maa7** [comment]
and is it possible to add information about hinting to the font version string? (for eample "Version 4.0 with hinting")

**Comment by AchillesBoi** [comment]
> For a number of reasons, I don't use font smoothing.

Can you provide one? I can't think of any good reason to not take advantage of modern font technologies and I think it's unfair to expect modern fonts to support older, much worse font display techniques. All fonts looks abysmal without antialiasing.

**Comment by maa7** [comment]
_>>Can you provide one?_
Fonts without smoothing look the most crisp. Fonts with smoothing look blurry.

_>>I can't think of any good reason to not take advantage of modern font technologies_
Font smoothing is not modern technology, but a crutch trying to hide the lack of pixel density of monitors.

_>>All fonts looks abysmal without antialiasing._
Well hinted fonts look good.
