### ISSUE TITLE
Superscript and subscript in Display styles still has design features of text styles

### ISSUE THREAD

**Issue by TaigaYamada** [rsms/inter#581]
**Describe the bug**
In the latest 4.0 beta (4.0-beta9f), superscript and subscript in Display styles still has design features of text styles.
Most obviously, they have angular stroke terminals.

**To Reproduce**
1. Open any app that renders text
2. Set the font to Inter Variable and set the optical size to maximum (28)
3. Type in a sequence of characters that includes superscript and subscript, like "ᵗt aₐ eᵉ"

**Expected behavior**
Letter shapes for superscript and subscript should reflect the display style design features too, such as stroke terminals being angled at 90 degrees.

**Screenshots**
![image](https://github.com/rsms/inter/assets/77144664/b4ac9646-cf7c-46f0-bf67-ecc911e3abed)

**Environment**
- OS: Windows 11
- Adobe Illustrator 27.5 (Latest at the time of the report)
- Inter 4.0-beta9f

**Comment by rsms** [comment]
I think it will have to remain so for version 4.0 or it might never ship :-P
