### ISSUE TITLE
usWeightClass in statics and variable - Beta 4

### ISSUE THREAD

**Issue by kenmcd** [rsms/inter#583]
While checking the beta static fonts you posted yesterday 
`Inter-4.0-d88ab4204a.zip (2023-06-08)`
I noticed the `usWeightClass` on some of the fonts looks like the designspace location/coordinates rather than the weight class values.
So I also checked the variable and it appears to be the same.
My understanding is that these are important especially for the variable web fonts which are setting these values in CSS.
Think there is even a FontBakery test for this.

SemiBold = 580 - should be 600
Bold = 660 - should be 700
ExtraBold = 780 - should be 800

GF discusses mapping these here:
https://googlefonts.github.io/gf-guide/variable.html#the-axis-mapping
Apparently it can be done in Glyphs or the `.designspace` file.

I think this is an issue which must be addressed for GF inclusion.
But not 100% sure.
Just so you are aware this may need addressing before final.

Sorry I cannot be much help on fixing this.
Would take me about five minutes in FontLab.
But have no idea in Glyphs or this build format.

**Comment by rsms** [comment]
After 2c652cfc9a3bfcec99d255ca1a6b860a29487179:

```
Inter-Black.ttf      "usWeightClass": 900,
Inter-Bold.ttf       "usWeightClass": 700,
Inter-ExtraBold.ttf  "usWeightClass": 800,
Inter-ExtraLight.ttf "usWeightClass": 200,
Inter-Light.ttf      "usWeightClass": 300,
Inter-Medium.ttf     "usWeightClass": 500,
Inter-Regular.ttf    "usWeightClass": 400,
Inter-SemiBold.ttf   "usWeightClass": 600,
Inter-Thin.ttf       "usWeightClass": 100,
```

(From `for f in build/fonts/static/Inter*.ttf; do; printf '%s ' $(basename $f); python misc/tools/fontinfo.py -pretty $f | grep 'usWeightClass"'; done`)

**Comment by kenmcd** [comment]
Did this not make it into the last beta?
Inter-4.0-b7ed03d0e2.zip (2023-06-11)
Because all those fonts still have the:
SemiBold = 580
Bold = 660
ExtraBold = 780

Will check the next full beta.

**Comment by rsms** [comment]
Seems correct on my end. Where and how do you see these values?

This is what I see (and how I see it):

```shell
$ for f in Inter-{SemiBold,Bold,ExtraBold}.ttf; do \
  ttx -i -f -s -t OS/2 $f &&
  grep usWeightClass $(basename $f .ttf).O_S_2f_2.ttx; done
Dumping "Inter-SemiBold.ttf" to "Inter-SemiBold.ttx"...
Dumping 'OS/2' table...
    <usWeightClass value="600"/>
Dumping "Inter-Bold.ttf" to "Inter-Bold.ttx"...
Dumping 'OS/2' table...
    <usWeightClass value="700"/>
Dumping "Inter-ExtraBold.ttf" to "Inter-ExtraBold.ttx"...
Dumping 'OS/2' table...
    <usWeightClass value="800"/>
```

**Comment by stpnkcrk** [comment]
@rsms Not sure if it's related to this, but I can still see these values in the inter.css file.

https://github.com/rsms/inter/blob/master/misc/dist/inter.css#L35-L40
https://github.com/rsms/inter/blob/master/misc/dist/inter.css#L53-L58

**Comment by kenmcd** [comment]
> Seems correct on my end. Where and how do you see these values?
> 
> This is what I see (and how I see it): ([v4.0-beta9g](https://github.com/rsms/inter/releases/tag/v4.0-beta9g))

I guess was looking at one of the ZIPs from the same day (with the fixed names).
Inter-4.0-b7ed03d0e2.zip (2023-06-11) - fonts say 4:03 PM
Your link above...
Inter-4.0-beta9g.zip (2023-06-11) - fonts say 11:33 PM
So I checked all these... and they look great.

So closing this. 
Hmmm... I do not have close button available.

**Comment by rsms** [comment]
> @rsms Not sure if it's related to this, but I can still see these values in the inter.css file.
> 
> https://github.com/rsms/inter/blob/master/misc/dist/inter.css#L35-L40 https://github.com/rsms/inter/blob/master/misc/dist/inter.css#L53-L58

Unrelated, but I should fix that! Thanks @stpnkcrk

**Comment by stpnkcrk** [comment]
@rsms I know it's a minor thing, but is there any chance of you releasing another beta with this fix, please?

**Comment by rsms** [comment]
https://github.com/rsms/inter/releases/tag/v4.0-beta9h
