### ISSUE TITLE
Oblique style for version 4

### ISSUE THREAD

**Issue by MattMayuga** [rsms/inter#586]
![image](https://github.com/rsms/inter/assets/26103475/2671be1a-bedd-4461-b3b2-fb79357b4f89)

Basically this is the italic style, except it doesn't diverge from the upright "roman" design (no true italic designs) and is simply a slanted version of the upright design similar to Inter version 3.

In case you didn't know, there is a font called Lucida Sans, which has italic (true italic) and oblique (no true italic) variants. The oblique variant would be a nice addition to Inter, as it can serve as an alternative to the italic version. As for the variable font files, there should be one roman, one oblique and one italic; all with wght and opsz axes.

**Comment by TaigaYamada** [comment]
I'm guessing the content is essentially #582?

**Comment by MattMayuga** [comment]
> I'm guessing the content is essentially #582?

Actually, what I'm requesting is a new oblique style, not an OpenType feature.

**Comment by rsms** [comment]
Merged into → #582

**Comment by rsms** [comment]
> Actually, what I'm requesting is a new oblique style, not an OpenType feature.

This will definitely not happen.

But let's consider a Stylistic Set for the Italic font with oblique letterforms. That way you can simply opt in to an "oblique style" by just turning on e.g. ss05. For scenarios where there's no way to control OpenType features, there's always [OpenType Feature Freezer](https://twardoch.github.io/fonttools-opentype-feature-freezer/)
