### ISSUE TITLE
I have issues downloading the ZIP file containing the released fonts.

### ISSUE THREAD

**Issue by rvy-2017** [rsms/inter#59]
While downloading it through Chrome or Chromium, the download freezes at 0 bytes per second and then fails. This is despite me being able to achieve nearly 5 MB/s on a separate download. Are there any other places you can consider for hosting the file? I believe that this may be related to Amazon's Web service though, judging from what I can see with the download URL. I'll try downloading another time and may raise this again if the issue persists.
Immediately after attempting to re-download, a Forbidden error is shown on my browser.
I've only been able to completely download this file through my mobile data. It seems to me that the issue comes from my ISP.

**Comment by rsms** [comment]
This seems like a github issue, or more likely an issue with your router or isp. (The zip file is served by github, not by anything relating to this project.)
