### ISSUE TITLE
Inter Beta9g – Light / Thin weighted numbers seem squezed...

### ISSUE THREAD

**Issue by Gabre-Rod** [rsms/inter#590]
Inter is perhaps the best display font I've seen. This first paragraph is dedicated to thank RSMS for his effort. I have never been happier seeing the evolution of this font, even in the most minute details.

### One Small Issue
The thin version of the numbers in version Beta9g seem too squashed together, and that doesn't happen with the letters at all (thats another thing that made me happy when I noticed the improvement on thin weights).

Maybe this already has been addressed and if so correct me. Here's a quick comparison I made on Inkscape along with a suggestion at the bottom:

<img width="800" alt="Inter Numbers" src="https://github.com/rsms/inter/assets/83919515/6d23be7f-6edf-43b8-8465-fea18b9d1aa1">

**Comment by kenmcd** [comment]
The default Optical Size (`opsz`) should probably be 14, not 28.
That would make the figures spacing similar to Inter v3.19 Thin.
So the old width and spacing is still available.
You just have to set the `opsz` to 14.
 
Inter 4 Beta9g has the default optical size set to the upper limit which is somewhat unusual.
The range is 14-28, with the default set at 28.
The most common `opsz` default setting in Google Fonts variable fonts is 14.
Which is very common for text fonts (12, or 14).
But some interface fonts are different (and some display fonts).

Apple System Font variable
Optical Size (opsz)
Default: 28
Range: 17-96

Microsoft Segoe UI variable
Optical Size (opsz)
Default: 10.5
Range: 5-36

@rsms 
What do you think about making the `opsz` default 14?
This would make the default visually closer to the old v3.19 fonts.
And prevent a lot of user shock and questions (like this).

**Comment by rsms** [comment]
@kenmcd as always, thank you for your thoughtful comment! As another example, Apple SF Pro uses the display value of opsz by default. My reasoning is that when software “fails” to set opsz according to actual optical size it’s better to show the display designs which are simpler (doesn’t have a bunch of tricks for small-scale legibility.) But really, I could go either way with default opsz.

Anyhow, I think @Gabre-Rod might be intentionally using a large opsz and that is fine. Perhaps the display design’s digits actually do need to be revisited. I drew those years back when there was a separate “Inter Display” font and did a relatively brief review of them a few months ago. The thin weight display digits did not have dedicated designs until recently and are based on the text design, which is a bit condensed for the thin weights. I’ll look into this when I find time!

**Comment by kenmcd** [comment]
> As another example, Apple SF Pro uses the display value of opsz by default. My reasoning is that when software “fails” to set opsz according to actual optical size it’s better to show the display designs which are simpler (doesn’t have a bunch of tricks for small-scale legibility.) But really, I could go either way with default opsz.

Keep in mind that with the Apple fonts the opsz is usually controlled automatically by the API. With the old SF Pro statics the API automatically switched to the display fonts at 21pt (IIRC). Have not checked but I assume the newer variable System Font is doing something similar automatically. So the 28 default is not really going to be used. And the primary use is on devices, not the web.

Same with Segoe UI Variable - the API automatically handles the opsz.

Inter on the other hand is also used a lot on the web, and in documents, as well as in devices. I would even guess much more on web and docs than in devices. And there is no automatic handling of the opsz. So this new default opsz is going to be a bit of a shock in those situations. Users changing from the current statics to the new variable are going to wonder what happened. The new default should be the same as the old default. 

As aways, up to you, but ya got my opinion. :-)

**Comment by rsms** [comment]
> I’ll look into this when I find time!

Did a quick review (at my office now) and indeed the thin+display designs (roman & italic) of digits needs to be widened. They are essentially identical to the thin+text designs.

**Comment by kenmcd** [comment]
Another thought... 
Google Fonts requires the default opsz to be text size - have to find it, but it is something like 10 to 14.
And the basic static text fonts should match the basic variable instances.
So for GF you are stuck with those requirements.

I do hope you continue to have more advanced VF fonts here in the repo. With more instances which are far more useful for applications which currently only support named instances (such as LibreOffice, etc.).

**Comment by rsms** [comment]
I've created a separate dedicated issue to do this work for the next release of Inter: https://github.com/rsms/inter/issues/608
