### ISSUE TITLE
Request: Square-shaped punctuation and accents

### ISSUE THREAD

**Issue by matchavez** [rsms/inter#591]
### Square pips

As an Inter user, I'd like to have an option that provides square pips instead of round ones. This could be for just the `i` and `j`, but I would prefer an option to use them on punctuation as well; particularly `,.;:'"`

**Comment by Gabre-Rod** [comment]
Inter is so neutral and aiming to be universal, that it will likely fit in perfectly. Specially for the thin designs were it's more difficult to see the rounded dots, so replacing them with squared punctuation that slowly converts into lines as the weight decreases is a benefit for designers.

But the default is still going to be rounded shapes. This was suggested already, I believe... Hopefully rsms can revisit this concept.

(At least for the display version)

**Comment by rsms** [comment]
Merge issue with #178

**Comment by rsms** [comment]
https://github.com/rsms/inter/issues/178#issuecomment-1738307384
