### ISSUE TITLE
Inter Beta9g - Italic small s's in all non-Display styles seem broken

### ISSUE THREAD

**Issue by Scratchbin** [rsms/inter#593]
Seems most of the glyphs of its small s in non-Display styles are broken:

![Inter's Sus Small S](https://github.com/rsms/inter/assets/29145652/3f30d73e-6ec7-4b10-ab7f-5ec1b52cf33d)

Then I checked them in FontForge and saw that they have not just a terminal but two, by extra corners and curves that seemingly should not exist. Seems all glyphs (except Display's styles) of the small s could be not co-ordinated (while the Black Italic one seems less bad).

- Version of font: 4.0-beta9g

**Comment by rsms** [comment]
Yup, same issue, which was fixed in a2665d00158ac52bbfc62e5d650dd721f0ceede9 (and will be included in the next release)
