### ISSUE TITLE
Tabular numbers not monospaced in Black, Bold and Medium

### ISSUE THREAD

**Issue by vladmoroz** [rsms/inter#60]
Tabular numbers are of variable width in Black, Bold and Medium:

![Black](https://user-images.githubusercontent.com/8441036/42393482-2e731af6-815f-11e8-841c-9f87c653a60b.png)
![Bold](https://user-images.githubusercontent.com/8441036/42393507-441bae86-815f-11e8-87fa-b31f4549a5d6.png)
![Medium](https://user-images.githubusercontent.com/8441036/42393522-4f4f5d16-815f-11e8-9447-2e296e360bf6.png)

Regular weight is not affected by this issue.

P.S: I love Inter UI, thank you so much for making it. I'm using it a lot and I believe it's one of the best open source fonts out there. I wish I could contribute, but I have little experience with type design and tooling.

**Comment by rsms** [comment]
Yikes!

**Comment by rsms** [comment]
<img width="923" alt="fix-tnum" src="https://user-images.githubusercontent.com/47046/44762938-c4ccbd00-aafd-11e8-809c-462352868143.png">

**Comment by rsms** [comment]
Also covers stylistic alternates #1 and slashed zero:

<img width="416" alt="screen shot 2018-08-28 at 20 09 08" src="https://user-images.githubusercontent.com/47046/44763060-4b819a00-aafe-11e8-91c0-28982fdce03c.png">

<img width="414" alt="screen shot 2018-08-28 at 20 09 16" src="https://user-images.githubusercontent.com/47046/44763063-4d4b5d80-aafe-11e8-84ef-5a44653ec11b.png">
