### ISSUE TITLE
Bad hints in Inter Display on Firefox in Arch Linux

### ISSUE THREAD

**Issue by alosarjos** [rsms/inter#606]
**Describe the bug**
The height of some characters is inconsistent.

**To Reproduce**
1. Use Inter Display as System Font
2. Open Firefox and go to Settings

**Screenshots**
Using Inter Display: 

![Captura desde 2023-08-17 17-28-19](https://github.com/rsms/inter/assets/29999427/65a11fa0-c686-4151-8d14-d922bdf514b7)

**Environment**
- OS: Arch Linux
- App that renders the font: Firefox
- Version of font: Inter Display from [4.0-beta9h](https://github.com/rsms/inter/releases/tag/v4.0-beta9h)

**Additional context**
Hi there. First of all thanks for the font, it's really great! Now... I'm not sure if it's a font or a Firefox issue, I'm looking for some guidance. Thing is, I had Inter font installed on Arch for months, probably using the [Inter Display beta 2](https://github.com/rsms/inter/releases/tag/display-beta-2) or [4.0-beta1](https://github.com/rsms/inter/releases/tag/v4.0-beta1). I checked yesterday to see there where some new versions and I updated. Now Inter Display on Firefox makes some character heights kind of inconsistent

**Comment by rsms** [comment]
Here's another related issue which was the cause for introducing some changes to hinting: https://github.com/rsms/inter/issues/580#issuecomment-1595848206

**Comment by alosarjos** [comment]
@rsms Not sure about the Shape Shifting setting. Or how could I've enabled it.

I installed the TTF in the `/extras/ttf` dir inside the ZIP  Inter-4.0-beta9h.zip downloaded from the releases page.

(https://github.com/rsms/inter/releases/tag/v4.0-beta9h)

I installed them on /usr/share/fonts/inter as system fonts

**Comment by alosarjos** [comment]
To be honest, I it was a bit weird at first but I think I prefer regular Inter to Display, everything is kinda more legible.
I started using the Display variant for the system because there was a bug on Gnome using the regular Inter that made elements not fit correctly (Reported [here](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6024)) but now seems to be working nice (Not sure if something fixed on the Gnome side or the font)

**Comment by rsms** [comment]
Inter Display is designed for large sizes (the “Display” in the name.) For smaller text you’ll definitely want to use “Inter.” When using the variable font it’s automatic, but when using the traditional static font files you have to manually select the appropriate font for the font size.

**Comment by rsms** [comment]
@alosarjos Here's a new build for you with a different ttfautohint setting. Please try this and let me know if it looks correct: 
[Inter-4.0-fe75d3a2cc-ttf-only.zip](https://github.com/rsms/inter/files/12467632/Inter-4.0-fe75d3a2cc-ttf-only.zip)

**Comment by rsms** [comment]
@alosarjos Here's another variant to test, which uses a different reference font. Please test "Inter Display" the way you have it in your original issue. Thank you!

[Inter-4.0-fe75d3a2cc-ttf-only-qqq.zip](https://github.com/rsms/inter/files/12467672/Inter-4.0-fe75d3a2cc-ttf-only-qqq.zip)

**Comment by alosarjos** [comment]
First variant: 

![Captura desde 2023-08-29 20-00-20](https://github.com/rsms/inter/assets/29999427/e722a1fc-3070-4574-9c6d-cfec03a5cfef)

Second variant:
![Captura desde 2023-08-29 20-02-49](https://github.com/rsms/inter/assets/29999427/4d6b01f6-69a5-4a41-948c-2237f90cc1b8)

Looks like the second one (The qqq) fixes it

**Comment by rsms** [comment]
Lovely! Thank you for your help!

**Comment by AchillesBoi** [comment]
> Ah, you have shape shifting enabled in your (presumably) FreeType-based font render. It's usually pretty bad (only Microsoft's implementation is decent, at best) and I recommend disabling it.

Just to add more information, the latest beta of Inter Display 4.0 (using the .ttc font) has these issues in both Linux AND Windows, so even ClearType doesn't know how to render them properly. I don't have screenshots right now since I'm at work (using Linux) but I can tell you for sure that this issue is present in non-FreeType font renderers too.

I'm glad it's been addressed because I was close to opening an issue report for the same thing.
