### ISSUE TITLE
Revised design of Display Thin digits

### ISSUE THREAD

**Issue by rsms** [rsms/inter#608]
The thin display designs (roman & italic) of digits needs to be widened. They are essentially identical to the thin+text designs.

_Originally posted by @rsms in https://github.com/rsms/inter/issues/590#issuecomment-1634414926_

**Comment by Gabre-Rod** [comment]
Lets go!

**Comment by Gabre-Rod** [comment]
Also @rsms would you like me to do a video showcasing the inter font family and it's evolution? Similar to an ad? It could get people invested.

**Comment by piypatil07** [comment]
hii

**Comment by rsms** [comment]
Before/after:
![123](https://github.com/rsms/inter/assets/47046/d13f91fd-633f-4af0-a16a-1f15d3582c95)

Waterfall: (after)
![123-waterfal](https://github.com/rsms/inter/assets/47046/b9d3dcdd-0f19-42a1-bfef-f06e7a88f8bd)

**Comment by Gabre-Rod** [comment]
Congrats rsms! Looking foward to the next release!
