### ISSUE TITLE
Request: `0` like DIN 1451 and Manrope

### ISSUE THREAD

**Issue by pkj-l** [rsms/inter#609]
I like this typeface and I’d like to see `0` like _DIN 1451_ and _Manrope_.
### DIN 1451
![DIN 1451](https://github.com/rsms/inter/assets/43498546/e6cd7fd9-59ec-4a53-a146-aab6c2c8f49d)
### Manrope
![Manrope](https://github.com/rsms/inter/assets/43498546/4d82beb3-50d2-4f17-9cb2-67a3f0fb7567)
Thanks.

**Comment by rsms** [comment]
Not the style of Inter. Sorry
