### ISSUE TITLE
Tabular nums incorrect on Chrome / Ubuntu

### ISSUE THREAD

**Issue by devkat** [rsms/inter#611]
**Describe the bug**

Tabular numbers are not working On Chrome on Ubuntu (Jammy Jellyfish). Does not occur with Firefox on the same OS.

Not sure if this can be remedied in the font, or if it is a bug in Chrome / Ubuntu.

Unfortunately this OS/browser combination is used by Playwright; the issue affects some of our tests.

**To Reproduce**
1. Use the variable font (woff2) with `font-feature-settings: 'tnum'`
2. The digits are rendered with different widths, depending on the font size (see screenshot)

**Expected behavior**
All digits should be rendered with the same width.

**Screenshots**
![tnum](https://github.com/rsms/inter/assets/1734637/4597ca7b-32a9-4248-8e91-6ec3b1d3eaad)

**Environment**
- OS: Ubuntu Jammy Jellyfish
- Chrome 117.0.5938.62 (also happens with older versions)
- Inter 4.0 beta 9h (variable font, woff2)

**Comment by devkat** [comment]
Setting `font-render-hinting=none` in Playwright seems to fix the issue:

```
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        launchOptions: { args: ['--font-render-hinting=none'] },
      },
    },
  ],
```

**Comment by rsms** [comment]
@devkat did you figure out why setting font-render-hinting=none fixed the issue?

**Comment by devkat** [comment]
> @devkat did you figure out why setting font-render-hinting=none fixed the issue?

Unfortunately not, and unfortunately the change causes inconsistent rendering of another font (Source Code Pro).

**Comment by rsms** [comment]
> **Describe the bug**
> 
> Tabular numbers are not working On Chrome on Ubuntu (Jammy Jellyfish). Does not occur with Firefox on the same OS.
> 
> Not sure if this can be remedied in the font, or if it is a bug in Chrome / Ubuntu.
> 
> Unfortunately this OS/browser combination is used by Playwright; the issue affects some of our tests.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Use the variable font (woff2) with `font-feature-settings: 'tnum'`
> 2. The digits are rendered with different widths, depending on the font size (see screenshot)
> 
> **Expected behavior** All digits should be rendered with the same width.
> 
> **Screenshots** ![tnum](https://user-images.githubusercontent.com/1734637/269885853-4597ca7b-32a9-4248-8e91-6ec3b1d3eaad.png)
> 
> **Environment**
> 
> * OS: Ubuntu Jammy Jellyfish
> * Chrome 117.0.5938.62 (also happens with older versions)
> * Inter 4.0 beta 9h (variable font, woff2)

Can you please share the exact HTML that reproduces this so I can test?
