### ISSUE TITLE
The tail of the `y` in Inter v4 is unnatural

### ISSUE THREAD

**Issue by quiple** [rsms/inter#619]
**Describe the bug**
The tail of the `y` in Inter v4 is unnatural.

**Expected behavior**
I understand that it needs to fit with Inter's design language, but the current version seems too rigid to me. I'd like to see a little more curvature in the tail of the `y`.

What do you think?

**Screenshots**
![0](https://github.com/rsms/inter/assets/11014257/9b69c61b-f69f-4de4-89f8-5ae47af0763a)

Screenshots of `y` in Inter v4, Helvetica Neue and SF Pro.

**Comment by Gabre-Rod** [comment]
Fits well for Bold typefaces

**Comment by rsms** [comment]
By design
