### ISSUE TITLE
Issue with drachma sign (₯)

### ISSUE THREAD

**Issue by quiple** [rsms/inter#621]
**Describe the bug**
There is an issue with the outline of the drachma sign.

**Screenshots**
<img width="1280" alt="Screenshot 2023-10-19 112720" src="https://github.com/rsms/inter/assets/11014257/5b3885e8-be76-4068-9ee7-8c9805f8c4a4">

**Comment by rsms** [comment]
After bfb90448adab373b99183bc6a66a56ebec48f648:

![drachma](https://github.com/rsms/inter/assets/47046/603c863a-1bf7-4823-8623-387dbd97840f)
