### ISSUE TITLE
Weird shapes of Greek Capital/Small Reversed Lunate Sigma Symbol (U+03FD, U+037B)

### ISSUE THREAD

**Issue by quiple** [rsms/inter#622]
**Describe the bug**
The Greek Capital/Small Reversed Lunate Sigma Symbol (U+037B, U+03FD) has weird shapes.

**Screenshots**
![Inter-Variable---U+03FD](https://github.com/rsms/inter/assets/11014257/8ef4d1cc-5f44-43ae-a7eb-43423e9b511d) ![Inter-Variable---U+037B](https://github.com/rsms/inter/assets/11014257/f8b1ce7b-844d-4c40-840b-ea65b4f3c124)

GIFs comparing with Greek Capital/Small Reversed "Dotted" Lunate Sigma Symbol (U+03FF, U+037D).

Similarly, a GIF comparing the same glyphs in the Segoe UI.

![Segoe-UI-Variable---U+03FD](https://github.com/rsms/inter/assets/11014257/cb437384-6a75-4326-86f4-27550cf158fd) ![Segoe-UI-Variable---U+037B](https://github.com/rsms/inter/assets/11014257/f385b549-a113-4e82-b8cf-a89fc6cec866)

**Comment by rsms** [comment]
<img width="585" alt="lksidufl" src="https://github.com/rsms/inter/assets/47046/b06eeb02-a7a9-404b-9490-491384c77720">
