### ISSUE TITLE
Font indicates it supports small-caps, but doesn’t

### ISSUE THREAD

**Issue by SixFingeredAmish** [rsms/inter#63]
I use CSS to check for small caps support. The problem is, Inter UI seems to indicate that it does support small caps but doesn't.

Steps to reproduce:

Put something inside this rule. It shouldn’t activate, but it does.

`@supports not (font-feature-settings: 'smcp') {
}
`

Thanks!

**Comment by vladmoroz** [comment]
It has nothing to do with the font you are using, be it Inter UI or Times New Roman. `@supports` is used to test whether your browser supports a particular property, not a font.

In this case you will get exactly the same results with any font.
