### ISSUE TITLE
Capital Ghe is defective with stroke and/or descender in Italic only

### ISSUE THREAD

**Issue by cssobral2013** [rsms/inter#636]
**Describe the bug**
The glyphs Ghedescender, Ghestroke, and Ghestrokedescender are defective in Italic only

**To Reproduce**
Open Inter Italic variable font with, eg, Fontlab 8, and navigate through glyphs till you find the aforementioned glyphs

**Expected behavior**
The stroke and descender should be perfectly attached to Ghe-cyrl

**Screenshots**
![20231119_234447.jpg](https://github.com/rsms/inter/assets/19995437/96f7769d-ccc5-4195-bbc7-dc1ef4422d61)

**Environment**
- Every app and OS
- Version 4.0 and earlier versions

**Comment by kenmcd** [comment]
/Gehookstrokecyr/Gestrokecyr/Getailcyr

**Comment by rsms** [comment]
Thanks for catching this issue. Here's what it looks like after the fix, which will be included in the next release:

<img width="887" alt="oisdjf8h92jk" src="https://github.com/rsms/inter/assets/47046/54b232a9-c4f4-4c41-8e1c-5eee054c695b">
