### ISSUE TITLE
v4: 'frac' feature put all number into exponent

### ISSUE THREAD

**Issue by Bibalox** [rsms/inter#639]
**Describe the bug**
When applying the 'frac' feature, all the numbers are visually impacted.

**To Reproduce**
Activate the 'frac' feature with the css property 'font-feature-settings'.

**Expected behavior**
Only the number surrounding the '/' character must be concerned by the feature.

**Comment by Bibalox** [comment]
The issue can also easily be reproduced into the rsms.me lab

**Comment by markfcim** [comment]
I to am having this issue. All numbers have been visually impacted.

**Comment by aetinx** [comment]
+1

**Comment by KunalTanwar** [comment]
+1

**Comment by rsms** [comment]
After 5e4c3fa9640d7a7088d1a7440283cdf24ff8b4bd:

![frac2](https://github.com/rsms/inter/assets/47046/03d5f7ea-e6bb-4c50-afe8-457679de7fca)
