### ISSUE TITLE
Left and right bearing anomaly of number 5 along axis 'opsz'

### ISSUE THREAD

**Issue by quiple** [rsms/inter#641]
**Describe the bug**
The variation of the left and right bearings along the axis 'opsz' of the number 5 does not look consistent. The bolder the weight, the more prominent it appears. Other numbers, like 3 or 8, look fine.

**Screenshots**
![Screenshot-2023-11-22-at-10-00-22-Inter-font-family](https://github.com/rsms/inter/assets/11014257/c72c419c-eef4-4038-9f23-2cac0fa4bb12)
![Screenshot 2023-11-22 at 10-12-38 10 06 — Wed Nov 22 2023](https://github.com/rsms/inter/assets/11014257/99277258-04a4-49a2-a64f-441eb4ebfdaa)
![Screenshot 2023-11-22 at 10-12-38 10 06 — Wed Nov 22 20232](https://github.com/rsms/inter/assets/11014257/a53737bd-38d2-49a7-a4ef-5922c2799f66)

**Additional context**
I checked this out at https://rsms.me/inter/#glyphs and https://rsms.me/inter/lab/.

**Comment by rsms** [comment]
![](https://github.com/rsms/inter/assets/47046/3e10e324-20b7-431d-a143-93c9f28ec7a1)
