### ISSUE TITLE
Left and right bearing anomaly of some tabular numbers

### ISSUE THREAD

**Issue by quiple** [rsms/inter#642]
**Describe the bug**
The tabular number 3 looks biased to the left at 'opsz' 14, and the tabular number 5 looks biased to the left at 'opsz' 32.

The flat-top 3 appears to have the same problem.

**Screenshots**
![Screenshot 2023-11-22 at 10-48-25 10 38 — Wed Nov 22 20232](https://github.com/rsms/inter/assets/11014257/403496ef-3b8c-40c6-a8a1-e55aba6fb0c8)
![Screenshot 2023-11-22 at 10-48-25 10 38 — Wed Nov 22 2023](https://github.com/rsms/inter/assets/11014257/82d48ef3-d14e-4810-a457-a32b75c81c05)

**Additional context**
I checked this out at https://rsms.me/inter/#glyphs and https://rsms.me/inter/lab/.

**Comment by rsms** [comment]
Before 73509f5273fc8971363d4af60b0bb415beafe735:

![Tabular figures 1](https://github.com/rsms/inter/assets/47046/584cf92c-3309-4554-9f0a-ac77a916616b)

After 73509f5273fc8971363d4af60b0bb415beafe735:

![Tabular figures 2](https://github.com/rsms/inter/assets/47046/f4418dda-38fa-4e9b-bf8b-f302a79b18d7)
