### ISSUE TITLE
strange spacing when used on a terminal

### ISSUE THREAD

**Issue by jbrodriguez** [rsms/inter#643]
**Describe the bug**
there are extra spaces between characters, when used in a terminal app (iTerm2)

**To Reproduce**
1. set text to Inter (tried Inter Display too)
2. check terminal, characters are wrongly spaced

**Expected behavior**
should display correctly

**Screenshots**
![Screenshot 2023-11-22 at 14 24 08](https://github.com/rsms/inter/assets/1305422/40261c9a-b024-42a1-b1f5-e06b0994e4db)

**Environment**
- OS: macOS Sonoma 14.1.1
- App that renders the font: iTerm2
- Version of font: Inter Regular 4.000;git-a52131595 

**Additional context**
this doesn't happen when setting the font in an editor such as zed (haven't tried vscode)

**Comment by rben01** [comment]
I think this is up to your terminal; Inter is not a monospaced font, but your terminal might force it to be rendered as one.

**Comment by jbrodriguez** [comment]
makes sense, thanks for the awesome font ! i use it in my websites 👍
