### ISSUE TITLE
Hinted web font files missing from 4.0 release zip

### ISSUE THREAD

**Issue by philipbelesky** [rsms/inter#654]
Hi! Thanks to everyone who worked towards the 4.0 release, it looks great.

In the Github release for 4.0 the `extras/woff-hinted` file is empty. I'm looking to update the npm distribution to 4.0 and it would be great to include the hinted files — unfortunately I'm not experienced enough with font design tooling to be able to generate them myself from source.

**Comment by rsms** [comment]
Thanks for catching this
