### ISSUE TITLE
indistinguishable letters

### ISSUE THREAD

**Issue by howdev** [rsms/inter#66]
Illiterate, the word cannot distinguish  the first 3 letters. This is same complaint for Helvetica, a font long before Inter UI. And you are copying this mistake and claim to be legible

**Comment by rsms** [comment]
I'm sorry, but I will close this as it seems you're simply complaining, not reporting an actual issue.

And please, read through https://github.com/rsms/inter/blob/master/CODE_OF_CONDUCT.md#our-standards

**Comment by bunk3m** [comment]
While I agree that @howdev 's comment could have been written a bit nicer, the issue still remains.  

In Inter 2.5 the capital "I" and lower case "L" look identical.  Other than reading for context, you can't visually tell the difference.

I have read that the capital "I" is usually slightly less high than the lower case "L".

Perhaps this from Quora might help?
https://www.quora.com/How-do-you-differentiate-I-and-l-upper-case-I-and-lower-case-L?share=1

**Comment by howdev** [comment]
@rsms you simply cannot accept the truth and to received it as a complaint. You claimed your font to be highly legible with obvious mistake as a font designer and that mistake have that exist long before. You did copy the mistake. Which part I said is false? Good conduct you have to close the bug and reject the truth.

Your statement  below
"Inter UI is a typeface specially designed for user interfaces with focus on high legibility of small-to-medium sized text on computer screens."

**Comment by brianespinosa** [comment]
@howdev this is a **free open source** project. If you have a proposal on how to improve it, submit your proposal. What you submitted was not a proposal. It was a complaint about the current implementation with no proposal or suggestion on how to resolve the issue or what in your opinion would resolve the issue.

I don't understand how people come into a project that is provided free of charge that the community builds and complain about what is provided. If you are using the project and feel like you could improve it, add something constructive.

**Comment by howdev** [comment]
@brianespinosa Open Source have community of developers of the project that investigate and fix bugs reported by users. Therefore, users do not have to submit proposals they are not developers. You received the bug as a complaint because something you don't like to hear. You go and see more of the Open Source project bugs reports especially bug reports of desktop environments what real complaint is. 
No where I reported bugs that are closed without investigating, that is much worse than commercial software developers.

**Comment by howdev** [comment]
@brianespinosa something you missed also? you need to be in github to report any bugs, therefore people who report bugs don't come into the project

**Comment by brianespinosa** [comment]
@howdev people like you make working on open source projects not worth it. I am here to solve your problem though! Since commercial software developers are much better than open source ones, I'd suggest you go purchase a font to use for your project from a font foundry that better fits your needs. In the meantime, I hope you get a full refund on all the money you paid for Inter.

For the record, I have not yet committed any work to Inter. I just use the font in some of my projects and I appreciate the work of @rsms and everyone else who has contributed.

**Comment by rsms** [comment]
Thank you for chiming in @brianespinosa. @howdev this is in fact a tool for reporting bugs and propose changes. There is no customer support. If you are experiencing an issue, please provide objective materials supporting and describing the issue. If you’re here to propose a change you’re even able to do so via a Pull Request! Isn’t GitHub fantastic?!
Now, as I mentioned earlier, you really have to stick to the community guidelines. Please try to be nice and provide constructive feedback and concrete suggestions for improvements.

**Comment by rsms** [comment]
Locking this conversation.
If you do feel strongly about the lower-case L, please open a new issue and describe the problem in an objective fashion as well as provide any suggestions for improvements.
