### ISSUE TITLE
"a," "g," and "e" fonts downloaded from the website are not the same as seen on the website

### ISSUE THREAD

**Issue by Mythbusters123** [rsms/inter#661]
**Describe the bug**
While on the website, the "a" "g" and "e" glyphs have straight edges. At the end of the leg of the "g," the top hand of the "a" and the opening of the "e." I just downloaded Inter 4.0 from its release and it does not match up with the website. This is with the Windows standard font viewer.

**To Reproduce**
1. Observe Inter font on the [website](https://rsms.me/inter)
2. Download font from website
3. Observe differences between Inter.ttc and Inter on the website

**Expected behavior**
I expected both fonts to look the same.

**Screenshots**
![Inter font downloaded on Windows](https://github.com/rsms/inter/assets/58893124/279b6fc7-73be-426f-a1e9-ac924fddc212)
![Inter font on website](https://github.com/rsms/inter/assets/58893124/44a2744f-12c3-42bd-85a7-c8711a3bbf82)

**Environment**
- OS: Windows 11 22H2 (OS Build 22621.2861), However I have also tested this on Linux and the issue persists
- App that renders the font: Windows font viewer
- Version of font: 4.000;git-a52131595

**Comment by kenmcd** [comment]
It appears you are comparing the normal font on the website to a Display font in the TTC.
The TTC file has 36 fonts in it - 18 normal and 18 Display.
Look in the "extras" folder of the release ZIP for the individual font files (same ones as in the TTC).
Compare those individual files.
