### ISSUE TITLE
v4: kerning for "written" looks wrong for some reason

### ISSUE THREAD

**Issue by miragecraft** [rsms/inter#666]
Edit: this issue was originally about the kerning between "tt" being too tight, but after testing I'm no longer sure and gave up because I'm not that knowledgeable about font design.

**Describe the bug**
Under v4, the word "written" looks wrong for some reason, initially I thought it's because the kerning between "tt" was too tight, but after testing words like "little" I realized increasing the kerning between "tt" might not be the answer.

**To Reproduce**
1. Display the word "written" with Inter v4
4. Kerning between "tt" feels way too tight, or is the kerning between "ri" too loose? I can't tell anymore. 

**Expected behavior**
More natural looking kerning.

**Screenshots**
![image](https://github.com/rsms/inter/assets/1615599/3dfabbff-4850-48f7-9549-b7acb9966995)

**Environment**
- OS: Win10
- Firefox
- Inter Variable. Version 4.000;git-a52131595

**Comment by TaigaYamada** [comment]
"tt" is discretionary ligature. If the kerning there feels too tight, you might want to try turning them off?

**Comment by miragecraft** [comment]
> "tt" is discretionary ligature. If the kerning there feels too tight, you might want to try turning them off?

It's already off, discretionary ligature is off by default.

Do you mean turning them on? If I turn it on it disconnects "tt" so it looks less tight, but I don't like its effects in other instances, such as how "fi" gets fused together.

**Comment by TaigaYamada** [comment]
Oh, since "tt" is one of the possible combinations replaced by discretionary ligatures, I thought the reason for them being connected in your image was discretionary ligatures.

I thought Inter's "tt" was disconnected by default. My bad

**Comment by miragecraft** [comment]
No problem, I've done some more comparison with v3 and it looks like both "tt" and "ff" are much tighter than before.

I very much dislike the change, things like "writte", "little", "ruffle" etc. looks overly compressed in the middle.

**Comment by kenmcd** [comment]
The `tt` is probably too tight.
If you compare it to the Apple variable System Font or to the Microsoft Segoe UI Variable it looks tight by comparison.
And the `ut` in `About` also looks tight.

**Comment by rsms** [comment]
> The `tt` is probably too tight.

Agreed

**Comment by rsms** [comment]
This looks better, right?

<img width="729" alt="" src="https://github.com/rsms/inter/assets/47046/b62eb369-2b29-4042-a633-8b91b173c715">

**Comment by rsms** [comment]
After 1703fcda04c3e132499bdb020d125cf0d5f478f8:

![](https://github.com/rsms/inter/assets/47046/0e4b0ab9-2d29-4ac3-a631-0581a024bbda)
