### ISSUE TITLE
Inter v4.0 no longer contains ɪ (U+026A Latin Letter Small Capital I)

### ISSUE THREAD

**Issue by iliana** [rsms/inter#668]
**Describe the bug**
Inter v3.19 contains ɪ (U+026A Latin Letter Small Capital I), used to represent the [near-close near-front unrounded vowel](https://en.wikipedia.org/wiki/Near-close_near-front_unrounded_vowel) in the International Phonetic Alphabet. Inter v4.0 no longer contains this character.

**To Reproduce**
1. Type `/ɪliˈɑnə ɛˈtiːn/` at https://rsms.me/inter/lab/
2. Notice the substituted character; become sad

**Expected behavior**
Render the above IPA string with no substituted characters.

**Screenshots**
Wakamai Fondue (beta), in the font tester after uploading `InterVariable.ttf` from Inter-4.0.zip:
![image](https://github.com/rsms/inter/assets/52814/d71f61b4-4426-4364-a417-279c18fcd717)

**Environment**
- OS: macOS 13.6.3
- App that renders the font: Firefox
- Version of font: Version 4.000;git-a52131595

**Additional context**
N/A

**Comment by rsms** [comment]
After 1f6ea592a8e70c4a2007e8a35ce8dfb04851d486:

![](https://github.com/rsms/inter/assets/47046/2cd235fc-d6d7-435d-9193-8d873b54c8be)
