### ISSUE TITLE
Improvements to Hungarian diacritics

### ISSUE THREAD

**Issue by kra-mo** [rsms/inter#676]
Diacritics with forward leaning double lines (so ő, ű) are hard to distinguish from their dotted variants (so ö, ü).

Hungarian uses both of these so this can be an issue. Making the accent marks longer would probably be the best solution.

They are also not aligned properly. They are aligned from the bottom of the accents to the horizontal center, but in handwriting (as well as many fonts), they are aligned from the vertical middle, which feels much more natural.

Here are Liberation Serif and Noto Sans as examples of what I would perceive as natural alignment:

![image](https://github.com/rsms/inter/assets/93832451/cfd6d818-96f0-4ccc-831d-b403bde755cf)

![image](https://github.com/rsms/inter/assets/93832451/fe14202e-fbcd-47b8-b3ca-da6cf9acf82d)

And Inter in contrast:

![image](https://github.com/rsms/inter/assets/93832451/217eb597-bfa6-44ab-b4e5-8e067204f884)

**Comment by rsms** [comment]
After 4069128d64d362fefa037573a863bf1b90061c96:

![](https://github.com/rsms/inter/assets/47046/c7800a5d-d851-4580-bee6-128b6fb5ceba)
