### ISSUE TITLE
Non-variable font file builds not compiled properly

### ISSUE THREAD

**Issue by Pogimon3** [rsms/inter#677]
**Describe the bug**
The static font files in the latest release (v4) are not in line with the glyphs at rsms.me/inter. This is only an issue for the static font files for Inter and not for Inter Display. The variable font file seems to be perfectly in line with the glyphs at rsm.me/inter. 

**To Reproduce**
Steps to reproduce the behaviour:
1.  Open any of the static files for Inter 4 (for example Inter-Regular.otf) using Font Book on Mac. 
2. Compare the lower case 't' as displayed on the install screen of Font Book with the lower case 't' at [rsms.me/inter](https://rsms.me/inter/)

**Expected behaviour**
The lower case 't' should match the ones in the variable file and the ones at [rsms.me/inter](https://rsms.me/inter/)

** Screenshots**

Here's how the lower case 't' should look: 
<img width="125" alt="Screenshot 2024-02-02 at 12 21 40 AM" src="https://github.com/rsms/inter/assets/140201901/e7da304b-f75b-408f-a780-7ae64450bcd0">

Here's how it actually looks upon opening with Font Book on Mac:
<img width="125" alt="Screenshot 2024-02-02 at 12 20 55 AM" src="https://github.com/rsms/inter/assets/140201901/acd66a67-55ad-40dc-8aa4-de7c94ba86ef">

**Environment**
- MacOs Sonoma 14.2.1
- Version of font : Inter 4.0

**Comment by kenmcd** [comment]
The default "text" optical size is 14 - with the curve.
The "display" optical size is 32 - straighter tail.

![2024-02-01_13-48-54](https://github.com/rsms/inter/assets/844920/931929eb-d526-4d7f-a5dc-402b749d63ca)

Not an issue with the font.

**Comment by Pogimon3** [comment]
Understood and thanks a lot! Apologies, I am a newbie to typefaces. 

Correct me if I am wrong but this my understanding now: 

- flat tail = 'display version', better for large displays (higher optical size)
- curved tail = 'text version', better for other use cases (lower optical size)
- if you don't specify optical size in css, then it's set to 'auto' by default and the variable font will render as the most optimal version based on the font size and device resolution/ppi/browser/viewport etc.
