### ISSUE TITLE
Misalignment of bulletpoints when using inline

### ISSUE THREAD

**Issue by annaschumacher** [rsms/inter#679]
**Describe the bug**
While using both the Inter and Inter Variable fonts, I encountered an alignment issue with bullet points when attempting to conceal a portion of a phone number. When using the bullet points (option+8) to obscure digits like ••••••••787, I noticed that the alignment of the first few bullet points deviates from the rest. This inconsistency occurs only when there are 5 or more bullet points, and the subsequent characters are numeric.

Is this misalignment intentional for the Inter font, or is it a bug that can be addressed?

**To Reproduce**
1. Use either the Inter or Inter Variable font in e.g. Figma or a code editor
2. Attempt to mask a portion of a phone number using bullet points (••••••••787) (option+8, not the option+shift+9).

**Expected behavior**
The bullet points should maintain consistent alignment regardless of the number of characters or the type of characters following them.

**Actual result**
The first few bullet points are misaligned when followed by numeric characters after 5 or more bullet points.

**Screenshots**
<img width="773" alt="Screenshot 2024-02-14 at 11 02 43" src="https://github.com/rsms/inter/assets/50320060/9be095f3-a329-4961-88ae-bca3e844631b">
<img width="921" alt="Screenshot 2024-02-14 at 11 02 56" src="https://github.com/rsms/inter/assets/50320060/0f54c6b9-7219-4d90-9e82-f4e1ef89fae9">
<img width="1193" alt="Screenshot 2024-02-14 at 11 03 17" src="https://github.com/rsms/inter/assets/50320060/6de049c5-16b6-4714-a4a9-52150810a53f">

**Environment**
- OS: macOS 13.0 (Ventura)
- App that renders the font: Figma, Chrome, Arc
- Version of font: Inter Variable. Version 4.000;git-a52131595

**Additional context**
- This issue persists across different platforms; I observed it both in Figma and in cod/browser (Chrome, Arc).
- No similar alignment issues occur when using other fonts.

**Comment by kenmcd** [comment]
This is by design. 
Disable the OpenType Contextual Alternates (`calt`) feature to stop this.

See: https://github.com/rsms/inter/issues/442 and https://github.com/rsms/inter/issues/594 for similar issues.
