### ISSUE TITLE
init.sh won't run

### ISSUE THREAD

**Issue by vladmoroz** [rsms/inter#68]
Here's what I get when running init.sh

```
$ ./init.sh
$ Fetching https://download.savannah.gnu.org/releases/freetype/ttfautohint-1.8.2-tty-osx.tar.gz
$ Warning: Remote filename has no length!
$ curl: (23) Failed writing body (0 != 16139)
```

How do I fix this?

**Comment by rsms** [comment]
Please provide macOS version and the output of running `curl -I https://download.savannah.gnu.org/releases/freetype/ttfautohint-1.8.2-tty-osx.tar.gz`

It seems you are having trouble transferring data from download.savannah.gnu.org — the init.sh script simply runs curl to fetch that file, and curl is failing for you for some reason. Can you fetch other HTTP resources using curl?

I'll close this for now as this is 99% certain to be an issue on your end with curl and not the way the init.sh script is setup. Let me know if this is not the case and we can reopen this issue :–)

**Comment by vladmoroz** [comment]
Here's the output of `curl -I https://download.savannah.gnu.org/releases/freetype/ttfautohint-1.8.2-tty-osx.tar.gz`

```
HTTP/1.1 302 Moved Temporarily
Server: nginx/1.4.6 (Trisquel GNU/Linux)
Date: Mon, 24 Sep 2018 16:00:01 GMT
Connection: keep-alive
Location: https://quantum-mirror.hu/mirrors/pub/gnusavannah/freetype/ttfautohint-1.8.2-tty-osx.tar.gz
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
```

macOS version 10.13.6
`curl` works in my day-to-day as expected
