### ISSUE TITLE
A better shape of ƅ (U+0185)

### ISSUE THREAD

**Issue by Studyrat** [rsms/inter#680]
**Describe the bug**
It seems that the glyph of U+0185 has some mistake. Compared with "Times New Roman" and "Arial", maybe the "triangle" is in a wrong place.

**To Reproduce**
Redesign the glyph.

**Expected behavior**
See figure 2 in "Screenshots".

**Screenshots**
![old](https://github.com/rsms/inter/assets/100198924/b03596d7-9f12-400e-9c12-7b304294767a)
Figure 1: Original

![new](https://github.com/rsms/inter/assets/100198924/ec2d73a1-0333-44f9-bc67-3560424c67ad)
Figure 2: Expected

**Comment by moyogo** [comment]
This character has had its representative glyphs changed in the Unicode charts. The more accurate shape is like Ь ь, most often with an oblique upwards serif on the top left. So your expected glyph shape should be changed.

See:
- https://www.unicode.org/L2/L2021/21083-tone-six-glyphs.pdf
- https://www.unicode.org/charts/PDF/Unicode-14.0/U140-0180.pdf

**Comment by rsms** [comment]
Thank you @moyogo for the insight. Here's what /Tonesix and /tonesix looks like after 75b6c13e2f5906bb4157e82539b3ccbd89181b8b:

![](https://github.com/rsms/inter/assets/47046/53db9fa9-4151-4e11-8d01-52e34877115b)
