### ISSUE TITLE
Capital letters showing as "Squared Latin Capital" variants on some sites

### ISSUE THREAD

**Issue by poopsicles** [rsms/inter#681]
**Describe the bug**
On a few sites -- I can't remember a lot of them, but one is https://cider.sh -- when Inter is the default font (on my machine, "BlinkMacSystemFont" is aliased to Inter), capital letters are shown as their "Squared Latin Capital" variants.

**To Reproduce**
1. Open up https://cider.sh in a browser,
2. Right-click on "Listening to music" and click "Inspect" (or whatever your browser equivalent is).
3. Filter the styles by "font-family".
4. Make the text use Inter as its font by modifying the CSS attribute for the line (it should have "Satoshi" at the beginning by default) and adding "Inter" as the first font.

**Expected behavior**
The font on the page should simply become Inter, without any boxes.

**Screenshots**

Here's the site showing Inter:

![image](https://github.com/rsms/inter/assets/87488715/52402ad6-e71d-496d-8a9a-3cb2cb8b7b2e)

And it with Segoe UI:

![image](https://github.com/rsms/inter/assets/87488715/9dbb582a-b3f1-4448-864e-18acedfabf87)

Inter showing normally in GNOME Fonts:

![image](https://github.com/rsms/inter/assets/87488715/4f8023b4-aac8-4b12-97b8-3931732fa5dc)

**Environment**
- OS: Fedora Workstation 39 (GNOME 45.4, Linux 6.7.4-200.fc39.x86_64)
- App that renders the font: Firefox Nightly 124.0a1, Google Chrome 121.0.6167.184
- Version of font: Inter 4.000;git-a52131595

**Additional context**
My entire interface's font is Inter (thanks Rasmus!) and this only pops in a very tiny number of sites (I've come across it once or twice). At first I thought it might be my emoji acting up (I use Apple Color Emoji on here) but after tweaking my `.config/fontconfig/fonts.conf` for an hour or so I decided to play around with the devtools and voilà...

Luckily I have Chrome on here too, so it's not isolated to just a beta build of Firefox -- so I think at this point it's either the font itself, or something with how GNOME renders fonts? (not sure)

I've asked some friends on Windows and Mac to help me check it out and I'll update this issue if I get any more info.

**Comment by rsms** [comment]
Happens because that website has enabled OpenType feature ss06, which in Inter converts some glyphs to square framed glyphs.

<img width="1191" alt="Screen Shot 2024-03-25 at 17 20 56" src="https://github.com/rsms/inter/assets/47046/4ee216fd-3c5a-45ac-90bc-4d11f0c3f434">

**Comment by ardasevinc** [comment]
affected: swr.vercel.app, dns.sb
