### ISSUE TITLE
Pipe (vertical bar) character "|" should not be italicized/slanted.

### ISSUE THREAD

**Issue by miragecraft** [rsms/inter#684]
The pipe character "|" is by design vertical and should not be slanted ever.

**Comment by rsms** [comment]
I don’t agree with that.
In the future, please follow the issue template (don’t just erase it and write one sentence.)

**Comment by miragecraft** [comment]
> I don’t agree with that. In the future, please follow the issue template (don’t just erase it and write one sentence.)

Sorry about that, will do next time.
