### ISSUE TITLE
[Request] Horizontal touching Q (like Univers) as alternate for titling

### ISSUE THREAD

**Issue by cssobral2013** [rsms/inter#685]
**Additional context**
- Maybe... crossing or horizontal touching?
- It is good for titling, specially in all caps.

**Comment by OthoXYZ** [comment]
Would it work better if it was more like Univers or Helvetica (that is, do you still want a diagonal or just a horizontal)?

**Comment by cssobral2013** [comment]
@OthoXYZ - I'd, personally, prefer horizontal touching (Univers-like).
