### ISSUE TITLE
Inter Variable font weights don't render properly

### ISSUE THREAD

**Issue by michaelkremenetsky** [rsms/inter#686]
**Describe the bug**
On Inter 4, WebKit browsers other than Safari on MacOS seem not to be able to render the font-weight properly and end up rendering the fonts bolder than they are supposed to be. This doesn't happen if I use Inter 3.

**To Reproduce**
You can see it in production at refeedreader.com if you look at the "Refeed" text on Safari Mobile.

**Expected behavior**
Font Weight to render properly

**Screenshots**
Chrome:
![image](https://github.com/rsms/inter/assets/28833521/dc07626d-723b-4d56-b339-aa83e7eb2007)
![image](https://github.com/rsms/inter/assets/28833521/8aac3961-092f-44cd-ab68-add769454ccb)

WebKit-based browsers (Tested in Safari Mobile and GNOME Web):
![image](https://github.com/rsms/inter/assets/28833521/4498bf51-9072-4d8d-88d8-45cc46eaf908)
![image](https://github.com/rsms/inter/assets/28833521/7266fd71-8d29-4090-8c8c-32d94ef6b7cc)

**Environment**
- OS: Arch Linux
- GNOME Web, Safari Mobile
- Inter Variable

**Additional context**
I'm using it like this on nextjs if it matters:
```tsx
const inter = localFont({
  src: "../../public/InterVariable.woff2",
  variable: "--font-inter",
  preload: true,
  display: "swap",
});
```

**Comment by rsms** [comment]
I’m 99% certain that it is an issue with your font renderer. Disable sub-pixel anti-aliasing (what’s going on is SPAA that is post-processed to greyscale, which should never be done but happens for complicated reasons on the pages.

Think about it this way: if the same font looks correct in one app but not the other, the difference must be in how the apps render the font, not an issue with the font.

**Comment by pacocoursey** [comment]
@michaelkremenetsky You should specify `weight: 100 900` in the Next.js `localFont({})` block. It looks like Next.js doesn't include it by default, which leads to Safari/WebKit making some strange choices around rendering.

**Comment by michaelkremenetsky** [comment]
@pacocoursey Thank you so much this fixed it!

**Comment by ArnaudBarre** [comment]
Thank you so much @pacocoursey!
