### ISSUE TITLE
Tweak the interrobang (U+203d) glyph

### ISSUE THREAD

**Issue by kaushalmodi** [rsms/inter#69]
Wow, your font is beautiful! I recently learned about it from [here][2].

I might switch to it as the default font on my blog! 

I love interrobangs (‽). Can you please tweak its design so that the exclamation and question mark components of that unicode are not superimposed strictly vertically? (I like the fact that in the version in Inter UI, the ! is not intersecting ? -- which happens in almost all sans serif fonts.. making that glyph look like a typo!). 

For example, the interrobang in **Iosevka** ([specimens][1] - U+203d) is creatively designed; it's distinguishable, and also doesn't look like a typewriter typo. 

Thanks!

[1]: https://be5invis.github.io/Iosevka/specimen.html
[2]: https://tildes.net/~comp/66u/what_is_are_your_go_to_system_fonts#comment-1ru8

**Comment by rsms** [comment]
[Reference: Interrobang of Iosevka]
<img width="400" alt="screen shot 2018-09-17 at 09 18 18" src="https://user-images.githubusercontent.com/47046/45635762-b7e71d80-ba5a-11e8-95d1-596be557ed12.png">

**Comment by rsms** [comment]
BTW, have you seen this @kaushalmodi 
https://www.netflix.com/watch/80243761

**Comment by kaushalmodi** [comment]
@rsms Thanks for categorizing this as an enhancement.

> have you seen this @kaushalmodi https://www.netflix.com/watch/80243761

I have not seen that (didn't know of that "Explained" series).. adding that to my Watch List :)

I got hooked onto interrobangs after I listened to the [99% Invisible podcast episode - Interrobangs][1]. That led me to buy the [Shady Characters book][2] (which has the most delightful typography that I have seen in print). I am reading through it right now.

So, while I cannot do much typography stuff myself, I am really interested in it, and so will definitely watch the link you pasted :)

[1]: https://99percentinvisible.org/episode/interrobang/
[2]: https://www.amazon.com/Shady-Characters-Punctuation-Symbols-Typographical/dp/0393349721/

**Comment by kaushalmodi** [comment]
@rsms Thanks for linking that Explained episode. It contains more details about Interrobang history that the Shady Characters book did not cover.

Btw, another good candidate, I think, for the Interrobang glyph is the middle one in the picture below:

[![Proposed interrobangs from Type Talks, March-April 1962, as drawn by Jack Lipton](https://99percentinvisible.org/app/uploads/2018/07/proposed.png)][1]

[1]: https://99percentinvisible.org/episode/interrobang/

**Comment by rsms** [comment]
Here's a build with the above to test:
[Inter-UI-3.0-c178ada07d.zip](https://github.com/rsms/inter/files/2408459/Inter-UI-3.0-c178ada07d.zip)

**Comment by kaushalmodi** [comment]
@rsms Wow, thank you so much! That interrobang looks amazing!

**Comment by rsms** [comment]
Here's a take that's more similar to that of Iosevka:

<img width="265" alt="screen shot 2018-09-23 at 18 43 55" src="https://user-images.githubusercontent.com/47046/45935491-c6549e00-bf60-11e8-8fb9-c94da4ea7b4a.png">

Compared to other iterations:

<img width="439" alt="screen shot 2018-09-23 at 18 45 13" src="https://user-images.githubusercontent.com/47046/45935506-e1271280-bf60-11e8-8d2d-20005c8be344.png">

<img width="371" alt="screen shot 2018-09-23 at 18 45 19" src="https://user-images.githubusercontent.com/47046/45935507-e3896c80-bf60-11e8-825c-787c62c26bae.png">

**Comment by rsms** [comment]
A few more

<img width="354" alt="screen shot 2018-09-23 at 18 52 59" src="https://user-images.githubusercontent.com/47046/45935640-2a2b9680-bf62-11e8-8bf9-9335fbc3838e.png">

<img width="385" alt="screen shot 2018-09-23 at 18 53 44" src="https://user-images.githubusercontent.com/47046/45935641-2c8df080-bf62-11e8-97c8-b3b1b73f2898.png">

Close-ups of some of the alternatives:

<img width="350" alt="screen shot 2018-09-23 at 18 54 24" src="https://user-images.githubusercontent.com/47046/45935654-43344780-bf62-11e8-9790-6eb0c420bd3e.png"><img width="408" alt="screen shot 2018-09-23 at 18 54 15" src="https://user-images.githubusercontent.com/47046/45935655-44fe0b00-bf62-11e8-9755-f7b72ebbbc92.png"><img width="352" alt="screen shot 2018-09-23 at 18 54 08" src="https://user-images.githubusercontent.com/47046/45935659-46c7ce80-bf62-11e8-8fe9-9865505fa646.png"><img width="314" alt="screen shot 2018-09-23 at 18 54 01" src="https://user-images.githubusercontent.com/47046/45935660-492a2880-bf62-11e8-8ee3-c6042d77666a.png"><img width="347" alt="screen shot 2018-09-23 at 18 53 51" src="https://user-images.githubusercontent.com/47046/45935661-4af3ec00-bf62-11e8-9bc1-efdfd9030d3e.png">

**Comment by kaushalmodi** [comment]
## Pref 1

In terms of simplicity, and having the glyph quickly convey its meaning to the reader, I find this to be the best:

![](https://user-images.githubusercontent.com/47046/45935655-44fe0b00-bf62-11e8-9755-f7b72ebbbc92.png)

## Pref 2

This one is stylistic but not at the cost of losing its meaning. It's unique too.

![](https://user-images.githubusercontent.com/47046/45935661-4af3ec00-bf62-11e8-9bc1-efdfd9030d3e.png)

## Pref 3

About this last iteration, I'm not so sure and may be it's just me.. just because this does not have the 270 degree question mark hook. 

![](https://user-images.githubusercontent.com/47046/45935944-96f46000-bf65-11e8-8bcb-9cc88d46e249.png)

---

I cannot make up my mind on "Pref 1" vs "Pref 2"; both are awesome. I'll go by your judgment.

**Comment by kaushalmodi** [comment]
@rsms Was something else expected from me? Did my last comment not help?

**Comment by rsms** [comment]
@kaushalmodi It shipped in version 3.0 :–) I just forgot to close the issue when it did.
