### ISSUE TITLE
[Bug] ordmasculine/feminine don't match Inter style (they are still reminiscent of Roboto)

### ISSUE THREAD

**Issue by cssobral2013** [rsms/inter#691]
**Describe the bug**
Read the title.

**To Reproduce**
 - In your font editor (e.g., Glyphs), navigate to ordmasculine/feminine
 - You will see they are still reminiscent of Roboto

**Expected behavior**
 - They should match Inter style

**Screenshots**
 - Screenshots are below for Regular/Italic static weights.
![Sem título](https://github.com/rsms/inter/assets/19995437/8b1cb1b0-1f48-4c61-81a0-dbfb091345d9)
![Sem título1](https://github.com/rsms/inter/assets/19995437/0a828117-48de-471e-afda-e4056323062c)

**Environment**
- Every app and OS display this issue, because this is glyph-level
- Version of font: 4.0 (the latest, as of this writing)

**Comment by rsms** [comment]
After c569e272e40f26db8b194a07753b20ad1c2f15f1:

![](https://github.com/rsms/inter/assets/47046/6f01554f-0005-449a-9b37-fc78437998e9)

**Comment by rsms** [comment]
Thank you!
