### ISSUE TITLE
Add plane symbol (✈︎)

### ISSUE THREAD

**Issue by jack-jw** [rsms/inter#695]
I was just wondering if it'd be possible to add the aeroplane unicode symbol U+2708/✈︎ - the default one in most fonts is really ugly and the somewhat nicer SF/Segoe ones aren't consistent between platforms.

Thanks for the font!

**Comment by rsms** [comment]
I'm going to say no to this on principle — Inter isn't an "icon font". In other words: if we add a symbol for airplane, why wouldn't we also add a hundred other symbols?

I'd much rather see a free and open source project that implements symbols a la SF
