### ISSUE TITLE
TODO: Add list of package distributions & maintainers to README

### ISSUE THREAD

**Issue by holger1411** [rsms/inter#70]
Hi!
🥇 for this awesome font!
Any plans to make it available via npm or for any other package/dependency manager?

**Comment by rsms** [comment]
It's published by a third party as `inter-ui` in the npmjs (main) repository.

https://www.npmjs.com/package/inter-ui

Maintained by @philipbelesky

**Comment by rsms** [comment]
Archlinux package maintained by @chrissnell
https://aur.archlinux.org/packages/ttf-inter-ui/

**Comment by rsms** [comment]
(repuposing this task as a TODO for adding this info to README)

**Comment by chrissnell** [comment]
It would be helpful if we could use this task (or a fresh one) as a notification system for the package maintainers.  You could comment in it when there's a new release and we can get to work.

**Comment by rsms** [comment]
FYI, there's a pre-release available for early testing. This is the current release candidate for version 3.0.

It is **not** recommended to distribute this, but testing on Linux would be great. I've tested it on Gnome in Ubuntu, but I'm not an every-day Linux user, so would very much appreciate more testing :–)

https://github.com/rsms/inter/releases/tag/v3.0-rc2

**Comment by rsms** [comment]
**Announcement:** Version 3.0 has been released — https://github.com/rsms/inter/releases/tag/v3.0

**Comment by mcchrish** [comment]
FYI, it's available via homebrew cask and I made PR with the latest version and name change. https://github.com/Homebrew/homebrew-cask-fonts/pull/1797/files

**Comment by alexmyczko** [comment]
There's an overview here: https://repology.org/project/fonts:inter/versions
it's still missing the merge with pkg name fonts-inter from debian, which also has it:
https://packages.debian.org/sid/fonts-inter (ubuntu too)
