### ISSUE TITLE
Why Numbering is not aligned properly in MS Word

### ISSUE THREAD

**Issue by KunalTanwar** [rsms/inter#707]
**Describe the bug**
I don't know why but after the 9th numbering it behaves like this and then get fixed in 11th then again starts behaving like the same as 10th from number 12th.

**To Reproduce**
1. Open MS Word (I am using 365) *used 2019, 2021 etc* faced same issue in every versions.
2. Start ordered list go all the way to 10th number and see the issue.
3. The issue will get fixed at 11th but then again starts at 12th and so on.

**Expected behavior**
It should not add extra space automatically

**Screenshots**
![image](https://github.com/rsms/inter/assets/77537933/0c2e7103-fee5-4c8e-9e4a-a51178bcfee7)

**Environment**
- OS: Windows 11
- MS Word 354
- Inter v4 (the very latest)

**Comment by kenmcd** [comment]
Not an issue with the font.
This is an issue with the Word list style and the point size you are using.
Looks like your example above is set to 16pts.
There is a hanging indent in the List style of `0.25in`.
And there is also a tab set at `0.25in`.
Once the width of the leading numbers exceeds that `0.25in`, it jumps to the next tab setting.
The `11.` is narrower so at 16pts it still has not jumped.
You can see this happening if you highlight the text and change the point size up and down.
Turn-on Show the hidden marks and you can see the tabs.
Like this:
![Numbered-List-at-16pt-with-Inter](https://github.com/rsms/inter/assets/844920/3b11c980-90fc-40cb-a214-47c3f15f912a)

So you will need to make some adjustments to the list style in Word.
