### ISSUE TITLE
Italic missing round version of low quotes U+201E and U+201A

### ISSUE THREAD

**Issue by d-mal** [rsms/inter#711]
Using latest Inter Variable 4.0 Italic from the release page,
the stylistic variant for round quotes does not change the single and double "low-9" quotes U+201E and U+201A

1. „Copy“ this ‚line‘
2. Paste into https://rsms.me/inter/lab/?antialias=default&italic=1
3. Turn on ss03 - the low quotes are not changing.

**Expected behavior**
The low-9 quotes should turn into a rounded version, like the upper quotes.

**Screenshots**
![image](https://github.com/rsms/inter/assets/24476952/fce7a57d-531f-4676-aeaa-7078d3ad4601)

**Environment**
- OS: Win10 home x64
- Apps: Chrome and others
- Font Version 4.000;git-a52131595

**Additional context**
The ss08 square quotes do work fine.
The upright also does have no problem.
I haven't checked the static fonts.

**Comment by rsms** [comment]
Good catch. Thank you. Here's what it looks like with the fix:

<img width="1363" alt="Screen Shot 2024-11-15 at 10 11 31" src="https://github.com/user-attachments/assets/d4861309-3ea9-4f1f-bc36-6e51daf98741">
