### ISSUE TITLE
Add new stretch variations, like SF Pro

### ISSUE THREAD

**Issue by gthibaud** [rsms/inter#716]
Hi team, could you integrate different width variations for Inter, similar to the new expanded, compressed, and condensed variations introduced in the latest version of SF Pro? 

![out209](https://github.com/rsms/inter/assets/27550148/bb21eda9-7121-40a1-966f-befa94b5ec84)

![out145](https://github.com/rsms/inter/assets/27550148/244ca190-134f-4798-8a01-3dae4fcc8a63)

This would greatly enhance the usability of Inter! Here is the link to the presentation of these variations: https://developer.apple.com/wwdc22/110381

Thank you!

**Comment by rsms** [comment]
This would be a HUGE—like, many 100k's of USD huge—project.
It's unlikely to happen, but I'll keep this open as a feature request.

**Comment by rsms** [comment]
Duplicate of #318 & #71

**Comment by valutta** [comment]
Hello, https://github.com/valutta/InterWeight
