### ISSUE TITLE
Char `z` path defect since Inter UI 3.0 beta 3

### ISSUE THREAD

**Issue by jschopplich** [rsms/inter#72]
The `z` is displayed wrong since Inter UI 3.0 beta 3.

Inter UI Medium: ![grafik](https://user-images.githubusercontent.com/27850750/45609639-0eebf300-ba59-11e8-99b1-ac43b02f94ca.png)
Inter UI Bold: ![grafik](https://user-images.githubusercontent.com/27850750/45609652-19a68800-ba59-11e8-875e-8ce27f15e675.png)

****

Thank you for this incredible typeface.

**Comment by rsms** [comment]
Good catch! Fixing in a minute.

**Comment by rsms** [comment]
https://github.com/rsms/inter/releases/tag/v3.0-beta4
