### ISSUE TITLE
Missing U+266A Eighth Note and U+266B Beamed Eighth Notes for full subtitle support

### ISSUE THREAD

**Issue by thlinard** [rsms/inter#723]
♪ U+266A Eighth Note use is defined as such in Netflix Timed Text Style Guide:

> "I.15. Songs
> Song lyrics should be enclosed with a music note (♪) at the beginning and the end of each subtitle."

https://partnerhelp.netflixstudios.com/hc/en-us/articles/217350977-English-USA-Timed-Text-Style-Guide

♫ U+266B Beamed Eighth Notes use is defined as such in BBC Subtitle Guidelines:

> "9.3.2 Characters permitted online
> In addition to the characters above, the following characters are allowed if the subtitles are intended for online use only.
> online € ♫ (replaces # to indicate music) ← → (arrows can replace < and >)."

https://www.bbc.co.uk/accessibility/forproducts/guides/subtitles/#Characters-permitted-online

Both characters are widely used in subtitles.

**Comment by rsms** [comment]
Work in progress

<img width="1287" alt="Screen Shot 2024-11-15 at 12 41 23" src="https://github.com/user-attachments/assets/43e74deb-3401-4f56-a1b6-02dab7b063ac">

**Comment by rsms** [comment]
<img width="1184" alt="Screen Shot 2024-11-15 at 13 03 26" src="https://github.com/user-attachments/assets/5af5a1f4-f87f-480d-b0c5-8cbc4247283f">
