### ISSUE TITLE
Using the Inter font for the system clock makes the system clock move around

### ISSUE THREAD

**Issue by EyBmr** [rsms/inter#724]
![20240713_160128](https://github.com/user-attachments/assets/71b2efad-e459-41e6-be77-1e5b274cb5ca)

Using the Inter font for the KDE system clock makes the clock numbers move around.

Is there a way to make this behavior disappear, like a monospace version? Or make the numbers more mono spaced?

Operating System: Arch Linux 
KDE Plasma Version: 6.1.2
KDE Frameworks Version: 6.3.0
Qt Version: 6.7.2
Kernel Version: 6.9.9-zen1-1-zen (64-bit)
Graphics Platform: Wayland

**Comment by kenmcd** [comment]
The default figures in Inter are Proportional Lining (not going to change).
Tabular Lining (`tnum`) figures are available as an OpenType feature.
Tabular figures all have the same width.
See the Inter Features here:
https://rsms.me/inter/#features

You can "freeze" the `tnum` feature into your fonts using tools such as:
**OpenType Feature Freezer**
https://twardoch.github.io/fonttools-opentype-feature-freezer/
or
**FontFreeze**
https://github.com/MuTsunTsai/fontfreeze

**Comment by cpmsmith** [comment]
@EyBmr Good news: I [fixed this upstream in KDE Plasma](https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/4557), and judging by the milestone they added it to, I expect it'll be released with v6.2.

**Comment by EyBmr** [comment]
> @EyBmr Good news: I [fixed this upstream in KDE Plasma](https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/4557), and judging by the milestone they added it to, I expect it'll be released with v6.2.

Very nice. Thank you.
