### ISSUE TITLE
Double storey g character variant

### ISSUE THREAD

**Issue by rben01** [rsms/inter#726]
I prefer double storey ‘g’ to single storey. It would be great if a character variant were added for it.

**Comment by inferno986return** [comment]
While certainly less common in neo-grotesques, it can certainly work as Akkurat demonstrates nicely: https://lineto.com/typefaces/akkurat#family

**Comment by rsms** [comment]
Duplicate of #539

Also, please do not ignore [the issue template](https://github.com/rsms/inter/issues/new?assignees=&labels=&projects=&template=feature_request.md)
