### ISSUE TITLE
4x4xU

### ISSUE THREAD

**Issue by jooon** [rsms/inter#729]
**Describe the bug**
Lainey Wilson's song 4x4xU is a word play "four by four by you". If the x between the 4s turns into a multiplication symbol, then the x between 4 and U should as well.

**To Reproduce**
1. Write 4x4xU with Inter anywhere without disabling calt.
2. Notice the x between the 4s turns into a multiplication sign, while the x between 4 and U stays the same.

**Expected behavior**
I want consistency more than anything else. Either only multiplication symbols 4×4×U or only lower-case x 4x4xU.

**Environment**
- OS: Linux 
- Chrome
- https://rsms.me/inter/lab/

...

I guess you can always come up with more and more corner cases like this. I noticed an exception was made for c-style hex literals that begin with 0x. https://github.com/rsms/inter/issues/404

I am however not even sure if this one should be solved. For this specific case, it is possible to actually change the string to make it consistent.

If it can not be generalized without introducing an even bigger mess, do you know if there is a way to inject an escape hatch? If I insert a ZERO WIDTH NON-JOINER after the x in - https://rsms.me/inter/lab/ then that actually disables the contextual alternative for me. However, if I do the same in chrome inspector, for instance somewhere on https://rsms.me/inter/ it does nothing, but I am also not fully sure how web browsers work. I know I can disable it with css `font-variant-ligatures: no-contextual`, but I was wondering if there was some unicode way of doing it.

**Comment by rsms** [comment]
Fixed by https://github.com/rsms/inter/commit/dee8b1228bb393309b048d565938d8178bf98613

Thanks Jon!
