### ISSUE TITLE
Language Subsetting

### ISSUE THREAD

**Issue by Paul-Browne** [rsms/inter#73]
I only needed basic-latin so I used the fontsquirrel webfont generator https://www.fontsquirrel.com/tools/webfont-generator to reduce the webfont files eg. for inter-black from 105kb and 160kb to 25kb and 30kb (woff and woff2)

Maybe consider including these subsetted files so that people don't use the default webfonts with the full language support, when they probably don't need it.

**Comment by rsms** [comment]
Will *not* include subsetted font files for the following reasons:
- Everyone have different needs. To cover all cases, we would have to generate a very large number of permutations which would both make the downloadable package large and the build time long.
- Subsetting is easy to do yourself and easy to automate. Several high-quality free tools exists, like [fontmake](https://github.com/googlei18n/fontmake)

Related to #53

**Comment by savalina** [comment]
@Paul-Browne In FontSquirrel's generator check "Expert" and several options will appear. Among them there's a subsetting option, so you can create your basic subset from there.
