### ISSUE TITLE
Missing glyphs in Italic font

### ISSUE THREAD

**Issue by liroliro** [rsms/inter#731]
**Describe the bug**

**To Reproduce**

1. Download Inter Variable and Inter Italic Variable
2. Write in åå or ää
3. Compare the two and see the difference

**Expected behavior**

Should look like the regular font, but in italic. Now it displays another glyph.

**Screenshots**
<img width="238" alt="Screenshot 2024-08-20 at 10 01 31" src="https://github.com/user-attachments/assets/38b8c606-55d9-4657-b969-9312281b0297">

**Environment**
- OS: macOS 14.6.1
- App that renders the font: Chrome, Safari, Firefox
- Version of font "Inter-Variable-Italic 4.0", "Inter-Variable 4.0" Downloaded on 20th of August 2024. 

**Additional context**
The å and ä are used on several Swedish sites, which renders the wrong glyph after changing to the variable font.

**Comment by rsms** [comment]
This is by design. The lower-case a has a different design in the italic fonts
