### ISSUE TITLE
The 'fffi' ligature

### ISSUE THREAD

**Issue by RS-0000** [rsms/inter#732]
**Describe the bug**
The 'fffi' letter combination doesn't bahave according to Discretionary Ligatures function (or isn't defined in this alternate set). First letter 'f' is disjoined from the rest.

**To Reproduce**
1. Copy the following paragraph: 
`Die Schifffirma plante neue Routen für das kommende Jahr. In den Büros wurden effiziente Pläne erstellt, um die Kunden zufrieden zu stellen. Gleichzeitig wurde die Sicherheit der Fracht geprüft.`
2. Paste into [https://rsms.me/inter/lab/](url)

**Expected behavior**
It would be lovely to see the first 'f' joined the same way.

**Screenshots**
<img width="1035" alt="Screenshot 2024-08-20 at 14 40 43" src="https://github.com/user-attachments/assets/9b332f7a-0184-43b7-83b0-1b8ff1ee23f6">

**Environment**
- OS: Sonoma 14.6.1
- App that renders the font: Safari in this case, but the lack of necessary ligature is applicable in all cases.
- Version of font: 4.#?

**Additional context**
Triple consonants are rather rare but occure in German compound words. Examples: Schifffirma, Schifffahrt, Sauerstoffflasche, Baletttanzerin, etc.

**Comment by kenmcd** [comment]
> Triple consonants are rather rare but occure in German compound words. 
Examples: Schifffirma, Schifffahrt, Sauerstoffflasche, Baletttanzerin, etc.

fffi – fff – fffl – ttt 
Out of curiosity do you know of any fonts which have these ligatures?

**Comment by charakterziffer** [comment]
For your information: In German no ligature should be used across compound words. So the example „Schifffirma“ (ship company) may have the ligatures ff and fi, but not a ligature fffi. The same with the other examples: Schiff|fahrt, Sauerstoff|flasche, Balett|tänzerin.

As far as I know, only two ff and then one l or i can exist inside a word, e.g. in Soufflé or effizient. There’s no no-compound word with three f or t.

By the way: If you like to follow this good old typesetting rule then in German you often have to prevent ligatures, e.g. in Schilf|insel (reed island), Auf|lage (edition, no ligature with pre- or suffixes, too), Hof|fläche (yard area).

**Comment by kenmcd** [comment]
> For your information: In German no ligature should be used across compound words. So the example „Schifffirma“ (ship company) may have the ligatures ff and fi, but not a ligature fffi.

Well that explains what I have found.
I went looking for fonts with a `fffi` ligature.
And so far have not found that ligature.
But I do see fonts handling the `fffi` to make it _look_ like one ligature.

**Brill** replaces each character with modified versions which fit together like a ligature, but are not a single ligature.
In Schifffirma the `fffi` becomes `f._f/f._f/f._ij/i.f_`.
So it is still four separate characters, but visually integrated like a ligature.

![2024-08-22_13-41-30](https://github.com/user-attachments/assets/b7e19a48-9577-46e8-abbc-f98a67ad072d)

I found several fonts which work like this (most from Tiro).
All are serif fonts; have not found any sans serif fonts.

**Alegreya** is slightly different.
It does create the `fi` ligature, but keeps the first two `f`s separate.
So this `fffi` becomes `f.f/f.f/fi`.
Two `f`s and an `fi` ligature.

So these fonts seem to operate as you describe.

Have not yet found any fonts handling the `ttt`.

**Comment by RS-0000** [comment]
Sorry for the late reply. Thanks @charakterziffer for the info:
> For your information: In German no ligature should be used across compound words. (...) If you like to follow this good old typesetting rule then in German you often have to prevent ligatures, e.g. in Schilf|insel (reed island), Auf|lage (edition, no ligature with pre- or suffixes, too), Hof|fläche (yard area).

It seems like various fonts handle the [f][f][f][f] differently:

![240905 Inter ffi](https://github.com/user-attachments/assets/3a355243-fe00-4a18-b288-e36452827b8b)

So to summarise, Inter Variable acts like Lato (last on the list): merges three last characters in Schifffirma. It would be perfect if it could act like Helvetica Neue, Geneva, Plus Jakarta Sans and Myriad Pro – combine [ff] and [fi] separately in Shifffirma and [ffi] in efficient. (I hope I explained it in a clear way)

**Comment by rsms** [comment]
<img width="1562" alt="Screen Shot 2024-11-15 at 14 34 26" src="https://github.com/user-attachments/assets/6f139a28-de18-4ab2-9457-441128fbc910">
