### ISSUE TITLE
Avoid certain alt ligatures when inside of a URL

### ISSUE THREAD

**Issue by brianlovin** [rsms/inter#739]
**Describe the bug**
When sharing URLs, certain letter combinations can trigger alternative ligatures (like `x` → `×`) if the URL contains a number, x, and another number. These overrides can make URLs look "incorrect" because they aren't reflective of the actual characters being used.

**To Reproduce**
1. In a web environment that uses Inter, add a URL string with a `{number}x{number}` substring. The `x` will be converted to a mult `×`

**Expected behavior**
URLs should not be affected by ligature overrides as they can lead to confusion about what the actual URL represents.

**Screenshots**

![Screen Shot 2024-09-09 at 13 26 49@2x](https://github.com/user-attachments/assets/7f8e3560-ef72-47ae-ba79-63bbd4bc1dba)

**Environment**
- OS: macOS
- App that renders the font: Chrome

**Comment by rsms** [comment]
Fixed by https://github.com/rsms/inter/commit/dee8b1228bb393309b048d565938d8178bf98613

Thanks Brian!
