### ISSUE TITLE
The tabular figures' advance width in Regular weight do not match the other masters', mainly in 0-9 and operators

### ISSUE THREAD

**Issue by cssobral2013** [rsms/inter#741]
**Describe the bug**
The tabular figures' advance width in Regular weights, as stated in title, do not match the other masters' (mainly in 0-9 and operators).

**To Reproduce**
1. Activate tnum in your app that supports them;
2. Type without quotes "(0123456789+-)" in Text Regular weight, then do the same in Text Black Italic weight;
3. You will see that these texts slightly misalign.

**Expected behavior**
If you do both steps 1 and 2 above, the result should be perfect alignment.

**Screenshots**
The hightlighted glyphs below should have this advance width:
![Captura de tela 2024-09-09 180150](https://github.com/user-attachments/assets/8337d530-cbfe-4ece-a472-95aef9196782)
NOT this:
![Captura de tela 2024-09-09 180109](https://github.com/user-attachments/assets/8884895b-718d-404d-b628-f0d9b50d215d)

**Environment**
- This happens in every app/OS
- The screenshots were made by opening Inter version 4.0 (the latest in this repo) in FontLab 8.

**Comment by rsms** [comment]
This is by design. tnum in inter are not monospace; punctuation and digits have different width.
