### ISSUE TITLE
Confusion of Cyrillic letter at U+04E9

### ISSUE THREAD

**Issue by HHayasaka25** [rsms/inter#743]
On Inter font ver.4.0, there seems to be a confusion about a letter U+04E9. 
This Unicode is for CYRILLIC SMALL LETTER BARRED O, which is used for Mongolia for example. However, the glyph is mistakenly designd as the shape of U+0473(ѳ: CYRILLIC SMALL LETTER FITA). Fita is the old form of ф of Russian, so they are different. I would be happy if you to revise this confusion.
To tell detail, U+04E9 is designed as 'o plus ~', but it should be 'o plus -'.

**Comment by HHayasaka25** [comment]
To tell detail, U+04E9 is designed as 'o plus ~', but it should be 'o plus -'.

**Comment by rsms** [comment]
<img width="1000" alt="Screen Shot 2024-11-15 at 15 01 35" src="https://github.com/user-attachments/assets/452c37e3-e3ed-4323-9b3c-098d5b205d3c">
