### ISSUE TITLE
Letters inside circles in VS code

### ISSUE THREAD

**Issue by stereomato** [rsms/inter#746]
**Describe the bug**
title
**To Reproduce**
1. Open a Rust project on vscode, while using inter as ui font
2. Observe how the action/description text look

**Expected behavior**
No letters are inside circles

**Screenshots**
![image](https://github.com/user-attachments/assets/87fcd304-d01c-4353-89fd-cdd090dc889f)

**Environment**
- OS: Arch Linux, updated til 15-sep-2024
- App that renders the font Visual Studio Code
- Version of font: 4.0
**Additional context**
I suspect it's related to the composition feature, which can be disabled using fontconfig under linux, but chromium/electron don't respect those settings.

**Comment by kenmcd** [comment]
Disable Stylistic Set 5 (`ss05`).

![2024-09-18_18-50-42](https://github.com/user-attachments/assets/c9eabf06-61ca-4396-a025-3d2e71282b55)

**Comment by stereomato** [comment]
Yeah, this can be done using the `editor.fontLigatures` option in vscode, but the problem is that I enabled that stylistic set for the monospace font, and I don't know if this can be enabled just for it...

**Comment by D1360-64RC14** [comment]
Just to complement: if, after removing `ss05`, a square appears in the uppercase letters, remove the `ss06` too.
