### ISSUE TITLE
Add Support for U+20C0 (SOM SIGN)

### ISSUE THREAD

**Issue by ho1yspirt** [rsms/inter#747]
Would like to request the addition of U+20C0 (SOM SIGN) to the Inter font. This character is important for certain applications that require the representation of the SOM SIGN symbol (Kyrgyzstan country currency). Adding this character would enhance the usability of the Inter font across different contexts where this symbol is used.
Detailed information about unicode char here: https://www.unicodecharacter.org/U+20C0 and here: https://www.unicode.org/L2/L2020/20261-kyrgyz-som.pdf

**Why this is important:**
Currently, the Inter font does not support U+20C0, which makes it difficult for users who need to display this symbol in their projects. Incorporating it into the font will improve its versatility and ensure better support for a wider range of use cases.

**Proposed solution:**
Please, consider adding U+20C0 (SOM SIGN) to the font's character set in an upcoming release.

**Additional context**
The addition of this symbol would make Inter more suitable for applications and regions that require this character for proper display and usage.

**Comment by KrasnayaPloshchad** [comment]
This could be designed as с with underline, and it’s easy to do by combining glyph references from existed characters.

**Comment by ho1yspirt** [comment]
> See also https://www.unicode.org/charts/PDF/U20A0.pdf This could be designed as с with underline, and it’s easy to do by combining glyph references from existed characters.

It's not actually just underline, here is the proposal document with more details https://www.unicode.org/L2/L2020/20261-kyrgyz-som.pdf. But I'm also think that it's could be easy.

**Comment by rsms** [comment]
This is really helpful. Nice

<img width="768" alt="Screen Shot 2024-11-15 at 15 11 22" src="https://github.com/user-attachments/assets/6803cd3f-9b35-4f12-9fd6-7fb47c31fbda">

**Comment by rsms** [comment]
WIP
<img width="2672" alt="Screen Shot 2024-11-15 at 15 17 14" src="https://github.com/user-attachments/assets/8e46a688-729a-46d5-92cc-1fa38d921243">

**Comment by rsms** [comment]
<img width="1503" alt="Screen Shot 2024-11-15 at 15 21 17" src="https://github.com/user-attachments/assets/9bd8acb9-9736-40dc-8e3c-04c0e7636c2a">

**Comment by rsms** [comment]
![som2](https://github.com/user-attachments/assets/6a5d6faf-6dcf-4ab1-ac4f-10887e39b6e6)
![som1](https://github.com/user-attachments/assets/b1b44215-700d-4275-a8d6-96c1b6d91d35)

**Comment by ravid-dubsteper** [comment]
I don't think this is the way you should draw som for inter. it simply doesn't match to the style of the typeface

**Comment by ravid-dubsteper** [comment]
I don't think this is the way you should draw som for inter. it simply doesn't match to the style of the typeface. take the existing lowercase "c" for the symbol and move it to the cap height
<img width="1552" alt="image" src="https://github.com/user-attachments/assets/43e99701-c4f1-4ba0-bcf4-2d578a782c37">
<img width="1552" alt="image" src="https://github.com/user-attachments/assets/ed2daa71-84a3-487f-9aca-5393961cbff3">

**Comment by ho1yspirt** [comment]
@ravid-dubsteper yap, "c" is in fact a letter here, as its described in "... “C” of the Cyrillic alphabet with underlining ...". But its definitely **should not** sticking to cap of x-height, the proposal from National Bank of Kyrgyzstan is **clearly** illustrate it.
Another problem is that in proposal "c" mentions as "... Som sign is based on a capital letter ...", so there is a mismatch of text description and illustration, in graphics its low case; in text its up case.

**Comment by rsms** [comment]
Yup. The spec is very clear on the design. Case closed
