### ISSUE TITLE
Incorrect Glyph Shape for the Character پ (Unicode: U+067E)

### ISSUE THREAD

**Issue by 0xdolan** [rsms/inter#756]
**Describe the bug**  
The character **پ** (Unicode: `U+067E`), used in Kurdish and Persian, has an incorrect shape in the Inter font. While the Unicode mapping is correct, the displayed glyph shape doesn’t conform to standard typography for these languages, leading to readability issues.

**To Reproduce**  
1. I used Google Chrome, Brave Browser, Firefox apps
2. Enter the character پ (Unicode `U+067E`) in Kurdish or Persian text.
3. Observe the shape rendered in Inter.

**Expected behavior**  
The character **پ** should display with a shape that matches standard Kurdish and Persian typography. This would involve specific characteristics visible in the “Correct Display” section below.

**Screenshots**  

*Incorrect Display in Inter:*  
![Screenshot 01](https://github.com/user-attachments/assets/5e6971b6-6373-4294-be81-b1a294347459)
![Screenshot 05](https://github.com/user-attachments/assets/cb9f034b-bf78-49f8-99de-7d5155bd9e94)
![Screenshot 06](https://github.com/user-attachments/assets/ed015046-8389-47c2-ae7d-7e5058182033)

*Correct Display in Standard Typography:*  
![Screenshot 04](https://github.com/user-attachments/assets/2bc390ba-749e-4201-b4f0-07c0775fc279)

*Also another one is when the caret is added on top of **ل** (U+0644) to form **ڵ** (U+06B5), and then **ا** (U+0627) is added, the resulting shape should match **لا** (U+0644 + U+0627) exactly, with the only difference being the presence of the caret on **ڵ** (U+06B5) in the second case.*
![Screenshot 02](https://github.com/user-attachments/assets/7c5956bd-e896-43b8-a14f-3678bce30a64)

**Environment**  
- **OS**: Ubuntu 23.10
- **App that renders the font**: Google Chrome, Brave Browser, Firefox
- **Version of font**: Inter Regular 3.019;git-0a5106e0b
![Font Version](https://github.com/user-attachments/assets/58084832-8ea4-4f7a-aa4d-cff82e5fc2bd)

**Additional context**  
This correction would improve readability for Kurdish and Persian users, helping ensure that Inter is accessible and accurate for these languages. Thank you for your consideration of this issue and for your work on the Inter font project!

**Comment by 0xdolan** [comment]
Guess I got font-scammed by WhatFont! 😅
![WhatFont deceived me](https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/15/2f/e9/152fe96c-f6e1-818b-1c22-effff0fffc3d/AppIcon-0-85-220-0-0-0-0-4-0-0-0-2x-sRGB-0-0-0.png/1200x630bb.png)

**Comment by khaledhosny** [comment]
FWIW, the Arabic font looks like an outdated version of [Noto Sans Arabic](https://fonts.google.com/noto/specimen/Noto+Sans+Arabic). Current version of the font does not have these issues.
