### ISSUE TITLE
Bad vertical alignment of `u`

### ISSUE THREAD

**Issue by jschopplich** [rsms/inter#76]
**Describe the bug**
The character `u` is missaligned vertically

**To Reproduce**
Install hinted TTF version of Inter UI on an Windows machine and write something down.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/27850750/45957752-088be700-c016-11e8-85eb-a3727206e278.png)

**Environment**
- Version: Inter UI 3.0 RC1 (TTF hinted)
- OS: Windows 10

**Comment by rsms** [comment]
Yikes! Did you try the unhinged version? Also, are you using the traditional font files or the “variable” ones?

**Comment by jschopplich** [comment]
I will try the unhinted version for comparison. No, I'm using the traditional hinted TTF version.

**Comment by jschopplich** [comment]
Tested it. Seems like a hinting problem. I guess there's nothing you can do then.

**Comment by rsms** [comment]
We can definitely fix this :–)

Some glyphs are composed from other glyphs via something called "components" — a sort of hyperlink. This is the case with "u", which is an instance of the "n" component mirrored on the Y axis. However, I'm suspecting that autohint introduces TTF hints on the "n" glyph which flow over to the "u" glyph, but as "u" is transformed to mirror, the TTF hints will be off.

Here's a build with "u" as a regular glyph rather than a component:
[Inter-UI-3.0-7bf2380cf3.zip](https://github.com/rsms/inter/files/2411491/Inter-UI-3.0-7bf2380cf3.zip)

**Comment by jschopplich** [comment]
Wow, I didn't expect ttfautohint to have these options! Thanks for the component introduction. 🙂 

That looks much better:

![grafik](https://user-images.githubusercontent.com/27850750/45962574-77bb0880-c021-11e8-8787-7b18fb340950.png)

**Comment by rsms** [comment]
Can you share how you reproduce the above? I’m unable to repro that rendering on Windows 10.

**Comment by jschopplich** [comment]
It seems that Thunderbird 60.0b11 (which I used to test) renderes hinted TTFs differentl. I retested in MS Office Word and Inter UI renders failry fine even in largen sizes.

**Comment by rsms** [comment]
Interesting. It seems it may be an issue with Thunderbird. There are at least two open issues related to ClearType text rendering. https://bugzilla.mozilla.org/show_bug.cgi?id=1374225

If it looks good on Windows (apps on Windows that use the OSes text rendering) I'm going to call it and close tihis ticket. Let me know if that is not the case and we can reopen this and investigate rendering on Windows' :–)

**Comment by jschopplich** [comment]
Sounds like a plan. Thanks for the thoroughly research. Looking forward to RC2 now. 😄

**Comment by rsms** [comment]
RC2 should be released tomorrow.

**Comment by rsms** [comment]
RC 2 has been released and should fix this issue.
https://github.com/rsms/inter/releases/tag/v3.0-rc2
