### ISSUE TITLE
Hinted folder is missing .var. files

### ISSUE THREAD

**Issue by jbach** [rsms/inter#79]
**Describe the bug**
`inter-ui-hinted.css` references `Inter UI (web hinted)/Inter-UI.var.woff2`, but the `.var.` files don’t exist in the hinted folder.

**To Reproduce**
1. Download latest release
2. Look at `inter-ui-hinted.css` and `Inter UI (web hinted)/`

**Expected behavior**
The `.var.` files should also be present in the `(web hinted)` folder.

**Comment by rsms** [comment]
Fixed in c10bbc8a186cd7ee89d478653729355338066f46
