### ISSUE TITLE
Alternate glyphs - serifed capital "I" and digit 3 with a flat top.

### ISSUE THREAD

**Issue by mm-2018** [rsms/inter#89]
If this is possible, I would prefer to have an alternative character for `I` which would include serifs - for neo-grotesque typefaces similar to this, I would prefer to read serifed `I`s over curled lowercase `l`s. I commend you on being able to address this legibility issue quite promptly with `I` and `l` as well as `0` and `O`, which does not seem to be the case with many other existing open source sans-serif typefaces.

Additionally, for users of the Cyrillic alphabet, being easily able to distinguish between digit 3 and capital з would be highly beneficial for them, so I would like to suggest this as well. Few existing open source typefaces, especially sans-serif ones, take this into consideration. I suggest the inclusion of an alternative digit 3 glyph which uses a flat top, in order to create a distinction between the glyphs.

**Comment by rsms** [comment]
I've been wanting to add a serif upper case "i" for a while and have a change coming. I'll wrap it up...

**Comment by rsms** [comment]
[Inter-UI-3.0-47f3df3fcc.zip](https://github.com/rsms/inter/files/2611842/Inter-UI-3.0-47f3df3fcc.zip)

Here's a build with alternate serif upper case i.

Access it by enabling `cv08` or `ss02` (in a web browser, that means setting `font-feature-settings: "cv08"` in CSS)

Samples of the new glyphs:

<img width="1332" alt="screen shot 2018-11-23 at 14 32 09" src="https://user-images.githubusercontent.com/47046/48962199-9d856080-ef31-11e8-9979-a431de7c83ba.png">
<img width="1316" alt="screen shot 2018-11-23 at 14 32 13" src="https://user-images.githubusercontent.com/47046/48962200-a24a1480-ef31-11e8-9764-27982a18e3da.png">
<img width="1284" alt="screen shot 2018-11-23 at 14 32 20" src="https://user-images.githubusercontent.com/47046/48962202-a7a75f00-ef31-11e8-9c9f-fc582e12141c.png">
<img width="1291" alt="screen shot 2018-11-23 at 14 32 28" src="https://user-images.githubusercontent.com/47046/48962204-a9712280-ef31-11e8-955b-4b5ba2ba7889.png">
<img width="533" alt="screen shot 2018-11-23 at 15 01 31" src="https://user-images.githubusercontent.com/47046/48962206-af670380-ef31-11e8-9baf-d25ad23d2eec.png">
<img width="516" alt="screen shot 2018-11-23 at 15 01 26" src="https://user-images.githubusercontent.com/47046/48962207-b261f400-ef31-11e8-84df-89586f2803fe.png">
<img width="480" alt="screen shot 2018-11-23 at 15 01 41" src="https://user-images.githubusercontent.com/47046/48962209-b42bb780-ef31-11e8-9be1-386924df0768.png">
<img width="462" alt="screen shot 2018-11-23 at 15 01 37" src="https://user-images.githubusercontent.com/47046/48962211-b55ce480-ef31-11e8-8182-64829adc66fa.png">

**Comment by mm-2018** [comment]
Thank you very much for your response. Is there a way to access this alternate glyph without a web browser?

**Comment by rsms** [comment]
For the flat-top "three", it would be best with a separate issue to track that request.
