### ISSUE TITLE
Flat top 3 as an alternative glyph

### ISSUE THREAD

**Issue by mm-2018** [rsms/inter#91]
*This is following on from a previous issue, but under the recommendation of the author, I've decided to move this as another issue.*

I believe that users of the Cyrillic alphabet will benefit from being easily able to distinguish between digit 3 and capital з, especially in all capital texts, so I would like to see this implemented if possible. Few existing open source typefaces, especially sans-serif ones, take this into consideration from what I've seen. I suggest the inclusion of an alternative digit 3 glyph which uses a flat top, in order to create a distinction between the glyphs.

**Comment by rsms** [comment]
Fixed in c59342a8e94b9587b50abfe40fb630382c993499

**Comment by rsms** [comment]
Also included in [just-released version 3.1](https://github.com/rsms/inter/releases/tag/v3.1)
