### ISSUE TITLE
Alternative lower case a

### ISSUE THREAD

**Issue by vilav** [rsms/inter#92]
<img width="89" alt="screenshot 2018-11-25 23 03 56" src="https://user-images.githubusercontent.com/849098/48980618-6b792780-f106-11e8-9ace-8082534d056a.png">

Would be nice to have an alternative 'a', a nice soft touch.
Cant wait for this to be on Google Fonts and switch to it full time.

**Comment by rekollekt** [comment]
Approximate ETA?

**Comment by nmassi** [comment]
Added — hopefully @rsms will merge 
https://github.com/rsms/inter/pull/122

**Comment by gmosx** [comment]
That would be *very* useful!

**Comment by vilav** [comment]
Any decision on the addition / omission of this specific glyph?

**Comment by rsms** [comment]
Landed in aa2a3fe60742824420b307b104fb09f4daf7a6c7
