### ISSUE TITLE
Capital G with a spur

### ISSUE THREAD

**Issue by mm-2018** [rsms/inter#95]
Firstly, I understand you may be very busy with this project. I want to say thank you for being responsive to the issues we have made here - this is starting to be my favourite font since the latest major version came out with its fixes. 

I would like an alternative character to use, specifically, a Helvetica-style "G". If there are any issues with this, please let me know.

**Comment by rsms** [comment]
https://github.com/rsms/inter/commit/ba424d4c08ccd7ed8376c33b945f77d563ae000d

Under `cv10`

![g-spur](https://user-images.githubusercontent.com/47046/52184320-9ea2fb80-27c6-11e9-899b-dbfbd865864e.png)
